### ISSUE TITLE
Problem at binding private channel from different server.

### ISSUE THREAD

**Issue by Debabrata-Ghosh** [beyondcode/laravel-websockets#100]
Hello, I want to bind private channel of a different server from my client (react). I mean my `php artisan websocket:serve` command is running at one server and my client is running at different server. Public channel is working fine (I can bind public channels from my client). But when I try to bind private channel authorization is not working. Getting response:  

`Couldn't retrieve authentication info. 419Clients must be authenticated to join private or presence channels`

**Comment by stayallive** [comment]
You will need to have an authentication endpoint in your Laravel app.

See: https://laravel.com/docs/5.7/broadcasting#authorizing-channels

And set the auth endpoint in your Pusher config to match: https://pusher.com/docs/authenticating_users#authEndpoint

**Comment by rbreahna** [comment]
> You will need to have an authentication endpoint in your Laravel app.
> 
> See: https://laravel.com/docs/5.7/broadcasting#authorizing-channels
> 
> And set the auth endpoint in your Pusher config to match: https://pusher.com/docs/authenticating_users#authEndpoint

@stayallive can you elaborate, I am having the same problem with this package + laravel passport for api, each running separately.
