### ISSUE TITLE
How to get all channels in order to get all connections?

### ISSUE THREAD

**Issue by hamidroohani** [beyondcode/laravel-websockets#1001]
I created a system that creates channels dynamically, For an admin panel I want to see a list of all connections.
After reading the package, I found the getChannels function that supposes to return all channel names, but it returns an empty array

```
 $channelManager = app(ChannelManager::class);
 $channels = Collection::make($channelManager->getChannels('devices'));
```

**Comment by elmehdielhamdi** [comment]
Hello ! Have you found a solution for this issue please ?
