### ISSUE TITLE
 Invalid WebSocket Controller provided 

### ISSUE THREAD

**Issue by soomay55** [beyondcode/laravel-websockets#1002]
Invalid WebSocket Controller provided. Expected instance of `Ratchet\WebSocket\MessageComponentInterface`, but received `App\Websockets\SocketHandler\UpdatePostSocketHandler`.

**Comment by LAGGOUNE-Walid** [comment]
Hello , your `App\Websockets\SocketHandler\UpdatePostSocketHandler` should implements `Ratchet\WebSocket\MessageComponentInterface`.
Take a look on this blog post : http://blog.usthb-celec.com/b/build-your-own-pusher-server
