### ISSUE TITLE
pusher version

### ISSUE THREAD

**Issue by theoreaves** [beyondcode/laravel-websockets#1006]
I just deployed my project to a new server.  

after running composer install, the following versions were installs:
Laravel Websockets: 1.4.0
php pusher server: 7.1.0-beta

What I discovered, is that the "channels" parameter inside TriggerEventController is not getting passed, thereby causing no events to get sent from the software.  I see on my local box, php pusher server is at version 5.0.3.  I forced pusher to that version and now all works well.

So, my question is this:
What version of Laravel Websockets and pusher do I need to be up to the latest version?  My project is still in Laravel 8, but I do place to migrate it to 9 next week.

Thanks in advance for any help!

**Comment by rezuantpr** [comment]
Did you find an answer for your question? It is still relevant to me. In my case 7.1.0-beta doesn't work. But almost all versions lower works well. 🙂

**Comment by mpociot** [comment]
I just fixed this in the 2.x branch 👍
