### ISSUE TITLE
Horizontal Scaling Laravel-Websockets (with Redis and Load Balancer)

### ISSUE THREAD

**Issue by trocker** [beyondcode/laravel-websockets#1011]
Hello - After reading all the docks and searching the issues, I decided to ask the question here. So far I have only been able to get laravel-websockets running on 1 machine but I wanted to scale that horizontally. How should I go about it?

I was hoping to take some inspiration from the [horizontal scaling article for socket.io with Redis](https://medium.com/containers-on-aws/scaling-a-realtime-chat-app-on-aws-using-socket-io-redis-and-aws-fargate-4ed63fb1b681) but I'm not sure how to get started on that.

I would greatly appreciate any help on this topic!

**Comment by sync667** [comment]
If i'm not wrong all you have to use is 2.0 beta versions. They have redis support and so on. https://github.com/beyondcode/laravel-websockets/blob/2.0.0-beta.37/config/websockets.php
