### ISSUE TITLE
Exception `Symfony\Component\HttpKernel\Exception\HttpException` thrown: `Invalid auth signature provided.`

### ISSUE THREAD

**Issue by feix0326** [beyondcode/laravel-websockets#1021]
When I run laravel websockets on a server, the console print this error. Anyone know how to solve it ?  thanks!
`Exception `Symfony\Component\HttpKernel\Exception\HttpException` thrown: `Invalid auth signature provided.`

**Comment by jose123v** [comment]
I fix it using [soketi](https://github.com/soketi/soketi)
