### ISSUE TITLE
Handle socket events from clinet to laravel-echo

### ISSUE THREAD

**Issue by mohhamedion** [beyondcode/laravel-websockets#1029]
Hi, am in a situation where clients need to emit socket events, 
then send back a laravel-echo push event from the server side

Is there anyway to do that with laravel-echo?

i don't want to add extra custom handler because thats mean extra connection (one for pusher and one for my handler)

**Comment by cesarreyes3** [comment]
>Is there anyway to do that with laravel-echo?

Yes
