### ISSUE TITLE
How to configure SSL with AWS using load-balancer 

### ISSUE THREAD

**Issue by rajjanorkar** [beyondcode/laravel-websockets#103]
I can run it successfully on my local server where i have ssl certificate path etc.
But i am having difficulty understand and implement it on AWS with load-balancer where we do not have local certificate path on the instance.

It will be really helpful if anyone share the details how to implement it on AWS?

thank you

**Comment by stayallive** [comment]
Disclaimer: I have not done this but to give you some pointers that might help you a bit:

- If you are on a load balancer setup do not use SSL in the websockets server itself but run it on plain/HTTP and let the load balancer terminate the SSL connection (see: https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx)

- Only have 1 back-end handling websockets:serve since currently the package has no support for running multiple processes

If someone has it running behind ELB please add some more insights :)

**Comment by rajjanorkar** [comment]
@stayallive  Thank you for reply.

Situation is : 
- We have laravel app (mylaraapp) which is hosted on AWS (currently using load balancer running on multiple instances)
- What i thought is we install this package as part of our mylaraapp and deploy it to AWS, but situation is this websockets most probably will be running on multiple instances behind load balancer.

I am trying to understand your comment which says "it does not currently support multiple processes."
so in that sense it looks to me i can not deploy this websockets server as part of mylaraapp deployment?

So to get it working fine i should use seperate "one instance" to run the websocket server and then configure it to use in any no. of application, is that right?

If i decide to go as seperate instance just for this websocket then i will only have laravel framework (without app) and then this websocket package ?

Thank you.

**Comment by stayallive** [comment]
IMHO you have a couple of options:

Not recommended: You can certainly deploy the websockets package as part of you application. However multiple running instances do not sync with each other. So you should configure the load balancer to stick to a single back-end for the websocket connections.

Recommended: However that wastes recources by having it running so yes I would say a seperated application (with a single server) running only `websockets:serve` would be the way to go here.

You don't need to create a totally seperate app for just the websockets (you can, but it's not strictly required). It is also possible to deploy your application code to an isolated server and only use it to run `php artisan websockets:serve`, not serving web requests. This way you keep your websockets code together with your main app.

And yes a single instance can serve multiple apps (and ofcourse multiple end-users).

Hope this gets you a step closer!

**Comment by kpebron** [comment]
@rajjanorkar were you able to solve this? Since right now I am also experiencing the same issue.
