### ISSUE TITLE
Any Permanent fix for "Pusher error: cURL error 35"

### ISSUE THREAD

**Issue by kimpoy010** [beyondcode/laravel-websockets#1030]
Hi all,

I'm not sure how can I get a permanent fix for this issue. This happens everyday and broadcasts stop working. This usually happens when I have at least 500 concurrent connections. 

after I restart the server, the error will be gone and it starts working again.

**Comment by jose123v** [comment]
I fix it using [soketi](https://github.com/soketi/soketi)
