### ISSUE TITLE
WSS connection Failed

### ISSUE THREAD

**Issue by p7Rck** [beyondcode/laravel-websockets#1032]
Hi, I'm trying to install WebSockets on my project.

It is a multi-tenant SAAS ERP. I'm using stancl/tenancy for multi-tenancy
I'm hosting it in Digital Ocean.
I'm using PLOI

**Configuration**

 - Nginx Server
 - LetsEncrypt SSL
 - "laravel/framework": "^8.0",,
 - "beyondcode/laravel-websockets": "^1.13",
 - "pusher/pusher-php-server": "^7.0",
 - "pusher-js": "^7.4.0",

**websockets.php**

```
        'apps' => [
            [
                'id' => env('PUSHER_APP_ID'),
                'name' => env('APP_NAME'),
                'key' => env('PUSHER_APP_KEY'),
                'secret' => env('PUSHER_APP_SECRET'),
                'enable_client_messages' => false,
                'enable_statistics' => true,
            ],
        ],
    'ssl' => [
        'local_cert' => env('SSL_CERT', null),
        'local_pk' => env('SSL_PK', null),
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
        'verify_peer' => false,

    ],
```

**broadcasting.php**
```
 'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'scheme' => 'https',
                'port' => 6001,
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],

            ],
        ],
```

WebSocket is not working getting this error:
pusher.min.js:8 WebSocket connection to 'wss://site_url:6001/app/8e7ce9e8c396ef0e6fed?protocol=7&client=js&version=4.3.1&flash=false' failed: WebSocket is closed before the connection is established.

I highly appreciate your help in this. Thank you in Advance

**Comment by jose123v** [comment]
I fix it using [soketi](https://github.com/soketi/soketi)
