### ISSUE TITLE
Do I need SSL certificate on the server ?

### ISSUE THREAD

**Issue by reactor123** [beyondcode/laravel-websockets#105]
i tried it in localhost and worked well but on the remote server the frontend (Echo) didn't connect to websockets server and here is the response :
![untitled](https://user-images.githubusercontent.com/9276573/52553340-d673f980-2deb-11e9-9241-8e467b02de88.png)

Do I need SSL certificate on the server to get it work ?

**Comment by stayallive** [comment]
The protocol in your screenshot is `ws` so the plain variant, no SSL needed :)

You do whoever need to open port 6001 in your firewall to allow you to connect to the websockets server (or the websockets:serve command was not running).

Check if your port is open here: https://www.portcheckers.com/
