### ISSUE TITLE
Broken and can't resolve

### ISSUE THREAD

**Issue by chirukinbb** [beyondcode/laravel-websockets#1056]
Hi, have a trouble:
run this websocket with letsencript certificate
it work some times without problem(broadcaster send messages)
then i create new events for broadcasters and reload socket
when i run socket i  got in console
Starting the WebSocket server on port 6001...
but client give me
WebSocket connection to 'wss://***?protocol=7&client=js&version=7.2.0&flash=false' failed:
reason empty
i try return old code base (using git)  but it not resolved trouble

ssl sertificate is good

how it possible?

broadcasting.php
`        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env ( 'PUSHER_APP_CLUSTER' ),
                'encrypted' => true,
                'host' => env('APP_HOST'),
                'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
                'scheme' => 'https',
                'curl_options' => [
                    'CURLOPT_SSL_VERIFYHOST' => 0,
                    'CURLOPT_SSL_VERIFYPEER' => 0,
                ]
            ],
        ],`

**Comment by madpilot78** [comment]
@chirukinbb Looks similar to #1041, you should try downgrading pusher-php-server to 7.0.2, as indicated in the other bug report.
