### ISSUE TITLE
events not broadcasting

### ISSUE THREAD

**Issue by MarceloLuis1997** [beyondcode/laravel-websockets#1064]
I'm trying to use this package with laravel Echo. Everything is working fine, but the events are not broadcasting. They are being processed by the queue but are not shown on the `localhost:8080/laravel-websockets` panel and are not being received on the echo `listen` method. My BROADCAST_DRIVER is set to pusher and all configuration are right.

I have one terminal with `php artisan websockets:serve` which shows the connection messages correctly:
```
New connection opened for app key docsKey123.
Connection id 672865752.519772707 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"672865752.519772707\",\"activity_timeout\":30}"}
docs-pusher-app: connection id 672865752.519772707 received message: {"event":"pusher:subscribe","data":{"auth":"docsKey123:cb274d3c9fbb717b6deaa146dff6db1f37c51debc152c324960ad58ede4bc90d","channel":"private-websockets-dashboard-disconnection"}}.
docs-pusher-app: connection id 158787006.485562343 received message: {"event":"pusher:ping","data":{}}.
Connection id 158787006.485562343 sending message {"event":"pusher:pong"}
```

And one terminal with `php artisan queue:work` which shows the events being processed correctly:
```
INFO  Processing jobs from the [default] queue.  

  2022-11-21 15:38:16 App\Events\Test ........................................................................................................................................................ 18.37ms DONE
  2022-11-21 15:38:22 App\Events\Test ........................................................................................................................................................ 10.01ms DONE
  2022-11-21 15:38:40 App\Events\Test ........................................................................................................................................................ 15.99ms DONE
```

```
        broadcast(new \App\Events\Test([
            'message' => 'testing',
            'data' => [1, 2]
        ]));
```

```
    public function broadcastAs()
    {
        return 'Test';
    }
```

In my laravel echo:
```
  echo.private('channel').subscribed(() => {
    console.log('subscribed') // it shows subscribed on the console
  }).error((error) => {
    console.log('ERROR: ', error)
  }).listen('.Test', (event) => {
    console.log('event: ', event) but this are never logged
  })
```

**Comment by MrDanielCadeau** [comment]
seems like its related to the pusher-php-server version
I had the same problem as you on 7.2.1, but on 7.0.2 version all is working properly

https://github.com/beyondcode/laravel-websockets/issues/1065#issue-1459687710

**Comment by alireza-salehi** [comment]
same issue with  pusher-php-server 7.2.1

**Comment by JeanSassi** [comment]
After hours. It worked for me.

https://github.com/beyondcode/laravel-websockets/commit/fe78daf914aa5a60d47402b2d0b6390e83c9102a

**Comment by vjanssens** [comment]
Yes, downgrading using `composer require pusher/pusher-php-server:7.0.2` did the trick for me.

**Comment by vpansuriya** [comment]
for me above solution not working. in my local "pusher/pusher-php-server": "7.2.0" is working fine but on server I used both "7.2.0" and "7.0.2", but none of is working.
