### ISSUE TITLE
not working with  pusher-php-server v7.2.1

### ISSUE THREAD

**Issue by alireza-salehi** [beyondcode/laravel-websockets#1065]
i'm using these packages:
laravel/framework v9.39.0
beyondcode/laravel-websockets 1.13.1
pusher/pusher-php-server 7.0.2
Redis
Horizon

and clients not getting any data when using (pusher-php-server 7.2.1)

more info on
https://github.com/pusher/pusher-http-php/issues/364

**Comment by smcgovern** [comment]
Same problems here, seems these tools are broken at the latest build?
