### ISSUE TITLE
Close WebSocket on Server-Side

### ISSUE THREAD

**Issue by lauritzh** [beyondcode/laravel-websockets#1077]
Hi there!

Is it possible to actively close a WebSocket connection from server-side?

I see that connections are for instance closed in case an error occurs:
https://github.com/beyondcode/laravel-websockets/blob/fb958fb851e75fab9b39a11b88bd7c52e1dd80e0/src/API/Controller.php#L137

The underlying *Ratchet* lib supports to close connections via `$conn->close();` (as can be seen above): 
https://github.com/ratchetphp/Ratchet/

I need to terminate the connection in case a user is logged out from the application (e.g. a session timeout occurs) but there is no reload. 

Thank you very much in advance! Best regards,
Lauritz

**Comment by Temepest74** [comment]
Idk how it works under the hood, but try to get the conn object and close it yourself. I highly advise you to use a debugger
