### ISSUE TITLE
Laravel 9 & PHP 8

### ISSUE THREAD

**Issue by kailasb10** [beyondcode/laravel-websockets#1082]
I've upgraded from Laravel 8 & PHP 7.3 to Laravel 9 & PHP 8. However, WebSocket is not working after the update.

**Below is the version currently installed:**
"beyondcode/laravel-websockets": "1.13.1",
"pusher/pusher-php-server": "7.2.1",
"guzzlehttp/guzzle": "7.5.0"

**Pusher Log:**
Pusher :  : ["State changed","connecting -> unavailable"]

**WebSocket request:**
URL: wss://test.com/app/ABCDEFG?protocol=7&client=js&version=7.0.3&flash=false
Message: WebSocket is closed before the connection is established.

The site has a valid SSL Certificate.

@rennokki @freekmurze 
can you guide me on how can I resolve this issue?

**Comment by bhushan** [comment]
<img width="1177" alt="Screenshot 2023-01-09 at 12 26 14 AM" src="https://user-images.githubusercontent.com/43483545/211213789-8b54c232-a80d-45e3-ba87-704a4b618871.png">


I think it needs to be version 3 :(

**Comment by soha1410** [comment]
I have the same problem nothing work.
Laravel Framework 9.44.0
PHP 8.1.3 
 "pusher/pusher-php-server": "7.0.2"
"beyondcode/laravel-websockets": "1.13.2"

can some body help?

**Comment by kailasb10** [comment]
Below are the configuration worked in CentosOS 7

**PHP:** 8.2.1
**Laravel Framework:** 9.43.0

**Composer.json**
beyondcode/laravel-websockets: 1.13.1
pusher/pusher-php-server: 7.2.1 -> pre-supported version by Laravel 9 (this is installed by dependencies not added in composer.json )

**Package.json**
pusher-js: 7.0.3

**Pusher Connection:**
pusher = new Pusher(process.env.MIX_PUSHER_APP_KEY, {
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: false,
    wsHost: window.location.hostname,
    // comment for use port 443
    // wsPort: 6001,
    // wssPort:6001,
    enabledTransports: ["ws", "wss"],
    forceTLS: true,
});

Above setting worked when I upgraded from Laravel 8 (PHP 7.3) to Laravel 9 (PHP 8.2.1)

For Rocky Linux 8.7 same setting is not working so, I'm still looking into it. I hope soon I'll find a perfect solution.

**Comment by maximal** [comment]
I can confirm that `2.x` beta is not working with Laravel 9 and PHP 8.2.

After downgrading `beyondcode/laravel-websockets` to `1.13.2` works fine on modern PHP.

**Comment by kailasb10** [comment]
> I can confirm that `2.x` beta is not working with Laravel 9 and PHP 8.2.
> 
> After downgrading `beyondcode/laravel-websockets` to `^1.13.2` works fine on modern PHP.

This is not work for Rocky Linux8.7 & Red Hat 8.7 it's worked only for Centos OS
