### ISSUE TITLE
GuzzleHttp problem

### ISSUE THREAD

**Issue by Biostate** [beyondcode/laravel-websockets#1086]
Hi, i saw a lot of issues abou guzzle http but these solved issues not solved my problem. I can connect the socket but when i try to dispatch any event it says:
`cURL error 60: SSL certificate problem: self signed certificate`

i tried to add these lines to my broadcasting.php config but it's not worked:

```php
'pusher' => [
  'driver' => 'pusher',
  'key' => env('PUSHER_APP_KEY'),
  'secret' => env('PUSHER_APP_SECRET'),
  'app_id' => env('PUSHER_APP_ID'),
  'options' => [
      'cluster' => env('PUSHER_APP_CLUSTER'),
      'host' => env('PUSHER_HOST', 'api-'.env('PUSHER_APP_CLUSTER', 'mt1').'.pusher.com') ?: 'api-'.env('PUSHER_APP_CLUSTER', 'mt1').'.pusher.com',
      'port' => env('PUSHER_PORT', 443),
      'scheme' => env('PUSHER_SCHEME', 'https'),
      'encrypted' => true,
      'useTLS' => env('PUSHER_SCHEME', 'https') === 'https',
      'curl_options' => [
          CURLOPT_SSL_VERIFYHOST => env('APP_ENV') === "local" ? 0 : 2,
          CURLOPT_SSL_VERIFYPEER => env('APP_ENV') === "local" ? 0 : 1,
      ],
  ],
  'client_options' => [
      // for self signed ssl cert
      'verify' => false, // <- Added this
      // Guzzle client options: https://docs.guzzlephp.org/en/stable/request-options.html
  ],
],
```

I tried to create my own certificate with other techniques but it's not worked neither.

```
"laravel/framework": "^9.0",
"pusher/pusher-php-server": "^7.2",
"beyondcode/laravel-websockets": "^1.13",
```

**Comment by parallels999** [comment]
Already without support

**Comment by maxcelos** [comment]
I'm using with Valet, the only solution I found was update my php.ini using the Valet ca-certificate in openssl.cafile.

Like this: 

```
// php.ini
openssl.cafile = "/Users/[my-user]/.config/valet/CA/LaravelValetCASelfSigned.pem"
```

A better sulution would pass it in the `client_options.verify` but this config is not being used by the package. 

I've suggested this in discussions [here](https://github.com/beyondcode/laravel-websockets/discussions/1110)
