### ISSUE TITLE
Problems with ssl certificate 

### ISSUE THREAD

**Issue by perezL22** [beyondcode/laravel-websockets#1087]
pusher.min.js:8 WebSocket connection to 'wss://********.net:6001/app/qwerrty?protocol=7&client=js&version=4.3.1&flash=false' failed: 
I am having problems with the installation of the ssl certificate can someone help me?

**Comment by ahmedusama250** [comment]
I am facing the same problem, any updates?

**Comment by perezL22** [comment]
check in which ssl extensions you are using, test with crt and if it doesn't work with csr.

**Comment by perezL22** [comment]
I share this example https://github.com/christophrumpel/blog-laravel-real-time-notifications/compare/feature/useTls

**Comment by ahmedusama250** [comment]
What is the version of web-socket you use?
