### ISSUE TITLE
Redis keys for sockets never expire?

### ISSUE THREAD

**Issue by effeks** [beyondcode/laravel-websockets#1088]
Hey!

Running Laravel 9 on PHP 8.1 with laravel-websockets 2.0.0-beta.37, where I use `WEBSOCKETS_REPLICATION_MODE=redis` (two separate servers running websockets, connecting to the same Redis).

I see clients registering fine and ping<>pong messages being sent back and forth.

My problem is that when I inspect the Redis key "<myprefix>:sockets" (using zrangebyscore ...), it looks like the list of sockets are never cleared out, i.e. the list of sockets just keep growing and growing over time. Eventually, my servers will die with a "php fatal error allowed memory size exhausted" as the PHP code is (I assume) trying to fetch the list of sockets and turn it into an array of some kind. By that point, if I simply remove the "<myprefix>:sockets" key in Redis, everything starts to work fine again.

I have also tested locally and here things seems to work fine as the list of sockets is automatically cleaned up, although locally I only run one websockets server.

I'm not super familiar with this package, so any pointers as to where I should start debugging what happens here? Is there a process that runs every now and then which should clear out the list of sockets, or does that happen as new clients register?

Thanks.

**Comment by Arr-n-D** [comment]
Hey @effeks! 
Have you also tried the 1.x version? As far as I know there's a memory leak with Redis. Unfortunately it seems the package is no longer being supported/maintained, so I've made my own fork to try and maintain it all.
