### ISSUE TITLE
Version 2 laravel 10 support

### ISSUE THREAD

**Issue by Temepest74** [beyondcode/laravel-websockets#1102]
Can you add it? I use it because it works way better than v1.

**Comment by websitevirtuoso** [comment]
Looks like nothing can't be done because maintainer didn't visit repo long time.

**Comment by Temepest74** [comment]
Yeah, they abandoned the project. I think i will have to change my websocket implementation soon.

**Comment by SilvioRamirez** [comment]
Any solutions to install in Laravel 10 and PHP 8.2?

**Comment by Temepest74** [comment]
> Any solutions to install in Laravel 10 and PHP 8.2? 

One to use v1 as of now :( i think you can fork it and run Shift by yourself, but I don't know if this will break v2 or not.

**Comment by desthercz** [comment]
V1 dont work with PHP 8.2. Not sure about V2 but i guess same issue.

**Comment by websitevirtuoso** [comment]
use soketi. it has good support and up-to date

**Comment by Linn-Htet123** [comment]
> Any solutions to install in Laravel 10 and PHP 8.2?

I also need it too

**Comment by oxicot** [comment]
Installation issue:

PHP 8.1
Laravel 10

`N504:/var/www/laravel_bouma_ws_example$ composer require beyondcode/laravel-websockets
./composer.json has been updated
Running composer update beyondcode/laravel-websockets
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[1.14.0, ..., 1.14.1] require react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., v1.9.0].
    - beyondcode/laravel-websockets[1.0.0, ..., 1.3.0] require php ^7.1 -> your php version (8.1.2) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.4.0, ..., 1.10.0] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.11.0, ..., 1.13.0] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.9.1] but the package is fixed to 2.6.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/laravel-websockets[1.13.1, ..., 1.13.2] require illuminate/broadcasting ^6.0|^7.0|^8.0|^9.0 -> found illuminate/broadcasting[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - react/http[v1.1.0, ..., v1.9.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets * -> satisfiable by beyondcode/laravel-websockets[1.0.0, ..., 1.14.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-websockets:*" to figure out if any version is installable, or "composer require beyondcode/laravel-websockets:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`
