### ISSUE TITLE
How to use Custom WebSocket Handlers?

### ISSUE THREAD

**Issue by Glarionov** [beyondcode/laravel-websockets#1107]
I'm trying to react to connecting with laravel-websockets.
There are custom handlers  
https://beyondco.de/docs/laravel-websockets/advanced-usage/custom-websocket-handlers

And there are endpoint
```
WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);
```
I don't understand, what I need to do to invoke this reaction?
Do I need to make new connection, using 
```
Echo.join('my-websocket');
```
?
Or I can join to any channel, and this events will be triggered?

**Comment by tahirafridi** [comment]
Their documentation is not clear, they just said setup route like that, but didn't tell after that what to do. How to connect.

**Comment by Glarionov** [comment]
@LAGGOUNE-Walid 
What I need to add on front to "listen" this handler?
Echo.channel('/app/{appKey}').listen(...
?

**Comment by Glarionov** [comment]
@LAGGOUNE-Walid 

Do you mean this key?
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: import.meta.env.VITE_PUSHER_APP_KEY,
```
   What I need to add there?

**Comment by Glarionov** [comment]
@LAGGOUNE-Walid

So after every websocket connection there will be handling through this implemented class?

**Comment by LAGGOUNE-Walid** [comment]
Yes exactly.

**Comment by Glarionov** [comment]
@LAGGOUNE-Walid 
It doesn't work, can you look at my code and tell, what's wrong with it?
I can pay you a little

**Comment by LAGGOUNE-Walid** [comment]
No need to pay . contact me on email and i will see what i can do . 
walidlaggoune159@gmail.com .

also could you close this issue , because it's not a bug .
