### ISSUE TITLE
How do I listen to websockets on the server and do something when the message arrives?

### ISSUE THREAD

**Issue by nekooee** [beyondcode/laravel-websockets#1113]
How do I listen to WebSockets on the server and do something when the message arrives?
I am downloading the file with Guzzle, which you can see below. The file may be large and it may take time to download the file. So I made it possible to cancel while downloading. But now I need to listen to the WebSocket and cancel it on receiving the cancel message. I read on the Internet that this can be done with the `Broadcast::listen` or `Broadcast::on` command. But Laravel does not recognize this command.
It should be noted that in the code below, the download percentage, total bytes, and downloaded bytes are sent correctly. The front-end code is written with Laravel-Echo.

```php
$client = new Client([
                'verify' => false
            ]);
            $promise = $client->requestAsync('GET', $requestUrl, [
                'headers' => [
                    'Origin' => '*',
                    'Access-Control-Request-Method' => 'GET',
                    'Access-Control-Allow-Headers' => 'Origin, Content-Type, Accept, Authorization',
                ],
                'sink' => storage_path("app/$path/{$mediaFullName}"),
                'progress' => function ($totalBytes, $downloadedBytes): void {
                    if ($totalBytes > 0) {
                        $percentage = round(($downloadedBytes / $totalBytes) * 100, 2);
                        // Send progress information to Vue using Server-Sent Events
                        downloadProgress::dispatch($percentage, $totalBytes, $downloadedBytes);
                    }
                }
            ]);

            try {
                Broadcast::listen('download-progress', function ($data) use($url, $promise) {
                  $promise->cancel();
                });
               $promise->wait();
            } catch (RequestException $e) {
                // Handle the exception here
            } catch (Throwable $e) {
            }
```

**Comment by filippotoso** [comment]
The easiest way to achive your objective is to:

1. Create an API endpoint that is called from the frontend when the user needs to cancel the download.
2. When it's called, save in the cache a "cancel command" with an unique ID (ie. your $requestUrl)
3. In the progress callback, check for the cache and cancel the promise if exists.

Otherwise you have to use a websocket client to listen to websockets events:
https://github.com/Textalk/websocket-php/blob/HEAD/docs/Client.md

**Comment by nekooee** [comment]
> The easiest way to achive your objective is to:
> 
> 1. Create an API endpoint that is called from the frontend when the user needs to cancel the download.
> 2. When it's called, save in the cache a "cancel command" with an unique ID (ie. your $requestUrl)
> 3. In the progress callback, check for the cache and cancel the promise if exists.
> 
> Otherwise you have to use a websocket client to listen to websockets events: https://github.com/Textalk/websocket-php/blob/HEAD/docs/Client.md

Using cache was a very good idea. Thank
