### ISSUE TITLE
Dependency vulnerability

### ISSUE THREAD

**Issue by ikechukwukalu** [beyondcode/laravel-websockets#1115]
According to [Snyk](https://security.snyk.io/vuln/SNYK-PHP-GUZZLEHTTPPSR7-2431148) the version of a particular dependency (`guzzlehttp/psr7`) you are utilising is vulnerable.

**Comment by parallels999** [comment]
https://github.com/beyondcode/laravel-websockets/discussions/1038#discussioncomment-4905548
