### ISSUE TITLE
The requested URL /apps/1234/events was not found on this server.

### ISSUE THREAD

**Issue by eichgi** [beyondcode/laravel-websockets#112]
I created an event which implements ShouldBrodcast but form some reason when I launch the event I got the error:

**The requested URL /apps/1234/events was not found on this server.**

I already setup the package with the next credentials:

PUSHER_APP_ID=123456
PUSHER_APP_KEY=ABCDEF
PUSHER_APP_SECRET=GHIJKL
PUSHER_APP_CLUSTER=mt1

And when I enter to the websockets dashboard it's working. 

I hope you can help me out here

**Comment by brayortepla12** [comment]
Buenas, cual fue la solución a tu problema ?
