### ISSUE TITLE
Improve support for current project.

### ISSUE THREAD

**Issue by websitevirtuoso** [beyondcode/laravel-websockets#1122]
We all can see that the current state of this package is a bit out of date.

Would be great to get extended permissions to maintain this great project.
I think many people 2-3 people could get extended permissions and help with PR, issues

I hope owner of this package will check my thread

**Comment by parallels999** [comment]
Already abandoned

**Comment by Arr-n-D** [comment]
Trying to move support over to my fork @websitevirtuoso 
https://github.com/Arr-n-D/laravel-websockets
