### ISSUE TITLE
Is this package still alive?

### ISSUE THREAD

**Issue by billyjustal** [beyondcode/laravel-websockets#1124]
Hey Guys,

just wanted to drop in and see if this package is still being worked on?

**Comment by tpharaoh** [comment]
I believe it is, there is a lot of traffic on the email...

However, I followed this guide and implemented another way
https://blog.laravel.com/deploying-soketi-to-laravel-forge

**Comment by billyjustal** [comment]
i already have it set up.

just wondering if it is still being maintained.

**Comment by Temepest74** [comment]
Sadly but no. No one check the issues anymore. just look here 
https://github.com/beyondcode/laravel-websockets/issues/1122
And here, the last update was in oct last year https://github.com/beyondcode/laravel-websockets/discussions/1038#discussioncomment-3793477

**Comment by parallels999** [comment]
Already abandoned

**Comment by huyc27** [comment]
So bad
