### ISSUE TITLE
Websocket is not running, could not able to debug

### ISSUE THREAD

**Issue by skodilkar** [beyondcode/laravel-websockets#1127]
Hi everyone,
I've implemented websockets with pusher replacement successfully on my system. However sometimes when I am installing it on dev servers it seems, websocket is not starting. Its only showing plain message as 'Starting the WebSocket server on port 6001..." .
I am not able to understand the reasons & don't know how to debug as no error messages are being shown from this package. Can anybody advice?

For your information,
my dev server IP is local network ie. 192.168.X.X  & pusher port 6001.
No SSL etc. Its plain. 
SITE_URL/laravel-websockets also not able to connect. So my understanding is websocket is not correctly starting.

Any clue would be great help to me.
Thanks

**Comment by parallels999** [comment]
Already abandoned

**Comment by skodilkar** [comment]
Hi Parallels999,
I didn't catch you. Could you please help me understanding.

**Comment by Arr-n-D** [comment]
Hello @skodilkar, are you using a Docker container to run your application? If so, make sure you forward your ports in your docker-compose 
```
 ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '6001:6001'
            ```
