### ISSUE TITLE
100% CPU Issue - Has anyone got a solution?

### ISSUE THREAD

**Issue by jonboywhite** [beyondcode/laravel-websockets#1134]
Hi,
This project is great but I cant seem to find a solution for my CPU suddenly maxing out at 100% every few minues. I have tried various different php versions, laravel versions and laravel-websockets versions but still encounter the same problem. Im curently restarting the service every 5 minutes to resolve this but it isnt really a fix as such.

My composer.json looks like this
`"require": {
        "php": "^8.1",
        "beyondcode/laravel-websockets": "^1.14",
        "clue/redis-react": "^2.4",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "predis/predis": "*",
        "pusher/pusher-php-server": "5.0.x-dev"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },`
 
if Anyone has a solution I would greatly appresciate some advice.

Kind regards
Jon

**Comment by Arr-n-D** [comment]
Hello @jonboywhite, what version are you using? Are you using this through Redis? If I'm not mistaken, there is currently a memory leak via Redis where the socket number keeps growing until the key is deleted. I've taken upon myself to take support on my repository, which can be found here. I hope to provide support and maintain the package over there. 
https://github.com/Arr-n-D/laravel-websockets

**Comment by jonboywhite** [comment]
Hi @Arr-n-D 
Thanks for taking the time to reply to my question. Im using 1.14 but I have tried all the recent V1 versions and the recent V2 versions and Im still encountering the issue.

I am not using this directly through Redis I am just starting from supervisor like this

command=/usr/bin/php /var/www/laravel/artisan websockets:serve --port=8443

I then have a second service that runs through redis and broadcasts events to the websocket server.

The websocket server appears to be the issue and there is no gradual buildup of CPU usage, it sits around 5% then suddenly jumps to 99% and stays there until restarted. The more traffic the faster this happens. Im using SSL and everything apart from this issue works like a dream.

**Comment by jonboywhite** [comment]
Hi 
Sorry for late reply

`namespace App\Console\Commands;

use Illuminate\Console\Command;
use \Clue\React\Redis\Factory;
use Libs\Events\TrackingPing;
use Libs\Transformers\TrackingPingTransformer;

use Libs\Services\RedisService;

class EventWorker extends Command
{
    
    protected $signature = 'eventworker';
    
    protected $description = 'Command description';

    const EVENT_KEY = '??????????';
    
    public function __construct(RedisService $redisService, TrackingPingTransformer $transformer)
    {
        $this->transformer = $transformer;
        $this->redisService = $redisService;
        $this->redisService->setListKey(static::EVENT_KEY);
        parent::__construct();
    }
    
    public function handle()
    {
        $this->info('EventWorker Starting');
        $this->redisService->setDatabase(8);
        $this->loop = \React\EventLoop\Loop::get();
        $this->factory = new Factory($this->loop);
        $this->info('EventWorker Started');
        $this->loop->addPeriodicTimer(1 , function () {
            $data = $this->redisService->getRange(50);
            if(!empty($data)) {
                $eventArray = [];
                foreach($data as $event) {
                    if($event) {
                        $event = $this->transformer->item(unserialize($event)['data']);
                        $eventArray[$event['event_id']][] = $event;
                    }
                }
                foreach ($eventArray as $key => $event) {
                    $toWebsockets = [
                      'event_id' => $key,
                      'data' => $event
                    ];
                    event(new TrackingPing($toWebsockets));
                }
            }
        });
        $this->loop->run();
    }
}`

**Comment by Arr-n-D** [comment]
Hey @jonboywhite , could you show me example data of what $this->redisService->getRange returns?

**Comment by Arr-n-D** [comment]
I've seen to have managed to recreate your high CPU usage when sending a LOT of events through the EventWorker, here's the code that I used
![image](https://github.com/beyondcode/laravel-websockets/assets/5721042/3d5a651e-d0f9-46b0-8bbd-62595a561dac)

Messages are sent through pusher
Connection id 966065911.462007246 sending message {"event":"log-message","channel":"private-websockets-dashboard-api-message","data":{"type":"api-message","time":"20:10:27","details":"Channel: trades, Event: App\\Events\\TrackingPing","data":"[]"}}

**Comment by Arr-n-D** [comment]
Hey @jonboywhite 

Just wanted to check in with you on something. So, after testing things out, I noticed that when I bombard my web socket server with a ton of data and run the loop (service) without involving Redis, the CPU usage shoots up to 100%. However, when I dispatch messages or events from a node process, it doesn't seem to affect the CPU over 35% usage, which seems acceptable to me.

Could you do me a favor and double-check if your Redis service is running properly, on Redis itself? Apart from that, everything looks good to me and seems like a non-issue

Thanks!

**Comment by jonboywhite** [comment]
Hi @Arr-n-D 
Sorry Ive been off with a nasty case of gastroenteritis for the last 36 hours. Very unpleasant. I will check my redis service but Im sure its working correctly. What exactly should i be looking for?

**Comment by Arr-n-D** [comment]
Hey @jonboywhite , sorry to hear about that, hope you're getting better. 

I apologize, I made a mistake in my previous comment. Although your Redis service is working properly, I have it in good faith that it is your EventWorker loop that creates the high CPU usage. If you were to split the EventWorker into a different Laravel application, you would probably see it reach 100% CPU usage as well. 

Could you perhaps try and run your EventWorker code via a Redis queue? See if the CPU still rockets?
