### ISSUE TITLE
Only user ids are returned when fetching user info

### ISSUE THREAD

**Issue by medvesekg** [beyondcode/laravel-websockets#1136]
When calling `get_users_info()` from the pusher client only the user ids are returned. 
This is the relevant code snippet:
https://github.com/beyondcode/laravel-websockets/blob/1f25913ce05c66bbff1f925106bf9490ec0eb3bf/src/API/FetchUsers.php#L23-L33

It would be very useful to receive all the info about the users.

**Comment by Arr-n-D** [comment]
> 



> When calling `get_users_info()` from the pusher client only the user ids are returned. This is the relevant code snippet:
> 
> https://github.com/beyondcode/laravel-websockets/blob/1f25913ce05c66bbff1f925106bf9490ec0eb3bf/src/API/FetchUsers.php#L23-L33
> 
> It would be very useful to receive all the info about the users.

Considering this would be simply for your use case, why not implement your own FetchUser?
