### ISSUE TITLE
Statistics logging not working in docker environment

### ISSUE THREAD

**Issue by francislavoie** [beyondcode/laravel-websockets#114]
The fix in #31, i.e. DNS resolver, doesn't solve the issue for me.

The problem is that `action()` is used in `HttpStatisticsLogger` to push the stats. This is an issue for me, because the URL for HTTP is different for internal services than external users. Since the websockets server is running in its own container, I need it to reach out directly to my webserver container for it to work.

In this case, I have a `websockets` container and a `caddy` container, so I need `HttpStatisticsLogger` to make requests to `http://caddy` or whatever that IP resolves to (using Docker's DNS resolver).

Should we add an `config('url')` override as a config option? I think that might be the simplest way to solve this. I don't think it's a correct assumption that APP_URL will always allow a backend service to connect to itself.

**Comment by pactode** [comment]
Any updates on this? I have the same issue.

**Comment by francislavoie** [comment]
See #115, I wrote a simple implementation. We're stuck waiting until the project maintainers take a look at the open PRs.

In the meantime, you could just make your own fork with those changes if you urgently need them (or directly edit the code in vendor/ but that's a very temporary solution)

**Comment by pactode** [comment]
@francislavoie Thanks. I want to push for a more permanent solution, so I'll support your PR.

**Comment by francislavoie** [comment]
@canhkieu this is not resolved, the PR is not merged. Why are you closing so many issues today?
