### ISSUE TITLE
Unable to install in latest laravel release

### ISSUE THREAD

**Issue by l3aro** [beyondcode/laravel-websockets#1140]
![image](https://github.com/beyondcode/laravel-websockets/assets/25253808/288d7424-baa4-4bb8-af58-f481dbbf30b7)

Package no longer can be installed in the latest Laravel 10. Its dependencies are falling behind too much. 
I believe this PR can fix this. But there is no active on this project :<
https://github.com/beyondcode/laravel-websockets/pull/1092

**Comment by mpociot** [comment]
You can install the package in the latest version of Laravel just fine by passing the `-W` flag to composer

```
composer require beyondcode/laravel-websockets -W
```

**Comment by l3aro** [comment]
tks for reply
