### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by imkonsowa** [beyondcode/laravel-websockets#1141]
I'm starting a new big Laravel project that needs real-time communications, This package has been my first choice for every project of that kind, but it seems to be abandoned. 

Are there any maintained alternatives out there? Or this one will be working fine?

**Comment by mpociot** [comment]
Version 1.x works fine - and if you ever need a different WS solution, it's easy to swap it out with something like Soketi, Pusher or Ably.
