### ISSUE TITLE
Getting Websocket React Error Log, How to fix this issue?

### ISSUE THREAD

**Issue by Soe-Moe** [beyondcode/laravel-websockets#1142]
When i run php artisan websockets:serve, websockets is normally working but I getting React error in log.
I using Vuejs + Laravel, not using React. Why?

Error message > Unhandled promise rejection with TypeError: Argument 1 passed to React\Http\Io\ClientRequestStream::closeError() must be an instance of Exception, instance of TypeError given, called in /Users/SoeMoe/DevProjects/titi/vendor/react/promise/src/Internal/RejectedPromise.php on line 73 in /Users/SoeMoe/DevProjects/titi/vendor/react/http/src/Io/ClientRequestStream.php:238

<img width="1438" alt="Screenshot 2023-07-28 at 1 08 43 PM" src="https://github.com/beyondcode/laravel-websockets/assets/28599778/d95c19ec-a0d9-4d19-bf47-9d4960775b6c">

**Comment by malau1** [comment]
I have the same problem in Laravel 10.

**Comment by khoazero123** [comment]
Workaround solution work for me:
```
composer require react/promise:^2.3
```

The origin exception cause the problem is `Class "React\Promise\FulfilledPromise" not found` in `vendor/beyondcode/laravel-websockets/src/Statistics/DnsResolver.php:32`
`react/promise` in version 3x has [removed that class](https://reactphp.org/promise/changelog.html).

react/http required `"react/promise": "^3 || ^2.3 || ^1.2.1",`

**Comment by Soe-Moe** [comment]
That works for me.
Thanks for your answer @khoazero123

**Comment by rehmatweb** [comment]
> Workaround solution work for me:
> 
> ```
> composer require react/promise:^2.3
> ```
> 
> The origin exception cause the problem is `Class "React\Promise\FulfilledPromise" not found` in `vendor/beyondcode/laravel-websockets/src/Statistics/DnsResolver.php:32` `react/promise` in version 3x has [removed that class](https://reactphp.org/promise/changelog.html).
> 
> react/http required `"react/promise": "^3 || ^2.3 || ^1.2.1",`

thanks you it worked for me this problem take my 2 days

**Comment by AlejandroCabezaCarsi** [comment]
WOOOOW, thank yoy very much. It fixed the problem! This error took me 3 days.

**Comment by rehmatweb** [comment]
Glad to hear it!
