### ISSUE TITLE
How to fix "WebSocket connection to 'wss://.....' failed: WebSocket is closed before the connection is established." ERROR ???

### ISSUE THREAD

**Issue by chegmarco1989** [beyondcode/laravel-websockets#1143]
Hello.

After installing with `composer` (_in our "**composer.json**"_):
```
"beyondcode/laravel-websockets": "^1.12",
"pusher/pusher-php-server": "^7.2",
"laravel/framework": "^9.51"
```

And, OPEN Port `3030` by doing: `ufw allow 3030` in our Ubuntu Terminal.

Knowing that our Laravel's `.env` file contains this description:
```
PUSHER_APP_ID="........................."
PUSHER_APP_KEY="......................."
PUSHER_APP_SECRET=".........................."
PUSHER_APP_CLUSTER="........................."
LARAVEL_WEBSOCKETS_HOST="domain.name"
LARAVEL_WEBSOCKETS_PORT=3030
LARAVEL_WEBSOCKETS_KEY="${PUSHER_APP_KEY}"
LARAVEL_WEBSOCKETS_CLUSTER="${PUSHER_APP_CLUSTER}"
```

**And AFTER LAUCHING:** `php artisan websockets:serve --port=3030`, WE GET THIS FOLLOWING ERROR:

`WebSocket connection to 'wss://.....:3030/app/...............?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established.`

**Can anyone help us please to run our WebSocket please ???**

**Comment by ZnarKhalil** [comment]
We had the same issue and turned out that we had wrong ssl configuration in the config/websockets.php
`'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => 'path_to_your_certificate',

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => 'path_to_your_key',

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => 'add_correct_passphrase',
        'verify_peer' => false,
    ],`

**Comment by nabil12ful** [comment]
i have this error

**Comment by chegmarco1989** [comment]
The error disappeared only you put your own Pusher.com credentials. I thought that Laravel-websoket is stand-alone ???

**Comment by ZnarKhalil** [comment]
> The error disappeared only you put your own Pusher.com credentials. I thought that Laravel-websoket is stand-alone ???

No, you don't need credentials from pusher.com, you could just add any 
as an example
`PUSHER_APP_ID=staging
PUSHER_APP_KEY=staging
PUSHER_APP_SECRET=staging
PUSHER_APP_CLUSTER=mt1`

**Comment by chegmarco1989** [comment]
> No, you don't need credentials from pusher.com, you could just add any as an example `PUSHER_APP_ID=staging PUSHER_APP_KEY=staging PUSHER_APP_SECRET=staging PUSHER_APP_CLUSTER=mt1`

Doing that, it returns us that error: `WebSocket connection to 'wss://.....:3030/app/...............?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established.`

**Comment by ZnarKhalil** [comment]
> > No, you don't need credentials from pusher.com, you could just add any as an example `PUSHER_APP_ID=staging PUSHER_APP_KEY=staging PUSHER_APP_SECRET=staging PUSHER_APP_CLUSTER=mt1`
> 
> Doing that, it returns us that error: `WebSocket connection to 'wss://.....:3030/app/...............?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established.`

for us we where using 
```
'useTLS' => true,
'encrypted' => true,
```
and what we were missing first was the proper ssl certificate and key with the correct passphrase the certificate was generated with, doing that solved the issue for us.

and we had below  code in bootstrap.js file

import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: WEBSOCKET_HOST, // change this to you websocket host 
    wsPort: 6001,
    wssPort: 6001,
    forceTLS: true,
    enabledTransports: ['ws', 'wss'],
});
```

**Comment by chegmarco1989** [comment]
Are we necessarily need that Laravel-Echo and pusher-js ??? Because we did not install them

**Comment by ZnarKhalil** [comment]
> Are we necessarily need that Laravel-Echo and pusher-js ??? Because we did not install them

Then how do you listen to the broadcast event on the frontend, maybe there is other libraries, but we followed the official [laravel docs](https://laravel.com/docs/10.x/broadcasting#receiving-broadcasts)

what laravel websockets does is that it replace the pusher server, so you don't need to connect to Pusher (paid) instead you connect to laravel websocket (your own websockets)

**Comment by chegmarco1989** [comment]
We only used in `config/brodcasting.php`, this:

```
'pusher' => [
			'driver' => 'pusher',
			'key' => env('PUSHER_APP_KEY'),
			'secret' => env('PUSHER_APP_SECRET'),
			'app_id' => env('PUSHER_APP_ID'),
			'options' => [
				'cluster' => env('PUSHER_APP_CLUSTER'),
				'encrypted' => true,
				'host' => 'localhost',
				'port' => 6001,
				'scheme' => 'http'
			],
		],
```
Despite that configuration in `config/brodcasting.php`, we get this error: 

`WebSocket connection to 'wss://.....:3030/app/...............?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established`.

Do you think it's insufficient ???

**Comment by ZnarKhalil** [comment]
> We only used in `config/brodcasting.php`, this:
> 
> ```
> 'pusher' => [
> 			'driver' => 'pusher',
> 			'key' => env('PUSHER_APP_KEY'),
> 			'secret' => env('PUSHER_APP_SECRET'),
> 			'app_id' => env('PUSHER_APP_ID'),
> 			'options' => [
> 				'cluster' => env('PUSHER_APP_CLUSTER'),
> 				'encrypted' => true,
> 				'host' => 'localhost',
> 				'port' => 6001,
> 				'scheme' => 'http'
> 			],
> 		],
> ```
> 
> Despite that configuration in `config/brodcasting.php`, we get this error:
> 
> `WebSocket connection to 'wss://.....:3030/app/...............?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established`.
> 
> Do you think it's insufficient ???

Here you have the port set to be 6001 and in your websockets section above in your question the port is 3030 so make sure you use the same port for the broadcasting and websockets.
and use pusher.js and echo only if you need to get to subscribe to the event in the frontend.

below is our broadcasting configuration, check it may help:
```

'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => true,
                'host' => 'yourdomain.com', // replace with your own domain
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
```

and websockets.php
```

return [

    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => true,
            'enable_statistics' => true,
        ],
    ],

    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,

    'allowed_origins' => [
        //
    ],

    'max_request_size_in_kb' => 250,

    'path' => 'laravel-websockets',

    'statistics' => [
	WebSocketsStatisticsEntry` provided by this package.
         */
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,

        'interval_in_seconds' => 60,

        'delete_statistics_older_than_days' => 60,

        'perform_dns_lookup' => false,
    ],

    'ssl' => [

        'local_cert' => 'path_to_your_ssl', // replace with your own

        'local_pk' => 'path_to_your_ssl.key', // replace with your own

        'passphrase' => 'ssl_password', // replace with your own
        'verify_peer' => false,
    ],
];
```

**Comment by chegmarco1989** [comment]
Thanks for your answer. Now we got the following error:

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
WebSocket connection to 'wss://ourdomain.com:6001/app/b646bff9a1113f3de9f51989?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established.

However, we have already executed `php artisan websockets:serve`.

Do I forgot somethink ???

**Comment by nabil12ful** [comment]
check this port is opened in your server

**Comment by nabil12ful** [comment]
> The error disappeared only you put your own Pusher.com credentials. I thought that Laravel-websoket is stand-alone ???

yes

**Comment by chegmarco1989** [comment]
> check this port is opened in your server

YES it is open

**Comment by viral-3dsurgicals** [comment]
Same here. 
Tried all possible solutions from almost all places on web.
- Tried Different ports. ie. :6002
- Inboud Security allow allow traffic from :6001.
- Configured EC2 Multiple time
- Verified SSL certificate path and permission

![websocket_image_2023_08_03T12_43_48_766Z](https://github.com/beyondcode/laravel-websockets/assets/111500457/58bd16d3-c42b-41e5-b80b-c8d66179b809)

**Comment by HasmukhG** [comment]
In aws ec2 instance with apache2 production mode laravel websocket show failed to connect error and chat is not working try multiple solution found over internet but still getting protocol=7&client=js&version=7.6.0&flash=false' failed error so please help me on that.

**Comment by Faxriddin077** [comment]
Hi everyone.

I have the same error, I did several config combinations. This is my last config:

"beyondcode/laravel-websockets": "^1.13",
"pusher/pusher-php-server": "7.0.2",

**I generated SSL by using OpenSSL on Mac by passing country, region, city,...common-name, email.... but not inserting password (phrase)**


**config/broadcasting.php**

'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => env('PUSHER_HOST'),
                'port' => env('PUSHER_PORT', 6001),
                'scheme' => env('PUSHER_SCHEME', 'https'),
                'forceTLS' => env('PUSHER_SCHEME') == 'https', // I wrote only forceTLS, only useTLS, useTLS and forceTLS
                'useTLS' => env('PUSHER_SCHEME') == 'https',  // 3 combination
                'encrypted' => true,
                'disableStats' => true,
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
            'curl_options' => [
                CURLOPT_SSL_VERIFYHOST => 0,
                CURLOPT_SSL_VERIFYPEER => 0,
            ],

        ],


**config/weboscket.php** (here is main params, other params are default)

'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => true,
            'enable_statistics' => true,
        ],
    ],
'ssl' => [
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
        'verify_peer' => false,
    ],

**.env**

BROADCAST_DRIVER=pusher
PUSHER_HOST="mydomain.local"
PUSHER_APP_PATH='/key'
PUSHER_APP_CLUSTER="bp"
PUSHER_APP_ID=12345
PUSHER_APP_KEY=12345
PUSHER_APP_SECRET=12345
PUSHER_SCHEME="https"
PUSHER_PORT=6001

LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT="../path/cert.pem"
LARAVEL_WEBSOCKETS_SSL_LOCAL_PK="../path/private-key.key"

**Comment by matiazar** [comment]
@HasmukhG did you fix it ?

**Comment by HasmukhG** [comment]
No

**Comment by matiazar** [comment]
@HasmukhG open the port on the server

**Comment by Faxriddin077** [comment]
I fixed this error. In my case it is related to certificate file. Because firstly I generated self signed certificate for my local, I think there were several incorrect  configs while generating. And so I got working certificate from production. And configured it to my local environment and this is worked

**Comment by imuhammadjabbar** [comment]
Is anyone able to resolve this issue?

**Comment by liza-nt** [comment]
> just change forceTLS: false and PUSHER_SCHEME=http only in local

what about production enviromnent

**Comment by MadhuSujan93** [comment]
> Hello.
> 
> After installing with `composer` (_in our "**composer.json**"_):
> 
> ```
> "beyondcode/laravel-websockets": "^1.12",
> "pusher/pusher-php-server": "^7.2",
> "laravel/framework": "^9.51"
> ```
> 
> And, OPEN Port `3030` by doing: `ufw allow 3030` in our Ubuntu Terminal.
> 
> Knowing that our Laravel's `.env` file contains this description:
> 
> ```
> PUSHER_APP_ID="........................."
> PUSHER_APP_KEY="......................."
> PUSHER_APP_SECRET=".........................."
> PUSHER_APP_CLUSTER="........................."
> LARAVEL_WEBSOCKETS_HOST="domain.name"
> LARAVEL_WEBSOCKETS_PORT=3030
> LARAVEL_WEBSOCKETS_KEY="${PUSHER_APP_KEY}"
> LARAVEL_WEBSOCKETS_CLUSTER="${PUSHER_APP_CLUSTER}"
> ```
> 
> **And AFTER LAUCHING:** `php artisan websockets:serve --port=3030`, WE GET THIS FOLLOWING ERROR:
> 
> `WebSocket connection to 'wss://.....:3030/app/...............?protocol=7&client=js&version=7.6.0&flash=false' failed: WebSocket is closed before the connection is established.`
> 
> **Can anyone help us please to run our WebSocket please ???**

Hii is this issue resolved if yes can you please tell me I am also facing same error?

**Comment by MadhuSujan93** [comment]
Hii is this issue resolved if yes can anyone please help me I am also facing same errror

**Comment by SMDEVIGH** [comment]
Could someone assist me? I'm encountering a similar issue involving Laravel 9, Vue.js, and Vite on a VPS using CloudPanel.

**Comment by chegmarco1989** [comment]
I I didn't use Laravel-websocket anymore. I finally decided on “Pusher”. Thanks

**Comment by caendesilva** [comment]
This package does not seem to be compatible with Herd when using a secure URL. If you have problems when using Herd, try visiting through `php artisan serve`.

**Comment by jdthehelper** [comment]
For ssl issue we have to create ssl certificate in local system and you can check i have give all step by step example.
https://myphpinformation.blogspot.com/2024/01/laravel-websocket-setup-and-example-how-to-use-it.html
