### ISSUE TITLE
Exception `InvalidArgumentException`

### ISSUE THREAD

**Issue by pajkho** [beyondcode/laravel-websockets#1146]
In some instances the following error is thrown:

Exception `InvalidArgumentException` thrown: `Expected a scalar value as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::get()", "array" given.

I believe this is due to Symfony no longer accepting scalar default values in inputBag which is used in TriggerEventController.php on line 19.

**Comment by judgej** [comment]
Been tearing my hair out on this one. It is Symfony 6 that no longer accepts non-scalars as a default (doesn't seem to be able to get non-scalars either).

I'm using Laravel 9, which pulls on Symfony 6, broadcasting an event to more than one channel:

```php
// App\Events\OrderUpdated:

    public function broadcastOn()
    {
        return [
            new Channel(sprintf('order.%s', $this->orderUuid)),
            new Channel(sprintf('order')),
        ];
    }
```

If either channel is commented out, so the event is broadcast to just one channel, then the broadcast works. With two or more it fails with the OP exception message logged to `stderr`, then hangs, presumably in some kind of loop.

The code in question is:

```php
// BeyondCode\LaravelWebSockets\HttpApi\Controllers\TriggerEventController:

    public function __invoke(Request $request)
    {
        $this->ensureValidSignature($request);
        $payload = $request->json();

        if ($payload->has('channel')) {
            $channels = [$payload->get('channel')];
        } else {
            $channels = $payload->get('channels', []); // <<< this array here

            if (is_string($channels)) {
                $channels = [$channels];
            }
        }
...
```
```

This is passed to Symfony's `InputBag()` that does not like the non-scalar default.

I tried removing the default, but then Symfony complains about the array in the payload.

The workaround is to limit each event to one broadcast channel. That means doubling up some events, so I may have to dispatch for example `OrderUpdatedEvent` and `AnyOrderUpdatedEvent` to send to two channels.

**Comment by pajkho** [comment]
I have submitted a PR to fix this issue. @mpociot could you take a look at it?

**Comment by rehmatweb** [comment]
php artisan websockets:serve it give me te error

Unhandled promise rejection with TypeError: React\Http\Io\ClientRequestStream::closeError(): Argument #1 ($error) must be of type Exception, Error given, 
called in C:\Users\touse\Desktop\pj_backend_new\vendor\react\promise\src\Internal\RejectedPromise.php on line 73 in C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\ClientRequestStream.php:238
Stack trace: 


#0 C:\Users\touse\Desktop\pj_backend_new\vendor\react\promise\src\Internal\RejectedPromise.php(73): React\Http\Io\ClientRequestStream->closeError(Object(Error))
#1 C:\Users\touse\Desktop\pj_backend_new\vendor\react\promise\src\Promise.php(43): React\Promise\Internal\RejectedPromise->then(Object(Closure), Array)   
#2 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\ClientRequestStream.php(100): React\Promise\Promise->then(Object(Closure), Array)       
#3 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\ClientRequestStream.php(122): React\Http\Io\ClientRequestStream->writeHead()
#4 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\ClientRequestStream.php(135): React\Http\Io\ClientRequestStream->write('{"app_id":"anyi...')
#5 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\Sender.php(152): React\Http\Io\ClientRequestStream->end('{"app_id":"anyi...')
#6 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\Transaction.php(146): React\Http\Io\Sender->send(Object(React\Http\Message\Request))    
#7 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Io\Transaction.php(83): React\Http\Io\Transaction->next(Object(React\Http\Message\Request), Object(React\Promise\Deferred), Object(React\Http\Io\ClientRequestState))   
#8 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Browser.php(854): React\Http\Io\Transaction->send(Object(React\Http\Message\Request))      
#9 C:\Users\touse\Desktop\pj_backend_new\vendor\react\http\src\Browser.php(176): React\Http\Browser->requestMayBeStreaming('POST', 'http://localhos...', Array, Object(GuzzleHttp\Psr7\Stream))
#10 C:\Users\touse\Desktop\pj_backend_new\vendor\beyondcode\laravel-websockets\src\Statistics\Logger\HttpStatisticsLogger.php(84): React\Http\Browser->post('http://localhos...', Array, Object(GuzzleHttp\Psr7\Stream))
#11 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(353): BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger->save()
#12 C:\Users\touse\Desktop\pj_backend_new\vendor\beyondcode\laravel-websockets\src\Console\StartWebSocketServer.php(75): Illuminate\Support\Facades\Facade::__callStatic('save', Array)
#13 C:\Users\touse\Desktop\pj_backend_new\vendor\react\event-loop\src\Timer\Timers.php(101): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->BeyondCode\LaravelWebSockets\Console\{closure}(Object(React\EventLoop\Timer\Timer))
#14 C:\Users\touse\Desktop\pj_backend_new\vendor\react\event-loop\src\StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
#15 C:\Users\touse\Desktop\pj_backend_new\vendor\cboden\ratchet\src\Ratchet\Server\IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#16 C:\Users\touse\Desktop\pj_backend_new\vendor\beyondcode\laravel-websockets\src\Console\StartWebSocketServer.php(155): Ratchet\Server\IoServer->run()  
#17 C:\Users\touse\Desktop\pj_backend_new\vendor\beyondcode\laravel-websockets\src\Console\StartWebSocketServer.php(52): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->startWebSocketServer()
#18 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->handle()
#19 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#21 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))  
#22 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Console\Command.php(211): Illuminate\Container\Container->call(Array)   
#24 C:\Users\touse\Desktop\pj_backend_new\vendor\symfony\console\Command\Command.php(326): Illuminate\Console\Command->execute(Object(Symfony\Component\o 
nsole\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#25 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Console\Command.php(181): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#26 C:\Users\touse\Desktop\pj_backend_new\vendor\symfony\console\Application.php(1081): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))     
#27 C:\Users\touse\Desktop\pj_backend_new\vendor\symfony\console\Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(BeyondCode\LaravelWebSockets\Console\StartWebSocketServer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 C:\Users\touse\Desktop\pj_backend_new\vendor\symfony\console\Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 C:\Users\touse\Desktop\pj_backend_new\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(201): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 C:\Users\touse\Desktop\pj_backend_new\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 {main}
anyid: connection id 118175893.689032531 received message: {"event":"pusher:ping","data":{}}.
Connection id 118175893.689032531 send

**Comment by phpmac** [comment]
look this 

https://github.com/beyondcode/laravel-websockets/issues/1158

you need install fix this error

```sh

composer require react/promise:^2.3


```

please close this,

**Comment by rehmatweb** [comment]
thanks

**Comment by rehmatweb** [comment]
my issue solved

**Comment by judgej** [comment]
I have `react/promise` 2.10.0 installed, and this error is present in Laravel 9. Also have:

* `symfony/http-foundation` v6.3.2
* `beyondcode/laravel-websockets` 1.14.0

**Comment by rehmatweb** [comment]
@judgej i have removed this error after installing the react/promise package. I also change the pusher version.
Note: i am using laravel 10 version and php 8.1 version and sympony 6.2, react/promise :2.3

**Comment by judgej** [comment]
You have removed a *different* error. It's not the same error, and is not against the same package.

**Comment by rehmatweb** [comment]
have you make the persistent connection using web sockets?

**Comment by pedrophsms** [comment]
> In some instances the following error is thrown:
> 
> Exception `InvalidArgumentException` thrown: `Expected a scalar value as a 2nd argument to "Symfony\Component\HttpFoundation\InputBag::get()", "array" given.
> 
> I believe this is due to Symfony no longer accepting scalar default values in inputBag which is used in TriggerEventController.php on line 19.

Did you have fix it? Im facing the same error

**Comment by pajkho** [comment]
Downgrading the dependency only works as a temporary fix as eventually we have to upgrade the package. 


@mpociot @freekmurze do you have any update on this? Let me know if I can assist in any way to get this fixed.

**Comment by m-pastuszek** [comment]
Can we consider this package as archive?

No support, no patches and updates.
Do we have any alternatives or forks?
