### ISSUE TITLE
How to fix "403 | FORBIDDEN" error that prevent "/laravel-websockets" route of my domain (webserver) ???

### ISSUE THREAD

**Issue by chegmarco1989** [beyondcode/laravel-websockets#1148]
Hello.

I installed Laravel-websockets successfully on Ubuntu 20.04 LTS. 
But when I try to access `/laravel-websockets` route, I get **403 | FORBIDDEN** Error as you can see on the following screenshot:

![image](https://github.com/beyondcode/laravel-websockets/assets/51763985/09bbac4c-5e88-48e9-b50c-f46ee6bc8718)

What is wrong with me ???
How to access this `/laravel-websockets` of my Webserver ???

**Comment by FahrenheitIndi** [comment]
Change APP_ENV. It's work only local env

**Comment by chegmarco1989** [comment]
Thanks
