### ISSUE TITLE
Custom Routes (WebSocketsRouter::webSocket) Never Registered

### ISSUE THREAD

**Issue by erwinclloh** [beyondcode/laravel-websockets#1149]
Laravel : 8.83.27
Laravel - Websocket : 1.14.0

please help,

try to follow this documentation to add custom routes,
https://beyondco.de/docs/laravel-websockets/advanced-usage/custom-websocket-handlers

it's working when I put on AppServiceProvider, but I need that customRoutes can be adding at web.php

**Comment by a2mdigital** [comment]
I have the same problem.


` Error 

  Class "BeyondCode\LaravelWebSockets\Facades\WebSocketsRouter" not found

  at routes/web.php:26
     22▕ 
     23▕ 
     24▕ 
     25▕ 
  ➜  26▕ WebSocketsRouter::webSocket('/my-websocket', \App\Http\Middleware\WebSocketHandler::class);
     27▕ 
     28▕ 
`

**Comment by CosmosLibra** [comment]
So after 3 months, this bug has not been solved?
