### ISSUE TITLE
Can't install onto Laravel 10

### ISSUE THREAD

**Issue by DePalmo** [beyondcode/laravel-websockets#1152]
This is my composer.json file (partial):
```
    "require": {
        "php": "^8.1",
        "ext-pdo": "*",
        "darkaonline/l5-swagger": "^8.5",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.8",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "maatwebsite/excel": "^3.1",
        "santigarcor/laratrust": "^8.2",
        "sentry/sentry-laravel": "^3.4",
        "spatie/laravel-activitylog": "^4.7",
        "tinify/tinify": "^1.6",
        "yajra/laravel-datatables": "^10.0"
    },
```
And this is the error I'm getting when trying to install v1.14.0:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets 1.14.0 requires react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., v1.9.0].
    - beyondcode/laravel-websockets[1.0.0, ..., 1.3.0] require php ^7.1 -> your php version (8.1.12) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.4.0, ..., 1.10.0] require php ^7.2 -> your php version (8.1.12) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.11.0, ..., 1.13.0] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.9.1] but the package is fixed to 2.5.0 (lock file version) by a partial update and that version does not match. Make sure you list it as 
an argument for the update command.
    - beyondcode/laravel-websockets[1.13.1, ..., 1.13.2] require illuminate/broadcasting ^6.0|^7.0|^8.0|^9.0 -> found illuminate/broadcasting[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] but these were not loaded, li
kely because it conflicts with another require.
    - react/http[v1.1.0, ..., v1.9.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the u
pdate command.
    - Root composer.json requires beyondcode/laravel-websockets * -> satisfiable by beyondcode/laravel-websockets[1.0.0, ..., 1.14.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-websockets:*" to figure out if any version is installable, or "composer require beyondcode/laravel-websockets:^2.1" if you know which you 
need.
```
When I try to install latest, v2.0.0-beta.37, I get this:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires beyondcode/laravel-websockets 2.0.0-beta.37 -> satisfiable by beyondcode/laravel-websockets[2.0.0-beta.37].
    - beyondcode/laravel-websockets 2.0.0-beta.37 requires illuminate/broadcasting ^6.3|^7.0|^8.0|^9.0 -> found illuminate/broadcasting[v6.3.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] but these were not loaded, likely b
ecause it conflicts with another require.
```

I also tried installing the `dev-master`:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires beyondcode/laravel-websockets dev-master -> satisfiable by beyondcode/laravel-websockets[dev-master].
    - beyondcode/laravel-websockets dev-master requires doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.13.9] but the package is fixed to 3.6.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument
 for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by paraflu** [comment]
Same problem for new created app.

step:
1. `composer create-project laravel/laravel example-app`
2. `cd example-app && composer require beyondcode/laravel-websockets`

Got

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - react/http[v1.1.0, ..., v1.9.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/laravel-websockets 1.14.0 requires react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., v1.9.0].
    - Root composer.json requires beyondcode/laravel-websockets ^1.14 -> satisfiable by beyondcode/laravel-websockets[1.14.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-websockets:*" to figure out if any version is installable, or "composer require beyondcode/laravel-websockets:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by madroot** [comment]
I have the same problem, has anyone solved it?

**Comment by parallels999** [comment]
Laravel 10.x is not supported, this package has no changes since 2022

**Comment by paraflu** [comment]
I've installed succesfully with -W parameter

**Comment by Temepest74** [comment]
Oh, it looks like this package does not support the latest version of laravel :(

**Comment by DePalmo** [comment]
I do not want to use -W parameter, since it sounds a bit scary. Updating any dependency? No, thanks.

I solved it by using paid service, Pusher. For now.

**Comment by parallels999** [comment]
[Soketi](https://github.com/soketi/soketi) also is a good option

**Comment by alireza-hnzpv** [comment]
me to :(

` composer require beyondcode/laravel-websockets
./composer.json has been updated
Running composer update beyondcode/laravel-websockets
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[1.14.0, ..., 1.14.1] require react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., v1.9.0].
    - beyondcode/laravel-websockets[1.0.0, ..., 1.3.0] require php ^7.1 -> your php version (8.2.4) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.4.0, ..., 1.10.0] require php ^7.2 -> your php version (8.2.4) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.11.0, ..., 1.13.0] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.9.1] but the package is fixed to 2.6.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/laravel-websockets[1.13.1, ..., 1.13.2] require illuminate/broadcasting ^6.0|^7.0|^8.0|^9.0 -> found illuminate/broadcasting[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
    - react/http[v1.1.0, ..., v1.9.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets * -> satisfiable by beyondcode/laravel-websockets[1.0.0, ..., 1.14.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-websockets:*" to figure out if any version is installable, or "composer require beyondcode/laravel-websockets:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by Linn-Htet123** [comment]
I also encounter that problem too 
composer require beyondcode/laravel-websockets
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[1.14.0, ..., 1.14.1] require react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., v1.9.0]. 
    - beyondcode/laravel-websockets[1.0.0, ..., 1.3.0] require php ^7.1 -> your php version (8.2.4) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.4.0, ..., 1.10.0] require php ^7.2 -> your php version (8.2.4) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.11.0, ..., 1.13.0] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.9.1] but the package is fixed to 2.6.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/laravel-websockets[1.13.1, ..., 1.13.2] require illuminate/broadcasting ^6.0|^7.0|^8.0|^9.0 -> found illuminate/broadcasting[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
    - react/http[v1.1.0, ..., v1.9.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets * -> satisfiable by beyondcode/laravel-websockets[1.0.0, ..., 1.14.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require beyondcode/laravel-websockets:*" to figure out if any version is installable, or "composer require beyondcode/laravel-websockets:^2.1" if you know which you need.

**Comment by faganchalabizada** [comment]
Same. Any updates?

**Comment by stephenjason89** [comment]
use version 1.14.1

**Comment by Kweku-Sammy** [comment]
> use version 1.14.1

worked for laravel 10 :+1:

**Comment by nabilkrs** [comment]
I'm facing the same problem!!! Any updates?

**Comment by Kweku-Sammy** [comment]
> I'm facing the same problem!!! Any updates?

use version 1.14.1

**Comment by nabilkrs** [comment]
@Kweku-Sammy  it's not working. I tried this command but the error persists `composer require beyondcode/laravel-websockets:1.14.1`

**Comment by matiazar** [comment]
same problem here

**Comment by Epigie** [comment]
sam problem any help?

**Comment by Epigie** [comment]
am using laravel v10.10

**Comment by komarinsky** [comment]
same problem
beyondcode/laravel-websockets[1.0.0, ..., 1.3.0] require php ^7.1 -> your php version (8.2.14) does not satisfy that requirement.

**Comment by monir0153** [comment]
i already run `composer require beyondcode/laravel-websockets:1.14.1`
Error: 
```
Problem 1
    - react/http[v1.1.0, ..., v1.9.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/laravel-websockets 1.14.1 requires react/http ^1.1 -> satisfiable by react/http[v1.1.0, ..., v1.9.0].
    - Root composer.json requires beyondcode/laravel-websockets 1.14.1 -> satisfiable by beyondcode/laravel-websockets[1.14.1].

```

**Comment by Kweku-Sammy** [comment]
> @Kweku-Sammy it's not working. I tried this command but the error persists `composer require beyondcode/laravel-websockets:1.14.1`

try composer require beyondcode/laravel-websockets -W

**Comment by caendesilva** [comment]
It seems like v2 of this package does not support Laravel 10. To use Laravel 10 you need to use v1 of this package. It makes absolutely zero sense. Furthermore, the package seems to be abandoned by Beyond Code. Sadly there seems to be no other officially supported PHP implementation of WebSockets which is a total shame. I hardly feel like this package is "done right."
