### ISSUE TITLE
I am not able to send evenr

### ISSUE THREAD

**Issue by karanmiglani** [beyondcode/laravel-websockets#1153]
Unhandled promise rejection with TypeError: Argument 1 passed to React\Http\Io\ClientRequestStream::closeError() must be an instance of 
Exception, instance of Error given, called in C:\Users\karan\Desktop\New folder (2)\WebSocket\vendor\react\promise\src\Internal\RejectedPromise.php on line 73 in C:\Users\karan\Desktop\New folder (2)\WebSocket\vendor\react\http\src\Io\ClientRequestStream.php:238
Stack trace:

**Comment by phpmac** [comment]
look this 

https://github.com/beyondcode/laravel-websockets/issues/1158

you need install fix this error

```sh

composer require react/promise:^2.3


```

please close this,

**Comment by ha-jitendra** [comment]
stil i have issue
Failed to connect to Pusher. {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Failed to connect to Pusher. at /var/www/html/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:121)
