### ISSUE TITLE
Symfony InputBag Exception

### ISSUE THREAD

**Issue by enterlight** [beyondcode/laravel-websockets#1154]
Hello. 👋 

I have come across this error 

```Exception `Symfony\Component\HttpFoundation\Exception\BadRequestException` thrown: `Input value "channels" contains a non-scalar value.```

It all boils down to how you access the InputBag from the request here in `class TriggerEventController extends Controller`
```
$channels = $payload->get('channels', []);
```
So I replaced the previous line with 
```
$channels = data_get($payload->all(), 'channels', []);
```
per (https://github.com/symfony/symfony/issues/44432)
and everything works fine.

Is there any possibility to fix this?
Thanks

**Comment by ManuelLeiner** [comment]
Hi @enterlight 

Should be fixed by https://github.com/beyondcode/laravel-websockets/pull/1147 and available via [v1.14.1](https://github.com/beyondcode/laravel-websockets/releases/tag/1.14.1)
