### ISSUE TITLE
 Adding Laravel 10 Compatibility for 2.x-dev and dev-master

### ISSUE THREAD

**Issue by SamaRostami** [beyondcode/laravel-websockets#1155]
Hello @mpociot ,

I hope you're doing well. I wanted to let you know that Laravel-WebSockets 2.x-dev and dev-master are not compatible with Laravel 10. I appreciate your efforts in maintaining the package and thought it would be a valuable addition.

Thank you for your time!

**Comment by Dennis-Mwea** [comment]
@parallels999 Here is a PR to add Laravel 10 support https://github.com/beyondcode/laravel-websockets/pull/1160

**Comment by parallels999** [comment]
@Dennis-Mwea seems abandoned, you may have to wait a long time for a review

**Comment by lstables** [comment]
I found this to be an issue, but after some google'ing, I found `composer require beyondcode/laravel-websockets -w` to work therefore I got websockets setup in a Laravel 10 app no problem.

Just leaving this here in case anyone finds it useful and until the package is updated accordingly.
