### ISSUE TITLE
Different React Promise issue (v2.9.0)

### ISSUE THREAD

**Issue by davidwbsc** [beyondcode/laravel-websockets#1156]
I'm running this on a Centos 7 server and getting the following error which is breaking it:

```
In ExtendedPromiseInterface.php line 37:                                                                                                                  
Declaration of React\Promise\ExtendedPromiseInterface::otherwise(callable $onRejected) must be compatible with React\Promise\PromiseInterface::otherwise(callable $onRejected): React\Promise\PromiseInterface
```

**Comment by ha-jitendra** [comment]
Unhandled promise rejection with TypeError: Argument 1 passed to React\Http\Io\ClientRequestStream::closeError() must be an instance of Exception, instance of TypeError given, called in /var/www/html/vendor/react/promise/src/Internal/RejectedPromise.php on line 73 in /var/www/html/vendor/react/http/src/Io/ClientRequestStream.php:238
Stack trace:
#0 /var/www/html/vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Http\Io\ClientRequestStream->closeError(Object(TypeError))
#1 /var/www/html/vendor/react/promise/src/Promise.php(43): React\Promise\Internal\RejectedPromise->then(Object(Closure), Array)
#2 /var/www/html/vendor/react/http/src/Io/ClientRequestStream.php(100): React\Promise\Promise->then(Object(Closure), Array)
#3 /var/www/html/vendor/react/http/src/Io/ClientRequestStream.php(122): React\Http\Io\ClientRequestStream->writeHead()
#4 /var/www/html/vendor/react/http/src/Io/ClientRequestStream.php(135): React\Http\Io\ClientRequestStream->write('{"app_id":"myId...')
#5 /var/www/html/vendor/react/http/src/Io/Sender.php(152): React\Http\Io\ClientRequestStream->end('{"app_id":"myId...')
#6 /var/www/html/vendor/react/http/src/Io/Transaction.php(146): React\Http\Io\Sender->send(Object(React\Http\Message\Request))
#7 /var/www/html/vendor/react/http/src/Io/Transaction.php(83): React\Http\Io\Transaction->next(Object(React\Http\Message\Request), Object(React\Promise\Deferred), Object(React\Http\Io\ClientRequestState))
#8 /var/www/html/vendor/react/http/src/Browser.php(854): React\Http\Io\Transaction->send(Object(React\Http\Message\Request))
#9 /var/www/html/vendor/react/http/src/Browser.php(176): React\Http\Browser->requestMayBeStreaming('POST', 'https://reviews...', Array, Object(GuzzleHttp\Psr7\Stream))
#10 /var/www/html/vendor/beyondcode/laravel-websockets/src/Statistics/Logger/HttpStatisticsLogger.php(84): React\Http\Browser->post('https://reviews...', Array, Object(GuzzleHttp\Psr7\Stream))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger->save()
#12 /var/www/html/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(75): Illuminate\Support\Facades\Facade::__callStatic('save', Array)
#13 /var/www/html/vendor/react/event-loop/src/Timer/Timers.php(101): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->BeyondCode\LaravelWebSockets\Console\{closure}(Object(React\EventLoop\Timer\Timer))
#14 /var/www/html/vendor/react/event-loop/src/StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
#15 /var/www/html/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#16 /var/www/html/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(155): Ratchet\Server\IoServer->run()
#17 /var/www/html/vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(52): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->startWebSocketServer()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#24 /var/www/html/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#26 /var/www/html/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(BeyondCode\LaravelWebSockets\Console\StartWebSocketServer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 {main}

**Comment by bardolf69** [comment]
Checkout this issue - https://github.com/beyondcode/laravel-websockets/issues/1158
