### ISSUE TITLE
Let's encrypt ssl not working.

### ISSUE THREAD

**Issue by sarthaksavvy** [beyondcode/laravel-websockets#116]
I did almost everything write.

Connected local ssl crt and key.

```
'local_cert' =>  '/etc/letsencrypt/live/domain.com/fullchain.pem',

'local_pk' => '/etc/letsencrypt/live/domain.com/privkey.pem'
```

set the nginx for Same location for websockets and web contents
```
map $http_upgrade $type {
  default "web";
  websocket "ws";
}

server {
  # Your default configuration comes here...

  location / {
    try_files /nonexistent @$type;
  }
  
  location @web {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location @ws {
    proxy_pass             http://127.0.0.1:6001;
    proxy_set_header Host  $host;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
```

statred websocket server with supervisor.

Even after this dashboard not connecting to websocket

**Comment by homeserverinc** [comment]
Why you close this?

I'm stuck in the same problem!

I'm a subscriber of your channel (great laravel and vuejs content, see a lot of videos). I guess that this installation was for a new video series maybe?

Until then can you provide the solution that you find?

**Comment by sarthaksavvy** [comment]
Bro, just give path of your server ssl key, it will work fine.
