### ISSUE TITLE
Pusher error: cURL error 7

### ISSUE THREAD

**Issue by mevishnudas** [beyondcode/laravel-websockets#1162]
How to solve this error 🥲🥲🥲, 
This error occurs when we try fire a event

Broadcasting.php
![image](https://github.com/beyondcode/laravel-websockets/assets/95905352/87539137-c714-46d0-8fcd-8499786f501c)

Error
![image](https://github.com/beyondcode/laravel-websockets/assets/95905352/05d91474-d2c6-4d38-8f95-62942c342f38)

**Comment by mevishnudas** [comment]
I found the solution. Thank you 🔥

**Comment by RyanSacks** [comment]
> I found the solution. Thank you 🔥

@mevishnudas I'm having the same issue on production! Can you tell me how you solved it??

**Comment by mevishnudas** [comment]
> > I found the solution. Thank you 🔥
> 
> @mevishnudas I'm having the same issue on production. Can you tell me how you solved it?

Downgrade Pusher to 7.0.0 , 7.0.1 , 7.0.2

![image](https://github.com/beyondcode/laravel-websockets/assets/95905352/09871264-3633-46a4-99e1-57e61346b000)
