### ISSUE TITLE
which version is everyone using? 1, 2 or dev-master?

### ISSUE THREAD

**Issue by vesper8** [beyondcode/laravel-websockets#1164]
I have to admit I'm hella confused by this project. I was using the beta 2 branch for many years now, and recently ran into the new pusher 7.2 issue which meant that the beta 2 branch stopped working. I also realized that the v1 has received a few updates in the last few years, including a fix to the pusher 7.2 issue. So I switched to v1 (1.14.x to be precise).

But then other stuff wasn't working anymore, the stat collection wasn't working, I had some weird bugs with the config file, I didn't like that I lost the nicer formatting in the debug dashboard that v2 beta provided.

So i decided to fork the repo and made a few changes.. in order to pull in my fork I pulled from `dev-master` because that's what I usually do.

But lo and behold.. my dashboard looked nicer now.. it looked nicer than on either v1 or v2! The stats were working again.. yet it seemed to be using the code from the v2 beta branch, but had the latest bug fixes too.. so I'm just even more confused now.. not too sure what I'm using now.. a mix of v1 and v2.. but it looks nice, and works well.. so I'm going to stick to it, and stick to using my fork.

**Comment by Temepest74** [comment]
Just don't use this anymore... They abandoned the project and fix only when they feel like it (the pusher bug was for a while in the package).

**Comment by vesper8** [comment]
> Just don't use this anymore... They abandoned the project and fix only when they feel like it (the pusher bug was for a while in the package).

use what then? I looked at Soketi many times.. it looks quite good and well maintained but there's just something about it I don't like as much. I like this package, I like that it's Laravel. And it's working fine.. just needs a little extra effort to keep updated but it's fine.. what other alternatives are there anyway? I don't want to go back to depending on Pusher directly.

**Comment by Temepest74** [comment]
Tbh there are no alternatives outside of soketi (which idk how it works, but everyone praises it) and pusher.

If you still wanna use this package, go for v2 for laravel 9 and below, and v1 for l10. Idk if l11 will bebsupoorted at all

**Comment by stephenjason89** [comment]
where's your fork @vesper8 can you share it?
Thanks!

**Comment by parallels999** [comment]
Maybe someone will make a fork where fixes can be uploaded more regularly

**Comment by bbashy** [comment]
Just moved to Soketi, seems a lot better. No more 100% cpu after few days and don't have to restart after deployments.

**Comment by moneya** [comment]
> Just moved to Soketi, seems a lot better. No more 100% cpu after few days and don't have to restart after deployments.

How do you handle bi-directional communication client to server on soketi.

**Comment by bbashy** [comment]
> 
> is there a way to process data i.e update a column on laravel end when using soketi?
> 
> something like this?
> 
> https://beyondco.de/docs/laravel-websockets/advanced-usage/custom-websocket-handlers

No idea, you'd have to check their docs?

**Comment by caendesilva** [comment]
> Tbh there are no alternatives outside of soketi (which idk how it works, but everyone praises it) and pusher.
> 
> If you still wanna use this package, go for v2 for laravel 9 and below, and v1 for l10. Idk if l11 will bebsupoorted at all

Wait we really need to use v1 for newer versions of Laravel, and v2 for older? That makes no sense. (I'm not saying that you are wrong here, I could only install v1 on L10)

**Comment by Temepest74** [comment]
> > Tbh there are no alternatives outside of soketi (which idk how it works, but everyone praises it) and pusher.
> > If you still wanna use this package, go for v2 for laravel 9 and below, and v1 for l10. Idk if l11 will bebsupoorted at all
> 
> Wait we really need to use v1 for newer versions of Laravel, and v2 for older? That makes no sense. (I'm not saying that you are wrong here, I could only install v1 on L10)

Sadly this is what it is. they abandoned this project a long time ago and they don't even accept any new pr that would fix v2. 
V2 was abandoned before V1 was, so this is why V1 is compatible with L10

**Comment by emmadesilva** [comment]
> > > Tbh there are no alternatives outside of soketi (which idk how it works, but everyone praises it) and pusher.
> > > If you still wanna use this package, go for v2 for laravel 9 and below, and v1 for l10. Idk if l11 will bebsupoorted at all
> > 
> > 
> > Wait we really need to use v1 for newer versions of Laravel, and v2 for older? That makes no sense. (I'm not saying that you are wrong here, I could only install v1 on L10)
> 
> Sadly this is what it is. they abandoned this project a long time ago and they don't even accept any new pr that would fix v2. V2 was abandoned before V1 was, so this is why V1 is compatible with L10

It's such a shame that BeyondCode makes so many cool things, only to quickly abandon them later. I know it's a small company, but so is Spatie and they seem much better at maintaining their projects even though they have an insane amount of packages.
