### ISSUE TITLE
Unhandeled promise rejection!

### ISSUE THREAD

**Issue by rezasys2** [beyondcode/laravel-websockets#1165]
Hi there
My socket was working until a few months ago when this error happened to the command line I'm running the socket server

nhandled promise rejection with TypeError: Argument 1 passed to React\Http\Io\ClientRequestStream::closeError() must be an instance of Exception, instance of TypeError given, called in /var/www//vendor/react/promise/src/Internal/RejectedPromise.php on line 73 in /var/www//vendor/react/http/src/Io/ClientRequestStream.php:238
Stack trace:
#0 /var/www//vendor/react/promise/src/Internal/RejectedPromise.php(73): React\Http\Io\ClientRequestStream->closeError()
#1 /var/www//vendor/react/promise/src/Promise.php(43): React\Promise\Internal\RejectedPromise->then()
#2 /var/www//vendor/react/http/src/Io/ClientRequestStream.php(100): React\Promise\Promise->then()
#3 /var/www//vendor/react/http/src/Io/ClientRequestStream.php(122): React\Http\Io\ClientRequestStream->writeHead()
#4 /var/www//vendor/react/http/src/Io/ClientRequestStream.php(135): React\Http\Io\ClientRequestStream->write()
#5 /var/www//vendor/react/http/src/Io/Sender.php(152): React\Http\Io\ClientRequestStream->end()
#6 /var/www//vendor/react/http/src/Io/Transaction.php(146): React\Http\Io\Sender->send()
#7 /var/www//vendor/react/http/src/Io/Transaction.php(83): React\Http\Io\Transaction->next()
#8 /var/www//vendor/react/http/src/Browser.php(854): React\Http\Io\Transaction->send()
#9 /var/www//vendor/react/http/src/Browser.php(176): React\Http\Browser->requestMayBeStreaming()
#10 /var/www//vendor/beyondcode/laravel-websockets/src/Statistics/Logger/HttpStatisticsLogger.php(84): React\Http\Browser->post()
#11 /var/www//vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger->save()
#12 /var/www//vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(75): Illuminate\Support\Facades\Facade::__callStatic()
#13 /var/www//vendor/react/event-loop/src/Timer/Timers.php(101): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->BeyondCode\LaravelWebSockets\Console\{closure}()
#14 /var/www//vendor/react/event-loop/src/StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
#15 /var/www//vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#16 /var/www//vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(155): Ratchet\Server\IoServer->run()
#17 /var/www//vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(52): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->startWebSocketServer()
#18 /var/www//vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->handle()
#19 /var/www//vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www//vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#21 /var/www//vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#22 /var/www//vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#23 /var/www//vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#24 /var/www//vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#25 /var/www//vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#26 /var/www//vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#27 /var/www//vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#28 /var/www//vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#29 /var/www//vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#30 /var/www//vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#31 /var/www//artisan(41): Illuminate\Foundation\Console\Kernel->handle()
#32 {main}
Unhandled promise rejection with RuntimeException: Request timed out after 60 seconds in /var/www//vendor/react/http/src/Io/Transaction.php:129
Stack trace:
#0 /var/www//vendor/react/event-loop/src/Timer/Timers.php(101): React\Http\Io\Transaction->React\Http\Io\{closure}()
#1 /var/www//vendor/react/event-loop/src/StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
#2 /var/www//vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#3 /var/www//vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(155): Ratchet\Server\IoServer->run()
#4 /var/www//vendor/beyondcode/laravel-websockets/src/Console/StartWebSocketServer.php(52): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->startWebSocketServer()
#5 /var/www//vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): BeyondCode\LaravelWebSockets\Console\StartWebSocketServer->handle()
#6 /var/www//vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /var/www//vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#8 /var/www//vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#9 /var/www//vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#10 /var/www//vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#11 /var/www//vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#12 /var/www//vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#13 /var/www//vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#14 /var/www//vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www//vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#16 /var/www//vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#17 /var/www//vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#18 /var/www//artisan(41): Illuminate\Foundation\Console\Kernel->handle()
#19 {main}

**Comment by jonnywilliamson** [comment]
Just too add a +1

Don't suppose you worked out what happened or how to fix. My guess is that it's a php version issue as I think it's started the same time I updated my server to use 8.2

Doesn't seem to be affecting the websocket itself though which is good

**Comment by AlejandroCabezaCarsi** [comment]
I have the same error, but I don't know how to fix it. If I find some fix y will send you in a comment.

**Comment by rezasys2** [comment]
Thank you, problem solved @AlejandroCabezaCarsi
