### ISSUE TITLE
Redis replication configuration is missing

### ISSUE THREAD

**Issue by gneam** [beyondcode/laravel-websockets#1170]
I have included "`beyondcode/laravel-websockets`" into the dependencies of my Laravel application, after running `composer update/composer require beyondcode/laravel-websockets ` I'm unable to find replication configuration in `config/websockets.php`, besides `RedisChannelManager` and `RedisCollector` classes are missing. Did I miss anything in my installation?

**Comment by bardolf69** [comment]
Did you run ```php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="migrations"``` and ```php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="config"```

**Comment by gneam** [comment]
Thanks for the reply @bardolf69. I have both ran OK. The problem is the second command generates `config/websockets.php` which is missing the replication config that is here https://github.com/beyondcode/laravel-websockets/blob/1f25913ce05c66bbff1f925106bf9490ec0eb3bf/config/websockets.php#L122.
