### ISSUE TITLE
channel routes not work

### ISSUE THREAD

**Issue by nikorol** [beyondcode/laravel-websockets#1174]
Routing does not work and in private channels regardless of processing returns successful authorization

```
 "beyondcode/laravel-websockets": "^1.14.1",
 "pusher/pusher-php-server": "^7.2.1",
```

```
Broadcast::channel('users.1', function (User $user, int $userId) {
    return false;
});
```

```
testapp: connection id 288426454.774642121 received message: {"event":"pusher:subscribe","data":{"auth":"websocketkey:0903fc7ae38e6df122f7f38afea7111afa4c498d390498f01bbce50129a171a8","channel":"private-users.1"}}.
Connection id 288426454.774642121 sending message {"event":"pusher_internal:subscription_succeeded","channel":"private-users.1"}
```

**Comment by PabloZET** [comment]
Hi, 
Do you uncomment/add line service provider in `config/app.php`?

`App\Providers\BroadcastServiceProvider::class`

**Comment by nikorol** [comment]
> Hi, Do you uncomment/add line service provider in `config/app.php`?
> 
> `App\Providers\BroadcastServiceProvider::class`

Hey, yeah.

**Comment by PabloZET** [comment]
> > Hi, Do you uncomment/add line service provider in `config/app.php`?
> > `App\Providers\BroadcastServiceProvider::class`
> 
> Hey, yeah.

Do you set in `.env` broadcast driver on `pusher`?

`BROADCAST_DRIVER=pusher`

**Comment by nikorol** [comment]
> > > Hi, Do you uncomment/add line service provider in `config/app.php`?
> > > `App\Providers\BroadcastServiceProvider::class`
> > 
> > 
> > Hey, yeah.
> 
> Do you set in `.env` broadcast driver on `pusher`?
> 
> `BROADCAST_DRIVER=pusher`

yes
