### ISSUE TITLE
How to run the service on cpanel

### ISSUE THREAD

**Issue by ElegantSoft** [beyondcode/laravel-websockets#118]
I tried this awesome package and all things go well
I used to run $ php artisan websocket:serve to run service on port 6001
now I want to know how to do that in cpanel after uploading project to host

**Comment by sooonism** [comment]
I never try this, but i think it will work.
at cPanel, look for terminal icon, then from Terminal, cd to your laravel folder, then you can run all your php artisan command there.
good luck.

**Comment by h6s8n** [comment]
> I tried this awesome package and all things go well
> I used to run $ php artisan websocket:serve to run service on port 6001
> now I want to know how to do that in cpanel after uploading project to host

do you solved this issue,plz share me if you sloved it
