### ISSUE TITLE
Project dead ?!

### ISSUE THREAD

**Issue by paraflu** [beyondcode/laravel-websockets#1186]
The project seem dead and is time to take a choice for my project...

Anyone can share experience with self hosted websocket server for Laravel?

**Comment by m-pastuszek** [comment]
Hey, I ended up deploying standalone Soketi server.
It was quite easy, because it uses same Pusher driver so only variables changes are required on client and server sides.

About Soketi, It was quite easy to setup on Debian with Virtualmin.

**Comment by lacoste-sochi** [comment]
Hi!

It is a pity that the project has not been developing for a long time =(

As for Soketi, I don't think it's a good idea. Unfortunately, developers are engaged in politics and propaganda.
https://github.com/soketi/soketi/issues/420

I think that Taylor Otwell would not approve of such a thing, recommending the project on official documentation.
https://laravel.com/docs/10.x/broadcasting#open-source-alternatives-node

I believe that there should be no politics in programming. 

Please do not abandon your project.

**Comment by parallels999** [comment]
@lacoste-sochi also the maintainer is a j3лk, but it's the only option left.

**Comment by lacoste-sochi** [comment]
@parallels999 

I think there are many more alternatives
For example
https://centrifugal.dev/blog/2021/12/14/laravel-multi-room-chat-tutorial

https://github.com/centrifugal/centrifugo

**Comment by parallels999** [comment]
Looks interesting, thanks for the information.

**Comment by epixian** [comment]
> I think that Taylor Otwell would not approve of such a thing, recommending the project on official documentation. https://laravel.com/docs/10.x/broadcasting#open-source-alternatives-node

Completely agree. It devalues the Laravel brand name when the packages listed in official docs don't work out of the box with the framework. I opened a PR but Taylor immediately closed it. :/

https://github.com/laravel/docs/pull/9284

**Comment by parallels999** [comment]
@epixian look at laravel-docs again, already removed https://github.com/laravel/docs/commit/9c42f8596c5ceadc3496f20044b7a38f620419a2

**Comment by epixian** [comment]
> @epixian look at laravel-docs again, already removed [laravel/docs@9c42f85](https://github.com/laravel/docs/commit/9c42f8596c5ceadc3496f20044b7a38f620419a2)

Good to see! Bit of a snub to close the PR and do it himself, but glad to see it's been updated.
