### ISSUE TITLE
Dashboard not working when server under other URL

### ISSUE THREAD

**Issue by LKaemmerling** [beyondcode/laravel-websockets#12]
I have the following setup:
Webserver 1 : dev.myapp.com
Socketserver 1 : ws-dev.myapp.com

When i now try to connect to the Sockerserver from the dashboard it tries to connect to dev.myapp.com instead of ws-dev.myapp.com. Looks like it doesn't now that is should connect to ws-dev.myapp.com, because it is not specified :) An App Option for specifying the URL would be good. 

I'll submit a pr shortly :)

**Comment by freekmurze** [comment]
We'll continue this in #14
