### ISSUE TITLE
Client events do not seem to work

### ISSUE THREAD

**Issue by idragon81** [beyondcode/laravel-websockets#121]
Pusher Client events do not seem to work.

There is no error in the console.
Tested with Laravel echo and Android pusher client.

On using with official Pusher credentials everything runs fine.
On switching out the implementation with laravel-websocket it stops working. All other events seem to work fine

**Comment by idragon81** [comment]
Turns out I missed how to enable it in the documentation

**Comment by vesper8** [comment]
for those in the same boat, you have to change "enable_client_messages" from false to true in your websockets.php configuration file in order for events such as whisper / listenToWhisper to work
