### ISSUE TITLE
cors issue poped when deployed to vps server on centos

### ISSUE THREAD

**Issue by ynspc** [beyondcode/laravel-websockets#125]
In local it works fine but when it is hosted in live server, it shows following issue

> 
Access to XMLHttpRequest at 'http://sockjs.pusher.com/pusher/app/myKey/20/2o3o018b/xhr_streaming?protocol=7&client=js&version=4.3.1&t=1551526399491&n=3' from origin 'http://202.51.74.152' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

and 

> Firefox can’t establish a connection to the server at ws://202.51.74.152:6001/app/myKey?protocol=7&client=js&version=4.3.1&flash=false

Any help is appreciated, thank you.

**Comment by MartinsOnuoha** [comment]
Has any help been offered regarding this?

**Comment by powolnymarcel** [comment]
Same issue for me

**Comment by francislavoie** [comment]
First, see here: https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#usage-with-laravel-echo you'll need to set `disableStats: true` to prevent Echo from firing off requests to `sockjs.pusher.com`.

For the second issue, make sure your port 6001 is open on your server's firewall.

**Comment by salvationarinze** [comment]
@francislavoie I followed your instructions and I still facing this issue. I deployed on Laravel Forge. It works on localhost and I have set up websockets on forge using the instruction in the docs but still I face this issue. Help please  
<img width="308" alt="Screenshot 2020-05-11 at 04 52 43" src="https://user-images.githubusercontent.com/7917974/81522739-79932600-9343-11ea-833a-653556483cb4.png">

**Comment by simar88** [comment]
Same here, any solution about it?

**Comment by rickyanwar** [comment]
Same here, any solution about it? 
pusher  work on my computer where the app is installed, but in another device is connected on my local is not work, have an issue with cors 
![image](https://user-images.githubusercontent.com/36995966/127891935-e286e40d-c1b0-4360-a985-0f278f98367e.png)
