### ISSUE TITLE
Dashboard VueJS Developer Mode is active

### ISSUE THREAD

**Issue by LKaemmerling** [beyondcode/laravel-websockets#13]
Hello guys,

currently is the (vueJS) developer mode on the dashboard active :) 
Is that so intentional or a mistake?

**Comment by mpociot** [comment]
It is not intentional. I just pulled in VueJS from a CDN, to avoid having to publish assets with the package.
If you want, you can provide a PR that disables the developer mode on the dashboard.

**Comment by LKaemmerling** [comment]
PR #17 is there :)
