### ISSUE TITLE
Connections not closed

### ISSUE THREAD

**Issue by BadChoice** [beyondcode/laravel-websockets#130]
Dear,
we have been using the lib for a real app and it works really well, thank you so much for your effort!

We are using a custom handler, and connecting to it using an ios/android app. We find that if while the connection is active, we put the device in airplane mode, the connections sometimes is not closed / error and it keeps there in the server forever

Any idea how to solve it?

**Comment by masterix21** [comment]
hi,

is still active on client (ios/android app) or server (laravel-websockets)?

**Comment by BadChoice** [comment]
Well as it is in airplane mode, i believe it is closed

**Comment by masterix21** [comment]
This is a similar problem:
https://github.com/pusher/pusher-websocket-java/issues/59

I think that the only way is to implement a ping on laravel-websockets.

**Comment by zek** [comment]
Correct me if I'm wrong, client pings server every 30 seconds. So if client doesn't ping in 60 seconds we can assume it is disconnected?

**Comment by lukasirsak** [comment]
Is this ping-pong actually implemented in 1.9?

My server sits behinds private VPN, when user disconnects from VPN (or shut down network), he is still showing as online for hours.
