### ISSUE TITLE
Connect to websocket server outside Laravel

### ISSUE THREAD

**Issue by george-kar** [beyondcode/laravel-websockets#131]
I have a websocket client that already works with a node websocket server. But when my client tries to connect to laravel-websocket it automatically disconnects with the error message:

Error Decoding Header: Switching Protocols [HTTP/1.1 404 Not Found]

Then I found a Pusher API client for Delphi (my programming language)

and when I connect to the localhost 6001 it returns:

Error Decoding Header: Switching Protocols [HTTP/1.0 400 Bad request]

I tried lot of different things and I also had another error

HTTP /1.1 426 Upgrade Required

Any idea how can I connect?

**Comment by karelbyte** [comment]
Hi, I also want to connect a client outside Laravel but it always gives me that
Firefox could not establish a connection to the server in ws: //socialcore.jet/: 6001 / app / secretus? Protocol = 7 & client = js & version = 4.4.0 & flash = false.

have you found a solution?

**Comment by sharmaankit25** [comment]
i did made i work with my react app generated from create-react-app and seperate laravel based api.
`
import Echo from "laravel-echo"
import "pusher-js"

const echo = new Echo({
    broadcaster: 'pusher',
    key: "your-pusher-key",
    wsHost: "api.laravel-server.com",
    wsPort: 6001,
    disableStats: true,
  });
  
  echo.channel('home')
  .listen("NewMessage", (e) => {
      console.log(e);
  });
`

**Comment by junaidrasheed** [comment]
I'm facing the same issue. @sharmaankit25 I'm not able to authenticate users by your solution. Did you use the same database for both apps?

**Comment by sharmaankit25** [comment]
> I'm facing the same issue. @sharmaankit25 I'm not able to authenticate users by your solution. Did you use the same database for both apps?

I have a separate api running on different domain and react client on another. Laravel creating the API and react application is just client consuming the API

**Comment by Pushkraj19** [comment]
The solutions is simple.

Make sure your pusher credentials are same on both ends

like if server have 

```
PUSHER_APP_ID=12345
PUSHER_APP_KEY=ABCDEFG
PUSHER_APP_SECRET=HIJKLMNOP
```

make sure your local app also uses

```
PUSHER_APP_ID=12345
PUSHER_APP_KEY=ABCDEFG
PUSHER_APP_SECRET=HIJKLMNOP
```

**Comment by swartjie** [comment]
> I have a websocket client that already works with a node websocket server. But when my client tries to connect to laravel-websocket it automatically disconnects with the error message:
> 
> Error Decoding Header: Switching Protocols [HTTP/1.1 404 Not Found]
> 
> Then I found a Pusher API client for Delphi (my programming language)
> 
> and when I connect to the localhost 6001 it returns:
> 
> Error Decoding Header: Switching Protocols [HTTP/1.0 400 Bad request]
> 
> I tried lot of different things and I also had another error
> 
> HTTP /1.1 426 Upgrade Required
> 
> Any idea how can I connect?

Were you able to connect as I am running into the same walls?
