### ISSUE TITLE
Websockets on localhost

### ISSUE THREAD

**Issue by Karacraft** [beyondcode/laravel-websockets#136]
I was wondering, can this plugin be used without serving the laravel app using `php artisan serve` like in `localhost/myapp/public` only?

**Comment by GusevVasily** [comment]
and i

**Comment by masterix21** [comment]
no, you can't.

**Comment by molerat619** [comment]
Why not? We wanted to do it the same way and run into problems now.

**Comment by masterix21** [comment]
If i have understood, you want to use websockets without start "websockets: serve": this is not possible.

**Comment by molerat619** [comment]
No, I meant that we want to serve the dashboard without `php artisan serve` (not `websocket:serve`) but directly with our Apache service.

**Comment by Karacraft** [comment]
> 
> 
> If i have understood, you want to use websockets without start "websockets: serve": this is not possible.

no, i am ok with using `php websocket:serve` , but i don't want to use `php artisan serve` , so is there a way?

**Comment by enzonotario** [comment]
What are your problems? `php artisan serve` is just a dev server, but could be replaced by nginx, apache or any other... just make sure you have the server on `localhost:8000` (or any other port).

**Comment by enzonotario** [comment]
Think that when we go to production, we don't have a `php artisan serve` running, but a nginx or apache. So it SHOULD work without problems. If you show your problems, maybe we can help you...

**Comment by Karacraft** [comment]
> 
> 
> Think that when we go to production, we don't have a `php artisan serve` running, but a nginx or apache. So it SHOULD work without problems. If you show your problems, maybe we can help you...

no it doesn't work. websocket doesn't connect.  with simple `http://localhost/laravel/public` it doesn't work. If there is a work around to make it work with using `php artisan serve` then please share.

**Comment by francislavoie** [comment]
You need both an HTTP and websocket server running. Not just one or the other.

In one terminal tab, run `php artisan serve`, in the other run `php artisan websocket:serve`.

**Comment by Karacraft** [comment]
> 
> 
> You need both an HTTP and websocket server running. Not just one or the other.
> 
> In one terminal tab, run `php artisan serve`, in the other run `php artisan websocket:serve`.
> 
> If it still doesn't work, it's a configuration issue, and you'll need to consult the docs again, or give us more information to help. Otherwise, nothing anyone can do.

i know how it works. my question was, will it work without `php server` on plain old apache server inside htdocs folder

**Comment by francislavoie** [comment]
Yes, like others have already told you, there's no difference when it comes to running with PHP's built-in server (using `php artisan serve`) or Apache.

**Comment by molerat619** [comment]
There is a difference. `php artisan serve` runs on a different port than the usual apache applications on the same server. Also, when you have a folder structure in your xampp/htdocs holding a folder for each application, the path of `php artisan serve` also points to the root directory of the htdocs folder only. 
I'm sure you can configure artisan serve in a way that it still works for that kind of architecture. But if its only task is to serve the application, then it would be great if it could simply be replaced by the apache server that serves the rest of the applications.

**Comment by francislavoie** [comment]
Of course, but what I meant was that this library is agnostic to that.

**Comment by molerat619** [comment]
Ok, so it should work either way, right?

**Comment by mantiz8x** [comment]
@Karacraft https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/starting.html#keeping-the-socket-server-running-with-supervisord

**Comment by juanPao** [comment]
Make your server (e.g wamp) to serve your app as root directory. You can configure this on vhosts. 
From localhost/yourLaravelApp/public/home to localhost/home.

**Comment by Karacraft** [comment]
> 
> 
> Make your server (e.g wamp) to serve your app as root directory. You can configure this on vhosts.
> From localhost/yourLaravelApp/public/home to localhost/home.

Thanks for the suggestion. It worked like a charm. 
I am already using vhosts on my windows10 box. so i added a virtual host (both in my hosts file & apache/extra/vhosts.conf) and started the websocket server. It worked like a charm.

I suggest that developer should add this information on official docs.
