### ISSUE TITLE
Correct way of turning off websocket service ?

### ISSUE THREAD

**Issue by sergeynilov** [beyondcode/laravel-websockets#137]
Hello,
Which is correct way of turning off websocket service, without uninstalling
beyondcode/laravel-websockets pahckege ?

Thanks!

**Comment by masterix21** [comment]
Hi, 

have you tried killing the "serve" process?

**Comment by sergeynilov** [comment]
No, please provide a sample or link to to make it.

**Comment by masterix21** [comment]
There is no sample: simple kill the process that you start with "php artisan websockets:serve".

If you don't know how to kill a process, Google is your friend :)
