### ISSUE TITLE
stuck on Starting the WebSocket server on port 6001... after running php artisan websockets:serve

### ISSUE THREAD

**Issue by AMINEDGE** [beyondcode/laravel-websockets#138]
Hi there
My project uses Laravel 5.8 and I followed the [Installation](https://docs.beyondco.de/laravel-websockets/1.0/getting-started/installation.html) guide and set up my pusher configs and then when I type `php artisan websockets:serve` from terminal it just stuck on `Starting the WebSocket server on port 6001...` and won't run the server, I tried several times and nothing changed, I googled my problem and didn't find anything related to my issue, can someone tell me where's the problem? Thanks.

**Comment by anshul321** [comment]
@AMINEDGE How you have checked that your socket server is not started? Because when you hit the command it just print a message `Starting the WebSocket server on port 6001...` and server has been started already.

**Comment by AMINEDGE** [comment]
@anshul321 Oh, I thought it should print the url like when you run `php artisan serve` which represents `Laravel development server started: <http://127.0.0.1:8000>`, then it seems to have no problem, but is there any quick way to check if it's running other than connecting from client app?

**Comment by anshul321** [comment]
@AMINEDGE Yes, it should print but the creator does not print that I think -_-

You can test this by connecting the socket server from your client side, like in JS `new WebSocket("ws://site-url:6001/pusher-app-key");`

It will then log the events on the terminal.

**Comment by Scout3030** [comment]
You should activate your server connection on http://localhost/laravel-websockets. It doesn't work with valet.
