### ISSUE TITLE
How can we listen client events on laravel

### ISSUE THREAD

**Issue by anshul321** [beyondcode/laravel-websockets#139]
I am using JavaScript WebSocket and sending an event to the socket server of Laravel. I am not getting how can I listen to that event on Laravel?

And it through the error when the client sends a message to the socket server.

Sending the message to socket server by javascript:
`var socket = new WebSocket('ws://site-url:6001/app/pusher-app-key');
socket.send('hello');`

Error on socket server:
http://prntscr.com/n2gnvb

**Comment by stefandanaita** [comment]
Have a look at my replies in #21 and #80

**Comment by stephane303** [comment]
Can someone provide a full working example ? Thank you.

**Comment by nausixkiz** [comment]
> Can someone provide a full working example ? Thank you.

Hi @stefandanaita ,
Do you have full working example for JavaScript WebSocket ??
I faced same issue
