### ISSUE TITLE
Unhandled exception when there's a payload that isn't an object with events

### ISSUE THREAD

**Issue by ROMaster2** [beyondcode/laravel-websockets#141]
Manually testing the WebSocket, if a message is sent that isn't an object with an event value, such as `test`, an ErrorException is thrown:
```
exception `ErrorException` thrown: `Trying to get property 'event' of non-object`.
```
I traced the problem to here: https://github.com/beyondcode/laravel-websockets/blob/1c2b89b54d8d9d1c796b8391e41207da2a2f2423/src/WebSockets/Messages/PusherMessageFactory.php#L19

**Comment by rennokki** [comment]
The Pusher protocol enforces the prefix of `pusher:[event]` on calls: https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol

**Comment by jyotipati** [comment]
@ROMaster2 
How to resolve above exception? I am also facing same issue.

**Comment by ROMaster2** [comment]
@jyotipati Sorry, I don't remember how I resolved the issue, or if I ever did.

**Comment by jyotipati** [comment]
@ROMaster2 did yoy faced issue with laarvel websocket?

**Comment by jyotipati** [comment]
@ROMaster2 Please if possible could you help me

**Comment by ROMaster2** [comment]
@ jyotipati Sorry mate, I don't remember a thing. I can't help you.
