### ISSUE TITLE
how to user with application made with flutter ?? 

### ISSUE THREAD

**Issue by kunaldodiya** [beyondcode/laravel-websockets#145]
Hi, I have installed it and running fine, but i am not sure how can i use this instead of laravel-echo, I want to use 3rd party client like custom app, made with android sdk, react native or in my case flutter :) your help would be appreciable

**Comment by francislavoie** [comment]
You should be able to use any pusher client library https://pusher.com/docs/android_quick_start to use it from an app. You'll need to configure the host you're pointing to, etc.

**Comment by kunaldodiya** [comment]
Thanks, I guess i will have a look

**Comment by fabianArlex** [comment]
hi, you made the connection from flutter??

**Comment by satoblacksato** [comment]
https://pub.dev/packages/laravel_echo

**Comment by fabianArlex** [comment]
laravel-websockets package does not work

**Comment by fabianArlex** [comment]
> https://pub.dev/packages/laravel_echo

laravel_echo package doesn't work

**Comment by chinloyal** [comment]
@fabianArlex Try https://pub.dev/packages/pusher_client
