### ISSUE TITLE
Request: Fire a connect/disconnect Laravel event.

### ISSUE THREAD

**Issue by dellow** [beyondcode/laravel-websockets#147]
Hi,

I'm trying to use Laravel Websockets to create something similar to the Google Analytics Realtime.

All I need to do is log when someone connects and when they disconnect.

Now, obviously I can use presence channels, but as I understand it these are for authorized users only. I want to find out when any user (authorized or otherwise) connects/disconnects.

I tried hooking into Echo and can send an Ajax request when they connect, this works but obviously the disconnect event doesn't fire when they, say, close the window/tab.

So I looked into doing this on the server side. From what I can see Laravel Websockets doesn't have any Laravel events we can hook into with a listener which would probably work. So I tried adding a rudimentary event call in `Websockets\WebSocketHandler\WebSocketHandler.php` which works:

`onClose` method:

    public function onClose(ConnectionInterface $connection)
    {
        $this->channelManager->removeFromAllChannels($connection);

        DashboardLogger::disconnection($connection);

        StatisticsLogger::disconnection($connection);

        // Fire event for tracking status.
        event(new \App\Events\WebsocketsStatusEvent('disconnected'));
    }

`establishConnection` method:

    protected function establishConnection(ConnectionInterface $connection)
    {
        $connection->send(json_encode([
            'event' => 'pusher:connection_established',
            'data' => json_encode([
                'socket_id' => $connection->socketId,
                'activity_timeout' => 30,
            ]),
        ]));

        DashboardLogger::connection($connection);

        StatisticsLogger::connection($connection);

        // Fire event for tracking status.
        event(new \App\Events\WebsocketsStatusEvent('connected'));

        return $this;
    }

This example is pretty basic but I'm assuming we can send the socket ID and status to event which we could hook into with the EventServiceProvider.

Is this something that could be added or am I just being stupid here?

**Comment by pislaru** [comment]
Bump, i'm actively looking for this

**Comment by aguzt95** [comment]
@pislaru @dellow do u guys get error while broadcasting inside onclose event? Do u guys override the websocket handler? My error is broadcasting exception thrown ''(no message)

**Comment by ming1111dev** [comment]
Why closed issue?
