### ISSUE TITLE
Connection Refused when using Python websocket client

### ISSUE THREAD

**Issue by saleem-hadad** [beyondcode/laravel-websockets#15]
Hi, thanks for this awesome package.
I've tried to connect to the websocket server using Python client [this](https://pypi.org/project/websocket-client/) and the code I've used is this:

```python
import websocket
ws = websocket.WebSocket()
ws.connect("ws://localhost", http_proxy_host="::", http_proxy_port=6001)
```

I just want to connect and see if the connection was successful or not via the dashboard provided by this package. However, the error I've got is:
```
socket.error: [Errno 61] Connection refused
```

Are there any other settings I've to add in order to establish the connection?

**Comment by mpociot** [comment]
@saleem-hadad The websocket server uses the Pusher protocol and is not listening for websocket connections on the hostname itself. 
It listens to websocket connections on a route that looks like: `/app/{pusher-app-key}`.

The protocol involves some additional app key verification steps before the connection can be established successfully. 

Please use one of the available [Pusher client  libraries](https://pusher.com/docs/libraries) to connect to the websocket server.

**Comment by saleem-hadad** [comment]
Ohh! awesome thank you @mpociot 🌸

**Comment by saleem-hadad** [comment]
I managed to connect to the endpoint without using Python Pusher client but I really don't have time to build the interface for the endpoints provided by this package, instead, I used Python Pusher client to speed up, but the messages I sent from the Python side did not reach the Laravel side I think that because I'm using it locally so Pusher side can't reach my localhost address in order to receive the messages, do you think that's the reason?

**Comment by vipin733** [comment]
I'm getting this error s

```
WebSocket connection to 'wss://b0eb0d43.ngrok.io/app/my_pusher_app_key?protocol=7&client=js&version=4.3.1&flash=false' failed: Error during WebSocket handshake: Unexpected response code: 404
createWebSocket @ app.js?id=8215935177c4ab7eac0f:41289
getSocket @ app.js?id=8215935177c4ab7eac0f:42199
TransportConnection.connect @ app.js?id=8215935177c4ab7eac0f:42340
onInitialized @ app.js?id=8215935177c4ab7eac0f:49273
Dispatcher.emit @ app.js?id=8215935177c4ab7eac0f:42505
TransportConnection.changeState @ app.js?id=8215935177c4ab7eac0f:42448
default_1 @ app.js?id=8215935177c4ab7eac0f:42732
TransportStrategy.connect @ app.js?id=8215935177c4ab7eac0f:49302
SequentialStrategy.tryStrategy @ app.js?id=8215935177c4ab7eac0f:49416
SequentialStrategy.connect @ app.js?id=8215935177c4ab7eac0f:49394
(anonymous) @ app.js?id=8215935177c4ab7eac0f:49480
map @ app.js?id=8215935177c4ab7eac0f:41651
connect @ app.js?id=8215935177c4ab7eac0f:49479
BestConnectedEverStrategy.connect @ app.js?id=8215935177c4ab7eac0f:49458
IfStrategy.connect @ app.js?id=8215935177c4ab7eac0f:49680
FirstConnectedStrategy.connect @ app.js?id=8215935177c4ab7eac0f:49701
CachedStrategy.connect @ app.js?id=8215935177c4ab7eac0f:49545
ConnectionManager.startConnecting @ app.js?id=8215935177c4ab7eac0f:48986
ConnectionManager.connect @ app.js?id=8215935177c4ab7eac0f:48938
Pusher.connect @ app.js?id=8215935177c4ab7eac0f:41088
Pusher @ app.js?id=8215935177c4ab7eac0f:41064
connect @ app.js?id=8215935177c4ab7eac0f:20222
Connector @ app.js?id=8215935177c4ab7eac0f:19572
PusherConnector @ app.js?id=8215935177c4ab7eac0f:20206
connect @ app.js?id=8215935177c4ab7eac0f:20591
Echo @ app.js?id=8215935177c4ab7eac0f:20570
./resources/js/bootstrap.js @ app.js?id=8215935177c4ab7eac0f:77622
_webpack_require_ @ app.js?id=8215935177c4ab7eac0f:20
./resources/js/app.js @ app.js?id=8215935177c4ab7eac0f:77562
_webpack_require_ @ app.js?id=8215935177c4ab7eac0f:20
0 @ app.js?id=8215935177c4ab7eac0f:77903
_webpack_require_ @ app.js?id=8215935177c4ab7eac0f:20
(anonymous) @ app.js?id=8215935177c4ab7eac0f:84
(anonymous) @ app.js?id=8215935177c4ab7eac0f:87
2app.js?id=8215935177c4ab7eac0f:42944 OPTIONS https://sockjs.pusher.com/pusher/app/my_pusher_app_key/773/2de81cai/xhr_streaming?protocol=7&client=js&version=4.3.1&t=1545332225762&n=1 404 (Not Found)

```

while accessing on my computer localhost its fine but when I use ngrok to access on another computer its given error(I'm using laravel/echo client not any other )
