### ISSUE TITLE
 Illuminate \ Broadcasting \ BroadcastException No message

### ISSUE THREAD

**Issue by sanjarani** [beyondcode/laravel-websockets#152]
First of all thank you for your great work.

I'm using your package for a few days and after some test, I could connect to my dashboard with connection to websocket.

In next step I create an event name `NewQuestion`  that have a very simple event for test:

```
class NewQuestion implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('moderator');
    }
}
```

When I simply call my event after new question store in `QuestionController` , laravel says:

> 
>  Illuminate \ Broadcasting \ BroadcastException
> No message

**and this is part of laravel report:** 

>        $response = $this->pusher->trigger(
>             $this->formatChannels($channels), $event, $payload, $socket, true
>         );
>  
>         if ((is_array($response) && $response['status'] >= 200 && $response['status'] <= 299)
>             || $response === true) {
>             return;
>         }
>  
>         throw new BroadcastException(
>             is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
>         );
>     }
>  
>     /**
>      * Get the Pusher SDK instance.
>      *
>      * @return \Pusher\Pusher
>      */
>     public function getPusher()
>     {
>         return $this->pusher;
>     }
> }

***Would you please let me know what wrong in my case?***

my configurations:

**broadcasting.php:**

```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https'
            ],
        ],
```

**websockets.php:**

```
    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],
.
.
.
          'local_cert' => '/home/myDomain/domains/myDomain.com/private_html/local.cert',
.
.
.
        'local_pk' => '/home/myDomain/domains/myDomain.com/private_html/key.cert',
.
.
.

```

**Comment by RafaelCorreaQuantik** [comment]
The same thing is happening to me, I will try to debug what is happening too.

**Comment by RafaelCorreaQuantik** [comment]
@sanjarani - how is your config/broadcast file? Are you setting the host and the port?

**Comment by sanjarani** [comment]
In my case the problem was solved when I put my `cert keys` to a path which apache could access to those files.

I did add `curl options` array with this values:
```
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]

```
And then do not forget to:

`php artisan cache:clear`
`php artisan config:clear`

Hope this heal your headache because did mine ;-)

**Comment by eleftrik** [comment]
Same problem here. Did anyone solve?
Thanks

**Comment by Kyon147** [comment]
Yeah have the same issue, looking at where the error comes from:

`Illuminate\Broadcasting\BroadcastException in /laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:117`

It's this line
```
 throw new BroadcastException(
            is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
        );
```
Looks like it is still trying to connect to pusher even with the host being 127.0.01

**Comment by franzgithub25** [comment]
if your working on localhost try setting your .env file

set 

`
APP_URL=http://localhost

DB_HOST=localhost
`

and run 

`
php artisan config:cache
`

hope this helps you :)

**Comment by indigoram89** [comment]
I have the same error :(

**Comment by franzgithub25** [comment]
@indigoram89 have you tried my solution?

**Comment by indigoram89** [comment]
@franzgithub25 I don't understand how can it help? The application works in production as a microservice by a local network (+ public domain for UI) and this error happens a few times a day.

**Comment by swash13** [comment]
Guys, i found the issue. If you're on localhost, try set in broadcasting.php file PUSHER_APP_HOST to 127.0.0.1 instead of your domain that it points to and it will work.
If you're using forge - practice is the same. For javascript it stays the same `window.location.hostname`

**Comment by alichius** [comment]
We have the same issue. Sporadic exceptions which we drilled down to be Curl operation timeout. Currently we have no clue how to debug that issue further. There are no logs on the server side.

@indigoram89 What did you do to solve your issue and how did you find you solution?

**Comment by indigoram89** [comment]
I did next actions and it helps me:

* nginx
    * /etc/nginx/nginx.conf
    * worker_processes auto
    * worker_connections = 10240
    * worker_rlimit_nofile = 100000
* ulimit
    * /etc/security/limits.conf
    * {username_here} soft nofile 10240
    * {username_here} hard nofile 10240
* php
    * sudo pecl install ev
    * php.ini (Dynamic Extensions section):
    * extension=ev.so

**Comment by indigoram89** [comment]
And one more think is supervisor also has some limit on opening files and I couldn't set it up. So it working good without supervisor using screen for example.

**Comment by alichius** [comment]
@indigoram89 
Thanks for your reply.
I think that we did the first too, but we are still running with supervisor. Maybe that could be the solution. Did you find the problem in any log or how did you debuged the problem?

**Comment by indigoram89** [comment]
@alichius
I soo the information about supervisor limits in the internet and just tried not use supervisor and it worked.

**Comment by snowman15** [comment]
> In my case the problem was solved when I put my `cert keys` to a path which apache could access to those files.
> 
> I did add `curl options` array with this values:
> 
> ```
>             'options' => [
>                 'cluster' => env('PUSHER_APP_CLUSTER'),
>                 'encrypted' => true,
>                 'host' => '127.0.0.1',
>                 'port' => 6001,
>                 'scheme' => 'https',
>                 'curl_options' => [
>                     CURLOPT_SSL_VERIFYHOST => 0,
>                     CURLOPT_SSL_VERIFYPEER => 0,
>                 ]
> ```
> 
> And then do not forget to:
> 
> `php artisan cache:clear`
> `php artisan config:clear`
> 
> Hope this heal your headache because did mine ;-)

The problem was solved for me too

**Comment by alichius** [comment]
@indigoram89 
I have checked the limits of the websocket server process and the look good. But I think we will have a try without supervisor too.

@snowman15 
It is not a permanent error. We see sporadic curl timeout exception a few times a day. Currently we do not use the websocket server for all customer instances but only a few for testing. 
For debugging purposes we modified the exception handling code and in this block we can ping the server on which the websocket process is running an we "curled" a google api which works too. What does not work ist directly sending the failed websocket request again. This throws a timeout exception again. So we assume that the websocket process is by whatever reason not responding in this moment.
But currently we have no clue why this happens or how to analyse the problem further.

**Comment by thearyanahmed** [comment]
I had this problem, I forgot to install the pusher php sdk. After the installation, php artisan config:clear followed by config:cache to ensure the .env is set and fresh. 

That solved the problem.

**Comment by devSithu** [comment]
ok i think this can be work

**Comment by devSithu** [comment]
> Same problem here. Did anyone solve?
> Thanks

ok i will

**Comment by abhiburk** [comment]
I am facing similar kind of issue. This works on my testing server and is giving me error on production server. (Both testing and production are on same hosting)

**Comment by fvanhove** [comment]
@abhiburk Did you find a solution?

**Comment by yurik94** [comment]
any solution?
Our horizon hangs after a lot of BroadcastException appears on failed jobs.

**Comment by fvanhove** [comment]
@yurik94 I created a separate issue for this with all configurations https://github.com/beyondcode/laravel-websockets/issues/348 

For me the issue was that the server the events were broadcasting from could not properly reach our database when a new job was fired. Setting the queue driver to sync worked. But this is not a solution of course. 

Happy coincidence, but after changing the server for Apple verification (totally unrelated) our server could reach the database. 

If in your case everything works with the queue driver on sync, but it fails on database. The problem might be the connection. I made sure
- We were using tls 1.2 
- Cloudflare was not causing troubles
- We covered deprecated Cipher suites
- Our Ip was whitelisted to gain access to the database

Not sure if this would cover your issue but it worked for me.

**Comment by hemant17** [comment]
> Yeah have the same issue, looking at where the error comes from:
> 
> `Illuminate\Broadcasting\BroadcastException in /laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:117`
> 
> It's this line
> 
> ```
>  throw new BroadcastException(
>             is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
>         );
> ```
> 
> Looks like it is still trying to connect to pusher even with the host being 127.0.01

i am also getting this error and i tried almost all solution and My SSL thing is working fine too on localhost because when i go in laravel-websoket it's connected without any issues and even when i Echo user it gives it with the channel but when I try to fire EVENT it's giving me the same error. Please Help

**Comment by yurik94** [comment]
> @yurik94 I created a separate issue for this with all configurations #348
> 
> For me the issue was that the server the events were broadcasting from could not properly reach our database when a new job was fired. Setting the queue driver to sync worked. But this is not a solution of course.
> 
> Happy coincidence, but after changing the server for Apple verification (totally unrelated) our server could reach the database.
> 
> If in your case everything works with the queue driver on sync, but it fails on database. The problem might be the connection. I made sure
> 
> * We were using tls 1.2
> * Cloudflare was not causing troubles
> * We covered deprecated Cipher suites
> * Our Ip was whitelisted to gain access to the database
> 
> Not sure if this would cover your issue but it worked for me.

Today our websocket is again stalled.

`"vendor / laravel / framework / src / Illuminate / Broadcasting / Broadcasters / PusherBroadcaster.php"`
```
/**
     * Broadcast the given event.
     *
     * @param  array  $channels
     * @param  string  $event
     * @param  array  $payload
     * @return void
     */
    public function broadcast(array $channels, $event, array $payload = [])
    {
        $socket = Arr::pull($payload, 'socket');

        $response = $this->pusher->trigger(
            $this->formatChannels($channels), $event, $payload, $socket, true
        );
		
	\Illuminate\Support\Facades\Log::critical('broadcast', [$response, $event, $payload, $socket]);

        if ((is_array($response) && $response['status'] >= 200 && $response['status'] <= 299)
            || $response === true) {
            return;
        }

        throw new BroadcastException(
            is_bool($response) ? 'Failed to connect to Pusher.' : $response['body']
        );
    }
```
Note the Log::critical inserted, its output when a job fail is this:
`production.CRITICAL: broadcast [{"body":false,"status":0},"App\\Events\EventRedacted",{...},null]`

and here's a Sentry log
![image](https://user-images.githubusercontent.com/13189646/81940854-55ac3a80-95f8-11ea-9484-9cea5b5e7981.png)

Our broadcasting.php config:
 ```
'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0
                ]
            ],
            'log' => true
        ],
```

Websocket panel:
![image](https://user-images.githubusercontent.com/13189646/81941930-c1db6e00-95f9-11ea-90df-c720c64b16a1.png)


I think i'll go for a new issue as this is still closed.

**Comment by ZeusGolohor** [comment]
You're a life saver. changing my ip on my server worked for me.

**Comment by ZeusGolohor** [comment]
> Guys, i found the issue. If you're on localhost, try set in broadcasting.php file PUSHER_APP_HOST to 127.0.0.1 instead of your domain that it points to and it will work.
> If you're using forge - practice is the same. For javascript it stays the same `window.location.hostname`

You're a life saver. changing my ip on my server worked for me.

**Comment by RiksaParadilaPasa** [comment]
I solved this problem

on config/broadcasting.php
use this code  
            'options' => [
              'cluster' => 'eu',
              'useTLS' => false
            ],
make useTLS false

**Comment by gbelot2003** [comment]
I have the same problem, but is weird, because event() does work on tinker, same thing on the controller fails!!

**Comment by gabgustavo** [comment]
hi, I have a same problem, for default I developed the system make petitions to pusher and this worked success but when I change the setting to my pusher server show me that error, help me please!
