### ISSUE TITLE
So many good Pull Requests

### ISSUE THREAD

**Issue by vesper8** [beyondcode/laravel-websockets#156]
Will you ever get around to pulling/declining them @mpociot 

You made this amazing package that is so useful and has the potential to be so widely used, a lot of us are already using it in production apps. Here's to hoping you'll find the time to update it and merge some of these delicious PRs! <3

**Comment by ibrunotome** [comment]
Yes! Please @mpociot and @sschlein, this package is great and will be more great with some PR's like #140 and #90 😄

**Comment by mpociot** [comment]
I’m on vacation for a week now and will take care of the PRs when I get back. 🙂
