### ISSUE TITLE
Deploy And Usage on shared hosting with SSH Access

### ISSUE THREAD

**Issue by W3bDeveloper7** [beyondcode/laravel-websockets#157]
i can access my shared hosting with ssh but i have this error after running php artisan websockets:serve

>>WebSocket connection to 'ws://test.codeixi.com:6001/app/websocketkey?protocol=7&client=js&version=4.3.1&flash=false' failed: WebSocket is closed before the connection is established.

>>app.js:37780 WebSocket connection to 'wss://test.codeixi.com/app/websocketkey?protocol=7&client=js&version=4.3.1&flash=false' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

**Comment by masterix21** [comment]
Are you sure that you can open ports on shared hosting?

**Comment by stefandanaita** [comment]
@masterix21 is right, normally you can't port forward on shared hosting
