### ISSUE TITLE
 WebSocket connection to 'wss://myhot:6001/app/websocketkey?protocol=7&client=js&version=4.3.1&flash=false' failed: Error during WebSocket handshake: Unexpected response code: 503

### ISSUE THREAD

**Issue by AbhinavDobhal** [beyondcode/laravel-websockets#158]
Hi Team ,
i m facing WebSocket handshake: Unexpected response code: 503 issue on AWs Server With
netgateway ALB and Centos 7
Can you Please help me

**Comment by SteaveAshmore** [comment]
i am also facing this error, to make sure i have also tried to run your sample project but found same error.
please assist
