### ISSUE TITLE
Problem Connecting Debug Dashboard to Websocket Server

### ISSUE THREAD

**Issue by sudden-break** [beyondcode/laravel-websockets#16]
Hey I followed your guide/docs for installation and setup.
I run the php artisan websockets:serve command, travel to the debug dashboard url, select my app and click on connect.
I then receive the following error in the console:
`WebSocket connection to 'wss://hipm.test/app/24e751527b7716d6c2be?protocol=7&client=js&version=4.3.1&flash=false' failed: Error during WebSocket handshake: Unexpected response code: 404`

**Comment by stayallive** [comment]
Same, is because I'm (and you probably) are developing on SSL (I with `valet secure`) which causes Pusher JS to default to the `wss` protocol wich has no port set (and also won't work without an certificate set).

**Comment by tshafer** [comment]
Same with me, I as well am using https, I do have a cert set up to use.

**Comment by vesper8** [comment]
This has been resolved now with new instructions added for Laravel Valet (I was having this problem too and now it's working)

https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-laravel-valet

However as far as I know this is also causing the statistics/graph not to work and that hasn't been resolved yet

**Comment by mpociot** [comment]
@vesper8 the statistics issue was also resolved in version 1.0.1
