### ISSUE TITLE
Question: Registration with pusher necessary to use this package

### ISSUE THREAD

**Issue by AbdulRafay** [beyondcode/laravel-websockets#161]
I went through the documentation and one thing i was unable to understand is that is it necessary to register with pusher.com and get api keys, or-order to use this package? I want to use it as a pusher-replacement, if i leave configurations keys with prefix of "PUSHER_" will i still be able to use this package? 

Any help in this regard is much appreciated. Thank you.

**Comment by ivuorinen** [comment]
No, you don't need to register with Pusher (the product) for this to work. This package just provides the same API so you can use the `pusher-js` npm package.

You can define your `PUSHER_*` variables as you please and just remember to reference the same keys in your [connection configuration](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#usage-with-laravel-echo).

I'm referencing my websocket in multiple places, so my `socket.js` looks like this:

```js
import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

const socket = new Echo({
  broadcaster: 'pusher',
  key: process.env.MIX_PUSHER_APP_KEY,
  host: `${process.env.MIX_PUSHER_HOST}:${process.env.MIX_PUSHER_PORT}`,
  wsHost: process.env.MIX_PUSHER_HOST,
  wsPort: process.env.MIX_PUSHER_PORT,
  disableStats: true,
});

export default socket;

```

And in my `.env` I have following settings:

```
PUSHER_HOST="localhost"
PUSHER_PORT=6001
PUSHER_APP_ID="local-dev"
PUSHER_APP_KEY="super-secret-key"
PUSHER_APP_SECRET="super-secret-app-secret"

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_HOST="${PUSHER_HOST}"
MIX_PUSHER_PORT="${PUSHER_PORT}"
```

You also should check your `config/broadcasting.php` and `config/websockets.php` (comes with this package) that the `env()` keys makes sense.

I hope this helps!

**Comment by AbdulRafay** [comment]
@ivuorinen Thank you! for explaining everything in detail, that helped alot :)
