### ISSUE TITLE
Recipe for making a similar Realtime table/grid to the one in the Dashboard?

### ISSUE THREAD

**Issue by tinonetic** [beyondcode/laravel-websockets#164]
Hi there,

Thanks for the great component. Brought here through Botman but for a different use case

I don't want to be spoon fed, but I am currently stuck.

I followed through the documentation and was able to get a small app working. I have an average understanding of VueJs and jQuery, but I can't figure out how to create a table that is updated in realtime.

Would appreciate any guidance or reference on what I need to to bring it together

Thanks Again!
TK

EDIT: I have seen that the Dashboard is a potential starting point

**Comment by francislavoie** [comment]
Basically, you need to broadcast events in Laravel for any changes made to the data, and on the JS side, listen for events on the data being displayed. This could be create/update/delete events, depending on what you're making. There's honestly a lot of ways to approach it, it's very dependent on what the data is. You might not care about create/delete for example.

In Vue, this could mean replacing the rows in your table based on the data received in the events, you'd key the data by ID or something like that. Vue would automatically re-render the table with the updated data.

Make sure to read the Laravel broadcasting docs.

**Comment by tinonetic** [comment]
Thanks @francislavoie! Will try it out. Have been learning Vue, so will hopefully be able to piece it together soon
