### ISSUE TITLE
Statistics not inserted into database table

### ISSUE THREAD

**Issue by sanjarani** [beyondcode/laravel-websockets#166]
I did re-install this package several times. when I was trying to learn that. So, I had more of one `websockets_statistics_entries` migration and I deleted more migrations manually and ran composer dump-autoload ant etc.

Now my realtime statistics works fine, **but** my statistics do not insert into my table.

Does anyone know why is that?

**Comment by francislavoie** [comment]
The stats get inserted by doing an HTTP request to your main app at `127.0.0.1` (localhost) by default. If your websocket server can't reach that, the stats don't get recorded.

See this config option https://github.com/beyondcode/laravel-websockets/blob/master/config/websockets.php#L87 which will use your APP_URL config to connect to your app over HTTP. If your app needs a different URL than your .env APP_URL, then you'll need to wait until https://github.com/beyondcode/laravel-websockets/pull/115 is merged to add support for that.

**Comment by sanjarani** [comment]
Thanks for your respone.
```
        'perform_dns_lookup' => '127.0.0.1',
```
did solve my probblem.

**Comment by pmochine** [comment]
@francislavoie So I have the problem that my statistic is not recorded as well when I use the subdomain nginx method. 

For example:

staging.mydomain.com communications with socket.mydomain.com

Even though I fire messages etc all the time and two users are connected, I don't see it reflected in the database `websockets_statistics_entries`.

Is `base_url_override` going to help me?

**Comment by francislavoie** [comment]
I'm not certain but it should be easy for you to try - either make the change in-place in your vendor to test it, or make a fork and add the change to that, and target that dependency in composer instead. Hope you figure it out!

**Comment by pmochine** [comment]
@francislavoie Oh you were fast responding. Thanks! I'm going to try it out. Currently, I changed my server to ["Same location for websockets and web contents"](Same location for websockets and web contents), but still no luck. (Cleared chache and restarted supervision). Trying the fork out.

**Comment by rehmatweb** [comment]
> Thanks for your respone.
> 
> ```
>         'perform_dns_lookup' => '127.0.0.1',
> ```
> 
> did solve my probblem.

where  you add this line i am also facing this issue
