### ISSUE TITLE
subdirectory xhr request 404

### ISSUE THREAD

**Issue by Cjleto** [beyondcode/laravel-websockets#169]
Hi,
I installed the package correctly in a my project with URL is mydomain.com/test.
after laravel-websocket setup and websocket:serve, i reach the dashboard on mydomain.com/test/laravel-websockets and no problems to connect.
In terminal i get this

`php artisan websockets:serve`
`Starting the WebSocket server on port 6001...`
`New connection opened for app key ABCDEFG.`
`Connection id 980440594.199788334 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"980440594.199788334\",\"activity_timeout\":30}"}`
`123456: connection id 980440594.199788334 received message: {"event":"pusher:ping","data":{}}`

But when i try to create an event, xhr requests in console give me an 404 error because it send the requests to mydomain.com/laravel-websockets/auth instead mydomain.com/**test**/laravel-websockets/auth.

I tried to change host on config/broadcasting.php, config/websockets.php and bootstrap.js but it doesn't solve my problem

My actual configuration is the same in the documentation

can someone help me?

**Comment by ibrainventures** [comment]
on the client side, you can extend the connection parameters.

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
});

add:

[...},
**authEndpoint** :'http://virtual_host/broadcasting/auth',
[...]

with your matching params

more you find on 

https://pusher.com/docs/channels/using_channels/connection#authendpoint-string-

**Comment by Cjleto** [comment]
i tried but problem is still here

**Comment by sayhicoelho** [comment]
![image](https://user-images.githubusercontent.com/8188365/57575685-8b3aa880-7425-11e9-8078-431a558e2f7e.png)

same issue here...

**Comment by sayhicoelho** [comment]
Sorry, there was a misunderstanding. I've forgot to register the `App\Providers\BroadcastServiceProvider` in `config/app.php`. I'll register the broadcasting/auth route to authenticate users. Maybe this is your solution too, @Cjleto?

**Comment by Xantios** [comment]
> Sorry, there was a misunderstanding. I've forgot to register the `App\Providers\BroadcastServiceProvider` in `config/app.php`. It will register the **broadcasting/auth** route to authenticate users. Maybe this is your solution too, @Cjleto?

You sir, deserve a cookie! 
This is never mentioned in the docs, so maybe it would be kinda usefull to add it?

**Comment by sayhicoelho** [comment]
Thanks @Xantios !

Maybe you should try to make a PR to the [documentation's repository](https://github.com/beyondcode/docs.beyondco.de) to add this configuration. It would be very useful, I guess.

Check this repository too: https://github.com/sayhicoelho/laravel-websockets

**Comment by Xantios** [comment]
If im not mistaking there is already a PR ready for it:
https://github.com/beyondcode/docs.beyondco.de/pull/23

I'd say it would be a pity not to merge that one, because @edtorba already took the liberty to 'fix' this.
