### ISSUE TITLE
What credentials to use for broadcasting.php

### ISSUE THREAD

**Issue by steakbbq** [beyondcode/laravel-websockets#171]
'key'               => env('PUSHER_APP_KEY'),
'secret'            => env('PUSHER_APP_SECRET'),
'app_id'            => env('PUSHER_APP_ID'),

My understanding is I will be running my own pusher server, do I just make up whatever I want and put them in the .env file for those variables?

**Comment by ibrainventures** [comment]
https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#configuring-websocket-apps

![grafik](https://user-images.githubusercontent.com/8803626/57436816-ccbe2e80-7240-11e9-89da-cf6936e79333.png)

**Comment by ibrainventures** [comment]
so you can enter ABCDEFGH ..

**Comment by paschaldev** [comment]
@ibrainventures Were you able to get it to work?
