### ISSUE TITLE
Firefox could not establish a connection to the server

### ISSUE THREAD

**Issue by karelbyte** [beyondcode/laravel-websockets#172]
hello, I'm trying to use this excellent package in an app outside the laravel with quasar but at the time of connecting generates this error
Firefox could not establish a connection to the server in ws: //socialcore.jet/: 6001 / app / secretus? Protocol = 7 & client = js & version = 4.4.0 & flash = false ..
any clue why this is happening

**Comment by ksidibe** [comment]
I'm having the same issue.

-  **"beyondcode/laravel-websockets": "^1.1"**
-  **"pusher/pusher-php-server": "~3.0"**
-  **PHP: 7.2**

**Comment by francislavoie** [comment]
You both haven't provided enough information for anyone to help you.
