### ISSUE TITLE
Server slowness caused by statistics that is running even I set to false

### ISSUE THREAD

**Issue by sayhicoelho** [beyondcode/laravel-websockets#176]
Hi. Thank you for making our life easier! This lib helped me a lot!

I've tried to change the value of 'enable_statistics' to false to avoid server making extra load when sending messages through the WebSocket, but without success.

The `config/broadcasting.php` `apps` section:
```php
'apps' => [
    [
        'id' => env('PUSHER_APP_ID'),
        'name' => env('APP_NAME'),
        'key' => env('PUSHER_APP_KEY'),
        'secret' => env('PUSHER_APP_SECRET'),
        'enable_client_messages' => true,
        'enable_statistics' => false,
    ],
],
```

![image](https://user-images.githubusercontent.com/8188365/57894284-b6097000-781c-11e9-93ef-14440d6a2b0c.png)

As you can see, the `laravel-websockets` route still working. I think it also works when sending events through the server and it's causing the slowness.

**Comment by stefandanaita** [comment]
The route will always work. I think the difference if you set `enable_statistics` to false is that you won't see the nice stats graph anymore.

**Comment by sayhicoelho** [comment]
@stefandanaita Thanks for reply!

But, how to disable the statistics? Is it causing the slowness?

**Comment by andrew-bibby** [comment]
I would also like to know if this is responsible for slowness. @sayhicoelho did you find out more about this?

**Comment by sayhicoelho** [comment]
I did not know how to solve this yet @andrew-bibby

**Comment by rennokki** [comment]
I think it's a good fix to add an `--enable-statistics` flag when opening the server to avoid any ticker coming for statistics.
