### ISSUE TITLE
authantication

### ISSUE THREAD

**Issue by nexaas** [beyondcode/laravel-websockets#179]
hi,
this is a great project but we need help about a customization.
we want to make custom broadcasting.
for example: we have a channel about some events called "event.{eventID}" ,and each client has some permissions,we want send data to clients only has permission.so we want to create something like middleware for checking data before broadcast,could u help us about how can we do this.
we are using horizon library also for broadcast queues..

thanks.

**Comment by stefandanaita** [comment]
Generally you should broadcast to whatever channels you want and make sure only authorised clients can connect to those channels. So your validation/authentication should happen between the client and the websockets channel, not during the broadcast.

Look into Pusher authentication and make `event.{eventID}` a private channel that only authorised clients can connect to.
