### ISSUE TITLE
Reproduce Tests

### ISSUE THREAD

**Issue by aldoanizio** [beyondcode/laravel-websockets#180]
Hi There.

First of all, congratulations. This package is awesome.

I would to like how can I reproduce some kind os tests to achieve the same results in this page:

https://docs.beyondco.de/laravel-websockets/1.0/faq/scaling.html

Regards from Brazil.

**Comment by rennokki** [comment]
Like in the other PR, Artillery sounds good: https://itnext.io/websocket-load-testing-with-artillery-io-b8b7ecbcd7ed
