### ISSUE TITLE
Deploy on Google App Engine?

### ISSUE THREAD

**Issue by eadortsu** [beyondcode/laravel-websockets#183]
I need to implement a self-hosted web-socket server, can i deploy it on google cloud's app engine?

**Comment by ibrunotome** [comment]
Hi @eadortsu, I've done it. Take a look: https://github.com/ibrunotome/laravel-api-templates

The secret is that app engine will only forward ports 80 and 443, no matter your firewall rules. So in the nginx.conf you map the requests according to the type (ws or web).

**Comment by wmfairuz** [comment]
> Hi @eadortsu, I've done it. Take a look: https://github.com/ibrunotome/laravel-api-templates
> 
> The secret is that app engine will only forward ports 80 and 443, no matter your firewall rules. So in the nginx.conf you map the requests according to the type (ws or web).

So how do you handle it when there are multiple instance of the app running? (which means multiple of websockets server running)

**Comment by rennokki** [comment]
There's an incoming PR to address this issue with multiple WebSocket servers: https://github.com/beyondcode/laravel-websockets/pull/140
