### ISSUE TITLE
Hot set up my laravel-project to run in windows server 2012 R2 with apache xampp and open de socket with laravel-websockets 

### ISSUE THREAD

**Issue by joeariasc** [beyondcode/laravel-websockets#186]
Actually I'm work with a project in laravel 5.8, my server for the tests is run on Windows server 2012 R2 with apache on xampp. I need to know how work laravel-websockets with that setting. Is necesary run the sockets with the command "php artisan websockets:serve"? or Can I do something else?

**Comment by stonkeep** [comment]
Use windows service running 'php artisan websockets:serve'
