### ISSUE TITLE
Chrome not working with SSL

### ISSUE THREAD

**Issue by simioluwatomi** [beyondcode/laravel-websockets#187]
So I have 2 servers setup with Digital Ocean, both running Ubuntu 18.04 and apache. Certbot is used to install Let's Encrypt SSL certificates on both servers. Websockets was working well with `supervisord` running the websocket server until SSL certificates were installed on each server. I followed the documentation and even watched [this videos](https://www.youtube.com/watch?v=wknGvg0sTAc) for good measure to configure websockets with SSL.

However, Chrome always gives throws a **WebSocket opening handshake was cancelled** error when I try connecting to the dashboard or visit a route using websockets. **This error only occurs in Chrome.**

I found [this issue](https://github.com/beyondcode/laravel-websockets/issues/144) which is an exact replica but unfortunately, it was closed as it somehow resolved itself automagically when another server was provisioned using Forge. I do not have access to Forge so this isn't an option.

To solve this, I added  `'curl_options' => [ CURLOPT_SSL_VERIFYHOST => 0, CURLOPT_SSL_VERIFYPEER => 0, ],` to `config/broadcasting.php` and also set `'verify_peer' => false,` in `config/websockets.php`. But [this comment](https://github.com/beyondcode/laravel-websockets/issues/109) strongly advises against this.

Someone please help out; I'm at my wits end.

```
'pusher' => [
            'driver'  => 'pusher',
            'key'     => env('PUSHER_APP_KEY'),
            'secret'  => env('PUSHER_APP_SECRET'),
            'app_id'  => env('PUSHER_APP_ID'),
            'options' => [
                'cluster'      => env('PUSHER_APP_CLUSTER'),
                'encrypted'    => true,
                'host'         => '127.0.0.1',
                'port'         => 6001,
                'scheme'       => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
```

```
'ssl' => [        
        'local_cert' => env('LOCAL_CERT_FILE', null),       
        'local_pk' => env('LOCAL_PRIVATE_KEY', null),        
        'passphrase' => null,
        'verify_peer' => false,
    ],
```

```
import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    encrypted: true,
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});
```

```
LOCAL_CERT_FILE='/etc/letsencrypt/live/example.com/fullchain.pem'
LOCAL_PRIVATE_KEY='/etc/letsencrypt/live/example.com/privkey.pem'
```

Thanks

**Comment by vpratfr** [comment]
We have the exact same problem on our project. Let's Encrypt certificate for wildcard subdomains. The only fix working is to disable `verify_peer`.

Works properly in Firefox and Safari. Chrome fails though.

**Comment by renattonl** [comment]
Hey @simioluwatomi  . Could you solve this? i have the same problem

**Comment by chrystianpaulino** [comment]
i hame same problem :/

**Comment by jialbanc** [comment]
Same problem here, someone find a fix. Having this issue with a Let's Encrypt certificate.

**Comment by terion-name** [comment]
The same. Firefox ok, Chrome drops handshake :( Let'sencrypt cert, not wildcard, single domain

**Comment by Kyon147** [comment]
Yeah there seems to be an issue with Chrome at the moment with this. Works fine on Firefox but chrome keeps dropping the connection.

**Comment by dewsoftpvtltd** [comment]
Same issue, nothing in the documentation works for chrome, initial handshake fails; works fine on safari and firefox.

**Comment by Markovnin** [comment]
Same problem here. Any solution?

**Comment by FfionTree** [comment]
A **solution** to the '**WebSocket opening handshake was cancelled**' error, in chrome for wss/ssl connections.

I struggled with this too and finally identified the cause. 
Interestingly, I'm also using a lets encrypt certificate.
I Hope this helps, so you too can enjoy secure php websockets in laravel! 
(thank you @beyondcode, an @laravel an @ratchetphp .. :)

---

You can verify the issue and solution by trying to access your socket server directly in chrome. eg. 
1. Go to https://www.yourwebsite.com:6001 in the browser.
2. You should see the client certificate dialog appear.
3. Choose a certificate or press cancel 
4. and then try reconnecting to your socket server, hopefully you're successful.

When you initiate a TLS connection in chrome, to a socket server that accepts or requires client certificates.
Chrome immediately aborts the connection, unless you have explicitly selected, or not selected a client certificate.
The websocket connection is non-interactive, but requires a user choice for the ssl, so chrome doesn't show the dialog and aborts.

More details: [Issue 329884: Secure Websocket with client certificate not working](https://bugs.chromium.org/p/chromium/issues/detail?id=329884)

Other options:

> The usual solution is to serve the WebSocket from the same hostname as the page that uses it, 
so the user has always selected a certificate before the browser attempts a WebSocket connection.

I’m using the same hostname on port 6001 and still have the problem.
 
I guess I could proxy via 443 or seeif its possible to stop ratchet/php from mentioning client certs. 
Be nice to use 6001 direct on chrome without the dialog, havent got that far, if anyone knows or figures one out, please let me know :)

**Comment by robertgivens** [comment]
Here's what I added to apache config to add the proxy service.  This fixed the issue with Chrome. Thanks FfionTree!  

<Proxy "https://mysite.domain*">
  SSLProxyMachineCertificateFile /some/path
</Proxy>

**Comment by robertgivens** [comment]
> A **solution** to the '**WebSocket opening handshake was cancelled**' error, in chrome for wss/ssl connections.
> 
> I struggled with this too and finally identified the cause.
> I Hope this helps, so you too can enjoy secure php websockets in laravel!
> (thank you @beyondcode, an @laravel an @react .. :)
> 
> You can verify the issue and solution by trying to access your socket server directly in chrome. eg.
> 
> 1. Go to https://www.yourwebsite.com:6001 in the browser.
> 2. You should see the client certificate dialog appear.
> 3. Choose a certificate if you are using client certs, or press cancel if not.
> 4. and then try reconnecting to your socket server, hopefully you're successful.
> 
> When you initiate a TLS connection in chrome, to a socket server that accepts or requires client certificates.
> The websocket connection is classed 'non-interactive', but requires a user choice for the client cert, so chrome doesn't show the dialog and aborts.
> 
> More details: [Issue 329884: Secure Websocket with client certificate not working](https://bugs.chromium.org/p/chromium/issues/detail?id=329884)
> 
> Related Issue: [Chrome cannot connect via wss; returns error "WebSocket opening handshake was canceled"](https://github.com/beyondcode/laravel-websockets/issues/266)
> 
> The php implementation of SSL, which react uses behind the scenes, doesn't let you configure the SSLVerifyClient directive [context.ssl.php](https://www.php.net/manual/en/context.ssl.php).
> So it looks like php's ssl allows for client certificates by default, and chrome will just block those unless you have previously made a choice in the SSL client certificate dialog.
> 
> Solutions:
> 
> The only option in my situation seems to be to proxy (and not use phps ssl).
> 
> 1. proxy via 443, so any client cert choice is already satisfied.
> 2. proxy via any port, so the SSLVerifyClient directive can be removed.
> 
> It would be nice to use the secure socket server directly without a proxy service, if anyone has a better idea of how to work around this please let us know! :)
> 
> --
> 
> To reiterate the point above and disabling 'verify_peer'.
> 
> > "I would really advise anyone to NOT disable VERIFYHOST and VERIFYPEER, that's just throwing away all the security HTTPS provides." [reference](https://github.com/beyondcode/laravel-websockets/issues/109)

@FfionTree can you explain further how you how you setup the proxy?

**Comment by FfionTree** [comment]
Hi Robert
The easiest way to setup a proxy would be to use nginx, mainly because it is better documented:
- [Usage with a reverse proxy (like Nginx)](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx)
- [Deploying laravel-websockets with Nginx reverse proxy and supervisord](https://ma.ttias.be/deploying-laravel-websockets-with-nginx-reverse-proxy-and-supervisord/)

You can do the same thing with other servers inc apache but you have to google and piece together a solution. Hopefully the links are enough to get you started?

**Comment by abhiburk** [comment]
any solution I have the same issue and not able to work on chrome `failed: WebSocket opening handshake was canceled`

**Comment by salvationarinze** [comment]
Me too. Any solution will be appreciated

**Comment by rennokki** [comment]
Make sure the key and certificate are readable in the UNIX filesystem.

**Comment by irfanahmad7272** [comment]
> A **solution** to the '**WebSocket opening handshake was cancelled**' error, in chrome for wss/ssl connections.
> 
> I struggled with this too and finally identified the cause.
> I Hope this helps, so you too can enjoy secure php websockets in laravel!
> (thank you @beyondcode, an @laravel an @react .. :)
> 
> You can verify the issue and solution by trying to access your socket server directly in chrome. eg.
> 
> 1. Go to https://www.yourwebsite.com:6001 in the browser.
> 2. You should see the client certificate dialog appear.
> 3. Choose a certificate if you are using client certs, or press cancel if not.
> 4. and then try reconnecting to your socket server, hopefully you're successful.
> 
> When you initiate a TLS connection in chrome, to a socket server that accepts or requires client certificates.
> The websocket connection is classed 'non-interactive', but requires a user choice for the client cert, so chrome doesn't show the dialog and aborts.
> 
> More details: [Issue 329884: Secure Websocket with client certificate not working](https://bugs.chromium.org/p/chromium/issues/detail?id=329884)
> 
> Related Issue: [Chrome cannot connect via wss; returns error "WebSocket opening handshake was canceled"](https://github.com/beyondcode/laravel-websockets/issues/266)
> 
> The php implementation of SSL, which react uses behind the scenes, doesn't let you configure the SSLVerifyClient directive [context.ssl.php](https://www.php.net/manual/en/context.ssl.php).
> So it looks like php's ssl allows for client certificates by default, and chrome will just block those unless you have previously made a choice in the SSL client certificate dialog.
> 
> Solutions:
> 
> The only option in my situation seems to be to proxy (and not use phps ssl).
> 
> 1. proxy via 443 or another port, so the SSLVerifyClient directive can be removed.
> 
> If you are using client certificates, and your web and socket server are on the same domain, any client cert choice should already be satisfied and you shouldn't have this problem.
> 
> It would be nice to use the secure socket server directly without a proxy service, if anyone has a better idea of how to work around this please let us know! :)
> 
> --
> 
> To reiterate the point above and disabling 'verify_peer'.
> 
> > "I would really advise anyone to NOT disable VERIFYHOST and VERIFYPEER, that's just throwing away all the security HTTPS provides." [reference](https://github.com/beyondcode/laravel-websockets/issues/109)

By reading your detailed solution, i have resolved my issue :)
