### ISSUE TITLE
Are eloquent queries and other IO stuff non-blocking ?

### ISSUE THREAD

**Issue by imanghafoori1** [beyondcode/laravel-websockets#195]
I hear in an async environment like ratchet or node.js the database drivers should work non-blocking to deliver a good performance, otherwise we get the worst out the two worlds.

So we definitely need a non-blocking mysql driver or something like that. (maybe send the queries to a child process)
I wanted to know is it ok and straight forward to just install the package on laravel and start to query the database or we have to change something ?

**Comment by francislavoie** [comment]
Eloquent queries are blocking IO. Laravel unfortunately does not support any non-blocking/async IO backends by default.

You can use https://github.com/friends-of-reactphp/mysql which is an implementation of an async MySQL client, compatible with ReactPHP, which is what laravel-websockets is based on. You won't be able to use Eloquent with this though (unless you use the query builder, get the SQL, then run it raw with the async MySQL library, but then you'll still need to do model hydration yourself, etc, and ->save() won't work anyways)

**Comment by ROTGP** [comment]
@francislavoie I see this in the docs

> Make sure that you do not perform any IO blocking tasks in your AppProvider, as they will interfere with the asynchronous WebSocket execution.

However I don't see the same warning in the docs for [Custom Websocket Handlers](https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html). Does this mean that IO blocking is ok in Custom Websocket Handlers?

**Comment by francislavoie** [comment]
Nope, it's all running in the same event loop. Any blocking IO is not ideal.

**Comment by ROTGP** [comment]
I see. I might try this lib https://github.com/spatie/async

**Comment by francislavoie** [comment]
That's a good idea actually. I'd recommend using https://reactphp.org/child-process/ instead, which is an officially supported way to spawn some processes from within a ReactPHP event loop.

**Comment by ROTGP** [comment]
Great - thanks for the recommendation!
