### ISSUE TITLE
Serve websockets error: "There are no commands defined in the "websockets" namespace."

### ISSUE THREAD

**Issue by Hillcow** [beyondcode/laravel-websockets#197]
Just installed with Laravel 5.7. When I type "php artisan websockets:serve" I get this error:

There are no commands defined in the "websockets" namespace.

**Comment by Hillcow** [comment]
Closing, because it turned out to be a duplicate of my other isssue: https://github.com/beyondcode/laravel-websockets/issues/196

**Comment by kajal-7span** [comment]
May be some where you have written command like PHP artisan websockets:restart

Please remove it if you are not using this package.

**Comment by binary3oul** [comment]
Try with this code line:
`composer require beyondcode/laravel-websockets`
