### ISSUE TITLE
"Error sending event" error on dashboard

### ISSUE THREAD

**Issue by connecteev** [beyondcode/laravel-websockets#201]
After going to the dashboard and clicking 'send event' I see this: https://prnt.sc/o5bmrm 

Any ideas?

**Comment by erdiegoant** [comment]
Keeps happening to me too. Haven't figured out why yet

**Comment by francislavoie** [comment]
The string in `Data` needs to be a valid JSON object. e.g. `{"message": "blah"}`

**Comment by nkorent** [comment]
this happens on any type of error.
I have the exact issue like here: #185 
Everything is fine with formatting of inputs tho.

Tried even running it locally with 'php artisan serve' and 'php artisan websockets:serve' but still doesn't work.
