### ISSUE TITLE
Does the websocket connection timeout?

### ISSUE THREAD

**Issue by TheBigK** [beyondcode/laravel-websockets#204]
I'm curious to know if the websocket connection times-out if there is no message exchange? If yes, what is the default timeout; and is there any way to change it?

**Comment by francislavoie** [comment]
By default, if you're using Laravel Echo with the pusher driver, the pusher driver will send pings to the websocket server every 10s-120s. See here: https://github.com/pusher/pusher-js#activitytimeout-integer This should typically get around inactivity timeouts. The user's browser might cull it eventually though, if the browser tab isn't actively used by the user.
