### ISSUE TITLE
Queued notifications not receiving pusher settings (multi tenant)

### ISSUE THREAD

**Issue by adam-baliatico** [beyondcode/laravel-websockets#206]
I'm using hyn/multi-tenant and had Invalid Signature issues similar to a few other posters that I've resolved with the noted solutions. Now I'm finding that my queue worker is not receiving the proper pusher settings. I've done some investigation and it appears that the Pusher instance constructor is being called prior to the JobProcessing event handler assigning the tenant settings. Has anyone encountered/successfully dealt with this?

**Comment by francislavoie** [comment]
I haven't worked with the `multi-tenant` lib, but it sounds to me like you need to change the order in which your service providers are registered. I'm guessing by configuring the service provider manually: https://github.com/tenancy/multi-tenant#manual-service-registration

If you provide more info, I might be able to help you debug, but as-is, I don't know enough about the problem to help.
