### ISSUE TITLE
Help Needed to setup web-sockets on different laravel app

### ISSUE THREAD

**Issue by smitpatelx** [beyondcode/laravel-websockets#208]
Hey does anybody have any resources (Videos or Blog) on setting up a different server for laravel-websockets ? I have seen tutorials, but all of them were trying to integrate the package on the same app. I want to host my websocket app differently.

I tried using it differently but I am not getting Event on my socket-app. Do I have to create events on socket app?

**Comment by francislavoie** [comment]
This is all explained here: https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#configuring-websocket-apps
