### ISSUE TITLE
Misleading error title

### ISSUE THREAD

**Issue by RafaelCorreaQuantik** [beyondcode/laravel-websockets#210]
When I try to connect from laravel echo into the server. Sometimes the request works as it should, but sometimes it sends it's request to `http://sockjs.pusher.com/pusher/app/31121b9a7223/203/t2sl49qm/xhr_streaming?protocol=7&client=js&version=4.4.0&t=1561979374055&n=1` instead of my real server. But the strange thing is, that in the browser console, it says that it was trying to access my real server (thing that surely is not happening).

Plus:
- it seems to work on chrome (not on firefox), but it shows another error. It tries to connect to an auth url that it doesn't exist.

**Comment by RafaelCorreaQuantik** [comment]
Adding `wsHost`, `httpHost`, `host` with the hostname seems to have resolved the issue (for now)

**Comment by IngWARP** [comment]
@RafaelCorreaQuantik Where did you add wsHost, httpHost, host?

**Comment by RafaelCorreaQuantik** [comment]
``` javascript
new Echo({
    broadcaster: 	'pusher',
    key: 			"31121b9a7223",
    host: 			window.location.hostname,
    wsHost: 		window.location.hostname,
    httpHost: 		window.location.hostname,
    wsPort: 		6001,
    disableStats: 	true,
    auth: {
	headers: {
	    Authorization: 	"Bearer " + token,
	    "Content-Type":    "application/json",
	    "Accept": 	 	"application/json"
        }
    }
});
```

**Comment by francislavoie** [comment]
It seems you resolved your issue. Could you close this issue? Thanks
