### ISSUE TITLE
Pusher php sdk

### ISSUE THREAD

**Issue by fridzema** [beyondcode/laravel-websockets#212]
Hello, 

I can't install your package as i get the following error:
  Problem 1
    - beyondcode/laravel-websockets 1.1.1 requires pusher/pusher-php-server ~3.0 -> satisfiable by pusher/pusher-php-server[3.4.x-dev, 3.0.x-dev].
    - beyondcode/laravel-websockets 1.1.1 requires pusher/pusher-php-server ~3.0 -> satisfiable by pusher/pusher-php-server[3.4.x-dev, 3.0.x-dev].
    - beyondcode/laravel-websockets 1.1.1 requires pusher/pusher-php-server ~3.0 -> satisfiable by pusher/pusher-php-server[3.4.x-dev, 3.0.x-dev].
    - Can only install one of: pusher/pusher-php-server[v4.0.0, 3.4.x-dev].
    - Can only install one of: pusher/pusher-php-server[v4.0.0, 3.0.x-dev].
    - Installation request for pusher/pusher-php-server ^4.0 -> satisfiable by pusher/pusher-php-server[v4.0.0].
    - Installation request for beyondcode/laravel-websockets (locked at 1.1.1, required as *) -> satisfiable by beyondcode/laravel-websockets[1.1.1].

Look like i must use version 3.4 of pusher-php-server, this version is not compatible with my php version(7.3.6). 

Any ideas?

**Comment by irazasyed** [comment]
PR is already opened for this issue #209. Just needs to be merged.

**Comment by ttomdewit** [comment]
@fridzema PR https://github.com/beyondcode/laravel-websockets/pull/209 has been merged. Can you please target the `dev-master`-version (https://packagist.org/packages/beyondcode/laravel-websockets#dev-master) and verify your installation runs successfully?

**Comment by fridzema** [comment]
@ttomdewit everything installed successfully now!

**Comment by ttomdewit** [comment]
@fridzema Could you please be so kind & close this issue?

Much appreciated!
