### ISSUE TITLE
Is server running

### ISSUE THREAD

**Issue by VinceG** [beyondcode/laravel-websockets#213]
Is there a way to see if the socket server is currently running? programmatically i mean. If not will you be open for a PR that'll do that?

Similar to how Horizon has 'currentHorizonStatus'.

Thank You.

**Comment by francislavoie** [comment]
Horizon uses Redis as a storage backend for this info, so it's easy to pull up from anything that can connect to Redis. In the case of laravel-websockets, it doesn't have a centralized storage backend to work with. Out of the box, I don't see an easy way to do this with the existing defaults.

Once https://github.com/beyondcode/laravel-websockets/pull/140 is merged, we'll have precedent for using Redis for other features as well, meaning we could do this sort of thing to keep track of process status similarly to Horizon. On startup, laravel-websockets would write to Redis marking itself as alive, and on shutdown, it could remove that key, etc.

**Comment by VinceG** [comment]
@francislavoie Yeah, it's understandable. Currently i ended up just checking if the process runs, which works just fine for our needs.

```
    protected function currentSocketServerStatus()
    {
        $output = shell_exec("ps -A | grep -i websockets:serve | grep -v grep");

        return !empty($output) ? 'running' : 'inactive';
    }
```
