### ISSUE TITLE
Reload WebSocket Apps without restart WebSocket Server ?

### ISSUE THREAD

**Issue by daogr** [beyondcode/laravel-websockets#214]
Hi,

Is there any way to reload WebSocket Apps without restart WebSocket Server ?

Thank you,
Dimitris

**Comment by kszyrvercobrador** [comment]
Same problem here. I have custom AppProvider that will provide dynamic WebSocket Apps.

**Comment by daogr** [comment]
Hi,

You can call the forgetInstance() to remove it. As the doc's say, this method can be used to 
> [Remove a resolved instance from the instance cache.](https://laravel.com/api/5.1/Illuminate/Foundation/Application.html#method_forgetInstance)

`App::forgetInstance(AppProvider::class);`

Next time you'll try to get an instance of this service from the container, it will be re-created using the function you provided in the singleton() method.

Hope this helps,
Dimitris

**Comment by kszyrvercobrador** [comment]
Hi @daogr 

I think Ratchet still not picking up the new added app even though I clear the instance of AppProvider.

Logs
```
New connection opened for app key e446fc446d9809e7e18a989c0f4165a3.
Exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `e446fc446d9809e7e18a989c0f4165a3`.`
Unknown app id: exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `e446fc446d9809e7e18a989c0f4165a3`.`.
Connection id  sending message {"event":"pusher:error","data":{"message":"Could not find app key `e446fc446d9809e7e18a989c0f4165a3`.","code":4001}}
Connection id  closed.
Exception `ErrorException` thrown: `Undefined property: Ratchet\Server\IoConnection::$app`
```
I also tried this
```
App::forgetInstance(ChannelManager::class);
App::forgetInstance(WebSocketsServiceProvider::class);
```
but still it won't pick up my updated list of apps

Thanks

**Comment by faganchalabizada** [comment]
Any solution in 2023?)
