### ISSUE TITLE
Dashboard in Production?

### ISSUE THREAD

**Issue by irazasyed** [beyondcode/laravel-websockets#22]
I'm trying to run the dashboard in production and limit its access to specific users but it looks like the `$user` var in Gate's definition is always `null` for some reason.

How can I run it with limited access to specific users?

P.S. I used the same code as in the docs. It appears there is no auth info in the request payload when the dashboard is running.

**Comment by mpociot** [comment]
That’s probably because the middleware used for the dashboard is not configurable yet. 
I suggest that we make the middleware configurable, similar to how Laravel Telescope handles this.

**Comment by divdax** [comment]
Same problem here. Dashboard not running in production. User is null.

**Comment by vesper8** [comment]
@mpociot could you please merge https://github.com/beyondcode/laravel-websockets/pull/28 ?

We badly need to be able to access the dashboard in production and can't because of this

Thanks!

**Comment by wasitmirani** [comment]
how can i use laravel-websockets  on cpanel or other hosting platforms

**Comment by rennokki** [comment]
Shared hosting is by far the worst environment to make WebSockets work. 

Duplicate of https://github.com/beyondcode/laravel-websockets/issues/460

**Comment by wasitmirani** [comment]
ok bro i can deploy digital ocean  or Heroku  suitable for my application

**Comment by rennokki** [comment]
DigitalOcean is fine. You can deploy your app using Laravel Forge for example.

**Comment by mrABR** [comment]
Is it possible to disable the dashboard?

**Comment by dellert** [comment]
> Is it possible to disable the dashboard?

+
