### ISSUE TITLE
Q: BroadcastException - Fail gracefully

### ISSUE THREAD

**Issue by nea** [beyondcode/laravel-websockets#220]
Hi

I got a question regarding failing gracefully in the case the websocket server ist not running.

Right now, if the `websocket serve` is running all is working fine. But if the server is not running, all events trigger a 
```
Illuminate \ Broadcasting \ BroadcastException
No message
```
exception in `vendor\laravel\framework\src\Illuminate\Broadcasting\Broadcasters\PusherBroadcaster.php`.

I could try/catch all events I am firing, but as I am also listening to Eloquent events this will become complicated.

Is there a way to fail gracefully in general?

Thanks a lot

**Comment by hapidjus** [comment]
Did you figure this out?
The closest to a solution that I found is https://laracasts.com/discuss/channels/laravel/catch-broadcastexception-whilst-broadcasting-event

But it seems a bit overkill.
