### ISSUE TITLE
Websockets failed after reinstall node modules

### ISSUE THREAD

**Issue by sanjarani** [beyondcode/laravel-websockets#221]
I was using `Laravel websockets` and it worked fine till last night I did `remove **node_modules** folder and **package-lock.json** file` for some reasons.

I used these commands after that:

    npm install

    npm run dev

I expect that everything workes like before because I removed all changes. 

But know there's log message in console without any try and immediately after page load with this message:

> wss://mydomain.com:6001/app/aed96seda52b767a8996?protocol=7&client=js&version=4.4.0&flash=false' failed: Unknown reason

[https://i.stack.imgur.com/GBkxQ.png](url)

**This is my echo setting, Just for information:**

```
    window.Echo = new Echo({
        broadcaster: 'pusher',
        key: process.env.MIX_PUSHER_APP_KEY,
        wsHost: window.location.hostname,
        wsPort: 6001,
        wssPort: 6001,
        disableStats: true,
        encrypted: false,
        enabledTransports: ['ws', 'wss']
    });
```

***UPDATE :***

I did clean `npm cache` using `npm cache clean --force` and did above scenario again but there's no difference in result.

`StatisticsUpdated` event is working based on `websockets.php` configuration! Just there's no connection in client side!

Does anyone knnow where's my mistake?

***Thanks in Advance***
  [1]: https://i.stack.imgur.com/GBkxQ.png

**Comment by francislavoie** [comment]
Hmm, that's odd. I can't find any information on an `Unknown reason` error message from Chrome.

If you're able to put breakpoints in your app.js bundle, try to step through and find the `event.code` value from the `.onerror` callback on the websocket object. Hopefully that'll reveal what's actually happening.

**Comment by Zepryit** [comment]
Same error here. Is there any progresses on this?

**Comment by swash13** [comment]
same. Anyone found the issue ?

**Comment by mirko1593** [comment]
for my case, Safari works fine. it's Chrome's issue. fixed by restart Chrome.😂

**Comment by sanjarani** [comment]
It seems there's something about cache system of this package in my case , because this worked after a while by itself :-|

**Comment by Vanillabacke** [comment]
just in case -> addblocker caused this issue
