### ISSUE TITLE
Error with pusher broadcaster

### ISSUE THREAD

**Issue by pacoEspinoza123** [beyondcode/laravel-websockets#233]
Hi, yesterday I Configured a Laravel websocket server and everything was OK, but now when I try to make "php artisan serve" or "php artisan websocket:serve", it shows me an exception in the terminal and the only thing it says is:

In PusherBroadcaster.php line 119:
                                                
  [Illuminate\Broadcasting\BroadcastException]  

Now I don't know what to do... I'm pretty new in this and I'm so lost right now...

**Comment by semsphy** [comment]
@pacoEspinoza123 , If you can send  the broadcasting.php and websockets.php, it would be great to see how you configured it.

**Comment by pacoEspinoza123** [comment]
[This is my broadcasting.php](https://www.dropbox.com/s/sc92nqfvbsxj1yj/broadcasting.php?dl=0)

[And this is my websockets.php](https://www.dropbox.com/s/pcsxzvb9fwxeno8/websockets.php?dl=0)

**Comment by tibinvpaul** [comment]
Hey @pacoEspinoza123 - did you manage to fix the issue? I am also facing the same issue. Thanks in advance!

**Comment by stri8ed** [comment]
> Hey @pacoEspinoza123 - did you manage to fix the issue? I am also facing the same issue. Thanks in advance!

Would help if you posted more details. E.g. Exception stack-trace, when exception occurs etc..

**Comment by nkorent** [comment]
Got the same issue, no idea how to proceed.
Anyone encountered this and fixed it ?

**Comment by nlochala** [comment]
I'm having the same issue. Could really use some help!

**Comment by schtoffen** [comment]
The problem is most likely related to CURL. It tries to send event but fails.
Your can enable logging in broadcasting config for pusher:
`'connections' => [
        'pusher' => [
             // ...
             'log' => true
        ]
]`

And look in logs where problem in sending.

**Comment by Cello93** [comment]
what adjustment did you make?

**Comment by GianniCarlo** [comment]
Hi there, we're having two different instances of this happening

1.- 
```
[2020-05-24 13:35:20] production.ERROR: exec_curl error: {error} {"error":"Recv failure: Connection reset by peer"} 
[2020-05-24 13:35:20] production.INFO: exec_curl response: {response} {"response":"Array
(
    [body] => 
    [status] => 0
)
"} 
```

2.-
```
[2020-05-24 13:38:09] production.ERROR: exec_curl error: {error} {"error":"Operation timed out after 30000 milliseconds with 0 bytes received"} 
[2020-05-24 13:38:09] production.INFO: exec_curl response: {response} {"response":"Array
(
    [body] => 
    [status] => 0
)
"} 
```

When that starts appearing, we know that all our real-time events are dead and won't be dispatched, so we resort to restarting the laravel websockets service until it works, but it's a pain, and we don't quite understand why it's happening 🤔 are we hitting some bottleneck regarding socket connections?

**Comment by glrnz** [comment]
Thanks @schtoffen ! I enabled log then I found what causes the problem in my end and able to fix it.
> The problem is most likely related to CURL. It tries to send event but fails.
> Your can enable logging in broadcasting config for pusher:
> `'connections' => [ 'pusher' => [ // ... 'log' => true ] ]`
> 
> And look in logs where problem in sending.

If you happen to have the same error as mine:
```
[2020-06-30 16:30:39] prod.ERROR: exec_curl error: {error} {"error":"SSL: no alternative certificate subject name matches target host name '127.0.0.1'"}
[2020-06-30 16:30:39] prod.INFO: exec_curl response: {response} {"response":"Array
(
    [body] =>
    [status] => 0
)
```
I changed the options.host into domain name:
```
    'connections' => [
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'log' => true,
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => 'mydomain.com',
                'port' => 6001,
                'scheme' => 'https',
            ],
        ],
    ]
```
