### ISSUE TITLE
Supervisor errors

### ISSUE THREAD

**Issue by darklight9811** [beyondcode/laravel-websockets#234]
I'm starting to use laravel-websockets on my server. Let's say that's been a disaster.

## 1. Error
Installation got stuck on 94%

## 2. Error
After placing the `websockets.conf`, when I ask it to update, the console gives the following error:
```
root@srv:/root# supervisorctl update
error: <class 'xmlrpclib.Fault'>, <Fault 92: "CANT_REREAD: Invalid user name laravel-echo in section 'program:websockets' (file: '/etc/supervisor/conf.d/websockets.conf')">: file: /usr/lib/python2.7/xmlrpclib.py line: 800
```

## 3. Error
I changed the user from laravel-echo to root, then it apparently worked. But when I ask to start the websockets. This error appears:

```
root@srv:/root# supervisorctl start websockets
websockets: ERROR (spawn error)
```

When I log to see the status, this appears:
```
root@srv:/root# supervisorctl status           
websockets                       FATAL     Exited too quickly (process log may have details)
```

PS. I can't find any error logs related to this error.

**Comment by semsphy** [comment]
@darklight9811 , check the worker.log

**Comment by darklight9811** [comment]
@semsphy, Where should it be located? I looked up in the `/etc/supervisor`, `/tmp` folders and there was nothing there.

**Comment by semsphy** [comment]
In your config file, you should add these lines:

```config
redirect_stderr=true
stdout_logfile=/home/forge/app.com/worker.log
```

**Comment by Arpityadav** [comment]
Hey @darklight9811, can u elaborate how u solved the issue? I am having the same issue.
