### ISSUE TITLE
¿How to test the digital ocean server websocket  connection from a basic client?

### ISSUE THREAD

**Issue by JavBautista** [beyondcode/laravel-websockets#237]
I have been able to raise the server in Digital Ocean, and from a client in my local machine with Qasar I listen to the events and communicate without problems.

My Doubt is:
I have an arduino component that rejects the connection to the Digital Ocean IP and port 6001.

But if I do the test at wss: //echo.websocket.org it does, well then what would I need to configure so that http: // MyIPinDigitalOcean port: 6001 accept the connection? If you can or should change the option?
Thank you!

**Comment by canhkieu** [comment]
You can try with Firecamp Chrome plugin
