### ISSUE TITLE
How should I configure for this package running on different server?

### ISSUE THREAD

**Issue by TheBigK** [beyondcode/laravel-websockets#240]
I'm trying to figure out a way to make laravel-websockets work with Laravel Vapor. As of now, the only solution seems to be spinning out a new server in the same VPC as that of Vapor and make a connection to it. 

So it will look like
```
--------VPC-----------------
[Main Server] ---WS---> [ Websockets Server ]
-----------------------------
```

The websockets server, in this case would need a new Laravel Installation running this package. 

I'm wondering what are the configuration changes I'll have to make on the main server so that WS works as expected?

OR - is there any better approach?

**Comment by kiwo12345** [comment]
Did you get it to work with Vapor?

**Comment by jtomek** [comment]
Did you get it to work with Vapor?

**Comment by rennokki** [comment]
The only appropriate way is to use a separate instance with the WebSocket server.
