### ISSUE TITLE
Concurrent connections limited to ~1000

### ISSUE THREAD

**Issue by rflatt-reassured** [beyondcode/laravel-websockets#244]
The socket service restarts once we hit about 1000 connections:
![image](https://user-images.githubusercontent.com/26278889/64242572-af068a80-cefd-11e9-8621-39109c71cc5e.png)

I've followed the advice on the deployment page to increase ulimit, and the sysads have confirmed that it has been set to 50000. 

I'm going to try the pecl event extension. Once I've installed it, what further configuration is required?

**Comment by rflatt-reassured** [comment]
We've fixed the issue. We installed ev, but needed to do 2 things to ev,so:

1. set the permissions so that it was globally executable.
2. rename it. Apparently php extensions are loaded in alphabetical order, and it had dependencies that were loaded after. Renaming the file to z-ev.so fixed the issue. We're holding steady at ~2000 connections.

**Comment by lucasctd** [comment]
@rflatt-reassured so after you have installed "ev" extension, you didn't need to do the ulimit thing or you have to do both?
I think the docs are not so clear about it.

**Comment by rflatt-reassured** [comment]
You need to increase the limit as well. The ev extension allows that to work. Without increasing ulimit, the ev extension doesn't add any benefit.

**Comment by lucasctd** [comment]
@rflatt-reassured thank you so much.
I have installed "[event](https://gist.github.com/Mikulas/449746102591d636640467910eaf8aad)" on my container and set the ulimit using [docker-compose](https://docs.docker.com/compose/compose-file/compose-file-v2/#ulimits).
I'd like to test it, do you use any testing tool to check how many connections your app supports?
I just thought I could make a JS loop creating connecitions to my server, but I am unsure if it will work XD

**Comment by setkyar** [comment]
@rflatt-reassured How do you set the permission? 

Base on your comment https://github.com/beyondcode/laravel-websockets/issues/244#issuecomment-533123015

**Comment by riyastir** [comment]
EV means libev?
