### ISSUE TITLE
BeyondCode\LaravelWebSockets\Apps\App is missing `path` property

### ISSUE THREAD

**Issue by leo108** [beyondcode/laravel-websockets#245]
https://github.com/beyondcode/laravel-websockets/blob/master/resources/views/dashboard.blade.php#L119 This line will always return an empty string.

**Comment by rennokki** [comment]
Not unless the `apps` array from the config file contains a `path` key.

**Comment by leo108** [comment]
You are right for the current version, I think this bug was fixed in this commit https://github.com/beyondcode/laravel-websockets/commit/24101e456feb356f83abbc901b9d5d5d1aba1861
