### ISSUE TITLE
Do I still need a pusher key?

### ISSUE THREAD

**Issue by mathewparet** [beyondcode/laravel-websockets#25]
I can see in the example code provided in your documentation you have used something similar a lot:

```
'pusher' => [
    'driver' => 'pusher',
    'key' => env('PUSHER_APP_KEY'),
    'secret' => env('PUSHER_APP_SECRET'),
    'app_id' => env('PUSHER_APP_ID'),
    'options' => [
        'cluster' => env('PUSHER_APP_CLUSTER'),
        'encrypted' => true,
        'host' => '127.0.0.1',
        'port' => 6001,
        'scheme' => 'http'
    ],
],
```

and:

```
import Echo from "laravel-echo"

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key',
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
});
```

So do I still need a PUSHER_APP_SECRET or PUSHER_APP_ID or PUSHER_APP_CLUSTER or pusher-key for this to work?!

**Comment by mathewparet** [comment]
> You can generate every secret you want :) You don't need a Pusher Account anymore.

Sorry if this is too much basic. But my understanding is pusher secret, app id, key are generated on Pusher. So are you saying, to use this websocket module, I don't need to define key, secret or app id?

**Comment by LKaemmerling** [comment]
I say you don't need to use a secret from pusher. You can generate every string you want :)

**Comment by mathewparet** [comment]
Thanks for that 👍

**Comment by BenQoder** [comment]
@mathewparet Did using random strings work for you?

**Comment by jimmyt2003** [comment]
Its not obvious from the docs
