### ISSUE TITLE
Web Socket Connection from client To Server

### ISSUE THREAD

**Issue by r00nscapenab** [beyondcode/laravel-websockets#251]
hello, the websocket from my client unit is not working. (client and server has different network)

here's my configuration:

`window.Echo = new Echo({
    authEndpoint : 'http://my-ip/r10pmd/broadcasting/auth',
    broadcaster: 'pusher',
    key: 'anyKey',
    encrypted: false,
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
    enabledTransports: ['ws'],
});`

then i get this error from my client unit:

`WebSocket connection to 'ws://my-ip:6001/app/anyKey?protocol=7&client=js&version=5.0.0&flash=false' failed: WebSocket is closed before the connection is established.
`

then this also:
`app.js:39297 WebSocket connection to 'ws://my-ip:6001/app/anyKey?protocol=7&client=js&version=5.0.0&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

but in my server's unit (and same network with the server unit) is running fine.

**Comment by canhkieu** [comment]
Please setting exactly appkey in .env file.
```
'pusher' => [
    'driver' => 'pusher',
    'key' => env('PUSHER_APP_KEY'),
    'secret' => env('PUSHER_APP_SECRET'),
    'app_id' => env('PUSHER_APP_ID'),
    'options' => [
        'cluster' => env('PUSHER_APP_CLUSTER'),
        'encrypted' => true,
        'host' => '127.0.0.1',
        'port' => 6001,
        'scheme' => 'http'
    ],
],
```
