### ISSUE TITLE
Chrome->Firefox push notifications not working

### ISSUE THREAD

**Issue by connecteev** [beyondcode/laravel-websockets#253]
Go to https://docs.beyondco.de/laravel-websockets/ in Chrome and Firefox
Click the bell icon in Chrome. Notice that the Bell icon moves in Firefox. 
Wait a few seconds and click on the bell icon in Chrome again. Notice that the Bell icon does NOT move in Firefox the 2nd time (or beyond).

Also note that this works fine 100% of the time from Firefox -> Chrome, but Chrome -> Firefox does not, and the push notification is only sent the first time.

**Comment by BoxedBrain** [comment]
does work for me.

**Comment by rennokki** [comment]
The docs website is outdated.
