### ISSUE TITLE
Does this package support cors connection to socket server?

### ISSUE THREAD

**Issue by skatetdieu** [beyondcode/laravel-websockets#254]
Just wonder if the client domain or IP can be different than the domain or IP that th websocket server lives on? 

For example, if my websocket server is on http://socket.com can I set it up to connect to it from http://myapp.com? I couldn't tell from the documentation if this is possible. 

Thank you so much for the hard work you've put into this!

**Comment by theWebKeyGuy** [comment]
This is a really good question I'm wondering the same thing? :)

**Comment by Eldair** [comment]
Yeah, it works with different domains
