### ISSUE TITLE
Any plans on using native PHP websocket?

### ISSUE THREAD

**Issue by daison12006013** [beyondcode/laravel-websockets#26]
Currently we have this package that mostly supports websockets https://github.com/walkor/phpsocket.io and also https://reactphp.org/

Do you guys have plans on integrating this kind of connection? Is this package only wraps the existing implemented pusher in laravel services and just added with Dashboard to manage it?

**Edit:**
I have seen you guys have this `WebSocketHandler.php` that you used Ratchet, however I don't know why it is bound to Pusher only (correct me if I am wrong)

It would be better to make this class to have a default connection which is the pusher, then later if someone would like to add more connections or different implementations that could follow the contracts, that helps a lot.

This could join other developers specially who's more knowledgeable with the above links I mentioned.

**Comment by mpociot** [comment]
You can already implement custom
WebSocket handlers and ignore the existing Pusher implementation: https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html
