### ISSUE TITLE
OnMessage event in the WebsoketHadler file is not listened, when APP_DEBUG = false

### ISSUE THREAD

**Issue by haric655** [beyondcode/laravel-websockets#263]
The OnMessage event in the WebsoketHadler file is not listened, when APP_DEBUG = false in the .env file.
when APP_DEBUG = true listening for the OnMessage event works  

Where problems?

Laravel 5.8 
Websockets 1.3.0

**Comment by ayuningnareswari** [comment]
same problem here, anyone can explain this?

**Comment by rennokki** [comment]
The debugging is enabled when APP_DEBUG is set to true (like the local development env). But once you are in production and disable debugging, you need to specify `--debug` in the command if you want the output to take place.
