### ISSUE TITLE
Laravel Broadcast to Others

### ISSUE THREAD

**Issue by tibinvpaul** [beyondcode/laravel-websockets#264]
Hey,

I have installed the package in the server and working fine. I am trying to use `broadcast()->toOthers();` method to broadcast the events only to other users but not working for some reason. I am using Pusher JS client and passing `socket_id` with the post data. As the doc says, I am using `Illuminate\Broadcasting\InteractsWithSockets` trait too.

Could you help me understand what might be the issue?

**Comment by idrislab** [comment]
If you're using Laravel echo you must send an X-Socket-ID header with your request to the API. More info (go down to configuration): https://laravel.com/docs/5.8/broadcasting#only-to-others

**Comment by tibinvpaul** [comment]
I am using pusher JS client. Let me try with that header. Thanks, @idrislab.

**Comment by tibinvpaul** [comment]
Thanks much, @idrislab. That did the trick!
