### ISSUE TITLE
Chrome cannot connect via wss; returns error "WebSocket opening handshake was canceled".

### ISSUE THREAD

**Issue by jonaslm** [beyondcode/laravel-websockets#266]
See #144 and https://bugs.chromium.org/p/chromium/issues/detail?id=993907.

According to the debugging done on the chromium bug report above, `laravel-websockets` seems to request client certificates. Chrome then closes the connection since it needs to open a dialog to pick certificates, but doesn't allow that for websockets.

See documentation at https://cs.chromium.org/chromium/src/net/websockets/websocket_stream.cc?g=0&l=436
```
void Delegate::OnCertificateRequested(URLRequest* request,
                                      SSLCertRequestInfo* cert_request_info) {
  // This method is called when a client certificate is requested, and the
  // request context does not already contain a client certificate selection for
  // the endpoint. In this case, a main frame resource request would pop-up UI
  // to permit selection of a client certificate, but since WebSockets are
  // sub-resources they should not pop-up UI and so there is nothing more we can
  // do.
  request->Cancel();
}
```

I assume it's some sort of misconfiguration of `laravel-websockets` that causes it to request client certificates?

**Comment by CodeJunkieio** [comment]
So what I'm understanding is that this is a laravel-websockets issue and not a chrome issue? Is everyone literally just waiting for an update?

**Comment by FfionTree** [comment]
Laravel websockets uses phps built in implementation of SSL and sockets via the [react](https://github.com/reactphp/reactphp) and [ratchet](https://github.com/ratchetphp/Ratchet) libraries. 

Testing shows that client certs are being 'discussed' when connecting directly to my server.
```
>openssl s_client -state -connect www.[hidden].com:6001
SSL_connect:SSLv3/TLS read server certificate request
..
SSL_connect:SSLv3/TLS write client certificate
```

Unfortunately, it doesn't look like you can manage the `SSLVerifyClient` directive and change how php deals with client certificates, it seems to 'accept' them by default.

From what I understand, for chrome, if your not using client certs, the only option is to setup a proxy for SSL, instead of using the built in SSL that laravel-websockets and php provides. 
- Setup a proxy so you can manage the client certificate directives yourself, via apache or nginx for eg. And proxy to the socket service normally, without encryption .
- Otherwise you would have to get chrome to show the client cert dialog when the website was accessed, the user would have to click cancel on the dialog, then the websocket, on the same domain, would work.

If anyone knows a better way please let us know!? :)

More Info here: #187 'Chrome not working with SSL'

**Comment by alex-arabadjiev** [comment]
I had this exact problem and found the answer in [this comment](https://github.com/beyondcode/laravel-websockets/issues/102#issuecomment-460585741) very helpful.

Before, I had the SSL connection working in Firefox but Chrome gave me the "WebSocket opening handshake was cancelled" error. I can't say what exactly causes is but looks like Apache's [reverse-proxy for websockets](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) is a good workaround.

The basic idea is not trying to directly establish an SSL connection between the browser and the websocket server, but rather use Apache as a proxy. To expand a bit on the linked comment (at least this is how I managed to get it working):

`a2enmod proxy proxy_http proxy_wstunnel`
`service apache2 restart`

I then added `ProxyPass "/app/" "ws://127.0.0.1:6001/app/"` to the SSL version of my virtual host's config (Certbot always splits the config in two). I then removed the `local_cert` and `local_pk` from my `config/websockets.php` and restarted the websocket server.

Note that this might not work if you have any routes in your application that start with `/app/`.

**Comment by pixagraphic** [comment]
I just can't get it to work with Chrome. @alex-arabadjiev would you be so kind and provide your broadcast.php and websockets.php config files? Maybe also the laravel-echo client config if that's what you're using. Thanks in advance!

**Comment by alex-arabadjiev** [comment]
@pixagraphic here are my websockets.php and broadcasting.php config files.
[broadcasting.php.txt](https://github.com/beyondcode/laravel-websockets/files/4745565/broadcasting.php.txt)
[websockets.php.txt](https://github.com/beyondcode/laravel-websockets/files/4745566/websockets.php.txt)

I am also using laravel-echo. My Client config looks like this: 
in `app.blade.php`:
```
    <meta name="pusher-config" content="{{ json_encode([
        'key' => env('PUSHER_APP_KEY'),
        'port' => env('LARAVEL_WEBSOCKETS_PORT'),
    ]) }}">
```
and in `app.js`:
```
import Echo from 'laravel-echo';
window.Pusher = require('pusher-js');
let token = document.head.querySelector('meta[name="pusher-config"]');

if (token) {
    let pusherSettings = JSON.parse(token.content);

    window.Echo = new Echo({
        broadcaster: 'pusher',
        key: pusherSettings.key,
        wsHost: window.location.hostname,
        wsPort: parseInt(pusherSettings.port),
        disableStats: true,
        enabledTransports: ['ws', 'wss'],
        encrypted: (window.config.appEnv === 'production')
    });
} else {
    console.error('Pusher config not found!', 'Falling back to polling!');
    window.Echo = null;
}
```

Since I am using laravel-echo, my Pusher ID, Key, and Secret are all random strings I made up.
So my `.env` looks like this:
```
PUSHER_APP_ID=<random string>
PUSHER_APP_KEY=<random string>
PUSHER_APP_SECRET=<random string>
PUSHER_APP_CLUSTER=mt1
LARAVEL_WEBSOCKETS_PROTOCOL=https
LARAVEL_WEBSOCKETS_PORT=6001
```

I hope this helps.

**Comment by westor7** [comment]
Any hope for a fix on that issue? (using nginx)

It works from Firefox but not on Chrome and other browsers.

URL: https://irc.chathub.gr/dragondyce/
Error: `websocket.js:192 WebSocket connection to 'wss://irc.chathub.gr:7097/' failed: WebSocket opening handshake was canceled`

- Thanks!

**Comment by pixagraphic** [comment]
@alex-arabadjiev thanks alot. I finally ended up setting up an nginx proxy to delegate all the SSL handling to nginx. This is the most secure and clean way to make it work across browsers in my opinion.

@westor7 I'd really recommend you to use an nginx proxy like me. Take this as a good starting point: https://ma.ttias.be/deploying-laravel-websockets-with-nginx-reverse-proxy-and-supervisord/

**Comment by salvationarinze** [comment]
@pixagraphic I did the proxy settings and nothing changed. I still have the same error

**Comment by pixagraphic** [comment]
@salvationarinze could you share your websocket.php/broadcast.php the laravel echo settings and your proxy configuration. I could have a look into it and see if I can help.

**Comment by salvationarinze** [comment]
@pixagraphic I just got it working a few minutes ago. I followed the instructions on [laravel websockets documentation](https://beyondco.de/docs/laravel-websockets/basic-usage/ssl) and changing `proxy_pass             http://127.0.0.1:6001;` to `proxy_pass             https://127.0.0.1:6001;` did the trick. Thanks

**Comment by erickneverson** [comment]
> I had this exact problem and found the answer in [this comment](https://github.com/beyondcode/laravel-websockets/issues/102#issuecomment-460585741) very helpful.
> 
> Before, I had the SSL connection working in Firefox but Chrome gave me the "WebSocket opening handshake was cancelled" error. I can't say what exactly causes is but looks like Apache's [reverse-proxy for websockets](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) is a good workaround.
> 
> The basic idea is not trying to directly establish an SSL connection between the browser and the websocket server, but rather use Apache as a proxy. To expand a bit on the linked comment (at least this is how I managed to get it working):
> 
> `a2enmod proxy proxy_http proxy_wstunnel` `service apache2 restart`
> 
> I then added `ProxyPass "/app/" "ws://127.0.0.1:6001/app/"` to the SSL version of my virtual host's config (Certbot always splits the config in two). I then removed the `local_cert` and `local_pk` from my `config/websockets.php` and restarted the websocket server.
> 
> Note that this might not work if you have any routes in your application that start with `/app/`.

@alex-arabadjiev I know it's been a while on this but concerning the certs themselves, are those self signed?  Are you referencing them in the vhosts file or is your app behind a firewall?  Would you mind posting your vhost config here (redacting any sensitive info)? Thanks.

**Comment by erickneverson** [comment]
> @pixagraphic I just got it working a few minutes ago. I followed the instructions on [laravel websockets documentation](https://beyondco.de/docs/laravel-websockets/basic-usage/ssl) and changing `proxy_pass http://127.0.0.1:6001;` to `proxy_pass https://127.0.0.1:6001;` did the trick. Thanks

@salvationarinze would you mind sharing your apache port and .conf files?  I'm struggling with this same issue.
