### ISSUE TITLE
can not access statistics on laravel

### ISSUE THREAD

**Issue by Ahmad-kh** [beyondcode/laravel-websockets#267]
hi. i am using this package on my laravel project and every thing is ok.
but in websocket panel i can't see statistics. in config file enable_statistics is true but it does not work yet!

**Comment by CodeJunkieio** [comment]
Please provide more details like the server setup along with all of the code from the configuration

**Comment by UchennaPrudensia** [comment]
try 
    `php artisan config:clear` 
    `php artisan cache:clear `

**Comment by Ahmad-kh** [comment]
thanks for your reply, but I did it and does not work yet.

**Comment by rennokki** [comment]
Have you checked https://github.com/beyondcode/laravel-websockets/issues/270 ?
