### ISSUE TITLE
[Question] Could this be a problem? Subdomain-websocket-server for staging and production?

### ISSUE THREAD

**Issue by pmochine** [beyondcode/laravel-websockets#268]
Hey so I was wondering. If I'm using the [subdomain method](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx), could this be a problem for my staging and production server?

Situation:
Production and Staging-server on a same VPS. Even the websocket-server via `socket.mydomain.com`.

My thought:
When user 1 sends to user 2 a chat message via sockets, what would happen when user 2 is online via production server and a user 2 is online via the staging page?

Would both of them get the message or would echo distinguish those messages because those are two different urls: 

Production: mydomain.com
Staging: staging.mydomain.com

**Comment by harpreetsb** [comment]
Looking for an answer, we are about to do same. And i had similar thought. Please share your experience.
