### ISSUE TITLE
Statistics not working - WebSocketStatisticsEntriesController@store not reached

### ISSUE THREAD

**Issue by pmochine** [beyondcode/laravel-websockets#270]
As in this issue https://github.com/beyondcode/laravel-websockets/issues/88, I tried to log everything.

I dumped this data from the _foreach_ inside the `save()` method of `HttpStatisticsLogger`:
And I get:
> `info('Logger', [$appId, $statistic->isEnabled(), $statistic->toArray()]);`
> [2019-10-17 15:40:10] production.INFO: Logger [458107,true,{"app_id":"458107","peak_connection_count":3,"websocket_message_count":14,"api_message_count$

 I also added a dump at the `store()` method of `WebSocketStatisticsEntriesController`. `logger('WebSocketStatisticsEntriesController:', $request->all()); `

However, this method is never reached. So there is something wrong with this part of the code:

 ```
 $this
            ->browser
            ->post(
                 action([WebSocketStatisticsEntriesController::class, 'store']),
                 ['Content-Type' => 'application/json'],
                 stream_for(json_encode($postData))
             );
 ```

Everything is set to https and I have the lock symbol as well. The whole websocket-server works fine. I even checked the route address of `action([WebSocketStatisticsEntriesController::class, 'store'])`

and it says: `https://staging.mydomain.com/laravel-websockets/statistics`
And APP_URL is set to = `https://staging.mydomain.com`

[Now in this part:](https://github.com/beyondcode/laravel-websockets/blob/master/src/Console/StartWebSocketServer.php#L53), my values are:

`StartWebSocketServer {"dns":{"BeyondCode\\LaravelWebSockets\\Statistics\\DnsResolver":"127.0.0.1"},"tls":{"verify_peer":true,"verify_peer_name":true}}`

I think this is also correct for the browser connecter.

What else. I use this on a vps, with nginx ["Same location for websockets and web contents"](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx) with port 443.

Everything works fine, just that post is never fired to WebSocketStatisticsEntriesController and thus `websockets_statistics_entries` is always empty :(

Any idea why? Thank you!!

Edit:
The routes are also registered:
                                                                                                                       |
```
|                     | GET|HEAD                               | laravel-websockets                                                                         |                                   | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\ShowDashboard                               | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize                                                                                                              |
|                     | GET|HEAD                               | laravel-websockets/api/{appId}/statistics                                                  |                                   | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\DashboardApiController@getStatistics        | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize                                                                                                              |
|                     | POST                                   | laravel-websockets/auth                                                                    |                                   | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\AuthenticateDashboard                       | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize                                                                                                              |
|                     | POST                                   | laravel-websockets/event                                                                   |                                   | BeyondCode\LaravelWebSockets\Dashboard\Http\Controllers\SendMessage                                 | web,BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize                                                                                                              |
|                     | POST                                   | laravel-websockets/statistics                                                              |                                   | BeyondCode\LaravelWebSockets\Statistics\Http\Controllers\WebSocketStatisticsEntriesController@store | BeyondCode\LaravelWebSockets\Statistics\Http\Middleware\Authorize                                                                                                                 |

```

Edit 2:

On my supervisor conf file I just copypasta of the docs:
`command=/usr/bin/php /myroot/tomy/project/artisan websockets:serve`

Do I need to set a specific host maybe?

**Comment by marcoocram** [comment]
Have you tried to enable perform_dns_lookup at config? set as true and try again

**Comment by pmochine** [comment]
@marcoocram Unfortunately, it still does not work. I restarted my websocket with `sudo supervisorctl restart websockets` & waited the 60 secs, but still nothing :( 

This are my current settings, maybe I missed somthing:

```
<?php

use BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize;

return [
    /*
     * Set a custom dashboard configuration
     */
    'dashboard' => [
        'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
    ],
    /*
     * This package comes with multi tenancy out of the box. Here you can
     * configure the different apps that can use the webSockets server.
     *
     * Optionally you specify capacity so you can limit the maximum
     * concurrent connections for a specific app.
     *
     * Optionally you can disable client events so clients cannot send
     * messages to each other via the webSockets.
     */
    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],
    /*
     * This class is responsible for finding the apps. The default provider
     * will use the apps defined in this config file.
     *
     * You can create a custom provider by implementing the
     * `AppProvider` interface.
     */
    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,
    /*
     * This array contains the hosts of which you want to allow incoming requests.
     * Leave this empty if you want to accept requests from all hosts.
     */
    'allowed_origins' => [
        //
    ],
    /*
     * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
     */
    'max_request_size_in_kb' => 250,
    /*
     * This path will be used to register the necessary routes for the package.
     */
    'path' => 'laravel-websockets',
    /*
     * Dashboard Routes Middleware
     *
     * These middleware will be assigned to every dashboard route, giving you
     * the chance to add your own middleware to this list or change any of
     * the existing middleware. Or, you can simply stick with this list.
     */
    'middleware' => [
        'web',
        Authorize::class,
    ],
    'statistics' => [
        /*
         * This model will be used to store the statistics of the WebSocketsServer.
         * The only requirement is that the model should extend
         * `WebSocketsStatisticsEntry` provided by this package.
         */
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,
        /*
         * Here you can specify the interval in seconds at which statistics should be logged.
         */
        'interval_in_seconds' => 60,
        /*
         * When the clean-command is executed, all recorded statistics older than
         * the number of days specified here will be deleted.
         */
        'delete_statistics_older_than_days' => 60,
        /*
         * Use an DNS resolver to make the requests to the statistics logger
         * default is to resolve everything to 127.0.0.1.
         */
        'perform_dns_lookup' => true,
    ],
    /*
     * Define the optional SSL context for your WebSocket connections.
     * You can see all available options at: http://php.net/manual/en/context.ssl.php
     */
    'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),
        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),
        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
    ],
    /*
     * Channel Manager
     * This class handles how channel persistence is handled.
     * By default, persistence is stored in an array by the running webserver.
     * The only requirement is that the class should implement
     * `ChannelManager` interface provided by this package.
     */
    'channel_manager' => \BeyondCode\LaravelWebSockets\WebSockets\Channels\ChannelManagers\ArrayChannelManager::class,
];

```

**Comment by okaufmann** [comment]
Did you set your APP_URL to the correct base url of your app? I had a Problem where the statistics was sent to 'localhost' where nginx can't match it to the corrext instance.

Unfortunately no error will be logged if it can't send the stats to the right server.

**Comment by pmochine** [comment]
> And APP_URL is set to = `https://staging.mydomain.com`

@okaufmann, I just checked again and the APP_URL is still set correctly.

I do it like this:
```
//.env
APP_DOMAIN=staging.mydomain.com
URL_SECURE=https://
APP_URL=${URL_SECURE}${APP_DOMAIN}
```

**Comment by tibinvpaul** [comment]
Same issue here. The stats are available for just the day I have installed the package but not available after that. Were you able to solve this issue, @pmochine?

**Comment by pmochine** [comment]
@tibinvpaul Unfortunately no, I would post the solution if I would find the answer.

**Comment by tibinvpaul** [comment]
I restarted the process and it started working again! Let me monitor for some days and see if it goes down again.

**Comment by ragingdave** [comment]
I ran into this, and it turned out to be a sqlite issue in my case. Same symptoms though, never "hitting" the post method. I even had a dump statement in the stat controller on the store method and it never fired but it was because the overlying folder for the sqlite instance wasn't properly permissioned, so it was throwing a log error (https://serverfault.com/a/57597). After moving/fixing this issue, stats started working again. Mostly..there is still the issue of the dashboard not being updated as stats change

**Comment by pmochine** [comment]
@ragingdave thanks for the comment, unfortunately, I'm still using the good old mysql.

**Comment by RobGordijn** [comment]
I ran into similar issues with the mysql db.
Solved by setting `perform_dns_lookup` to `true` and adding the host entry in `/etc/hosts`.
Seems like it couldn't reach it via dnsmasq.

**Comment by Livijn** [comment]
I am having the same issue. I added `info(action([WebSocketStatisticsEntriesController::class, 'store']), $postData);` to https://github.com/beyondcode/laravel-websockets/blob/d7b996381d5c3a223f13b69cf35eb43cc6633fca/src/Statistics/Logger/HttpStatisticsLogger.php#L78

The output is this:

> [2020-04-03 08:11:02] local.INFO: https://sockets.test/dashboard/statistics {"app_id":"xxx-dev","peak_connection_count":1,"websocket_message_count":1,"api_message_count":0,"secret":"xxx"} 

So I used Postman to manually send a POST request to the same URL with the same data, and that works. So there is something wrong with this code:

```php
            $this
                ->browser
                ->post(
                    action([WebSocketStatisticsEntriesController::class, 'store']),
                    ['Content-Type' => 'application/json'],
                    stream_for(json_encode($postData))
                );
```

So looking at the browser connect, I see that it is not verifying the peer, so it is probably the DNS resolver.

```php
        $connector = new Connector($this->loop, [
            'dns' => $this->getDnsResolver(),
            'tls' => [
                'verify_peer' => config('app.env') === 'production',
                'verify_peer_name' => config('app.env') === 'production',
            ],
        ]);
```

But i've tried setting `perform_dns_lookup` to both true & false and neither works.

**Comment by mikkpokk** [comment]
```
    $this->browser
            ->post(
                    action([WebSocketStatisticsEntriesController::class, 'store']),
                    ['Content-Type' => 'application/json'],
                    stream_for(json_encode($postData))
                );
```

**Logic above returns following response error:**

`
/vendor/beyondcode/laravel-websockets/src/Statistics/Logger/HttpStatisticsLogger.php:92:
string(61) "Connection to socketserver.lar:80 timed out after 60 seconds"
`

However, socketserver.lar is the correct domain for a local environment. It's not possible to replicate issue with Postman nor Chrome.

**Comment by dhi2** [comment]
I set `perform_dns_lookup` to true and it worked.

**Comment by drewjoh** [comment]
In the hopes that my own findings helps anyone: 🙏 

After many hours, I narrowed it down to getting this error in production:
```
Argument 1 passed to BeyondCode\LaravelWebSockets\Apps\App::findByKey() must be of the type string, null given, called in /home/forge/{APP_URL}/releases/20210225191540/vendor/beyondcode/laravel-websockets/src/Statistics/Http/Middleware/Authorize.php on line 12 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to BeyondCode\\LaravelWebSockets\\Apps\\App::findByKey() must be of the type string, null given, called in /home/forge/{APP_URL}/releases/20210225191540/vendor/beyondcode/laravel-websockets/src/Statistics/Http/Middleware/Authorize.php on line 12 at /home/forge/{APP_URL}/releases/20210225191540/vendor/beyondcode/laravel-websockets/src/Apps/App.php:41)
```

It turns out, the payload being sent to record statistics was:
```
array (
  'app_id' => '111777',
  'peak_connection_count' => 0,
  'websocket_message_count' => 0,
  'api_message_count' => 2,
  'secret' => '92....77',
)
```

But the `handle()` method in  [`...\LaravelWebSockets\Statistics\...\Authorize.php`](https://github.com/beyondcode/laravel-websockets/blob/b793f7b98a42effa390a6eb4e562acd9eedac31c/src/Statistics/Http/Middleware/Authorize.php#L11) is expecting a `key` field to be sent in this payload.  

As a quick fix, I created my own `Authorize.php` class, changing the `::findByKey()` lookup to be `::findById()` and used the `app_id` field being sent... but... **this did not work**.  
For whatever reason, the app continued to use the `...\LaravelWebSockets\Statistics\...\Authorize.php` file... even though I changed it to my custom one in the `websockets.php` config.
(Maybe a different bug??)

So, **instead**, I copied and made a custom `...\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger.php`... and modified the [`$postData`](https://github.com/beyondcode/laravel-websockets/blob/b793f7b98a42effa390a6eb4e562acd9eedac31c/src/Statistics/Logger/HttpStatisticsLogger.php#L75) being sent to include the `key`.  
I set the `websockets.php` to use this logger, and it looks like **it works**!

If anyone knows some obvious thing I'm missing about the payload, I'd love to know!  

The config has to be just perfect for all these pieces to work together... so I wouldn't be surprised if the payload here is determined by something that I messed up.

**Comment by yevheniy2407** [comment]
I also rewrote the library
created CustomWebSocketsServiceProvider from WebSocketsServiceProvider
and register it in config/app providers section

and rewrited AuthorizeStatistics Middleware to use findById 
`$app = App::findById($request->app_id);`
