### ISSUE TITLE
Help with Dokku

### ISSUE THREAD

**Issue by paschaldev** [beyondcode/laravel-websockets#271]
I need anybody to help me how to get it working with dokku. I've tweaked my `nginx.conf` multiple times all to no avail.

I am at a standstill now and don't know what else to do. I have it working fine on localhost. My production server is Amazon AWS EC2 for which I have opened the port `6001` in the inbound security group.

From what I have gathered so far, dokku has some limitations with PORT and I was wondering if I can start the server `php artisan websocket:serve` on the default web PORT 80 ?? If yes, how do I go about it. 

Any help would be appreciated, thanks.

**Comment by paschaldev** [comment]
I had to switch to using `swoole` laravel server for dokku which has websocket implemented.

**Comment by AlexR1712** [comment]
@paschaldev could you give more documentation on how you implemented it in dokku?

**Comment by paschaldev** [comment]
@AlexR1712 I used laravel swoole (https://github.com/swooletw/laravel-swoole) which comes with its own websocket implementation.
