### ISSUE TITLE
Stateless authentication issue

### ISSUE THREAD

**Issue by deep80** [beyondcode/laravel-websockets#273]
I need to implement realtime broadcasting on a single page application (Laravel and Vue). I also need to broadcast to users on presence channel whose ever signs in. The authentication is done using vuex and works fine except broadcasting. The issue is that i am not able to authenticate the user on that channel.

I am sending the api middleware attribute to the broadcast auth method ans also passing the authorization access token on the echo config file. yet still not works.

I am strictly following laravel's guide to broadcasting.

**Comment by rennokki** [comment]
Is this problem still relevant?

**Comment by deep80** [comment]
I finally figured it out how to do that :-) You can close the issue !!

**Comment by rennokki** [comment]
@deep80 If you feel like you can pass the solution, you can do so, just in case anyone has this issue in the future.
