### ISSUE TITLE
how to setup config not to use Pusher?

### ISSUE THREAD

**Issue by goopter** [beyondcode/laravel-websockets#274]
it’s still relying on the pusher for the broadcast message service? In the config file, there’s pusher configuration, how do I disable pusher and use local messaging service via Redis or something ?

config/websockets.php

```
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],
```

**Comment by Gummibeer** [comment]
After reading Freeks blog post https://freek.dev/1228-introducing-laravel-websockets-an-easy-to-use-websocket-server-implemented-in-php I understand better why pusher is still there.
It's a drop-in replacement. So they implement the pusher API in your Laravel App. That's why they use the pusher variables by default.

**Comment by leonelngande** [comment]
Does this mean we register a Pusher account then use the config provided by Pusher in .env file..?

Have tried that and am getting the exception:
```
Exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `xxxxxxxxxxxxxxxxxxxx`.`
Unknown app id: exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `xxxxxxxxxxxxxxxxxxxx`.`.
```

Any help is appreciated, thanks.

**Comment by leonelngande** [comment]
> Does this mean we register a Pusher account then use the config provided by Pusher in .env file..?
> 
> Have tried that and am getting the exception:
> 
> ```
> Exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `xxxxxxxxxxxxxxxxxxxx`.`
> Unknown app id: exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `xxxxxxxxxxxxxxxxxxxx`.`.
> ```
> 
> Any help is appreciated, thanks.

Killed and restarted the websocket server and it now works as expected :-)
The server was already running when I updated the pusher .env variables, so guess I had to restart it so it makes use of the updated configuration.
