### ISSUE TITLE
how to setup subdomain for the websocket connection

### ISSUE THREAD

**Issue by goopter** [beyondcode/laravel-websockets#275]
does laravel-websockets require Echo for frontend to connect? is it possible to use native javascript or php websocket as a client to connect with laravel web sockets instead of Laravel-Echo? 

I tried the following js code, it's relying on the laravel-echo and able to connect to the server

import Echo from "laravel-echo";
window.Pusher = require("pusher-js");
window.Echo = new Echo({
    broadcaster: "pusher",
    key: "somekey",
    wsHost: "localhost",
    wsPort: 6001,
    disableStats: true
});

however, the standard websocket does not work:
window.Socket = new WebSocket("wss://localhost:6001");

**Comment by rennokki** [comment]
Laravel Websockets is a drop-in replacement for Pusher, so you'll need to use a client that has support for the Pusher protocol. 

You can use either Laravel Echo with `pusher` driver or use directly the Pusher JS SDK.
