### ISSUE TITLE
Working with tenancy/multi-tenant

### ISSUE THREAD

**Issue by fernandocoronatomf** [beyondcode/laravel-websockets#277]
I am using this package and it's been great so far.

Now I need to move my application into a multi-tenant environment and as I have only one tenant right now everything seems to be working perfectly fine with 'tenancy/multi-tenant'.

In the docs it says it comes with out of the box multi-tenant support but I can't find any further reading...

Is it the case indeed? I don't need any extra config? Thanks!

**Comment by vannut** [comment]
You could define several 'apps' in `websockets.apps`- array. But then, you'll have to extend that array with every new tenant you put to your SaaS.

I solved this by using just 1 app in the websockets-package and then have every tenant have their own channel. In your `routes/channels.php` you then can define restrict who is able to join the channel. 
```
Broadcast::channel('tennant.{id}' fuunction ($user, $id) {
   return (int) $user->tenant_id === (int) $id;
})
```

The same goes for your frontend: 
```
Echo.channel(`tenant.${window.settings.tenant_id}`)
    .listen('OrderShipped', (e) => {
        console.log(e.order.name);
    });
```

**Comment by fernandocoronatomf** [comment]
@vannut Yes I could do something like that but actually my multi-tenant system uses multiple databases so there's no $user->tenant_id.. I guess I could use the {website_id} + {user_id} as the channel?

**Comment by vannut** [comment]
Yeah well that's the same. Somehow you make the difference between different tennants. Use that unique identifier as `website_id`.

**Comment by ebaliatico** [comment]
@fernandocoronatomf I've had success using a custom app provider (https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/app-providers.html). I've included some code below. I also create a random key and secret per tenant upon their creation by overriding the Website model for the tenancy package.

```

// TenantAppProvider.php

use BeyondCode\LaravelWebSockets\Apps\App;
use BeyondCode\LaravelWebSockets\Apps\AppProvider;

class TenantAppProvider implements AppProvider
{
    // ....
    // see https://github.com/beyondcode/laravel-websockets/blob/master/src/Apps/ConfigAppProvider.php for rest of the methods

    protected function instanciate($website): ?App
    {
        $app = new App(
          $website->id,
          $website->pusher_key,
          $website->pusher_secret,
        );

        $app->setName($website->uuid);

        $app
            ->enableClientMessages(false)
            ->enableStatistics(true);

        return $app;
    }
}

// Website.php

use Hyn\Tenancy\Models\Website as BaseWebsite;

class Website extends BaseWebsite
{
    use \Hyn\Tenancy\Traits\UsesSystemConnection;

    protected $visible = ['pusher_key'];  // don't want to expose uuid or secret

    protected static function boot()
    {
        parent::boot();

        static::created(function ($model) {
            if (is_null($model->pusher_key)) {
                $model->pusher_key = bin2hex(random_bytes(16));
            }
            if (is_null($model->pusher_secret)) {
                $model->pusher_secret = bin2hex(random_bytes(32));
            }
            $model->save();
        });
    }
}

**Comment by scramatte** [comment]
Hello, 

I'm running Laravel 8 , and I got `Target class [App\Providers\WebsocketConfigAppProvider] does not exist.`
Any idea what occurs here?

Regards

**Comment by Surt** [comment]
> @fernandocoronatomf I've had success using a custom app provider (https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/app-providers.html). I've included some code below. I also create a random key and secret per tenant upon their creation by overriding the Website model for the tenancy package.
> 
> ```
> 
> // TenantAppProvider.php
> 
> use BeyondCode\LaravelWebSockets\Apps\App;
> use BeyondCode\LaravelWebSockets\Apps\AppProvider;
> 
> class TenantAppProvider implements AppProvider
> {
>     // ....
>     // see https://github.com/beyondcode/laravel-websockets/blob/master/src/Apps/ConfigAppProvider.php for rest of the methods
> 
>     protected function instanciate($website): ?App
>     {
>         $app = new App(
>           $website->id,
>           $website->pusher_key,
>           $website->pusher_secret,
>         );
> 
>         $app->setName($website->uuid);
> 
>         $app
>             ->enableClientMessages(false)
>             ->enableStatistics(true);
> 
>         return $app;
>     }
> }
> 
> // Website.php
> 
> use Hyn\Tenancy\Models\Website as BaseWebsite;
> 
> class Website extends BaseWebsite
> {
>     use \Hyn\Tenancy\Traits\UsesSystemConnection;
> 
>     protected $visible = ['pusher_key'];  // don't want to expose uuid or secret
> 
>     protected static function boot()
>     {
>         parent::boot();
> 
>         static::created(function ($model) {
>             if (is_null($model->pusher_key)) {
>                 $model->pusher_key = bin2hex(random_bytes(16));
>             }
>             if (is_null($model->pusher_secret)) {
>                 $model->pusher_secret = bin2hex(random_bytes(32));
>             }
>             $model->save();
>         });
>     }
> }
> ```

Hi, @ebaliatico . I was triying to use your solution for the tenancy package but I'm having problems trying to understand the App Provider (even on the documentation at websockets.
` protected function instanciate($website): ?App`  where is website especified when instantiating the App? on the documentation it's used as `protected function instanciate(?array $appAttributes) : ? App`  but still, where does `$appAttributes` come from?

I would like to use your AppProvider solution but using the "current tenant" as argument for the instantiate.

**Comment by Surt** [comment]
> @vannut Yes I could do something like that but actually my multi-tenant system uses multiple databases so there's no $user->tenant_id.. I guess I could use the {website_id} + {user_id} as the channel?

I know, it was a long time but, for the sake of documenting posibilities I did the same as @vannut but checking the tenant in this way:

```php
Broadcast::channel('Session.{id}', function ($user, $id) {
   return (tenancy()->tenant->id === $id);
});
```

just be sure of using `tenancy` on the BroadcastServiceProvider for routes

```php
        Broadcast::routes(['middleware' => ['tenancy', 'api']]);
```
