### ISSUE TITLE
Error broadcasting new event onClose websocket handler

### ISSUE THREAD

**Issue by aguzt95** [beyondcode/laravel-websockets#278]
I want to broadcast event when connection is close by force(closed tab), to notify front end which connection is closed, and i got this error while doing broadcasting inside onclose function in websockethandler file

Exception `Illuminate\Broadcasting\BroadcastException` thrown: ``

![Capture](https://user-images.githubusercontent.com/57226173/67956834-4ac72500-fc27-11e9-84e9-ee1492d624b1.JPG)

**Comment by dark0fire** [comment]
I got the same issue. Both the `event()` function and the `broadcast()` function do not work in the Handler scope. Found a solution to it?
