### ISSUE TITLE
Unable to revoke granted access to private channels

### ISSUE THREAD

**Issue by mpskovvang** [beyondcode/laravel-websockets#279]
I'm having a little security concern regarding private channels. After digging the code and reading the documentation on both beyondco.de and pusher.com, I can't find any authentication expiration or revoking functionality.

If my understanding is correct, a user has lifetime access to a private channel when first authenticated successfully as long as the connection is kept alive. The auth signature has no timestamp.

If this is true, a user invited to e.g. a private team channel might still have access to sensitive data after being removed from the team.

It would be great if we could revoke a specific user's access to a channel through server-side interactions. This probably requires more details on socket owner and connected channels than currently available - and might be the reason why such functionality doesn't exist yet.

I'm just curious how others are handling revoking? Perhaps I'm missing some basic knowledge. 🙂 

Btw, thanks for a really great package that just works! 👍

**Comment by rennokki** [comment]
This is not how it works. The Laravel Echo, for example, has a `auth` setting where you can set the authentication path that will make a request to and the response will determine if the user can, and make him able to, connect to the WebSocket server
