### ISSUE TITLE
laravel-websockets is working only in one application

### ISSUE THREAD

**Issue by naveed117** [beyondcode/laravel-websockets#280]
Hello All. 

i used this package for real time chat application, i tried this package first in demo project and it is working fine and now i am trying to implement the same thing with same configuration but when i try to enter the url localhost:8000/laravel-websockets then i get 404 not found error, although everything is installed correctly. when i try to run the command php artisan websocket:serve then it's showing that server started on 6001 but in browser console i get "can't establish the connection" error. i am stuck in it from 2 days. any help would be really appreciated. 

thank you

**Comment by edtorba** [comment]
@naveed117 ensure that `App\Providers\BroadcastServiceProvider::class,` is not commented out in `config\app.php` 👍
