### ISSUE TITLE
failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by periseas** [beyondcode/laravel-websockets#282]
I get the error: failed: WebSocket is closed before the connection is established.

![image](https://user-images.githubusercontent.com/5693741/68147372-8865cf80-feff-11e9-97f6-a7ce5b29c444.png)

I already checked many answers but I can't find the solution, I leave the codes.

 **websockets.php**  
 
![image](https://user-images.githubusercontent.com/5693741/68147950-b861a280-ff00-11e9-832c-70c716a43745.png)
![image](https://user-images.githubusercontent.com/5693741/68147970-c31c3780-ff00-11e9-8410-eb6f54b271bf.png)

**broadcasting.php**

![image](https://user-images.githubusercontent.com/5693741/68148045-e34bf680-ff00-11e9-8cdc-f1bf46a03a38.png)

**Bootstrap.js**
![image](https://user-images.githubusercontent.com/5693741/68148081-ed6df500-ff00-11e9-81fa-552bca9559ad.png)

> **Note**
> Already verify that port 6001 is open

**Comment by canhkieu** [comment]
Please show your debug logs of websockets:serve

**Comment by xlcrr** [comment]
I'm getting the same error. Been stuck on this for weeks with Forge + nginx + AWS. Would love to see a new tutorial making this work

**Comment by kiwo12345** [comment]
any news on this? I have the same problem

**Comment by canhkieu** [comment]
Please show your debug logs of websockets:serve

**Comment by Cello93** [comment]
verify that if you have the port open or you can enable it with,
sudo iptables -A INPUT -p tcp -i eth0 --dport 6001 -j ACCEPT

**Comment by r0bdiabl0** [comment]
I too am seeing this same error message. I am using Laravel Forge with a Digital Ocean instance. Latest Laravel 6 and PHP 7.4.

There are no debug logs of websocket:serve. It says:

`Starting the WebSocket server on port 6001...` but nothing else.

**Comment by r0bdiabl0** [comment]
I downgraded to PHP 7.3 to try as well as 7.4 required the latest pusher/pusher-php-server v4. After downgrading to 7.3, I updated to latest pusher/pusher-php-server v3. That did not help either.

**Comment by r0bdiabl0** [comment]
Ok, I think I solved the problem for myself and that this helps others. I am using Laravel Forge to provision the servers. I also use SSL option and Let's Encrypt. This automatically forces all traffic to use SSL. So when you are trying to connect to websockets, it's trying to connect over wss which is the secure url for websockets. 

I didn't have websockets configured for SSL so it was denying the connection. Once I configured SSL for websockets, I was finally able to connect the dashboard successfully. For Forge, I just used the path's that it created for the Let's Encrypt certs and added them to the websockets configuration.

**Comment by rennokki** [comment]
For future reference, there might be a problem with the client: https://github.com/beyondcode/laravel-websockets/issues/510

**Comment by mnuellas** [comment]
Hi ! Sorry for re-opening old subjects, I also found a solution after reading r0bdiabl0's answer.
If after configuring the ssl for your websockets and it stills not working try adding 
`'verify_peer' => false,`
to your config/websockets.php file in the ssl configuration.
Worked for me
