### ISSUE TITLE
Laravel websocket in subdirectory

### ISSUE THREAD

**Issue by kikedb** [beyondcode/laravel-websockets#283]
Hi, please can you help me.

My scheme of files  is: 

var/www/turnerosac           --> files base projects
/var/www/html/turnerosac   --> files public

When executing the command:

/usr/bin/php /var/www/turnerosac/artisan websocket:serve

Throw the following message in the console

Starting the WebSocket server on port 6001...
New connection opened for app key e992c96bf63f43766490.
Connection id 154192426.353203179 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"154192426.353203179\",\"activity_timeout\":30}"}

My bootstrap.js 
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'e992c96bf63f43766490',
    cluster: 'us2',
    wsHost: window.location.hostname,
    wsPort: 6001
    // disableStats: true,
});
```

**Comment by rennokki** [comment]
What's the issue here?
