### ISSUE TITLE
Undefined Property IoConnection::$app on WebsocketsLogger::onMessage

### ISSUE THREAD

**Issue by CristianHG2** [beyondcode/laravel-websockets#286]
I am currently experiencing an issue on a fresh install of `laravel-websockets`. I've used the library in the past which has worked fine, however this time I am experiencing an issue in Ubuntu 18.04 Desktop.

The exception comes from `Server\Logger\WebsocketsLogger::onMessage($connection, $message)` and seems to relate to the `app` property of the `$connection` parameter.

![code](https://user-images.githubusercontent.com/4695165/68618147-bb2b3d00-0496-11ea-9897-b216f5ba56a1.png)

![error](https://user-images.githubusercontent.com/4695165/68618554-997e8580-0497-11ea-968e-310f21633577.png)

I've published all the configurations, migrations and also tried setting up Pusher on the `.env` file, I've also cleared the config cache and still no results.

I was able to regain functionality by changing Server\Logger\WebSocketsLogger.php:41 to this (Just checks if the properties exist), of course this is just a horrible hack to make it work since I had to change the source code of the composer package directly:

![code2](https://user-images.githubusercontent.com/4695165/68619107-c67f6800-0498-11ea-9896-477db96e27d9.png)

**Comment by alfalfarias** [comment]
Did you solve this issue? It's happening the same to me

**Comment by CristianHG2** [comment]
@alfalfarias I solved it by modifying the vendor package directly which I wanted to avoid doing, but wasn't able to solve it any other way. Ended up rebuilding my Websockets server in Node and communicating with my applications via HTTP calls.

**Comment by alfalfarias** [comment]
@CristianHG2 i solved it with this other #342 .If you set the following attributes It works perfectly:
```
$connection->socketId 
$connection->app
```
Even though I don't know how it works, but i'm investigating.

**Comment by CristianHG2** [comment]
Well, at least we have a solution! Might consider using this library again in the future. Will investigate as well.

Thank you!
