### ISSUE TITLE
Usage in iOS

### ISSUE THREAD

**Issue by zarpio** [beyondcode/laravel-websockets#287]
Please guide how to use in iOS with Swift?

**Comment by anilios** [comment]
Did you figure this out?


I tried this but it never connects:

let options = PusherClientOptions(
            autoReconnect: true,
            host: .host("https://xyz.com"), //This is the server where web socket is working just fine.
            port: 6001
        )
        //Key is not actual key from Pusher, this is just some string that is set up on the server. Do we need to actually buy a key to make this work?
        let pusher = Pusher(key: "ChatAppKey", options: options)
        pusher.delegate=self
        pusher.connect()

**Comment by AugmentBLU** [comment]
@anilios Did you ever get this working with iOS/Swift?
