### ISSUE TITLE
Not working with Laravel Valet

### ISSUE THREAD

**Issue by ronfloraxCT** [beyondcode/laravel-websockets#29]
Thank you for making this package. It comes at the perfect time for me, I'm just starting to use websockets on a project I've got running.

It might be an oversight on my part, but I can't get this to work with Laravel Valet. Using Pusher with Laravel's default config works, but as soon as I make the necessary changes in the config and try to broadcast an event I get an empty `Illuminate\Broadcasting\BroadcastException`.

config/broadcasting.php
```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],
```

config/websockets.php
```
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],

    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,

    'allowed_origins' => [
        //
    ],

    'max_request_size_in_kb' => 250,

    'path' => 'laravel-websockets',

    'statistics' => [
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,

        'interval_in_seconds' => 60,

        'delete_statistics_older_than_days' => 60,
    ],

    'ssl' => [
        'local_cert' => '/Users/ronflorax/.config/valet/Certificates/snookerscores.test.crt',

        'local_pk' => '/Users/ronflorax/.config/valet/Certificates/snookerscores.test.key',

        'passphrase' => null,

        'verify_peer' => false,
    ],
```

**Comment by cashlion** [comment]
Are you seeing any errors in your browser console, like a closed connection or a 404 error? It's possible you just need to update your Echo config to use encrypted connections over wss.

```JavaScript
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    encrypted: true,
    disableStats: true
});
```

**Comment by cashlion** [comment]
Also, in **broadcasting.php**, add `'encrypted' => true` to your pusher config options.

**Comment by vesper8** [comment]
you don't need to add encrypted => true to your broadcasting.php

however you do need to add wssPort: 6001 in your bootstrap.js and then rebuild the app using npm run prod

had the same problem yesterday and it's working now. This is all explained here too https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-laravel-valet

**Comment by ronfloraxCT** [comment]
Thanks for the tips, however neither work, as it's actually going wrong before consuming the events, it goes wrong when dispatching them from an artisan command, so no javascript involved yet. I tried adding `'encrypted' => true` either way and it made no difference.

**Comment by Livijn** [comment]
I am having the same issue using Laravel Valet.

**Comment by anabeto93** [comment]
I tried every possible means to follow the docs with regards to SSL but just couldn't get it to work. However, this is how I finally got it working with SSL on homestead.

changed *boostrap.js* to listen on *6002* instead
`window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: process.env.MIX_PUSHER_WEBSOCKET_HOST,//window.location.hostname,
    wsPort: 6002,
    wssPort: 6002,
    disableStats: true,
    encrypted: true
});`

added these two keys to my .env file 
MIX_PUSHER_WEBSOCKET_HOST="${PUSHER_WEBSOCKET_HOST}"
PUSHER_WEBSOCKET_HOST=socket.websocket-demo.app

note that the above, websocket host, is actually a subdomain, 

`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => env('PUSHER_WEBSOCKET_HOST','127.0.0.1'),
                'port' => 6002,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],`
in *broadcasting.php*

and then finally using the sample nginx config found at [https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-a-reverse-proxy-like-nginx](url)

except, adding the line in the config to listen on *6002*

`listen        443 ssl;
  listen        [::]:443 ssl;
  listen 6002;`

and that's just about it

**Comment by Livijn** [comment]
Why is this issue closed? 😳

**Comment by freekmurze** [comment]
I was thinking the answer of @anabeto93 solved the issue. Reopended.

**Comment by vesper8** [comment]
@ronfloraxCT @Livijn 

I was having trouble getting this to work with Laravel Valet and now everything works fine. The demo works fine and I also have it working with a standalone websocket app that is now handling web sockets for 5 of my apps (this is all on my macbook dev using Laravel Valet with --secure

My thread here might prove useful https://github.com/beyondcode/laravel-websockets/issues/8

I suggest you take a step back and try to get the demo working with Laravel Valet first. Once you have that working then you can try to get your own apps working.

Also I think @anabeto93's response has nothing to do with Valet.. correct me if I'm wrong but when you use Homestead you don't use Valet at all.

**Comment by Livijn** [comment]
Adding this solved it for me!

    'curl_options' => [
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_SSL_VERIFYPEER => 0,
    ]

**Comment by ronfloraxCT** [comment]
@vesper8 Unfortunately that thread doesn't help me, because most of it concerns Laravel Echo, and my problem occurs before that. The one post in it which does show the same error as me is somehow resolved by using the same settings I have been using from the start, which is weird. I copy-pasted them to be sure. So in short, I'm still stuck with this!

**Comment by ronfloraxCT** [comment]
Turns out it does work if the server is running, but if it's not running it fails as described in the original post. I think it's quite misleading that it fails without any error to be honest! I don't have the server running permanently in my test environment, but it seems I'll have to keep an eye on this. Closing this for now.

**Comment by stayallive** [comment]
@ronfloraxCT ah. Yes. The server does need to be running to be able to broadcast any events since the events are broadcasted over the http(s) API.

You will also get a exception if Pusher goes down for example since the broadcast API request fails.

You could for example add a check around each broadcast, for example `if (env('ENABLE_BROADCASTS', true))` and add `ENABLE_BROADCASTS=false` to your `.env` locally to quickly disable broadcasting for your local environment.

**Comment by paulkatipunan** [comment]
Try this 
'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => '/Users/YOUR-USERNAME/.valet/Certificates/VALET-SITE.TLD.crt',

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => '/Users/YOUR-USERNAME/.valet/Certificates/VALET-SITE.TLD.key',

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => null,

        'verify_peer' => false,
    ],
