### ISSUE TITLE
Second websockets worker setup

### ISSUE THREAD

**Issue by aokozlov** [beyondcode/laravel-websockets#293]
We are using one websockets worker to send messages to 25k clients. It uses about 1GB RAM and 100% of one CPU core. It seems like it can't handle more active connections with messages sent. 

We use Nginx as reverse proxy for that. So is there any way to set up another `artisan websockets:serve` on different port and somehow set up our nginx to handle it all. Messages are sent from events with ShouldBroadcast. 

Maybe there are other ways to handle this highload?

**Comment by rennokki** [comment]
This PR adds support for horizontally scaling using Redis: https://github.com/beyondcode/laravel-websockets/pull/140

I assume that your issue can also be solved by creating a driver for local, file, cache.
