### ISSUE TITLE
Unknown app id provided 

### ISSUE THREAD

**Issue by allawitte** [beyondcode/laravel-websockets#294]
I get a constant error  "message": "{\"error\":\"Unknown app id `testapp` provided.\"}",  when I set in .env   PUSHER_APP_ID=testapp. How it works? Does it check with Pusher for real aplication IDs created with Pusher?

**Comment by ghprod** [comment]
Did you use a custom handler?

**Comment by allawitte** [comment]
For sure, 


Web-site: http//allawitte.nl

 

----- Reply to message -----
Subject: Re: [beyondcode/laravel-websockets] Unknown app id provided (#294)
Date: ср, 4 мар. 2020, 15:40

**Comment by rennokki** [comment]
`php artisan config:clear` ?

**Comment by Laraveldeep** [comment]
Same here. While developing, it was working fine on localhost. However, I am getting the same exact error after cloning to web server.
What is causing this?

**Comment by Sham3334** [comment]
Same problem... Any news? I haven't been able to decide for a week, do I really have to abandon laravel-websockets in favor of other solutions?
