### ISSUE TITLE
pusher.min.js:8 WebSocket connection to 'ws://127.0.0.1:6001/app/car?protocol=7&client=js&version=4.3.1&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by nguyen179son** [beyondcode/laravel-websockets#295]
I got this error on client after running php artisan websockets:serve.
My Broadcast.php: 
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],
websocket.php
 [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],

bootstrap.js

import Echo from "laravel-echo"

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'car',
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
});

**Comment by EduTechnodac** [comment]
Same here

**Comment by nguyen179son** [comment]
@EduTechnodac  my problem is that I use laradock to install the environment for my laravel project. The solution is [here](https://github.com/laradock/laradock/issues/2002#issuecomment-468884705)
