### ISSUE TITLE
Illuminate\Broadcasting\Broadcasters\PusherBroadcaster::broadcast :119

### ISSUE THREAD

**Issue by Cello93** [beyondcode/laravel-websockets#298]
I do not understand why this error appears in https when I want to execute the event, in http it works without problems.

![error_broadcast_pusher](https://user-images.githubusercontent.com/32339893/71256530-c4b68900-230f-11ea-8bcc-e0943c51df2c.png)

**Comment by devfake** [comment]
Try to activate `log` in the pusher connection in `broadcasting.php`, and see what error is logged in your log files.

```
    'connections' => [

        'pusher' => [
            // ...
            'log' => true, <-- THIS
            'options' => [
             // ....

```

**Comment by Cello93** [comment]
![error_broadcast_ssl](https://user-images.githubusercontent.com/32339893/72074761-40817100-32d1-11ea-9493-fe2d514bed04.png)


> Intente activar `log`la conexión de empuje `broadcasting.php`y vea qué error se registra en sus archivos de registro.
> 
> ```
>     'connections' => [
> 
>         'pusher' => [
>             // ...
>             'log' => true, <-- THIS
>             'options' => [
>              // ....
> ```

How do I solve this?
![error_broadcast_ssl](https://user-images.githubusercontent.com/32339893/72074826-63ac2080-32d1-11ea-98bb-52b2b2910fa4.png)

**Comment by devfake** [comment]
Can you try this out in the `options` array of the pusher connection:

```
'options' => [
        // ...
        'curl_options' => [
             CURLOPT_SSL_VERIFYHOST => 0,
             CURLOPT_SSL_VERIFYPEER => 0,
        ]
 ],
```

I think to disable it on development should be ok (?).

**Comment by Cello93** [comment]
> ¿Puedes probar esto en la `options`matriz de la conexión del empujador?
> 
> ```
> 'options' => [
>         // ...
>         'curl_options' => [
>              CURLOPT_SSL_VERIFYHOST => 0,
>              CURLOPT_SSL_VERIFYPEER => 0,
>         ]
>  ],
> ```
> 
> Creo que deshabilitarlo en el desarrollo debería estar bien (?).


Thank you very much, I solved it by updating the SSL and adding,
 'curl_options' => [
             CURLOPT_SSL_VERIFYHOST => 0,
             CURLOPT_SSL_VERIFYPEER => 0,
        ]

**Comment by Cello93** [comment]
Thank you very much, I solved it by updating the SSL and adding,
 'curl_options' => [              CURLOPT_SSL_VERIFYHOST => 0,
             CURLOPT_SSL_VERIFYPEER => 0,         ]
