### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by chadidi** [beyondcode/laravel-websockets#299]
I keep getting this error with my private channels,

```
Access to XMLHttpRequest at 'http://site.me/api/broadcasting/auth' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Cross-Origin Read Blocking (CORB) blocked cross-origin response http://site.me/api/broadcasting/auth with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```
public channel working fine, this happens on both local with homestead and production on VPS.

If can help I am using:
```
"barryvdh/laravel-cors": "^0.11.4",
"beyondcode/laravel-websockets": "^1.3",
"laravel-echo": "^1.6.1",
"pusher-js": "^5.0.3",
```

**Comment by pointermess** [comment]
I have the same issue. Have you been able to fix it?

**Comment by abhiburk** [comment]
Any solution for this? Getting similar message on VPS

**Comment by J4si3k** [comment]
I also have:

> Access to XMLHttpRequest at 'localhost:8000/api/broadcasting/auth' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https

of course I set CORS with [this package](https://github.com/fruitcake/laravel-cors). 

I'm using laravel passport and every passport routes works, but configuring push-js with a private channel doesn't work. Public channel work.

**Has anyone set up passport with websockets?**
