### ISSUE TITLE
issues in console using laravel docker

### ISSUE THREAD

**Issue by sarojbaskota** [beyondcode/laravel-websockets#300]
2pusher.min.js:8 WebSocket connection to 'ws://chat.local:6001/app/anyKey?protocol=7&client=js&version=4.3.1&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by csgt** [comment]
Check that chat.local is accessible from the host's browser.  Also check that the 6001 port is forwarded to the host.  I would suggest you try to set the url to "localhost" instead, since this host is relative to the client's side, not the docker's side

**Comment by rennokki** [comment]
Share your broadcasting, websockets and laravel echo configurations.
