### ISSUE TITLE
Custom WebSocket Handlers - Class 'WebSocketsRouter' not found

### ISSUE THREAD

**Issue by ahmadsyamim** [beyondcode/laravel-websockets#301]
Referring from :-
[https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html](https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html)

After adding 
`WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);`

Getting error 
**Custom WebSocket Handlers - Class 'WebSocketsRouter' not found**

Also referred to #21 

But causing all other socket somehow (like redirect to MyCustomWebSocketHandler)

**Comment by Sh3nl0ng** [comment]
Yeah I ran into this today. I scoped the class name as a quick fix. Wondering if there's a step missing from the documentation? 🤔 

```php
<?php
use BeyondCode\LaravelWebSockets\Facades\WebSocketsRouter;

WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);
```

**Comment by mujuonly** [comment]
@Sh3nl0ng  Getting error - 

>   Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [BeyondCode\LaravelWebSockets\Server\Logger\WebsocketsLogger].

**Comment by rennokki** [comment]
Any updates?

**Comment by winter-ice** [comment]
> @Sh3nl0ng Getting error -
> 
> > Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [BeyondCode\LaravelWebSockets\Server\Logger\WebsocketsLogger].

Same issue in 2.0.0-beta.26

**Comment by rennokki** [comment]
Does this seem like it's not run from the console?

**Comment by winter-ice** [comment]
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException

  Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [BeyondCode\LaravelWebSockets\Server\Loggers\WebSocketsLogger].

  at D:\code\laravel-projects\laravel-vuetify\vendor\laravel\framework\src\Illuminate\Container\Container.php:1017
    1013▕         } else {
    1014▕             $message = "Target [$concrete] is not instantiable.";
    1015▕         }
    1016▕
  ➜ 1017▕         throw new BindingResolutionException($message);
    1018▕     }
    1019▕
    1020▕     /**
    1021▕      * Throw an exception for an unresolvable primitive.

  1   D:\code\laravel-projects\laravel-vuetify\vendor\laravel\framework\src\Illuminate\Container\Container.php:818
      Illuminate\Container\Container::notInstantiable("Symfony\Component\Console\Output\OutputInterface")

  2   D:\code\laravel-projects\laravel-vuetify\vendor\laravel\framework\src\Illuminate\Container\Container.php:691
      Illuminate\Container\Container::build("Symfony\Component\Console\Output\OutputInterface")
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by winter-ice** [comment]
`composer dump-autoload` caused this error when defined custom websocket handler

**Comment by simonbuehler** [comment]
Same issue in 2.0.0-beta.32

**Comment by simonbuehler** [comment]
Actually there is no WebSocketsRouter Facade in 2.0 , only one without the 's' in `BeyondCode\LaravelWebSockets\Facades` so which is the correct one?

> ``` php
> <?php
> use BeyondCode\LaravelWebSockets\Facades\WebSocketsRouter;
> 
> WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);
> ```

**Comment by rennokki** [comment]
Here it is the docs on custom handlers: https://github.com/beyondcode/laravel-websockets/blob/2.x/docs/advanced-usage/custom-websocket-handlers.md

This is the good facade: https://github.com/beyondcode/laravel-websockets/blob/2.x/src/Facades/WebSocketRouter.php

**Comment by JL2014** [comment]
Hi,

For information, your link show a class name without a 's' between WebSocket and Router words,
I have a version with a 's'.

Greetings.

**Comment by FredZockt** [comment]
> Here it is the docs on custom handlers: https://github.com/beyondcode/laravel-websockets/blob/2.x/docs/advanced-usage/custom-websocket-handlers.md
> 
> This is the good facade: https://github.com/beyondcode/laravel-websockets/blob/2.x/src/Facades/WebSocketRouter.php

While registering the custom handler the server startup failes with: 
 Illuminate\Contracts\Container\BindingResolutionException 

  Target [Symfony\Component\Console\Output\OutputInterface] is not instantiable while building [BeyondCode\LaravelWebSockets\Server\Logger\WebsocketsLogger].
