### ISSUE TITLE
Issue in chrome

### ISSUE THREAD

**Issue by AdamKyle** [beyondcode/laravel-websockets#302]
So this isn't preventing my from using the library - Yet. and I wanted to know if you guys know of a solution.

> A cookie associated with a cross-site resource at http://support.pusher.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

So I have this configured on the laravel side as:

```js
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disabledStats: true,
    encrypted: false,
    enabledTransports: ['ws', 'wss'],
    namespace: 'App',
    auth: {
      headers: {
        'X-CSRF-TOKEN': token.content
      }
    }
});
```

Notice the `disabledStats` is set to true. Now there is an [open issue](https://github.com/pusher/pusher-js/issues/392) on the pusher js library, how ever - nothing any one has suggested is working. Every one sais set `disableStats` to true and that it fixes the issue. This is not the case.

This does still work, but soon - god knows when - it will no longer work, rendering this library unusable.

Thoughts?

Also is this project maintained any more?

**Comment by nilsringersma** [comment]
@AdamKyle the correct option name is `disableStats` not `disabledStats`. Try passing that into your Echo options and it should work!

**Comment by AdamKyle** [comment]
OMg thank you so much @nilsringersma  I have been dealing with this issue for days. Thank you :D
