### ISSUE TITLE
Laravel Websockets Connection closed before established 

### ISSUE THREAD

**Issue by ponikar** [beyondcode/laravel-websockets#303]
I have seen all previous issues still stuck in the middle of this error can't figure out what is going on?
it was working good before but now I am getting this so-called error.
can anyone please help me!!!

app.js:26702 WebSocket connection to 'ws://secretscrush.com:6001/app/myKey?protocol=7&client=js&version=4.4.0&flash=false' failed: WebSocket is closed before the connection is established.

I know I am using on HTTP configuration. i don't need HTTPS for now

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'myKey',
    wsHost: window.location.hostname,
    wsPort: 6001,
    enabledTransports: ['ws'],
    disableStats: true,
 });
broadcasting.php
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
            ],
        ],

broadcasting.php

'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => true,
            'enable_statistics' => true,
        ],
    ],
.env
PUSHER_APP_ID=52416398
PUSHER_APP_KEY=myKey
PUSHER_APP_SECRET=mySecretKey
PUSHER_APP_CLUSTER=mt1

it would be so good if anyone helps me to figure out this

**Comment by Cello93** [comment]
verify that if you have the port open or you can enable it with,
sudo iptables -A INPUT -p tcp -i eth0 --dport 6001 -j ACCEPT

**Comment by ponikar** [comment]
Thanks, pal! I am no longer using beyond code due to some reasons.  went back to the pusher.
