### ISSUE TITLE
websocket not run on wss https ssl supervisor

### ISSUE THREAD

**Issue by mgilank** [beyondcode/laravel-websockets#304]
hi all
we config our web with SSL and it works when using #php artisan websockets:serve
but dont work when using supervisord

error are : failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

![2020-01-15 14_47_57-Window](https://user-images.githubusercontent.com/4758636/72415042-31556400-37a6-11ea-92ed-34321b0e763f.png)

someone please enlight me where to make change again.

thanks!

**Comment by mgilank** [comment]
turn out i used systemd 
https://webmasters.stackexchange.com/questions/119037/how-do-i-run-websockets-as-a-service-when-the-web-server-starts-and-monitor-it-t

**Comment by yurik94** [comment]
> turn out i used systemd
> https://webmasters.stackexchange.com/questions/119037/how-do-i-run-websockets-as-a-service-when-the-web-server-starts-and-monitor-it-t

Was your `anyKey `intentional?
I use supervisord in multiple projects, you have to configure it correctly (I use also Plesk) :
```
[program:laravel-websocket]
command=/path/to/your/php /var/www/vhosts/path/to/yout/artisan websockets:serve
autostart=true
autorestart=true
user=your_user
stderr_logfile=/var/log/supervisor-laravel.websocket.err.log
stdout_logfile=/var/log/supervisor-laravel.websocket.out.log
```

- Never run as root
- Absolute paths, and of course follow supervisord config guide
- Check error logs
- Do a netcat/port scan on configured port to be sure you don't miss proxy/firewall rules

**Comment by mohamedalaa80000** [comment]
note must run command with root
[program:websockets]
command=sudo php /home/{{youusername}}/public_html/artisan websockets:serve
numprocs=1
autostart=true
autorestart=true
user=root

**Comment by rennokki** [comment]
Make sure the key and certificate files are readable through the UNIX permissions.
