### ISSUE TITLE
Is passport supported?

### ISSUE THREAD

**Issue by kostaspapad** [beyondcode/laravel-websockets#307]
If I change the routes of BroadcastServiceProvider to 

` public function boot() `
`{`
       ` Broadcast::routes(['middleware' => ['auth:api']]);`
      `  require base_path('routes/channels.php');`
`}`
can I use passport for private channels?

**Comment by ezzaze** [comment]
Yes you can use Passport, however how I did it is this : 

in my **routes/web.php**  :

`Broadcast::routes(["prefix" => "api", "middleware" => "auth:api"]);`

I hope it helps

**Comment by setkyar** [comment]
Yes, you can use Laravel WebSockets with Laravel. I just did recently and write about it. Maybe [my article](https://setkyar.com/laravel-websockets-spa-laravel-echo-passport/) might help.
