### ISSUE TITLE
PushNotifications is supported?

### ISSUE THREAD

**Issue by ezzaze** [beyondcode/laravel-websockets#310]
Hello, 
So Im working on a mobile app, which gonna have a realtime chat (something like Whatsapp...)
and I was wondering if this package supports PushNotifications ? 
cause on Pushers website, I saw that i have to install `composer require pusher/pusher-push-notifications` 

Link: https://pusher.com/docs/beams/reference/server-sdk-php

please your help is so much appreciated

**Comment by rennokki** [comment]
No, this package does not replicate a Pusher Beams behavior.

**Comment by siddharth** [comment]
Can you please recheck this? This tutorial on pusher.com appears to be using pusher channels for sending web push notifications : https://pusher.com/tutorials/desktop-notifications-laravel
