### ISSUE TITLE
Pusher library sending stats

### ISSUE THREAD

**Issue by tomvo** [beyondcode/laravel-websockets#311]
I guess this is not really an issue for this library but since it behaves as a pusher drop-in replacement it's maybe valuable to note that the pusher library by default sends usage statistics to their servers.

So if you are just using this library and have no affiliation with Pusher, it might be good to pass in `disableStats` to the Pusher lib like so:

```
import Echo from 'laravel-echo'
import Pusher from 'pusher-js'

const pusher = new Pusher(KEY, {
    disableStats: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
});

window.Echo = new Echo({
      broadcaster: 'pusher',
      encrypted: true
      client: pusher
});
```

**Comment by lorado** [comment]
Well, this is actually documented here: https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#usage-with-laravel-echo

**Comment by tomvo** [comment]
@lorado yeah I’ve seen it after I pasted. Sorry for not closing the issue. Cheers!
