### ISSUE TITLE
I am only facing this error on production host. Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by guoxiangke** [beyondcode/laravel-websockets#313]
1. local not use useTLS, works
2.when on production, the link changed to  wss://www.domain.com:6001/
instead of  ws://www.domain.com:6001/
why is ws changed wss, I config  useTLS = false,

wss://laravel_live.dev:6001/app/anyKey?protocol=7&client=js&version=5.0.3&flash=false
return: Error in connection establishment: net::ERR_CONNECTION_REFUSED
what I need is ws://laravel_live.dev:6001/app/anyKey?protocol=7&client=js&version=5.0.3&flash=false

 here are my configs:

**.env**
MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
MIX_WS_HOST=laravel_live.dev
MIX_WS_PORT=6001
MIX_WSS_PORT=6001

**bootstrap.js**
console.log(process.env.MIX_WS_HOST,process.env.MIX_WS_PORT,process.env.MIX_WSS_PORT)

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'anyKey',
    // key: process.env.MIX_PUSHER_APP_KEY,
    // cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: false,
    // wsHost: window.location.hostname,
    wsHost: process.env.MIX_WS_HOST,
    wsPort: process.env.MIX_WS_PORT,
    wssPort: process.env.MIX_WSS_PORT,
    disableStats: true,
    enabledTransports: ['ws','wss'], // <-- only use ws and wss as valid transports
});

**broadcasting.php**
 'options' => [

                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => false,
                'useTLS' => false,
                // 'host' => '127.0.0.1',
                'host' => env('APP_HOST'),
                'port' => 6001,
                'scheme' => 'http',
                'curl_options' => [
                     CURLOPT_SSL_VERIFYHOST => 0,
                     CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],

**Comment by guoxiangke** [comment]
works with no https
![image](https://user-images.githubusercontent.com/1160703/74213800-cda35580-4cd5-11ea-8fbc-f55cc45c5472.png)
when with https, the url changed to  wss://
![image](https://user-images.githubusercontent.com/1160703/74213864-12c78780-4cd6-11ea-8e4d-3ab98b6df609.png)
and callback some urls:

Request URL: https://sockjs.pusher.com/pusher/app/anyKey/586/sn21laqo/xhr_streaming?protocol=7&client=js&version=5.0.3&t=1581400399956&n=1
Request Method: OPTIONS
Status Code: 404 Not Found
Remote Address: 3.83.46.145:443
Referrer Policy: no-referrer-when-downgrade

**Comment by guoxiangke** [comment]
Same problem as described here https://www.reddit.com/r/laravel/comments/eml0sd/issue_with_laravelwebsockets_package_over_ssl/

sudo php artisan websockets:serve not work!

**Comment by guoxiangke** [comment]
same here : Laravel event is not broadcasting on production server
https://laracasts.com/discuss/channels/laravel/laravel-event-is-not-broadcasting-on-production-server?page=0

**Comment by rennokki** [comment]
To enforce `ws`, use `forceTLS: false`, not `useTLS` in your echo configuration.

The `useTLS` is only for the broadcaster configuration in `config/broadcasting.php`, but you don't need it as you want to use the HTTP-only.

I honestly don't recommend using WS over WSS in production, either way, so just get yourself some SSL from Let's Encrypt.
