### ISSUE TITLE
Only in Chrome on my PC - "ERR_CERT_AUTHORITY_INVALID" 

### ISSUE THREAD

**Issue by lao9s** [beyondcode/laravel-websockets#315]
I have an app.example.com domain and I use SSL from let's encrypt. Until today everything was working fine, but today on my computer, in the Chrome browser, it didn't work anymore. SSL is valid until May 2020. In browser i see green color.

Console log:

> wss://app.example.com:6001/app/dkfsndf443dn?protocol=7&client=js&version=5.0.3&flash=false' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

Messages log, time is wrong: 1/1/1970:
![image](https://user-images.githubusercontent.com/3392129/74611463-bf559f00-5104-11ea-83f5-6f0ade1769c8.png)

It works if:

- Opening in incognito from Chrome.
- Using other Browser on my PC.
- Using another PC with different browsers

**My settings:**

broadcasting.php
> 'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => env('APP_ENV') == 'production' ? 'https': 'http',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
]

websockets.php

> 'ssl' => [
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),
        'phrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
        'verify_peer' => false,
    ],
All variables env is completed in .env

front'end
>  echo = new Echo(this.socketSettings({
                    broadcaster: 'pusher',
                    key: process.env.MIX_PUSHER_APP_KEY,
                    auth:{
                        headers:
                            {
                                'Authorization': `Bearer ${token}`
                            }
                    },
                    wsHost: window.location.hostname,
                    wsPort: 6001,
                    wssPort: 6001,
                    enabledTransports: ['ws'],
                    forceTLS: true,
                    disableStats: true,
                    encrypted: window.App.encrypted
                }));

I restarted the computer, cleared the cache from the browser. But it didn't help.
### Has anyone else had such a problem?

**Comment by lao9s** [comment]
It seems that I solved the problem, I changed the location of the certificate from .crt to .pem. Now it works in all browsers from all pc's.
But i want to know: Is secure to use .pem file?

**Comment by yurik94** [comment]
> It seems that I solved the problem, I changed path local_cert from .crt to .pem. Now it works in all browsers from all pc's.
> But i want to know: Is secure to use .pem file?

That error occurs when you don't configure correctly SSL certs, happened to me too because of an incorrect (permissions are important!) path.
PEM format is just an encoding format, just keep secured your keys.
Watch out for key renewal especially if you use letsencrypt, better use nginx as SSL termination because you don't have to copy certs at every renewal and you just put key paths in your .conf once

**Comment by lao9s** [comment]
I use VestaCP, so i installed from vesta all cert.
Thank you for the informations.
