### ISSUE TITLE
Extending to get user

### ISSUE THREAD

**Issue by nicolasvahidzein** [beyondcode/laravel-websockets#319]
I implemented this approach:

https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html

but on close i don't know how to retrieve the user information so i can use it to process some other tasks when the users disconnects in my backend.

Could you point me to some tutorial or perhaps the right docs to do this?

Thanks.

**Comment by rennokki** [comment]
Somehow related to https://github.com/beyondcode/laravel-websockets/issues/366
