### ISSUE TITLE
Add support for Laravel 7

### ISSUE THREAD

**Issue by axit-joost** [beyondcode/laravel-websockets#327]
In addition to bumping `illuminate/*` to include the 7.x branch, care should also be taken for `symfony/http-kernel` as Laravel 7 bumps the Symfony deps to the 5.x branch, which may cause incompatibilities with the ~4.0 requirement which is in the `composer.json`.

**Comment by vitorarjol** [comment]
The current proposed pr for the upgrade (#326) also updates the http-kernel  libs 😄

**Comment by freekmurze** [comment]
We'll tag an L7 compatible version today.
