### ISSUE TITLE
[Laravel 7] Conflict with laravel/passport

### ISSUE THREAD

**Issue by pawel-marciniak** [beyondcode/laravel-websockets#331]
Hi,

I'm facing the issue while using this package with Laravel 7 and newest version of Laravel Passport. It's because this package has `symfony/psr-http-message-bridge ^1.1` dependency while newest Laravel Passport for Laravel 7 has `symfony/psr-http-message-bridge ^2.0` (Laravel documentation is also recommending installing newer version if you want to use psr7 requests).

Is there any chance to update this dependency?

**Comment by wdarins** [comment]
Remove vendor folder and use version 7.5 of laravel passport instead: "laravel/passport": "^7.5",
then do a composer install again.
