### ISSUE TITLE
ws protocol works, but wss don't: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by pablorsk** [beyondcode/laravel-websockets#336]
Hi!

I try all possible solutions presented on another issues, even when my scenario is a little different.

Case:
- I can connect to `ws://api.multinexo.com:2053` but dont to `wss://api.multinexo.com:2053`
- I'm using nanobox.io and I can connect using `ws`.
- I test with dashboard, my implemented client and also with "WebSocket Test Client", but I get a same result: only `ws` protocol.

Results on server `php artisan websockets:serve --port=2053 --debug`:
- When I use `ws`, dumps a lot of information
- When I use `wss`, any information are dumped :/  

I try...
- Disabling cloudflare, but don't work.
- Applying configurations on `broadcasting.php` like:
-- `scheme` http and https (https://alex.bouma.dev/posts/installing-laravel-websockets-on-forge/)
-- disabling/enabling `VERIFYHOST` and `VERIFYPEER`
-- setting `enabledTransports`
- Applying configurations on client like
-- `wsPort` equals to `wssPort`.

Any idea how can I test better and get where is the error?

**Comment by Yiddishe-Kop** [comment]
I have a similar issue:
Everything was working amazingly before I installed an SSL certificate.
After I installed the SSL cert. the wss:// responds with a 404.

I followed the [SSL support](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#configuration) docs, restarted the nginx server etc. but I'm still getting a 404.

My server is on Ubuntu 18.04, SSL let's encrypt.

**Comment by mchev** [comment]
I had the same issue and the problem was the read access of the local_cert and local_pk.

You can use `sudo php artisan websocket:serve` to try if this is the issue.

If it's the case, add read access to the files or use a user with the access in /etc/supervisor/conf.d/websockets.conf

**Comment by IpelaTech** [comment]
Follow the setup in this answer and the comment below. Worked for me.

[https://stackoverflow.com/a/59974713/1581495](url)

**Comment by rennokki** [comment]
This is a common issue. Make sure the key and certificates are readable, and that the configuration resembles more or less like this:

```
window.Echo = new Echo({
  broadcaster: 'pusher',
  wsHost: window.location.hostname,
  wsPort: 6001,
  wssHost: window.location.hostname,
  wssPort: 6001,
  key: 'client',
  disableStats: true,
  enabledTransports: ['ws', 'wss'],
});
```
