### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by chuksdsilent** [beyondcode/laravel-websockets#337]
I have tried tried to publish this package using
php artisan vendor:publish --provider="BeyondCode\LaravelWebSockets\WebSocketsServiceProvider" --tag="migrations"
but I am getting 
Unable to locate publishable resources
publishing complete

installation output

$ composer require beyondcode/laravel-websockets
Using version ^1.4 for beyondcode/laravel-websockets
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 63 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-mbstring (v1.14.0): Loading from cache
  - Installing symfony/polyfill-php72 (v1.14.0): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.14.0): Loading from cache
  - Installing symfony/mime (v5.0.5): Downloading (100%)
  - Installing symfony/http-foundation (v5.0.5): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing symfony/psr-http-message-bridge (v1.3.0): Downloading (100%)
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing symfony/polyfill-php73 (v1.14.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.14.0): Loading from cache
  - Installing psr/event-dispatcher (1.0.0): Downloading (100%)
  - Installing symfony/event-dispatcher-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/event-dispatcher (v5.0.5): Downloading (100%)
  - Installing symfony/var-dumper (v5.0.5): Downloading (100%)
  - Installing symfony/error-handler (v5.0.5): Downloading (100%)
  - Installing symfony/http-kernel (v5.0.5): Downloading (100%)
  - Installing psr/container (1.0.0): Loading from cache
  - Installing react/promise (v2.7.1): Downloading (100%)
  - Installing react/event-loop (v1.1.1): Downloading (100%)
  - Installing react/promise-timer (v1.5.1): Downloading (100%)
  - Installing react/cache (v1.0.0): Downloading (100%)
  - Installing react/dns (v1.2.0): Downloading (100%)
  - Installing paragonie/sodium_compat (v1.12.2): Downloading (100%)
  - Installing pusher/pusher-php-server (v4.1.1): Downloading (100%)
  - Installing voku/portable-ascii (1.4.10): Downloading (100%)
  - Installing symfony/translation-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/translation (v5.0.5): Downloading (100%)
  - Installing nesbot/carbon (2.31.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing illuminate/contracts (v7.1.3): Downloading (100%)
  - Installing doctrine/inflector (1.3.1): Loading from cache
  - Installing illuminate/support (v7.1.3): Downloading (100%)
  - Installing symfony/routing (v5.0.5): Downloading (100%)
  - Installing symfony/finder (v5.0.5): Downloading (100%)
  - Installing illuminate/filesystem (v7.1.3): Downloading (100%)
  - Installing illuminate/session (v7.1.3): Downloading (100%)
  - Installing illuminate/pipeline (v7.1.3): Downloading (100%)
  - Installing illuminate/http (v7.1.3): Downloading (100%)
  - Installing illuminate/container (v7.1.3): Downloading (100%)
  - Installing illuminate/routing (v7.1.3): Downloading (100%)
  - Installing symfony/process (v5.0.5): Downloading (100%)
  - Installing symfony/service-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/console (v5.0.5): Downloading (100%)
  - Installing illuminate/console (v7.1.3): Downloading (100%)
  - Installing opis/closure (3.5.1): Loading from cache
  - Installing illuminate/database (v7.1.3): Downloading (100%)
  - Installing illuminate/queue (v7.1.3): Downloading (100%)
  - Installing illuminate/bus (v7.1.3): Downloading (100%)
  - Installing illuminate/broadcasting (v7.1.3): Downloading (100%)
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing facade/ignition-contracts (1.0.0): Loading from cache
  - Installing ringcentral/psr7 (1.2.2): Downloading (100%)
  - Installing evenement/evenement (v3.0.1): Downloading (100%)
  - Installing react/stream (v1.1.0): Downloading (100%)
  - Installing react/socket (v1.4.0): Downloading (100%)
  - Installing react/promise-stream (v1.2.0): Downloading (100%)
  - Installing react/http-client (v0.5.10): Downloading (100%)
  - Installing clue/buzz-react (v2.7.0): Downloading (100%)
  - Installing ratchet/rfc6455 (v0.2.6): Downloading (100%)
  - Installing cboden/ratchet (v0.4.2): Downloading (100%)
  - Installing beyondcode/laravel-websockets (1.4.0): Downloading (100%)
symfony/polyfill-intl-idn suggests installing ext-intl (For best performance)
symfony/psr-http-message-bridge suggests installing nyholm/psr7 (For a super lightweight PSR-7/17 implementation)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
react/event-loop suggests installing ext-event (~1.0 for ExtEventLoop)
react/event-loop suggests installing ext-pcntl (For signal handling support when using the StreamSelectLoop)
react/event-loop suggests installing ext-uv (* for ExtUvLoop)
paragonie/sodium_compat suggests installing ext-libsodium (PHP < 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.)
paragonie/sodium_compat suggests installing ext-sodium (PHP >= 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.)
voku/portable-ascii suggests installing ext-intl (Use Intl for transliterator_transliterate() support)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
illuminate/support suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
illuminate/support suggests installing ramsey/uuid (Required to use Str::uuid() (^3.7).)
illuminate/support suggests installing vlucas/phpdotenv (Required to use the Env class and env helper (^4.0).)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (^1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
illuminate/filesystem suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
illuminate/filesystem suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
illuminate/http suggests installing guzzlehttp/guzzle (Required to use the HTTP Client (^6.3.1|^7.0).)
illuminate/routing suggests installing nyholm/psr7 (Required to use PSR-7 bridging features (^1.2).)
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/lock
illuminate/console suggests installing dragonmantank/cron-expression (Required to use scheduler (^2.0).)
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (^6.3.1|^7.0).)
illuminate/database suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (^2.6).)
illuminate/database suggests installing fzaninotto/faker (Required to use the eloquent factory builder (^1.4).)
illuminate/database suggests installing illuminate/events (Required to use the observers with Eloquent (^7.0).)
illuminate/database suggests installing illuminate/pagination (Required to paginate the result set (^7.0).)
illuminate/queue suggests installing ext-pcntl (Required to use all features of the queue worker.)
illuminate/queue suggests installing ext-posix (Required to use all features of the queue worker.)
illuminate/queue suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and DynamoDb failed job storage (^3.0).)
illuminate/queue suggests installing illuminate/redis (Required to use the Redis queue driver (^7.0).)
illuminate/queue suggests installing pda/pheanstalk (Required to use the Beanstalk queue driver (^4.0).)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
Writing lock file
Generating autoload files

**Comment by rennokki** [comment]
Does this issue still persist?

**Comment by blestab** [comment]
> 
> 
> Does this issue still persist?

I am seeing the same error, in a lumen project, though:

`        "laravel/lumen-framework": "^7.0",`

also using the below package to give me the ability to use _php artisan vendor:publish_

`        "irazasyed/larasupport": "^1.7",`

**Comment by rennokki** [comment]
Make sure you imported the `BeyondCode\LaravelWebSockets\LaravelWebSocketsServiceProvider::class` file as app provider.
