### ISSUE TITLE
Dashboard Events not showing

### ISSUE THREAD

**Issue by chuksdsilent** [beyondcode/laravel-websockets#338]
I am trying to broadcast using laravel event broadcast but it is not showing on the dashboard. it is showing on the log but not on the dashboard

my websocket.php

    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],
I am using version 6.18.8

**Comment by rennokki** [comment]
I know it's an old issue, but have you figured it out?
