### ISSUE TITLE
socket showing null

### ISSUE THREAD

**Issue by chuksdsilent** [beyondcode/laravel-websockets#340]
I created broadcast using pusher but the socket on the event is returning null. 

app.php
'connections' => [        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                // 'encrypted' => true,
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
            'curl_options' => [
                CURLOPT_SSL_VERIFYHOST => 0,
                CURLOPT_SSL_VERIFYPEER => 0,
            ],
        ],

.env file
BROADCAST_DRIVER=pusher
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

PUSHER_APP_ID=12345
PUSHER_APP_KEY=ABCDEFG
PUSHER_APP_SECRET=HKLMNOP
PUSHER_APP_CLUSTER=mt1
PUSHER_APP_HOST=127.0.0.1

output
[!] Aliasing 'NewMessage' to 'App\Events\NewMessage' for this Tinker session.
=> [
     null,
   ]

**Comment by dflm25** [comment]
I have the same issue

**Comment by rennokki** [comment]
Can you pass some reproduction steps? I can't seem to understand what the problem is.
