### ISSUE TITLE
Version package 1.4 no working in Laravel 5.7

### ISSUE THREAD

**Issue by calevano** [beyondcode/laravel-websockets#341]
I cannot install the package, because I feel like I must have a version 5.8 for version 1.4
What is the version for Laravel 5.7
Does the documentation change for versions?

![image](https://user-images.githubusercontent.com/1764561/77326787-51465e00-6ce8-11ea-87de-323e14358473.png)

**Comment by youngsdeveloper** [comment]
Same here

**Comment by stayallive** [comment]
Correct. Only Laravel 5.8 and up is supported on version 1.4.

For reference, you can always consult the `composer.json` file of a package to figure out what versions are supported: https://github.com/beyondcode/laravel-websockets/blob/d7b996381d5c3a223f13b69cf35eb43cc6633fca/composer.json#L31-L35.

**Comment by youngsdeveloper** [comment]
Okey.

Then please check this in the documentation, maybe is outdated

[Link](https://docs.beyondco.de/laravel-websockets/1.0/getting-started/introduction.html)

![image](https://user-images.githubusercontent.com/9423551/79620621-c1da7200-8110-11ea-9b1e-548e690d380a.png)

**Comment by stayallive** [comment]
Jep, looks like it, opened a PR to fix that: beyondcode/docs.beyondco.de#39

**Comment by calevano** [comment]
Excellent @stayallive
