### ISSUE TITLE
Version package 1.4 no working in Laravel 6.x

### ISSUE THREAD

**Issue by Gunnerr** [beyondcode/laravel-websockets#343]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for beyondcode/laravel-websockets ^1.4 -> satisfiable by beyondcode/laravel-websockets[1.4.0].
    - Conclusion: remove symfony/psr-http-message-bridge v2.0.0
    - Conclusion: don't install symfony/psr-http-message-bridge v2.0.0
    - beyondcode/laravel-websockets 1.4.0 requires symfony/psr-http-message-bridge ^1.1 -> satisfiable by symfony/psr-http-message-bridge[1.1.x-dev, v1.1.0, v1.1.1, v1.1.2, v1.2.0, v1.3.0].
    - Can only install one of: symfony/psr-http-message-bridge[1.1.x-dev, v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.1.0, v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.1.1, v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.1.2, v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.2.0, v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[v1.3.0, v2.0.0].
    - Installation request for symfony/psr-http-message-bridge (locked at v2.0.0) -> satisfiable by symfony/psr-http-message-bridge[v2.0.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by alexaf2000** [comment]
I'm having the same issue on Laravel 7.

**Comment by DexterPHP** [comment]
I'm having the same issue  on Laravel Framework 6.18.3

**Comment by alexaf2000** [comment]
Yes, seems to be the issue with Laravel Passport if the version is after 7.5, I've been read about it... But with some Laravels versions even changing the version is getting errors.

**Comment by DexterPHP** [comment]
> Yes, seems to be the issue with Laravel Passport if the version is after 7.5, I've been read about it... But with some Laravels versions even changing the version is getting errors.

so what are the solution what we can do ?

**Comment by DexterPHP** [comment]
i found the solution  Finally 😄  
just add [ "beyondcode/laravel-websockets":  "^1.4" ] to your composer in "require": 
and after it composer update 🆒
