### ISSUE TITLE
laravel websocket process shuts off automatically

### ISSUE THREAD

**Issue by sksingh1995** [beyondcode/laravel-websockets#344]
Hi,

I am using `laravel-websockets` in one of my project. I m using laravel forge and I have a Daemon process running to watch websocket:serve artisan command. 

Everything is working perfectly, but after a time of interval (2-3 days), The process shuts off automatically and on the client I get connection error.

This is not an issue with Daemon process as I already had a discussion with forge team and as per them the issue is with the package itself.

I am using this in a production app. A quick reply and solution would be really helpful.

Thanks in advance.

**Comment by yurik94** [comment]
Same here, randomly getting:

`Illuminate\Broadcasting\BroadcastException in /vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:117`

after some days.

**Comment by rennokki** [comment]
Share with us your broadcast, websockets and `laravel-echo` configurations.

**Comment by Tofandel** [comment]
Likely related to #325
