### ISSUE TITLE
[Question] Implement unittests in app

### ISSUE THREAD

**Issue by joveice** [beyondcode/laravel-websockets#345]
How can I implement Unittests in my app?
I tried looking thru the unittests here but it looks to be tied to the package in a way I don't understand how I could achieve the same for my app.

I could not find any documentation in regards to testing this.

**Comment by rennokki** [comment]
What you want to achieve actually is to use (I think) is the Laravel's Event fake: https://laravel.com/docs/7.x/mocking#event-fake
