### ISSUE TITLE
Can only install one of: symfony/psr-http-message-bridge

### ISSUE THREAD

**Issue by eaktadiur** [beyondcode/laravel-websockets#346]
**I am using Laravel 7**

Problem 1
    - Can only install one of: symfony/psr-http-message-bridge[v2.0.0, 1.1.x-dev].
    - Can only install one of: symfony/psr-http-message-bridge[1.1.x-dev, v2.0.0].
    - Can only install one of: symfony/psr-http-message-bridge[1.1.x-dev, v2.0.0].
    - beyondcode/laravel-websockets 1.4.0 requires symfony/psr-http-message-bridge ^1.1 -> satisfiable by symfony/psr-http-message-bridge[1.1.x-dev].
    - Installation request for beyondcode/laravel-websockets ^1.4 -> satisfiable by beyondcode/laravel-websockets[1.4.0].
    - Installation request for symfony/psr-http-message-bridge (locked at v2.0.0, required as ^2.0) -> satisfiable by symfony/psr-http-message-bridge[v2.0.0].

**Comment by hope-soft** [comment]
@eaktadiur : you have to change the version or add this on ur composer.json file "symfony/psr-http-message-bridge": "^1.0"

**Comment by hsndmr** [comment]
you can add beyondcode/laravel-websockets": "^1.4 in composer.json then you should run composer update. Probably you are using Laravel Passport. Because Laravel Passport have to require symfony/psr-http-message-bridge[v2.0.0]
