### ISSUE TITLE
Broadcasted events not sending over database queue driver

### ISSUE THREAD

**Issue by fvanhove** [beyondcode/laravel-websockets#348]
Hello,

I have configured the laravel-websockets on 3 servers (laravel forge), and 1 is not working. and I can not figure out what is wrong. It seems that even when I am setting the `BROADCAST_DRIVER` to pusher it keeps fallbacking to my log.

The set-up is a same server nginx websocket using the provided guide.
The version of laravel-websockets I am using is ` "^1.4"` and the version of laravel is `"5.8.*"`.
Hosted on digital ocean (don't think that should matter tho :-))

To start of, I have already checked with tinker on the production server config('broadcasting') if the variables are set correctly.  I also integrate cache and config clears in my build scripts. 

When I skip the env('BROADCAST_DRIVER') and manually set this to pusher I receive a `BroadcastException`
in
`Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:119)`

Currently, it seems that the broadcast can not connect to the pusher server and fall backs to log. 

The config I'm using works on the other servers:
```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
```

And `'verify_peer' => false,`  is enabled. 

I have tried using both enabling and disabling `LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT` and `LARAVEL_WEBSOCKETS_SSL_LOCAL_PK` same for `'useTLS' => true,`

Echo is connecting to the socket server, no problem, it's the events that are not broadcasting to pusher. And seeing the events end up in the log the queue is sending them correctly. 

[Update] when setting the driver to sync the events work fine

Any tips on what options I have not yet explored in order to resolve this issue?

**Comment by misanthrope1408** [comment]
I'm confirm, have same issue with 'database driver' I have spend few hours to figure out what a problem, after I came across your topic, I changed the driver QUEUE_DRIVER=sync, and it's worked
