### ISSUE TITLE
Event loop ev / event installation

### ISSUE THREAD

**Issue by tibinvpaul** [beyondcode/laravel-websockets#349]
Hello,

I am looking for some information regarding `ev/event` installation. I have posted this question in Stackoverflow but I did not get any answer so posting here.

I have `laravel-websockets` installation on `Ubuntu` OS. Inspired from the information under https://docs.beyondco.de/laravel-websockets/1.0/faq/deploying.html#changing-the-event-loop, I have installed `ev` and PHP is loading the extension successfully.

AFAIK the default event loop is `stream_select` for the package. My questions are,

1. Do I need to perform any other actions in order to get `ev` activated?
2. Is there a way to check which event loop the package uses?
3. Is there a hard limit for `ev`?

Thanks in advance!

**Comment by kinnngg** [comment]
Maybe this will help you.

Since it uses Ratchet this document explains how it works and what you need to do.

http://socketo.me/docs/deploy
