### ISSUE TITLE
POST broadcasting/auth 403 (Forbidden)

### ISSUE THREAD

**Issue by agusesetiyono** [beyondcode/laravel-websockets#357]
I use private channel, and got error like this:

`POST http://127.0.0.1:8000/broadcasting/auth 403 (Forbidden)`

`Pusher :  : ["Unable to retrieve auth string from auth endpoint - received status 403 from /broadcasting/auth. Clients must be authenticated to join private or presence channels`

please help me

**Comment by stayallive** [comment]
Without more info it just looks like the channel was not authorized correctly.

> https://laravel.com/docs/7.x/broadcasting#authorizing-channels

---

Remember that when you define an authorizer like:

```Broadcast::channel('order.{orderId}', function ($user, $orderId) {
    return $user->id === Order::findOrNew($orderId)->user_id;
});
```

You do _not_ need to prefix the `private-` part to the channel name (that might be causing confusion).

**Comment by berni23** [comment]
In my case it throws 403 forbidden altough i'm dealing with a public channel  .
