### ISSUE TITLE
run daemon on windows

### ISSUE THREAD

**Issue by peratik** [beyondcode/laravel-websockets#36]
Hello  documentation only describes run daemon on Linux, How can do it on windows? Thank you

**Comment by scheMeZa** [comment]
You can just open a new terminal, run and keep open:
`php artisan websockets:serve`

As long as the terminal is open and running this command, it will serve WebSockets.

For `supvervisord`-like functionality, a quick google search gives you some answers:
https://superuser.com/questions/331675/supervisord-like-tool-for-windows

**Comment by peratik** [comment]
I found a reliable solution:

https://hazaveh.net/2018/01/run-and-monitor-laravel-queue-using-pm2/
