### ISSUE TITLE
Do we need pusher account?

### ISSUE THREAD

**Issue by faizananwerali** [beyondcode/laravel-websockets#361]
Do we need pusher account?

    'pusher' => [
        'driver' => 'pusher',
        'key' => env('PUSHER_APP_KEY'),
        'secret' => env('PUSHER_APP_SECRET'),
        'app_id' => env('PUSHER_APP_ID'),
        'options' => [
            'cluster' => env('PUSHER_APP_CLUSTER'),
            'encrypted' => true,
            'host' => '127.0.0.1',
            'port' => 6001,
            'scheme' => 'http'
        ],
    ],

What do I assign these with? if I won't be using pusher account

**Comment by DanielFok99** [comment]
https://www.youtube.com/watch?v=pIGy7-7gGXI 
I think this video can solve your problem

**Comment by yurik94** [comment]
no as it's self hosted, you just use pusher SDK
