### ISSUE TITLE
BUG: presence channel: leaving event triggered only the first time

### ISSUE THREAD

**Issue by ivanomatteo** [beyondcode/laravel-websockets#362]
when the same user have multiple connection on a presence channel, the leaving event is triggered only the first time, and ignored for the next events.

for example:
- an user open 3 tabs 
- for each tab -> joining is triggered
- the user close tab 1 -> leaving is triggered
- the user close tab 2 -> no event triggered
- the user close tab 3 -> no event triggered

**this seems to be incompatible with pusher behavior:**

> The pusher:member_removed is triggered when a user leaves a channel. It's quite possible that a user can have multiple connections to the same channel (for example by having multiple browser tabs open) and in this case the events will only be triggered when the last one is closed.

https://pusher.com/docs/channels/using_channels/presence-channels#pusher-member-removed

**Comment by IvanGo82** [comment]
Proposed patch:
/src/WebSockets/Channels/PresenceChannel.php
` public function unsubscribe(ConnectionInterface $connection)
    {
        parent::unsubscribe($connection);

        if (!isset($this->users[$connection->socketId])) {
            return;
        }

        $last_connection = true;
        foreach ($this->users as $socketId => $channelData) {
            if ($socketId !== $connection->socketId && $channelData->user_id === $this->users[$connection->socketId]->user_id) {
                $last_connection = false;
                break;
            }
        }

        //fire the event only if is the user last connection
        if ($last_connection) {
            $this->broadcastToOthers($connection, [
                'event' => 'pusher_internal:member_removed',
                'channel' => $this->channelName,
                'data' => json_encode([
                    'user_id' => $this->users[$connection->socketId]->user_id,
                ]),
            ]);
        }

        unset($this->users[$connection->socketId]);
    }
`

**Comment by jojodadj** [comment]
Can you open a PR for this?

**Comment by ivanomatteo** [comment]
I opened a pull request.

**Comment by rennokki** [comment]
This has been fixed in 2.x, and won't accept the 1.x version since 2.x is close to being released as it shows better code quality.
