### ISSUE TITLE
Apache proxy configuration

### ISSUE THREAD

**Issue by ameerElsherif** [beyondcode/laravel-websockets#363]
Hello everyone,

I am facing serious problems trying to get this to work on production wih SSL. Eveything works great on local environment (no SSL)

I know the issue is not new but, I spent the last two days trying every method mentioned in the issues page and the documentation to get the package to work on production server with SSL and failed to get a good result.

I am now trying the second method mentioned in the documentation which is to configure a proxy. However, the documentation only explains how to do this on Nginx and my server is running Apache.

So, can anyone help with how apache should be configured to proxy requests?

Thanks...

**Comment by IpelaTech** [comment]
Check this answer [https://stackoverflow.com/a/59974713/1581495](url) and my comments below it for the setup for SSL. 

For proxying [https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-reverse-proxy-websockets-with-apache-2-4/](url)
