### ISSUE TITLE
How to use this in an api with 2 separated repositories?

### ISSUE THREAD

**Issue by mauriziocalarese** [beyondcode/laravel-websockets#37]
Hi,

What does it change if we use this package in a situation with Laravel as backend and React as frontend, in two separated repositories?

I suppose that we don't have to configure Laravel Echo in bootstrap.js, which extra steps we have to do?
Will it work anyway?

Thanks in advance!﻿

**Comment by stayallive** [comment]
Well, in theory the only thing is that you do the Laravel Echo (or Pusher JS) steps in your react project 👍 

Front-end steps in your front-end repo the rest in your back-end.

Exactly as @Namoshek mentioned, did that help or are you still running into issues?

**Comment by mauriziocalarese** [comment]
I would like to use this package in the backend and Laravel Echo for the React Frontend.

I have some problems with private channels, I'll let you know.
Thank for the answers.
