### ISSUE TITLE
Error On Websocket connection 

### ISSUE THREAD

**Issue by akmalabaa99** [beyondcode/laravel-websockets#374]
![image](https://user-images.githubusercontent.com/64131368/81916695-55af3900-95fe-11ea-932d-cd5675f94bf8.png)
i'm getting error like this.
I'm Using Laravel 7, still on localhost server using xampp with PHP 7.4

**Comment by ahmed25800** [comment]
have the same problem here

**Comment by BenMstfa** [comment]
The first thing you need to do is to disable stats in laravel echo configuration.

Regarding the issue

Are you sure that you've started the server by running php artisan websockets:serve ? and I can see you've forgotten to add the server port to your WebSockets connection URL, it should be like 
`ws://localhost:6001` or any custom port of your choice, Don't use `wss://` unless you've configured your SSL files within your server.

 Please post here if you still have any problems regarding this issue to assist further.

**Comment by henry9162** [comment]
Hello @BenMstfa the error still persist for me

**Comment by BenMstfa** [comment]
Hello @henry9162 Could you please post your JS implementation and your pusher configuration inside the broadcasting.php config file?

**Comment by henry9162** [comment]
@BenMstfa thanks for the reply, but i don't really get what you mean..
But here is my broadcasting.php config file
`'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

        'log' => [
            'driver' => 'log',
        ],

        'null' => [
            'driver' => 'null',
        ],

    ],`

Also here is my pusher and js implementation in bootstrap.js

`import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true
});

window.Echo.channel('DemoChannel').listen('DemoEvent', (e) => {
    console.log(e)
})
`

**Comment by BenMstfa** [comment]
Thanks for sharing @henry9162 ,  are your sure that you've cleared your configuration after changing pusher configuration by running `php artisan config:cache`? 

another thing your `window.location.hostname` must return `localhost or 127.0.0.1` so if you are running your app using virtual host this may be the issue reason as the socket server actually runs on `127.0.0.1`

**Comment by henry9162** [comment]
I'm using `php artisan serve` to run the app, meaning the hostname is 127.0.0.1.
Also, i just ran `php artisan config:cache` as advised, but still having the same errors popping in the console..
Been battling this for about 2days now and i'm pressured from work to get it working, could it be the version of laravel?.. i'm  currently using version 7x..
Thank you very much
![image](https://user-images.githubusercontent.com/19622135/82286704-344fa380-9996-11ea-9b3f-db77bab1c958.png)

**Comment by BenMstfa** [comment]
@henry9162  No laravel has nothing to do with this issue, its related to misconfiguration somewhere, I've struggled to make it works for the first time also. 

I'd recommend altering wsHost in Echo options with `localhost` and serving your app over a virtual host, you can make it by following these steps (I assume you are using xampp): 

- add this record `127.0.0.3 mysite-name.test` to your host file found in path `C:\Windows\System32\drivers\etc` 

- add this record to apache `httpd-vhosts.conf` found in path `I:\xampp\apache\conf\extra`
<VirtualHost 127.0.0.3:80>
    DocumentRoot I:\xampp\htdocs\project\public
    ServerName mysite-name.test
    ErrorLog "logs/project.log"
    CustomLog "logs/project.log" common
    <Directory I:\xampp\htdocs\project\public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride all
        Order Deny,Allow
        Allow from all
        Require all granted
    </Directory>
</VirtualHost>

then navigate to your website in the browser via mysite-name.test 

I can't ensure that will solve the problem but that's what I'm doing in all my projects and it just works fine.

**Comment by henry9162** [comment]
Okay.. let me try this, will revert soon..
Thank you

**Comment by henry9162** [comment]
Okay.. i use laragon to start up my server because of the ease. Not sure if the same configuration for virtual host you stated here would apply for it.
I have already located to the files to be modified as stated earlier.
This is the virtual host file below

` Virtual Hosts
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot "${SRVROOT}/docs/dummy-host.example.com"
    ServerName dummy-host.example.com
    ServerAlias www.dummy-host.example.com
    ErrorLog "logs/dummy-host.example.com-error.log"
    CustomLog "logs/dummy-host.example.com-access.log" common
</VirtualHost>

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host2.example.com
    DocumentRoot "${SRVROOT}/docs/dummy-host2.example.com"
    ServerName dummy-host2.example.com
    ErrorLog "logs/dummy-host2.example.com-error.log"
    CustomLog "logs/dummy-host2.example.com-access.log" common
</VirtualHost>



`

**Comment by BenMstfa** [comment]
@henry9162 sorry you couldn't solve your problem, are you sure that you've uncommented this line `App\Providers\BroadcastServiceProvider::class` in your app.php config file and also 
replaced broadcast routes `Broadcast::routes()`  in your web of api router files ? 

If that didn't solve your issue I hope you could some way, and please tell us what was wrong with your setup.

**Comment by mdutt247** [comment]
@akmalabaa99 I guess I also got the same error on the localhost. Try adding ` 'useTLS' => false`, `'encrypted' => false` in `config/broadcasting.php` and `forceTLS:false`,  `'encrypted':false` in `resources/js/bootstrap.js`

But I am not able to solve the same error on my shared hosting server.

**Comment by mralston** [comment]
`pusher-js` defaults to using `TLS` (`wss`) unless you explicitly tell it not to. Try this:

```js
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
    forceTLS: false // Critical if you want to use a non-secure WebSocket connection
});
```

See my explanation in this thread for more details:

https://github.com/beyondcode/laravel-websockets/issues/378

**Comment by rennokki** [comment]
Beside the `forceTLS` set to `false`, make sure you got `enabledTransporst: ['ws', 'wss']`.
