### ISSUE TITLE
laravel websocket give me this error. i try tree day to fix it, any  one in there fix like this plece help me if you can

### ISSUE THREAD

**Issue by sanjayaela** [beyondcode/laravel-websockets#381]
WebSocket connection to 'wss://127.0.0.1/app/anyKey?protocol=7&client=js&version=6.0.3&flash=false' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

Access to XMLHttpRequest at 'https://sockjs.pusher.com/pusher/app/anyKey/34/7qd33bkn/xhr_streaming?protocol=7&client=js&version=6.0.3&t=1589962704756&n=1' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

 bellow URL gives me a 404 error.

app.js:42245 POST https://sockjs.pusher.com/pusher/app/anyKey/34/7qd33bkn/xhr_streaming?protocol=7&client=js&version=6.0.3&t=1589962704756&n=1 net::ERR_FAILED

I try it my localhost.

.ENV

BROADCAST_DRIVER=pusher

PUSHER_APP_ID=anyID
PUSHER_APP_KEY=anyKey
PUSHER_APP_SECRET=anySecret

//broadcasting.php

'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],

**//bootstrap.js**

import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
});

**Comment by BenMstfa** [comment]
You are trying to connect over wss which requires SSL configuration which you clearly didn't configure.

**Comment by erlangp** [comment]
'useTLS' => false,

**Comment by shaikhfoysal** [comment]
What about it happened in web server? 
I have this problem in web?
Please help.
Thanks

**Comment by rennokki** [comment]
@shaikhfoysal Prior to Pusher v6, the `forceTLS` variable is enabled and in case you have no SSL set up, you will need to turn that into a `false`.

**Comment by Tinkal779-rathore** [comment]
@shaikhfoysal  
in your  bootstap.js( resources/js/bootstrap.js ) 
**forceTLS**  option **false** if you not have ssl set up

**Comment by rickyanwar** [comment]
same problem,
when i use it on my local it works, but when i access with another device on the same network, my WebSockets error CORS.

bootstrap.js
```
window.Echo = new Echo({
    broadcaster: "pusher",
    key: process.env.MIX_PUSHER_APP_KEY,
    encrypted: false,
    wsHost: window.location.hostname,
    wssHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    forceTLS: false,
    enabledTransports: ['ws', 'wss']
});
```
broadcasting.php
```
     'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => false,
                'useTLS' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',

            ],
        ],

```


![image](https://user-images.githubusercontent.com/36995966/127942172-052dbf8b-b8e8-436a-be1f-bedf998c1adf.png)

**Comment by Bergersun** [comment]
Ich zerficke duuuüu**😅🤣🤣🤣🤭**

**Comment by Bergersun** [comment]
Ip-geolocation nutzen..

**Comment by Balwant-Singh-Rathore** [comment]
Laravel

'useTLS' => false,

in Frontend 

disableStats: true,
forceTLS: false,

it's  working from me

**Comment by Diego-18** [comment]
I get the notification, but it still generates all these errors automatically, 
did any of them work without these errors?

![Captura de pantalla de 2022-03-21 09-48-38](https://user-images.githubusercontent.com/40433474/159287309-c80fd25d-d39d-4899-8d28-49b438923863.png)

**Comment by Diego-18** [comment]
Ready, I solved it, in my case it worked placing as value 127.0.0.1 to the wsHost in the JS.

![Captura de pantalla de 2022-03-21 10-05-42](https://user-images.githubusercontent.com/40433474/159290401-54bc1c25-a3e6-48e1-9ae7-c775004f6e7b.png)

**Comment by mahmoud-elhawy** [comment]
i have the same issue all solution are mad but still got error even if this is my config 
`bootsrab.js`
`window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: window.location.hostname,
    wsPort: 6001,
    forceTLS: false,
    disableStats: true,
	logToConsole: true

});`


`broadcasting.php`

`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'useTLS' => false,
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
                'encrypted' => false,
            ],
        ],`
        
        error 
        
![image](https://user-images.githubusercontent.com/93072752/170480883-5275ee6b-3c6b-4645-beb6-350ce6e51360.png)
