### ISSUE TITLE
PrivateChannel 403 error using Laravel Sanctum auth local setup

### ISSUE THREAD

**Issue by codertech120386** [beyondcode/laravel-websockets#386]
I am getting a 403 on broadcasting/auth route.

I have the below setup

    - Backend Laravel server ( on port 8000 )
    - Laravel Websockets Server ( laravel is running on 8001 and websocket server on 6001 )
    - Standalone Ionic React app ( on port 8100)

Now everything works when I am trying Public Channel but when I try Private Channel it fails.
I can see connection made in the dashboard with the same socketId as in the request.

I am using Laravel Sanctum for Authentication.

PFB :- my client side code

    const headers = {
        'Content-Type': 'application/json',
        Authorization: window.localStorage.getItem('token')
          ? `Bearer ${window.localStorage.getItem('token')}`
          : '',
        'Access-Control-Allow-Credentials': true,
      };
      const options = {
        broadcaster: 'pusher',
        key: 'abcsock',
        authEndpoint: 'http://localhost:8001/api/broadcasting/auth',
        authorizer: (channel, options) => {
          return {
            authorize: (socketId, callback) => {
              axios
                .post(
                  'http://localhost:8001/api/broadcasting/auth',
                  {
                    socket_id: socketId,
                    channel_name: channel.name,
                  },
                  { headers, withCredentials: true }
                )
                .then((response) => {
                  callback(false, response.data);
                })
                .catch((error) => {
                  callback(true, error);
                });
            },
          };
        },
        wsHost: '127.0.0.1',
        wsPort: 6001,
        encrypted: true,
        disableStats: true,
        enabledTransports: ['ws', 'wss'],
        forceTLS: false,
      };

Code from Laravel Websockets Server

  api.php file  

    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Route;
    use Illuminate\Support\Facades\Broadcast;
    
    Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
        return $request->user();
    });
    
    Broadcast::routes(['middleware' => ['auth:sanctum']]);
    
BroadcastServiceProvider.php
    
    namespace App\Providers;
    
    use Illuminate\Support\Facades\Broadcast;
    use Illuminate\Support\ServiceProvider;
    
    class BroadcastServiceProvider extends ServiceProvider
    {
        /**
         * Bootstrap any application services.
         *
         * @return void
         */
        public function boot()
        {
            Broadcast::routes(['middleware' => ['auth:sanctum']]);
    
            require base_path('routes/channels.php');
        }
    }

I have attached whatever I felt was sufficient to explain the issue but if you need anything more please ask.

Any help will be appreciated

**Comment by SebastianMueller87** [comment]
Hey, any updates on this? I also added the package with a sanctum middleware. I die not tested it yet from client side. 

What i am wondering about is, why do you add `Broadcast::routes(['middleware' => ['auth:sanctum']]);`  to `api.php` ? Should just called once within the BroadcastServiceProvider, should not?

**Comment by dtobi59** [comment]
You can still call this `Broadcast::routes(['middleware' => ['auth:sanctum']]);` from the BroadcastServiceProvider it will still work just that your URL will not be starting with api/...

**Comment by dtobi59** [comment]
> I am getting a 403 on broadcasting/auth route.
> 
> I have the below setup
> 
> ```
> - Backend Laravel server ( on port 8000 )
> - Laravel Websockets Server ( laravel is running on 8001 and websocket server on 6001 )
> - Standalone Ionic React app ( on port 8100)
> ```
> 
> Now everything works when I am trying Public Channel but when I try Private Channel it fails.
> I can see connection made in the dashboard with the same socketId as in the request.
> 
> I am using Laravel Sanctum for Authentication.
> 
> PFB :- my client side code
> 
> ```
> const headers = {
>     'Content-Type': 'application/json',
>     Authorization: window.localStorage.getItem('token')
>       ? `Bearer ${window.localStorage.getItem('token')}`
>       : '',
>     'Access-Control-Allow-Credentials': true,
>   };
>   const options = {
>     broadcaster: 'pusher',
>     key: 'abcsock',
>     authEndpoint: 'http://localhost:8001/api/broadcasting/auth',
>     authorizer: (channel, options) => {
>       return {
>         authorize: (socketId, callback) => {
>           axios
>             .post(
>               'http://localhost:8001/api/broadcasting/auth',
>               {
>                 socket_id: socketId,
>                 channel_name: channel.name,
>               },
>               { headers, withCredentials: true }
>             )
>             .then((response) => {
>               callback(false, response.data);
>             })
>             .catch((error) => {
>               callback(true, error);
>             });
>         },
>       };
>     },
>     wsHost: '127.0.0.1',
>     wsPort: 6001,
>     encrypted: true,
>     disableStats: true,
>     enabledTransports: ['ws', 'wss'],
>     forceTLS: false,
>   };
> ```
> 
> Code from Laravel Websockets Server
> 
> api.php file
> 
> ```
> use Illuminate\Http\Request;
> use Illuminate\Support\Facades\Route;
> use Illuminate\Support\Facades\Broadcast;
> 
> Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
>     return $request->user();
> });
> 
> Broadcast::routes(['middleware' => ['auth:sanctum']]);
> ```
> 
> BroadcastServiceProvider.php
> 
> ```
> namespace App\Providers;
> 
> use Illuminate\Support\Facades\Broadcast;
> use Illuminate\Support\ServiceProvider;
> 
> class BroadcastServiceProvider extends ServiceProvider
> {
>     /**
>      * Bootstrap any application services.
>      *
>      * @return void
>      */
>     public function boot()
>     {
>         Broadcast::routes(['middleware' => ['auth:sanctum']]);
> 
>         require base_path('routes/channels.php');
>     }
> }
> ```
> 
> I have attached whatever I felt was sufficient to explain the issue but if you need anything more please ask.
> 
> Any help will be appreciated

I'm also facing the same problem

**Comment by dtobi59** [comment]
I was able to resolve it by adding the channel on which I'm broadcasting on in the channel.php file inside the route directory.

**channel.php**

```
Broadcast::channel('request_channel.{device_id}', function ($user, $device_id) {
    return (int) $user->id === (int) \App\UserDevice::find($device_id)->user_id;
});
```
