### ISSUE TITLE
Conditionally Disable laravel-websockets on certain environments?

### ISSUE THREAD

**Issue by chuckienorton** [beyondcode/laravel-websockets#387]
Is there a way to disable this package based on an environment condition? 

I would like to use pusher.com in a heroku staging environment.

**Comment by mpociot** [comment]
Yeah you can create a custom broadcast driver in the config that uses this package and another one that uses pusher. Then just change the broadcast driver in your env 

You probably need different frontend JavaScript parts for each environment as well though
