### ISSUE TITLE
Channels current state is unavailable on my cloud server(digitalocen)

### ISSUE THREAD

**Issue by GopiPacha1996** [beyondcode/laravel-websockets#388]
I am working on Laravel-websocket package i got stucked on this error from quite long time.

i have configure basic laravel procject along with laravel websocket package on my local ubuntu as well as digitalocen ubuntu host server.I did same configuration on both places.**On my local service working like a charm but on my host server it is not at all working**.I have tried so many option but no luck i am mentioning My config file of my host server

broadcasting.php

'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host'  => '<ubuntu-server-ip>',
                'post'  => 6001,
                'scheme'    => 'http'
websockets.php:-

  'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],

 'ssl' => [
        'local_cert' => null,

        'local_pk' =>  null,

        'passphrase' =>  null,
    ],
.env

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=chat
DB_USERNAME=root
DB_PASSWORD=
BROADCAST_DRIVER=pusher
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=abcd
PUSHER_APP_KEY=abcd
PUSHER_APP_SECRET=abcd
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
/resource/js/bootstrap.js

import Echo from 'laravel-echo';

 window.Pusher = require('pusher-js');

 window.Echo = new Echo({
     broadcaster: 'pusher',
     key: '12',
     wsHost: window.location.hostname,
     wsPort: 6001,
     wssPort: 6001,
     disableStats: true,
     //enabledTransports: ['ws', 'wss']
 });
above all my configs but i don;\'t know why i am getting the above error.Can anyone help me out of this **note: i have allowed port 6001 on my server**

i would be happy if i get responce as early as possible

**Comment by GopiPacha1996** [comment]
Team  can i get any update on this ?

**Comment by GOPIPACHA** [comment]
I think i will not get any responce from here,team i got struck at this pont from lat three day can anyone respond on this?

**Comment by rennokki** [comment]
@GopiPacha1996 Any updates regarding this?
