### ISSUE TITLE
how we can use token based authentication?

### ISSUE THREAD

**Issue by NirajNik** [beyondcode/laravel-websockets#390]
I want to use laravel & laravel websocket as seperate server ,means i have abc.com which is core php project and xyz.com which is laravel & laravel websocket now i want to hit api from abc.com to xyz.com and authenticate the user to listen broadcating.Please let me know how i can achieve it.

**Comment by junaidrasheed** [comment]
I am currently working on a similar scenario and I was able to solve this using custom middlewares for token authentication

You can do something like this from abc.com using  `laravel-echo` and `pusher-js`.
```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-app-key-in-xyz.com',
    wsHost: 'xyz.com',
    wsPort: 6001,
    disableStats: false,
    forceTLS: false,
    authEndpoint: 'http:://xyz.com/broadcasting/auth'
    auth: {
        headers: {
            'Auth-Token': 'your-auth-token',
        }
    }
});
```
Now in your xyz.com application for authentication define a guard in `AuthServiceProvider.php` like this
```
 Auth::viaRequest('broadcast-auth',function ($request) {
            $client = User::where('auth_token',$request->header('auth-token'))->first();
            return $client;
        });
```

Register this new guard in `auth.php`

```
'client' => [
            'driver' => 'broadcast-auth', 
            'provider'  => 'users'
        ]
```

Now in your `BroadcastServiceProvider.php` add this in your boot method

```
Broadcast::routes(['middleware' => ['auth:client']]);
```
This will handle the token based authentication from any client for you. And finally for my private channels I have a middleware assigned which is also looking for the auth-header in the request

```
//My custom middleware
public function handle($request, Closure $next)
    {
       $token = $request->header('auth-token');
       if(empty($token)){
           return response()->json(['message'=>'Authentication header is missing.'],401);
       }
       $user = Client::where('auth_token',$token)->first();
       if(empty($user)){
            return response()->json(['message'=>'Invalid authentication token provided.'],401);
       }
       $next($request);
    }
```
My `channels.php` private channel

```
Broadcast::channel('channel-1',function($user){
    return !empty($user);
},['middleware' => 'websocket']);
```

**Comment by e-oheredia** [comment]
@rennokki I have a question, what's the difference between 
`Broadcast::routes(['middleware' => ['auth:client']]);`
and defining that custom middleware. Because, It seems like they are overriding?

**Comment by aybrl** [comment]
> I am currently working on a similar scenario and I was able to solve this using custom middlewares for token authentication
> 
> You can do something like this from abc.com using `laravel-echo` and `pusher-js`.
> 
> ```
> import Echo from 'laravel-echo';
> 
> window.Pusher = require('pusher-js');
> 
> window.Echo = new Echo({
>     broadcaster: 'pusher',
>     key: 'your-pusher-app-key-in-xyz.com',
>     wsHost: 'xyz.com',
>     wsPort: 6001,
>     disableStats: false,
>     forceTLS: false,
>     authEndpoint: 'http:://xyz.com/broadcasting/auth'
>     auth: {
>         headers: {
>             'Auth-Token': 'your-auth-token',
>         }
>     }
> });
> ```
> 
> Now in your xyz.com application for authentication define a guard in `AuthServiceProvider.php` like this
> 
> ```
>  Auth::viaRequest('broadcast-auth',function ($request) {
>             $client = User::where('auth_token',$request->header('auth-token'))->first();
>             return $client;
>         });
> ```
> 
> Register this new guard in `auth.php`
> 
> ```
> 'client' => [
>             'driver' => 'broadcast-auth', 
>             'provider'  => 'users'
>         ]
> ```
> 
> Now in your `BroadcastServiceProvider.php` add this in your boot method
> 
> ```
> Broadcast::routes(['middleware' => ['auth:client']]);
> ```
> 
> This will handle the token based authentication from any client for you. And finally for my private channels I have a middleware assigned which is also looking for the auth-header in the request
> 
> ```
> //My custom middleware
> public function handle($request, Closure $next)
>     {
>        $token = $request->header('auth-token');
>        if(empty($token)){
>            return response()->json(['message'=>'Authentication header is missing.'],401);
>        }
>        $user = Client::where('auth_token',$token)->first();
>        if(empty($user)){
>             return response()->json(['message'=>'Invalid authentication token provided.'],401);
>        }
>        $next($request);
>     }
> ```
> 
> My `channels.php` private channel
> 
> ```
> Broadcast::channel('channel-1',function($user){
>     return !empty($user);
> },['middleware' => 'websocket']);
> ```

Thank you very much. Very intuitive.
