### ISSUE TITLE
Websocket over 443 port

### ISSUE THREAD

**Issue by ricardoperovano** [beyondcode/laravel-websockets#392]
I'm using the websocket on port 6005, but some clients have this port blocked.

I was trying to set up nginx to proxy requests on port 443 to 6005, I did not manage to make it work.
I searched everywhere on google, but no solution worked for me.
Anyone managed to to that? I don't want the socket server to be exposed on port 6005, instead use https, redirecting to it.

I have this error on error.log:

`upstream prematurely closed connection while reading response header from upstream`

Here is may nginx configuration:

`server {
    root /var/www/html/websockets/public;
    index index.html index.htm index.php;
    server_name wss-dev.com;

    location /app {
     proxy_pass                          http://127.0.0.1:6005;
     proxy_http_version                  1.1;
     proxy_set_header Upgrade            $http_upgrade;
     proxy_set_header Connection         "Upgrade";
     proxy_set_header Host               $host;
     proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    }

    location /laravel-websockets {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
       include snippets/fastcgi-php.conf;
       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}`

**Comment by lovetoast** [comment]
Hi @ricardoperovano , I had the same issue and noticed you closed this, were you able to get this to work? Any help is much appreciated!

**Comment by ricardoperovano** [comment]
Hi @lovetoast i did not remember exactly what I did, if i'm not wrong this was a permission issue on certificate files.
Try to change the permissions on these files.
/etc/letsencrypt/live/wss.youdomain.com/fullchain.pem
/etc/letsencrypt/live/wss.youdomain.com/fullchain.pem

anyway, this is the nginx configuration i'm using right now and it is working:

```
server {
    root /var/www/html/wss.youdomain.com/public;
    index index.html index.htm index.php;
    server_name wss.youdomain.com;

    location /app/ {
        proxy_pass http://localhost:6002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /apps {
        proxy_pass http://localhost:6002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /laravel-websockets {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location /websocket {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
       include snippets/fastcgi-php.conf;
       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key/etc/letsencrypt/live/wss.youdomain.com/fullchain.pem # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = wss.youdomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name wss.youdomain.com;
    return 404; # managed by Certbot


}
```

**Comment by lovetoast** [comment]
> Hi @lovetoast i did not remember exactly what I did, if i'm not wrong this was a permission issue on certificate files.
> Try to change the permissions on these files.
> /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem
> /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem
> 
> anyway, this is the nginx configuration i'm using right now and it is working:
> 
> ```
> server {
>     root /var/www/html/wss.youdomain.com/public;
>     index index.html index.htm index.php;
>     server_name wss.youdomain.com;
> 
>     location /app/ {
>         proxy_pass http://localhost:6002;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> 
>     location /apps {
>         proxy_pass http://localhost:6002;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> 
>     location /laravel-websockets {
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> 
>     location /websocket {
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> 
>     location ~ \.php$ {
>        include snippets/fastcgi-php.conf;
>        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
>     }
> 
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key/etc/letsencrypt/live/wss.youdomain.com/fullchain.pem # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> }
> server {
>     if ($host = wss.youdomain.com) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
>     listen 80;
>     server_name wss.youdomain.com;
>     return 404; # managed by Certbot
> 
> 
> }
> ```

Hi thanks for your reply, I had a similar server block to you but the issue was I had stupidly set the certs and key in the websockets.php file and that was not necessary!

Do you stats work? Because in mine, the app is not calling the statistics endpoint according to the nginx logs.

**Comment by lovetoast** [comment]
Sorry, ignore me, perform dns lookup needed to be true :) thanks again

**Comment by ricardoperovano** [comment]
I'ts working like a charm :D

**Comment by Kailas10** [comment]
> Hi @lovetoast i did not remember exactly what I did, if i'm not wrong this was a permission issue on certificate files.
> Try to change the permissions on these files.
> /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem
> /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem
> 
> anyway, this is the nginx configuration i'm using right now and it is working:
> 
> ```
> server {
>     root /var/www/html/wss.youdomain.com/public;
>     index index.html index.htm index.php;
>     server_name wss.youdomain.com;
> 
>     location /app/ {
>         proxy_pass http://localhost:6002;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> 
>     location /apps {
>         proxy_pass http://localhost:6002;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>     }
> 
>     location /laravel-websockets {
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> 
>     location /websocket {
>         try_files $uri $uri/ /index.php$is_args$args;
>     }
> 
>     location ~ \.php$ {
>        include snippets/fastcgi-php.conf;
>        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
>     }
> 
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/wss.youdomain.com/fullchain.pem; # managed by Certbot
>     ssl_certificate_key/etc/letsencrypt/live/wss.youdomain.com/fullchain.pem # managed by Certbot
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> }
> server {
>     if ($host = wss.youdomain.com) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
>     listen 80;
>     server_name wss.youdomain.com;
>     return 404; # managed by Certbot
> 
> 
> }
> ```

what permission to be set to the file-> 777 OR 775?

**Comment by sopheary** [comment]
I has the same issue as the above mentioned and my configurations are the same as yours but still does not work on LEMP. Here is my current permission for cert folder: I was wondering what is a right permission for cert files?
![image](https://user-images.githubusercontent.com/4669603/133884270-723a05ac-8eb3-4331-aae8-fecdc82f2237.png)
