### ISSUE TITLE
Can this package be used without laravel-echo?

### ISSUE THREAD

**Issue by nanaaikinson** [beyondcode/laravel-websockets#393]
Hello, I wanna know if this package can be used without laravel-echo. Also can I send data to the client without broadcasting?

**Comment by depixedprojects** [comment]
Ya. I want to use direct web-socket client :)

**Comment by rennokki** [comment]
You can use it without laravel-echo and use the Pusher JS SDK instead like the dashboard uses: https://github.com/beyondcode/laravel-websockets/blob/1.4.1/resources/views/dashboard.blade.php#L115-L157

This is the Pusher JS SDK: https://github.com/pusher/pusher-js
