### ISSUE TITLE
How can i connect Laravel Websocket to Android

### ISSUE THREAD

**Issue by GOPIPACHA** [beyondcode/laravel-websockets#396]
Hi Team,
I have successfully configured laravel websocket  on my server machine.But when i try to connect to Android apllication with with my pusher credentials I am not able to connect. Below is Android code and env config
       ```
 HttpAuthorizer authorizer = new HttpAuthorizer("URL");
        PusherOptions options = new PusherOptions().setCluster("ap2");
        PusherOptions options = new PusherOptions().setAuthorizer(authorizer);
        Pusher pusher = new Pusher("a5dcde54b3f8c6c06355", options);

```
.env config;-
```

PUSHER_APP_ID=myid
PUSHER_APP_KEY=mykey
PUSHER_APP_SECRET=mysecret
PUSHER_APP_CLUSTER=mt1
```
can anyone help me out how can i connect laravel websocket to android

**Comment by sahandverbosity** [comment]
@ GOPIPACHA, did you find any solution? /Thanks!

**Comment by tomandpoolee** [comment]
@GOPIPACHA Did you found any solution?
