### ISSUE TITLE
How can I address the Websocket Routes via a subdomain?

### ISSUE THREAD

**Issue by informatJonas** [beyondcode/laravel-websockets#402]
Hello from Germany, I have installed the laravel web sockets but would now like to call them up via "websockets.example.com".  How do i do this?  I have already tried to set the host in the config to the subdomain including the root domain, but without success.  Which web is the right one?  I use Windows 10 locally with XAMPP and my server is running Ubuntu in conjunction with Plesk.

**Comment by KevinHN** [comment]
I think this may help you:
https://ghostscypher.medium.com/running-laravel-websockets-in-production-def368a84d56
