### ISSUE TITLE
Free And Connection Limit Solved?

### ISSUE THREAD

**Issue by Mrbeyond** [beyondcode/laravel-websockets#406]
When I saw pusher integration, I was skeptical if this is free with no limited connection count like pusher itself. Does its integration implement endless connection and no message count unlike pusher and how can it be served on shared hosting?

**Comment by gbelot2003** [comment]
My friend, there is a tons of videos on youtube that explain in detail this question!!

**Comment by adrianschubek** [comment]
Take a look at https://beyondco.de/docs/laravel-websockets/faq/scaling
