### ISSUE TITLE
Multiple Websockets routes

### ISSUE THREAD

**Issue by Tofandel** [beyondcode/laravel-websockets#412]
I have multiple websockets handlers and when defining the routes, I can indeed only access the defined routes the rest will return 404 but for some reason only the last defined controller is called.. (Can check by dumping on the onOpen handler)

```php
WebSocketsRouter::webSocket('ws/site', \App\Http\WebSocket\Site::class); //The admin controller is used when accessing /ws/site
WebSocketsRouter::webSocket('ws/admin', \App\Http\WebSocket\Admin::class);
```

Am I missing something or is there a huge bug there?

**Comment by Tofandel** [comment]
I have debugged this and there is indeed a huge bug due to the logger being a singleton and the decoration overriding the previous one

**Comment by Tofandel** [comment]
I have found a way to fix the bug without refactor, will make a PR

**Comment by Tofandel** [comment]
#413

**Comment by Tofandel** [comment]
#414 Correctly fixes the issue by cloning the singleton on decoration

**Comment by rennokki** [comment]
@Tofandel Indeed this was an actual problem. I have tagged 1.6.1 with this fix.
