### ISSUE TITLE
Is there no limitation like pusher?

### ISSUE THREAD

**Issue by Mrbeyond** [beyondcode/laravel-websockets#419]
I want to know if it is absolutely free unlike pusher which counts concurrent connection and number of messages.

**Comment by adrianschubek** [comment]
Take a look at https://beyondco.de/docs/laravel-websockets/faq/scaling

**Comment by rennokki** [comment]
@Mrbeyond This package is a drop-in pusher replacement, meaning that you can run it and still be compatible with the Pusher libraries (for PHP, JS, etc.)
