### ISSUE TITLE
Is it possible to stream video to subscribers from Laravel

### ISSUE THREAD

**Issue by azeemhassni** [beyondcode/laravel-websockets#42]
Greetings,

I'm working on a mobile app, I'm thinking to use this package for realtime communication.

I'm wondering if it's possible to stream a video file from laravel to all the connected clients using this package?

Thanks for any help. 🥂

**Comment by mpociot** [comment]
Hi,

I don't think websockets are made for streaming chunks of video to be honest. You could probably use websockets to trigger the simultaneous playback on all connected clients - but streaming itself is probably better done via HTTP.
