### ISSUE TITLE
Echo isn't working issue

### ISSUE THREAD

**Issue by sam-src** [beyondcode/laravel-websockets#420]
I followed the documentation and it's finally working!
But I'm facing an issue while listening to an event at the client.
At the Websockets Dashboard I can see when a client connects to the server, and when the event is created, but I can't see the message at the client's console.
I also can't see (subscribed) in the Websockets Dashboard.

**The script part at the client:**
`<script src="{{asset('js/app.js')}}"/>
    <script>
        Echo.channel('home')
        .listen('NewMessage', (e)=> {
            console.log(e.message)
                });
        </script>`

**The Event:**
` class NewMessage implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;
    public $message;
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('home');
    }
} `

**I tried even to use alert but nothing is showing on the client-side**
![Screenshot_2020-07-13 WebSockets Dashboard](https://user-images.githubusercontent.com/60327375/87324999-91e91200-c539-11ea-884e-edcdeaf52544.png)

**Comment by rennokki** [comment]
Is this still bothering you? Can you share the `laravel-echo` configuration (the `new Echo(...)` part)?

**Comment by lucasctd** [comment]
@sam-src I had the same issue, so I used pusher-js instead and it worked =D.
Btw, I am using` pusher/pusher-php-server: "~4.0"` and it is also working as expected.
Idk whether the guys who works on this project have forgotten to update the docs or they really use v3, so in case somebody is wondering if it works with pusher sdk v4, yes, it does work. :)

**Comment by xlcrr** [comment]
I have the same problem. laravel-websockets connects, but `api-message.socket` is empty, and not showing up on the client. Same config works for me with laravel 5.8 and laravel-websockets 1.1

Currently upgrading to laravel 7 with laravel-websockets v1.8.1 and unable to make it work

**Comment by xlcrr** [comment]
I was able to get this working by downgrading pusher-js to 4.4.0
