### ISSUE TITLE
Custom WebSocket Handler - onMessage not receiving anything, while connection works

### ISSUE THREAD

**Issue by TribalKing** [beyondcode/laravel-websockets#421]
Hello,

Method onOpen is working perfectly on my custom websocket handler:

```
public function onOpen(ConnectionInterface $connection)
{
      \Log::info('connected!');
       $connection->send(json_encode([ 'connected' => true ]));
}

```
So here I'm getting connected in my log file, and receiving message back from the websocket.

But onMessage method is not working from some reason:

```
public function onMessage(ConnectionInterface $connection, MessageInterface $message)
{
        \Log::info('WORK!');
        $connection->send(json_encode([ 'message' => $message ]));
}
```

So issue is that nothing is happening. On sending a message it's dead.

I tried connecting with multiple testing tools (WebSocket Test Client in chrome, websocket.org), and I created a Node.js app just in case sending messages is not working properly, and still not receiving anything on the server, while I can connect without a problem.

Please help! This is my first ever git comment in years :D

Kind Regards

**Comment by TribalKing** [comment]
Solved the problem by adding this to the onConnect method:

```
$socketId = sprintf('%d.%d', random_int(1, 1000000000), random_int(1, 1000000000));
$connection->socketId = $socketId;
$connection->app = App::findById(env('PUSHER_APP_ID'));
```

This one should be added to the documentation. I managed to dig it somehow on some old closed threads on sixth page of Google hell.

**Comment by ismaail** [comment]
@TribalKing in What file did you changed the `onConnect` method ?

**Comment by rennokki** [comment]
@TribalKing There's something wrong with what you did there.

To me, it seems like the `onOpen()` generates the Socket ID properly: https://github.com/beyondcode/laravel-websockets/blob/master/src/WebSockets/WebSocketHandler.php#L34

What you did was:

```php
public function onOpen(ConnectionInterface $connection)
{
      \Log::info('connected!');
       $connection->send(json_encode([ 'connected' => true ]));
}
```

To make sure everything works well too, make sure to add the `parent::onOpen(ConnectionInterface $connection)` after you extended the original class:

```php
public function onOpen(ConnectionInterface $connection)
{
      parent::onOpen(ConnectionInterface $connection);

      \Log::info('connected!');
       $connection->send(json_encode([ 'connected' => true ]));
}
```

If you are missing the `parent::onOpen()`, you might as well miss all the security checks, putting your app at risk: https://github.com/beyondcode/laravel-websockets/blob/master/src/WebSockets/WebSocketHandler.php#L31-L35

As a side note, 2.x makes the WebSocketHandler file extendable via the config file.
