### ISSUE TITLE
How can i increase Open Connection Limit in my websocket application?

### ISSUE THREAD

**Issue by GOPIPACHA** [beyondcode/laravel-websockets#424]
Hi everyone,

I am using laravel websocket in my production environment and it is working fine,but the problem that i am facing is Opne connection are getting drained up after some period of time when application Is running.I am using 2 vCpu adn 2GB machine and as per documents machine can handle 6ok connections.When connection crosses 1024 my application is not working at all i  i had tried with  "uLimit"  option but no luck with this.Can anyone please help me out how can increase open limit connections in application.

issue on production server if i get solution ASAP it will be more useful for me thanks in advance

**Comment by adeiming** [comment]
same problem

**Comment by RahulDey12** [comment]
https://beyondco.de/docs/laravel-websockets/faq/deploying#increasing-the-maximum-number-of-file-descriptors
