### ISSUE TITLE
Is there any way to ping all connections on $x time?

### ISSUE THREAD

**Issue by TribalKing** [beyondcode/laravel-websockets#425]
Hello,

Trying to ping all connections, because connections are closing after two minutes without any messages between connections.

Is there any way to do this?

Kind Regards

**Comment by redalpha01** [comment]
Create a daemon on your server that calls an artisan command that broadcasts a ping message which calls js for a response every x minutes ? Like a CRON

**Comment by TribalKing** [comment]
Thing is it's an API working through wss, so there is no js side for this.

Connections are coming from remote servers directly on the url, and everything is working through the custom websocket handler. I thought maybe there is a way to ping each connection, so they can stay alive.

**Comment by rennokki** [comment]
@TribalKing This is what the Pusher protocol already does, by pinging users to make sure they are kept alive.

Are you (somehow) using multiple (load balanced) servers to host the WebSockets server?
