### ISSUE TITLE
Connection reset after users reach 800 online

### ISSUE THREAD

**Issue by adeiming** [beyondcode/laravel-websockets#426]
I use Nginx server with SSL connection, when users enter under 800, everything runs normally, but when the user rises above 800, sometimes a connection reset class occurs, even though it has raised the ulimit to 40000, please help

**Comment by rennokki** [comment]
Do you run it using Supervisor?

**Comment by adeiming** [comment]
Exactly

**Comment by rennokki** [comment]
Check this documentation: http://socketo.me/docs/deploy#supervisor

You might need to also set `minfds` a higher number.

**Comment by adeiming** [comment]
I have set it to 40000, but nothing changes.

in the end I changed the queue driver from sync to redis,

**Comment by rennokki** [comment]
A bit of googling got me here: https://github.com/Oefenweb/ansible-supervisor/issues/49

**Comment by adeiming** [comment]
okay, thanks for the response. I think I have applied it in [Oefenweb/ansible-supervisor#49](https://github.com/Oefenweb/ansible-supervisor/issues/49), and I skipped the configuration from [http://socketo.me/docs/deploy](http://socketo.me/docs/deploy). I have applied it, I will wait for it tomorrow morning, because the user will peak at 7 to 9 am. I'll update you later, thanks again

**Comment by rennokki** [comment]
Come back on this issue if it didn't work out.
