### ISSUE TITLE
Peak connection in mysql logs incorrect

### ISSUE THREAD

**Issue by lovetoast** [beyondcode/laravel-websockets#428]
Rather strange issue!

I have about 20 connections online according to the API, but according to the mysql logs I have 180 peak connections!

Any ideas?

Thanks in advance and for the great package.

**Comment by rennokki** [comment]
The MySQL peak connections have nothing to do with the peak connections that this package store.

**Comment by rennokki** [comment]
@lovetoast The package version you're using? We have fixed some memory leaks in 2.x (beta for now): https://github.com/beyondcode/laravel-websockets/pull/475

**Comment by lovetoast** [comment]
Ah right, I'll check this and revert back, it could also be a quick in how window.load works but I'll let you know as it may help others :)

**Comment by lovetoast** [comment]
@rennokki 
Hi, as promised, I've been monitoring, using version 1.4.1. We use laravel websockets in document.ready, and there does seem to be an issue with multiple connections made from the same client. I don't think this is a memory leak, but I can see one person, with just 1 browser and 1 tab open and they have 54 connections, as mentioned, using pusher.js.

I'm not sure if an upgrade would fix this?
