### ISSUE TITLE
Laravel-echo not receiving event from Laravel web-socket but receives from pusher

### ISSUE THREAD

**Issue by Mrbeyond** [beyondcode/laravel-websockets#429]
I can't receive any event from the the laravel web-socket in my laravel-echo in react js App and I can confirm the event being fired on "27.0.0.1:8000/laravel-websockets" whenever the event is triggered along with its payload. When I use the pusher page event console as well, I can receive the event on the laravel-echo client side when I send the event from the pusher page. Below is the configuration of my laravel-echo:

import Echo from 'laravel-echo';
window.pusher = require('pusher-js');

  React.useEffect(()=>{
    // alert( window.location.hostname,)
    window.Echo = new Echo({
      broadcaster: 'pusher',
      key: 'f15c2778e5cfa0565027',
      wsHost: window.location.hostname,
      wsPort: 6001,
      disableStats: true,
      cluster: 'eu'
  });
 

  window.Echo.channel('chat')
  .listen('.chats', (data)=>{
    console.log(data);
  })

  },[])

The event class below is used, I implement the logs to confirm if the event is being fired successfully and it works well as I can also receive the event and the payload on the "127.0.0.1/laravel-websockets" page:

class TestEvent implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;
    public $data;
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($data)
    {
        //
        Log::info('This is some useful information.');
        error_log('triggering');
        $this->data = $data;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('chat');
    }
    public function broadcastAs(){
        return 'chats';
    }

    public function broadcastwith(){
        return [
            'statusId'=> $this->data
        ];

    }
}

The method below calls the event from the controller and it works asbolutely well also:

public function socket(Request $request){
        // return $request->header();
        try {
            broadcast( new TestEvent(250));
            return 5;
        } catch (\Throwable $th) {
            return $th;
        }
    }

The event creator from the laravel-websockets page is used but the event is not received by the laravel-echo too.

I suspect the issue to be from the laravel-echo side.

please I need help with this.

**Comment by Mrbeyond** [comment]
When I used the forceTLS:false option in the new Echo object, it is now working fine but is there an implication for that?

**Comment by saeedmashmoli** [comment]
thanks

**Comment by rennokki** [comment]
@Mrbeyond If you are using Google Chrome's inspector tool, you might hover over the WS request.

If you haven't set up SSL and see `wss://...` instead of `ws://`, it's because of the `forceTLS` options.
