### ISSUE TITLE
Questions - 100% Pusher replacement , channels and SPA client 

### ISSUE THREAD

**Issue by kadinho** [beyondcode/laravel-websockets#43]
Hi,

First of all thanks for another great package and another great contribution for the community !!

Im thinking about replacing our existing pusher implemention by this package, my idea is a standalone project just for this , and i mean just to serve websockets. 

I had a quick look on the documentation, i think i didn't miss anything, so and i have some questions:

Sorry if the answers are in the docs, i think not.

- can i completly replace pusher ? 
- its possible to have private and public channels ?
- How can we integrate laravel-websockets in a SPA (vuejs) app ? Laravel echo ? I just need the technical info, bc if possible and no right package we can build a js package.

Thanks
CV

**Comment by snellingio** [comment]
1. You can completely replace pusher from the standpoint of laravel's Broadcasting (https://laravel.com/docs/5.7/broadcasting). Pusher has other products available.

2. Yes it's possible to have public, private, and presence channels.

3. It works out of the box with laravel echo.
