### ISSUE TITLE
How to deploy in Google Flex Engine?

### ISSUE THREAD

**Issue by wmfairuz** [beyondcode/laravel-websockets#436]
Hi,

I wonder what is the best way to deploy a Laravel application alongside beyongcode websocket server in Google Flex Engine?

I've tried below configuration in app.yaml;

network:
    session_affinity: true
    forwarded_ports:
    - 6001/tcp
    instance_tag: websocket

This results in port 6001 is being forwarded to the instance (from the gaeapp container).

`netstat -tuplen` 

...
tcp6       0      0 :::6001                 :::*                    LISTEN      0          99751      -
...

`docker ps`

...
.. 0.0.0.0:6001->6001/tcp, 172.17.0.1:8080->8080/tcp
...

While this look promising, doing a telnet from my local machine to port 6001 using xxx.an.r.appspot.com hostname gives nothing. However, when using IP, port 6001 is accessible (but I want to avoid using IP since the IP is not fixed).

I wonder if I'm missing some more configuration? Or this approach is simply not doable. Thanks

P/S: Just to clarify, I'm aware that laravel websocket is not ready for auto scaling yet, currently I'm in manual scaling mode and the number of instance is limited to 1

**Comment by the-provost** [comment]
Same issue here. I was thinking of deploying to Google Cloud Run but can't figure out how to set it up

**Comment by wmfairuz** [comment]
@the-provost What I end up doing is to have a specific service just for the websocket server (even though they are in the same code base).

You can use port 80 for this websocket service (we are required to use this port anyways) and reroute them to your websocket server port (eg 6001).

To do this create nginx-app.conf with this content:

```
location / {
    proxy_pass         "http://localhost:6001";
    proxy_http_version  1.1;
    proxy_set_header    Upgrade $http_upgrade;
    proxy_set_header    Connection "upgrade";
    proxy_set_header    Host $http_host;
    proxy_set_header    X-Real-IP $remote_addr;
}
```

**Comment by the-provost** [comment]
Thank you so much. I was thinking that too! 

Did you have an issue of pusher not broadcasting events when the number of users went up? How are you handling scaling?

I've increased ulimit and even played with MaxRequestWorkers. Is there anything else I need to do? Any changes in php.ini?

**Comment by wmfairuz** [comment]
In my usage the connection is not that high, so we end up don't use any scaling. And IIRC, this package does not support scaling yet.

Did you take a look at nginx configs as well? like max_connections

**Comment by the-provost** [comment]
I'm using apache2. Any suggestion there on max connections?
