### ISSUE TITLE
Would it make sense to include this in Laravel Homestead?

### ISSUE THREAD

**Issue by svpernova09** [beyondcode/laravel-websockets#45]
Would it make sense for Homestead to come prepackaged with this installed and configured and ready to use? 

My thought would be to have it as a site configured for multiple project usage as needed.

**Comment by svpernova09** [comment]
This will be in the next base box update of Homestead! Thanks for the feedback :D

**Comment by 33sKamal** [comment]
i tired and locked for all tutotials but still not working 
please did find out how to do it
