### ISSUE TITLE
Statistic not show in https nginx

### ISSUE THREAD

**Issue by adeiming** [beyondcode/laravel-websockets#455]
when I use port 80 on nginx, the statistics on the dashboard run smoothly, but when I point to port 443 using `redirect 301 https://xxx` it doesn't work. But strangely, when I use apache it doesn't matter if the redirect is from 80 to 443.

**Comment by adeiming** [comment]
for the time being I keep port 80 and 443 open because I need statistics for analysis, I only rely on the laravel middleware to redirect from port 80 to 443

**Comment by adeiming** [comment]
one more, in apache `app_url=http / https` it doesn't matter. But in nginx, I have to use `app_url=http://..` to still see statistics even though it is running on port 443

**Comment by adeiming** [comment]
and it turns out, if app_env = local, it doesn't have a problem in nginx, but app_env = production doesn't work (only 443)

**Comment by rennokki** [comment]
Try to enable the perform_dns_lookup setting from the configuration file.

**Comment by adeiming** [comment]
I have done all the config, because in Apache there are no problems, only in SSL Nginx the problem is

**Comment by rennokki** [comment]
The 2.x version would fix these issues related to the logging storage. It can take a while until the stable 2.0.0 is released, but you can try to read the changelog and upgrade to `2.x-dev` version of the package: https://github.com/beyondcode/laravel-websockets/pull/447

**Comment by lionslair** [comment]
We got it working

in caddy we have
`

project.test:443 {
    root /var/www/project/public
    tls self_signed
    proxy /socket php-worker:6001 {
        without /socket
        transparent
        websocket
    }
    fastcgi / php-fpm:9000 php {
        index index.php
    }
    rewrite {
        if {path} not_starts_with /socket
        to {path} {path}/ /index.php?{query}
    }
}

`

bootstrap.js
`

import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    encrypted: true,
    wsHost: process.env.MIX_WS_HOST,
    wsPath: process.env.MIX_WS_PATH, <== is the important one
    wsPort: process.env.MIX_PUSHER_PORT,
    wssPort: process.env.MIX_PUSHER_PORT,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});

`

then env
`

BROADCAST_DRIVER=websockets

PUSHER_APP_ID="project-websockets-local"
PUSHER_APP_KEY="12345678"
PUSHER_APP_SECRET="87654321"
PUSHER_APP_CLUSTER=mt1
PUSHER_PORT=443
PUSHER_HOST=project.test

MIX_PUSHER_APP_KEY="12345678"
MIX_PUSHER_APP_CLUSTER="mt1"
MIX_PUSHER_PORT=443
MIX_WS_HOST=project.test

# For Local ENV only
PUSHER_APP_PATH="/socket" # for the dashboard
PUSHER_PATH="/socket" # for sending broadcasts from php
MIX_WS_PATH="/socket"

`

**Comment by adeiming** [comment]
hi @lionslair  now I am changing the start Websocket Server.php file like this:
```
protected function configureStatisticsLogger()
    {
        $connector = new Connector($this->loop, [
            'dns' => $this->getDnsResolver(),
            'tls' => [
                'verify_peer' => false,//config('app.env') === 'production',
                'verify_peer_name' => false,//config('app.env') === 'production',
            ],
        ]);
       
       ...

}

```
and its work, and I don't know whether to open a security hole or not.

which makes me curious, why in apache everything works well (local and production), but in nginx only production is the one that is at fault for special statistics on port 443

**Comment by lionslair** [comment]
We have not needed to modify that. My guess is the ssl you are using is not valid. @rennokki  might know

**Comment by adeiming** [comment]
I think the config in bootstrap.js has nothing to do with it, because without even opening the web the statistics are still running, I use redis for the queue driver, and there you can see that there is a statistical update queue in redis.

![1](https://user-images.githubusercontent.com/13284072/91278666-b7ab3d00-e7ae-11ea-965b-10d17bb6d0ac.PNG)

I already guessed it (`ssl you are using is not valid`). There are some users who have complained that ssl is not valid in the old chrome browser (as I recall after migrating from apache to nginx and re-generating the certificate), but I told him to use the new chrome and it worked. i use lets encrypt for ssl, maybe i should buy a premium certificate?

**Comment by lionslair** [comment]
No we are using letsencrypt. your setup could differ to ours. we are using a subdomain then filtering the traffic based on its type

**Comment by rennokki** [comment]
The certificate might not be valid. Take it locally on your PC and send us some details about the certificate.

**Comment by adeiming** [comment]
hai @rennokki, hi, please see the report at [#this](https://www.ssllabs.com/ssltest/analyze.html?d=sis.smk%2dalmufti.sch.id&latest)

**Comment by lionslair** [comment]
Locally using Caddy and so its using a self signed ssl cert. still works fine

**Comment by adeiming** [comment]
thanks for the advice @lionslair

**Comment by adeiming** [comment]
hi all, I've used ver 2 with ssl, but this time the statistics don't work at all, what I missed?

php 8
laravel 8
apache2
