### ISSUE TITLE
How to use it over reverse proxy?

### ISSUE THREAD

**Issue by leemmoox** [beyondcode/laravel-websockets#46]
Hello,

I would like to use your package(and replace old laravel-echo-server), but it doesn't work if you need to connect to websocker service  running in subdirectory....

for example something like this:
http://yourdomain.com/application_name/ws

I have configured nginx as reverse proxy to redirect any connection from http://yourdomain.com/application_name/ws to websocket running on 6001 . how to configure this URL in laravel-echo?

There is only  wsHost and wsPort and I need something like this:

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'your-pusher-key',
    **wsUrl**: 'http://yourdomain.com/application_name/ws',
    disableStats: true,
});

Thx

**Comment by irazasyed** [comment]
Try with `wsPath` option and pass your endpoint to it. You can find more about other supported config options [here](https://github.com/pusher/pusher-js#configuration).

**Comment by acacha** [comment]
Could somebody share a working configuration with Laravel Forge. I'm not sure how to config, my doubts:

- Use port 6001: we need to open firewall but what more? How to config encryption an what config use in Laravel Echo (Javascript) and what config in PHP Laravel
- Use Nginx proxy: what config use in Laravel Echo (Javascript) and what config in PHP Laravel? WE need to set SSL config in websockets.php config file ot only in Nginx proxy config?

**Comment by stayallive** [comment]
There is a forge specific thread that might be useful: #51

**Comment by stefandanaita** [comment]
Here's a very good tutorial of how to get it working: https://alex.bouma.me/installing-laravel-websockets-on-forge/#what-about-cloudflare

**Comment by Erutan409** [comment]
Anyone coming here from a google search, [take a look at this](https://beyondco.de/docs/laravel-websockets/basic-usage/ssl#usage-with-a-reverse-proxy-like-nginx). Seems pretty straight-forward to shim in with any other previous configurations you may have for this need.
