### ISSUE TITLE
The socket server running with supervisord not working

### ISSUE THREAD

**Issue by namsudtho** [beyondcode/laravel-websockets#48]
I follow the official documentation. As detailed below But it does not working.
![image](https://user-images.githubusercontent.com/15089720/49847216-913e4600-fe01-11e8-99f5-2bf3c070e5db.png)
![image](https://user-images.githubusercontent.com/15089720/49847263-c9de1f80-fe01-11e8-87ce-597181c985f2.png)

Please help me please.

**Comment by maartenvw** [comment]
@namsudtho
I think you have to change
`user=laravel-echo`
to
`user=YOUR_SERVER_USER`

**Comment by namsudtho** [comment]
@maartenvw 
I change `user=laravel-echo` to `user=root`
But it still show error. Do you have another way?

**Comment by stayallive** [comment]
@namsudtho did you try to run the command after `command=` yourself to see if that is working correctly?

Also `supervisorctl update` should have mentioned it detected the new process. So I think your configuration is not picked up.

Run `supervisorctl status` to see all processes it knows and their status, if `websockets` is not listed there check if you config is in the correct place. It might need to have a .ini/.conf extension on some distro's or it's just in the wrong folder.
