### ISSUE TITLE
Deployment - open files limit - event loop with supervisor

### ISSUE THREAD

**Issue by lovetoast** [beyondcode/laravel-websockets#485]
Hi All,

If I'm using supervisor and have set the open file limit, and I have also set the open file limit for that user, do I also need to use a different even loop for the process to have more than 1024 connections, or because I'm using supervisor, does that override this anyway?

**Comment by rennokki** [comment]
Please check https://github.com/beyondcode/laravel-websockets/issues/426

**Comment by lovetoast** [comment]
Thanks, though, that thread isn't quite clear, I'm not sure whether he did not or did not install ev/event as he said he skipped it?
