### ISSUE TITLE
Syntax Error on Admin Panel - Vue

### ISSUE THREAD

**Issue by maxhacker11** [beyondcode/laravel-websockets#487]
Hello!
First of all I can't express how awesome this package is:) Thanks for making such an amazing package! I love it:D
I have been using it for a while without problems, however recently a really silly bug keeps occurring..

When I visit the websocket panel I see this:
![image](https://user-images.githubusercontent.com/9881034/91118591-94d73680-e691-11ea-8ea4-0012236c47d0.png)

In the App input section it says {{ App.name }}
And the port section is empty.
It doesn't work literally everywhere where there is a Vue expression like
`@{{ }}
`

I also get a JS syntax error which happens because of Vue either not being recognized or not working, not sure.

The thing that baffles me is that it all works great on the server, but it doesn't work on my local machine where I do testing.
I am not getting any errors in the logs.

I tried reverting to older revisions, I tried changing the config files, tried removing the vendor/beyondcode and then using composer install again, tried a few more things that I can't remember now..

Any sort of help would be appreciated!
Regards,
Max

**Comment by rennokki** [comment]
@maxhacker11 As far as I experience on my own, the fact that no components are rendered (like showing the raw {{ }} blocks) shows me that the js files are not being loaded. Can you take a screenshot with all the `JS` connections from the network tab?

**Comment by maxhacker11** [comment]
@rennokki thanks for taking the time to try and help out:) Is this what you wanted to see?
![image](https://user-images.githubusercontent.com/9881034/91173869-c88c7d80-e6de-11ea-8bcf-55379469fc8f.png)
This is where the syntax error occurs. Here it is using {{ }} expressions and not Vue @{{ }} expressions, so it is working but it seems like none of the variables are defined and all default to null so that's why the error occurs..
![image](https://user-images.githubusercontent.com/9881034/91174201-3c2e8a80-e6df-11ea-93e1-3028f53e329e.png)

**Comment by rennokki** [comment]
Oh yea, upgraded recently to 2.x?

**Comment by maxhacker11** [comment]
I don't think I have upgraded Vue manually, buy If `composer update` does that automatically then, yes, I probably upgraded recently.
In package.json under devDependencies it says that I am using:
```
"vue": "^2.6.10",
"vue-headful": "^2.1.0",
"vue-router": "^3.1.5",
"vue-template-compiler": "^2.6.10"
```

**Comment by rennokki** [comment]
It doesn't pretty much help me. It's because of this bit in the config:

```php
/*
 * Set a custom dashboard configuration
 */
'dashboard' => [
    'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
],
```

is making the `port` value `null`. Make sure you got no `LARAVEL_WEBSOCKETS_PORT` in your env.

**Comment by maxhacker11** [comment]
It seems that i accidentally deleted my environmental variables on my local machine, it's working on the server because the .env is different, I copied the servers .env to my local machine and now it works *massive facepalm* :P
Thanks for the help, sorry for the lame issue!
