### ISSUE TITLE
Laravel Websockets not working suddenly.

### ISSUE THREAD

**Issue by faizan-glowlogix** [beyondcode/laravel-websockets#488]
I have implemented laravel websockets in my laravel application. about a month ago. it was working fine now when i check functionality yesterday they are not working the message is not broadcasting. it show no error in laravel log or in console or anywhere.. what should i do any have a similar problem?

**Comment by rennokki** [comment]
Package version?

**Comment by faizan-glowlogix** [comment]
"beyondcode/laravel-websockets": "^1.4", @rennokki

**Comment by faizan-glowlogix** [comment]
I have laravel 7 with vue 2.5

**Comment by rennokki** [comment]
I need some more details from your side, like what's the reason why they don't get triggered. Make sure you configured the right broadcaster driver (pusher) and the events get broadcasted properly, the channels are implemented properly.

See https://laravel.com/docs/7.x/broadcasting for broadcasting docs.

**Comment by faizan-glowlogix** [comment]
they are implemented properly as it was running three weeks ago. i have presented this chat module to my client he liked it very much. but now suddenly it stopped. i dont know why. nor i know how to diagnose this error.. as because there is no error anywhere. not in log file or console or any where else.

**Comment by rennokki** [comment]
If there is no error anywhere, prolly you need to start the websockets server with `--debug` and see what it outputs.

**Comment by faizan-glowlogix** [comment]
it will error in terminal or any log file will be created?

**Comment by faizan-glowlogix** [comment]
there is no error in laravel log file. still after opening in debug mode

**Comment by rennokki** [comment]
It does not create a log file, it outputs the status in the console.

**Comment by faizan-glowlogix** [comment]
it is not showing any error as well

**Comment by faizan-glowlogix** [comment]
any other option? @rennokki

**Comment by rennokki** [comment]
It shouldn't show any errors, it should display everything that goes through the websockets server. If you got a channel and the user does not get connected to it, it won't broadcast any message.

Send the `routes/channels.php` file and the event classes you try to broadcast.

**Comment by faizan-glowlogix** [comment]
it shows that a presence channel is open and all other details but the message is not being broadcast.  i have authenticated channels as well.and at chat page it shows in XHR that user is autheticated to this channel

**Comment by rennokki** [comment]
Have you re-checked the docs on presence: https://laravel.com/docs/7.x/broadcasting#broadcasting-to-presence-channels ?

Perhaps there are issues with the broadcast name: https://laravel.com/docs/7.x/broadcasting#broadcast-name ?

**Comment by lionslair** [comment]
Anything in your browser console regarding subscribing to the channel. I assume if nothing is logged and nothing in debug then its a listener issue not a broardcasting issue then

**Comment by faizan-glowlogix** [comment]
found the issue.. When the event is broadcasting it was lining up in the queue.. i need to to check the implement class ShouldBroadcast to ShouldBroaddcastNow. Thanks for the help...
