### ISSUE TITLE
Intermittently 525 SSL Handshake Error during high traffic

### ISSUE THREAD

**Issue by kelvin195eclipse** [beyondcode/laravel-websockets#495]
Hi, I have developed my app with this package to run live updates on the app contents, and have been in production for months. My app is using Cloudflare, flexible SSL mode. Regarding the Websocket server, I've been using https scheme, TLS true and port 8443, and it works like charm during normal hours.

However, during peak hours (roughly 2000 users keep on access the server api, and continuously and concurrently subscribing and unsubscribing to multiple channels, "525 SSL handshake error" begins to occur intermittently, looked like my server blocked something and causing unable to send any events to Websocket server for sometime, then it only recovers after awhile when the users become lesser.

What I can identify is this issue only occurs during high traffic.

I would like to ask, whether:
- Keep on subscribing and unsubscribing to channel in extremely high frequency is causing this problem?
- Or is that keep on sending events to Websocket server causing this.
- Or is it some other possible issues causing this?

Thank you!

**Comment by bernisnukic** [comment]
Cloudflare has websocket connection limits depending on which plan you have for your website, it might be worth looking into if you are using the free plan:

https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets

**Comment by kelvin195eclipse** [comment]
> Cloudflare has websocket connection limits depending on which plan you have for your website, it might be worth looking into if you are using the free plan:
> 
> https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets

Thanks for the reply, 

However I didnt receive any message like mentioning the problems so far, in the article u sent (like cloudflare telling me that my usage is beyond limit, etc), it seems like happened from origin server end, the error message is about Cloudflare is unable to complete the ssl handshake with my server.

**Comment by kelvin195eclipse** [comment]
Problem Solve!

It was caused by delay during SSL handshake between Cloudflare and my server due to occasional heavy load. I've changed the Cloudflare SSL mode from "Full" to "Flexible", 
and set my values as below to fire event directly to localhost instead of going through Cloudflare in broadcasting.php:

'driver' => 'pusher',
'key' => 'XXXX',
'secret' => 'XXXX',
'app_id' => 'XXXX',
'options' => [
    'cluster' => 'xxx',
    'host' => '127.0.0.1',
    'port' => 8443,
    'encrypted' => false,
    'scheme' => 'http',
    'useTLS' => false,
    'curl_options' => [
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_SSL_VERIFYPEER => 0,
    ]
],
