### ISSUE TITLE
Only works when dashboard connected

### ISSUE THREAD

**Issue by bloomlive** [beyondcode/laravel-websockets#504]
I've set up a seperate Laravel Websockets server that is running on websockets.test. I'm able to connect on the dashboard, however, when my Lumen application broadcasts, it only works while I'm connected on the dashboard. As soon as I disconnect the dashboard console output no longer comes through. 

Am I missing something and it's expected or..?

**Comment by Pfannkuchensack** [comment]
so you have no console output if nobody is connect to the websocket ?
cause i think if nobody is connect the websocket dont need to output stuff because the subscriptions is gone and only come back if somebody connects to the websocket.

**Comment by bloomlive** [comment]
Figured so a seconds after my post, too, however wouldn't it be lovely, as it's purpose is debugging, to have that. Atleast an option to.

**Comment by rennokki** [comment]
If you don't have connected users to the channel you're trying to broadcast, no message will be sent or logged in the websockets server.
