### ISSUE TITLE
Failed to connect to Pusher.

### ISSUE THREAD

**Issue by faustbrian** [beyondcode/laravel-websockets#507]
Trying at the moment to get the WebSockets working as a replacement for Pusher but I always receive the error message `Failed to connect to Pusher.` when trying to follow the steps in https://beyondco.de/docs/laravel-websockets/basic-usage/pusher#pusher-configuration.

```php
        'pusher' => [
            'driver'  => 'pusher',
            'key'     => env('PUSHER_APP_KEY'),
            'secret'  => env('PUSHER_APP_SECRET'),
            'app_id'  => env('PUSHER_APP_ID'),
            'options' => [
                'cluster'      => env('PUSHER_APP_CLUSTER'),
                'useTLS'       => true,
                'host'         => 'valet.host',
                'port'         => 6001,
                'scheme'       => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => env('APP_ENV') !== 'local',
                    CURLOPT_SSL_VERIFYPEER => env('APP_ENV') !== 'local',
                ],
            ],
        ],
```

Is there any configuration that I am overlooking or misusing? Normal pusher works fine and the WebSockets are also running without issues.

**Comment by rennokki** [comment]
Perhaps you need to set the scheme to `http` if you don't use SSL.

**Comment by faustbrian** [comment]
I am using HTTPS both with Valet and the production system and configured the SSL certificates.

**Comment by rennokki** [comment]
Having self-signed certificates need the `curl_options` to have them set to true.

**Comment by faustbrian** [comment]
Tried that before and tried it again but that results in the same issue.

```
// With curl_options explicitly set to true
            'options' => [
                'cluster'      => env('PUSHER_APP_CLUSTER'),
                'useTLS'       => true,
                'host'         => '127.0.0.1',
                'port'         => 6001,
                'scheme'       => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => true,
                    CURLOPT_SSL_VERIFYPEER => true,
                ],
            ],

// Without curl_options, letting it use defaults
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS'  => true,
                'host'    => '127.0.0.1',
                'port'    => 6001,
                'scheme'  => 'https',
            ],
```

Also tried to set `useTLS` to false to avoid wrong ports but the same issue persists.

**Comment by rennokki** [comment]
Sorry for disorienting you, but values should be false so they won't check for additional SSL verifications.

**Comment by faustbrian** [comment]
That's what the behaviour at the moment is when I run it locally because I use `env('APP_ENV') !== 'local'` which will only enable the SSL checks in production/staging.

**Comment by rennokki** [comment]
Is your websockets server running?

**Comment by faustbrian** [comment]
Yeah, when I manually post it I can see that it receives the requests by throwing an error because I am omitting the signature.

```
>>> https://valet.test:6001/apps/ID/events
Starting the WebSocket server on port 6001...
Exception `Symfony\Component\HttpKernel\Exception\HttpException` thrown: `Invalid auth signature provided.`
Exception `Symfony\Component\HttpKernel\Exception\HttpException` thrown: `Invalid auth signature provided.`
Exception `Symfony\Component\HttpKernel\Exception\HttpException` thrown: `Invalid auth signature provided.`
```

**Comment by faustbrian** [comment]
Based on some logging it looks like `auth_signature` is always empty and thus a 401 is thrown which is just being swallowed into a generic request failure without more details.

**Comment by faustbrian** [comment]
Looks like this is a known issue with the combination of Valet, Guzzle and curl https://github.com/laravel/valet/issues/736#issuecomment-511789470.

**Comment by ziagit** [comment]
I had the same problem, websockets was not running in the server, run: `php artisan websockets:serve`
