### ISSUE TITLE
Triggering an event in custom websocket handler

### ISSUE THREAD

**Issue by hadiaec20h** [beyondcode/laravel-websockets#509]
I created a custom handler in laravel 5.8. I can trigger the event from controller without problem. Then I Tried to trigger the event inside the handler.  But it seems that nothing happens and no response will be send from the server to client. It seems triggering event inside the handler will cause a halt and there is no error.

Triggering an event is an important part of my application. I appreciate if you help me through this.

**steps to recreate:**

1. **create a websocket route:**
WebSocketsRouter::webSocket('/test', \App\Http\Websocket\TestSocketHandler::class);

2. **create an Event:**
```
class TestEvent  implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $test = "test";

    public function __construct()
    {

    }

    public function broadcastOn()
    {
        return new Channel('test');
    }
}
```
3. **trigger event in the onMessage method of the handler**
```
  public function onMessage(ConnectionInterface $connection, MessageInterface $msg)
    {
        $result = [
            'status' => 'success',
            'message' => 'message'
        ];
         event(new TestEvent()); 
         // it does not really matter in which line the event is triggered
         // the existence if this trigger in any line of this method will cause same results
         // it would happen again if you use a model in which an observer is utilized
        $connection->send(json_encode($result));
}
```

4. **send something to server using javascript**
```
testSocket = new WebSocket('ws://'
        + window.location.hostname
        + ':6001/test');

testSocket.send(JSON.stringify({
                'something' : 1,
            }) );

testSocket.onmessage = function (event) {
    console.log(event); //if the code runs successfully a message will be seen in console log.
}

```
5. restart websocket for the changes to take place
6. observe /laravel-websocket to see if the event is triggered (it will not)

Now if you run the code, the message will be sent to the server but no response will be sent to the client and the TestEvent will not broadcast on the test channel. If you comment out the `event(new TestEvent());` the response will be sent to the client.

**Comment by rennokki** [comment]
Please use the Pusher SDK for JS instead of a direct connection to the WebSocket.

**Comment by hadiaec20h** [comment]
> Please use the Pusher SDK for JS instead of a direct connection to the WebSocket.

Is that necessary for a custom handler? if so, how do i suppose to send data to a custom URL using pusher?

**Comment by rennokki** [comment]
There is not tested using the standard WebSocket method. Plus, I assume it needs a PSR-7 Request for this, not using the websockets.

**Comment by azizahmed45** [comment]
@HadiAghandeh 

Any solution found?
