### ISSUE TITLE
Websocket Server own't run on PHP 7.4

### ISSUE THREAD

**Issue by robs007** [beyondcode/laravel-websockets#510]
I can't get the websocket server to run a php ver 7.4. When I run the websocket:serve command it just says starting and sits there. My current service provider is running 7.4. I can duplicate the issue in my local dev environment. if I start it with php 7.3 it works fine, if I start it with 7.4 it won't run. Any ideas?
I'm seeing if the provider can give me 7.3 cli access, Any reason it wouldn't run in 7.4?
Thanks

**Comment by rennokki** [comment]
You mentioned the that provider can give you 7.3 cli address. Is it shared hosting or VPS?

**Comment by robs007** [comment]
Yes, it is a shared provider. I’m having trouble actually getting it to run anywhere other then local dev. I moved to another host provider that has php 7.3 and it does the same thing. So I don’t know if it’s a config problem or what. I get no error messages anywhere.

**Comment by robs007** [comment]
I also brough up my own Ubuntu server and can’t get it to run there either on

**Comment by robs007** [comment]
I upgraded to the beta 2.0.0-beta.18 and now I get saving statistics after starting the server. Which don't seem to g into the DB. Also, I don't see a route to the debug page, I get a 404 error. I realize this is a beta version, but I seem to be having slightly more success with it.

**Comment by rennokki** [comment]
After upgrading to 2.x beta, make sure you read the PR that contains the migration guide as well as the full modifications.

**Comment by mxmtsk** [comment]
I'm running into the same issue with PHP 7.4. Anyway to debug this further? Is PHP 7.4 not supported currently?

**Comment by rennokki** [comment]
Package version?

**Comment by kdevan** [comment]
Having the same issue with PHP 7.4 and `"beyondcode/laravel-websockets": "^1.8"`.

**Comment by rennokki** [comment]
Updating to 2.x beta and checking it again on php 7.4 do any relieving?

**Comment by kdevan** [comment]
Just updated to beta, same issue for me. `art websockets:serve --debug` "Starting the WebSocket server on port 6001..." and then hangs, no more output after that.

**Comment by rennokki** [comment]
If there is no logging, it means there are no connections that interact with the server. Can you make sure you also get some network logging for the WS connection in the browser?

**Comment by kdevan** [comment]
Working with 7.4. In my case it was not an issue with PHP 7.4 and pointing in the direction of the client helped here. Thank you!
