### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by AdamKyle** [beyondcode/laravel-websockets#511]
Should be simple to change the composer package to include 8.0 for the appropriate packages.

Not aware of anything that would shatter.

Is this something that can be done?

**Comment by yashris** [comment]
Yeah, it gives me this error when I try to upgrade to Laravel 8.0 :
 Problem 1
    - Conclusion: remove beyondcode/laravel-websockets 1.6.1
 beyondcode/laravel-websockets 1.x-dev requires illuminate/support 5.8.*|^6.0|^7.0

Any fix for this would be appreciated guys!

**Comment by AdamKyle** [comment]
@yashris The only way to fix this is two options:

1. Fork Project, Update composer to have `|^8.0`, pull from your own github.
2. Do the same as above but submit a pr.

I don't think this project is very active anymore. So I would go with option one.

**Comment by stephenjason89** [comment]
I hope this get merged soon. 
Would like to keep the original repo linked and not my own github.

**Comment by on-kim** [comment]
Merge. Please. I need Websockets in Combination with Jetstream <3

**Comment by chrispage1** [comment]
@AdamKyle the last release was only 22 days ago. BeyondCode are generally on it when it comes to these things, give it a couple of days 👍

**Comment by rennokki** [comment]
You can use the `dev-master` version if you will to use Laravel Websockets with Laravel 8.x, until we get fixed the CI pipeline.

```bash
composer update beyondcode/laravel-websockets:"dev-master"
```
