### ISSUE TITLE
Port 443 apache -> Error: handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by adishardiseffectris** [beyondcode/laravel-websockets#513]
Hi, does anyone have any tips or links on how to setup laravel-websockets with port 443 on apache server. We are not allowed to open any other ports than the already open 443.

Here's the console output:
WebSocket connection to 'wss://mysite.com/app/myKey?protocol=7&client=js&version=4.3.1&flash=false' failed: Error during WebSocket handshake: Unexpected response code: 404

broadcasting.php
```
'pusher' => [
			'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 443,
                'scheme' => 'https',
                 'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],
```
bootstrap.js
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wssPort: 443,
    disableStats: true,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true,
    enabledTransports: ['wss'],
    forceTLS: true
});
```

**Comment by rennokki** [comment]
Have you set the SSL certificates in the config file?

**Comment by adishardiseffectris** [comment]
Thanks for your reply!

Yes i have :/

**Comment by rennokki** [comment]
I assume that the 443 port is opened by the webserver, so you cannot use it in your websockets. By running `php artisan websockets:serve --port=443` will surely throw an error. You need an additional port.

**Comment by adishardiseffectris** [comment]
In the documents there is a section https://beyondco.de/docs/laravel-websockets/basic-usage/ssl which talks about having "Same location for websockets and web contents". My interpratation of that was that it is possible to have webserver and websocket to share port (443), but I just cant get it working.

**Comment by rennokki** [comment]
You need additional nginx configuration for this that will mark some paths like `mydomain.com/ws` to respond to 443, but underlyingly, the `6001` port is used for local connection.
