### ISSUE TITLE
Max message size not working

### ISSUE THREAD

**Issue by lovetoast** [beyondcode/laravel-websockets#515]
Not exactly urgent, but using:

"php": "^7.2.5",
        "beyondcode/laravel-websockets": "^1.6",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.24",
        "laravel/tinker": "^2.0"

And a max message size of 250kb, I can send a message of over 300kb, via the PHP API, and it is all received in my browser via the websocket.

**Comment by esroyo** [comment]
@lovetoast is your question about a message send from the server to the client?
Apparently the config param is a security feature meant for incoming messages (only):
```
    /*
     * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
     */
    'max_request_size_in_kb' => 250,
```
Ref: https://github.com/ratchetphp/Ratchet/blob/bca7183c5a4bd895f8a59f09ade17069e58c5ec2/src/Ratchet/Http/HttpRequestParser.php#L20

**Comment by lovetoast** [comment]
@esroyo Thanks for your reply, I thought so, I think the confusion arises because we assume it is a drop-in for Pusher and generally, on Pusher, my understanding is the corresponding limit would be for messages sent from the server to client, right? Perhaps a change to the docs might be helpful?

**Comment by esroyo** [comment]
@lovetoast Yes, It seems as you say that Pusher limits the outgoing messages [1]. I don't know about incoming messages.

About the docs, do you mean some kind of callout or clarification in the Pusher section [2]? Or in the FAQ?
The explanation of the param in `config/websockets.php` is clear to me.
Regards

[1] https://support.pusher.com/hc/en-us/articles/360019115473-What-is-the-message-size-limit-when-publishing-a-message-in-Channels-
[2] https://beyondco.de/docs/laravel-websockets/basic-usage/pusher

**Comment by lovetoast** [comment]
Hi @esroyo 

Hmm, yes now that I read it, it does seem clear, but from a first glance, as pusher does not having this setting,  one may look at what they believe to be the analogous setting in pusher and assume it was the the Pusher limit?

**Comment by esroyo** [comment]
@lovetoast My impression is that deep down you are right. However I'm not a regular folk here.

On one hand documentation could be improved as you asked, but I can't really say where (an extra super clear notice in the `config/websockets.php` template?).

On the other hand, may be It would be nice to have another parameter `max_response_size_in_kb` to limit the sever sent bytes? Then names would be obvious, and you could have more control than using Pusher. @rennokki does it make sense?

**Comment by rennokki** [comment]
When creating a new server, the construct method receives the `max_request_size_in_kb`: https://github.com/beyondcode/laravel-websockets/blob/master/src/Server/HttpServer.php#L13

According to the Ratchet docs, the `maxSize` attribute is used to specify the maximum request size but has no built-in support for specifying the response size. This can be easily worked around by adding another middleware to the WebSocket handler (2.x has currently full support to extend and replace the handlers for both API and WS protocols).

**Comment by esroyo** [comment]
@rennokki thanks for your answer, that is fair enough. Though I was more asking about how interesting would be to have that option baked in.

If it is so easy, then It would be great to have a quick example to add in the FAQ, or somewhere.
