### ISSUE TITLE
Nginx/proxy strategy

### ISSUE THREAD

**Issue by mgralikowski** [beyondcode/laravel-websockets#516]
I tried 2.x version with success. I installed WS WebSocket server on a separate server (vhost) and a different domain as sockets.example.com. I use Nginx config based on this section:
https://github.com/beyondcode/laravel-websockets/blob/2.x/docs/basic-usage/ssl.md#usage-with-a-reverse-proxy-like-nginx

`ws://sockets.example.com:443/app/myapp-sockets-remote` - connection by Echo works.
`https://sockets.example.com:443/apps/myApp/events` - sending POST requests by Laravel broadcasting works.
I see also stats in the database but I stuck with the dashboard. It returns nginx 404 (not Laravel 404) but I guess it is normal, due to proxy.

Are there missing some steps in the documentation about the dashboard? Have I to make some URL patterns in port redirect?

**Comment by vikas5914** [comment]
You can try this in Nginx: (Not the complete conf. you still need to handle .php file, root, and SSL. )

 ```
location / {
        try_files $uri $uri/ /index.php$is_args$args;
}

location /app {
      proxy_pass             http://socket_ip:6001;
      proxy_set_header Host  $host;
      proxy_read_timeout     60;
      proxy_connect_timeout  60;
      proxy_redirect         off;
    
      # Allow the use of websockets
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
}

**Comment by mgralikowski** [comment]
My admin made it ;) I forgot about this issue. 

```
      location / {
            return 301 https://sockets.example.com$request_uri;
        }
```

```       location ~ ^/laravel-websockets {
            try_files $uri $uri/ /index.php;
        }
```

+ https://beyondco.de/docs/laravel-websockets/basic-usage/ssl#usage-with-a-reverse-proxy-like-nginx
