### ISSUE TITLE
Concurrent connections limited to ~410

### ISSUE THREAD

**Issue by setkyar** [beyondcode/laravel-websockets#520]
![image](https://user-images.githubusercontent.com/4435358/92989542-053bdf80-f4fb-11ea-9a42-179b83c3ad7a.png)

I've followed the advice on the deployment page to increase ulimit, and the had confirmed that it has been set to 10000.

I already installed the `pecl` event extension. Is there any advice for this?

**Comment by rennokki** [comment]
Check https://github.com/beyondcode/laravel-websockets/issues/426 and https://github.com/beyondcode/laravel-websockets/issues/244

**Comment by setkyar** [comment]
@rennokki already checked both issues. Already set the supervisor process open file limits. Still does not help.

![image](https://user-images.githubusercontent.com/4435358/92995094-2cf46d00-f526-11ea-8c88-55b0e1771a31.png)

**Comment by setkyar** [comment]
My suspect was on Nginx reverse proxy. Asked question on server fault as well.

https://serverfault.com/questions/1033676/nginx-socket-reverse-proxy-got-503-responses-on-concurrent-requests

**Comment by setkyar** [comment]
@rennokki I found out the issue. My suspect was on NGINX. But turn out it's Cloudflare DNS. Cloudflare got limit on websocket connection. In order not to block by them, I need to turn of Cloudflare DNS proxy and use DNS only mode. 

Thanks for your help. I will write about this as a blog post later on. 🙏

**Comment by rauschmerscen** [comment]
Hi @rennokki , it would be great if the deployment section in the documentation is expanded by explaining existing content & addressing these common issues in the official doc. My opinion always is that "Moving to production" documentation should always be well explained because it helps a lot of developers with varying experiences.
