### ISSUE TITLE
Stuck on "Starting the WebSocket server on port 6001"

### ISSUE THREAD

**Issue by mxmtsk** [beyondcode/laravel-websockets#525]
I'm trying to run Websockets locally on my Mac but it is stuck forever on `Starting the WebSocket server on port 6001`.
I thought I had the same issue as #510, but event after I switched to PHP 7.3.22 it still won't start.

Any way to debug this further?

**Comment by rennokki** [comment]
If you do not have any kind of connections actively connecting to the server, it won't display any debug info. You also need `--debug` on non-prod environments.

**Comment by splashsky** [comment]
I am also having this issue, and haven't found a solution as of yet. I am running Valet on Linux, no SSL cert. Package version is "^1.7". I have basic values in my `PUSHER_` environment variables. No error codes aside from the `Channels current state is unavailable` message on the dashboard when attempting to connect to port 6001.

My terminal is also stuck on `Starting the WebSocket server on port 6001...` when I enter the serve command. Adding --debug to the command causes no changes.

```
'pusher' => [
    'driver' => 'pusher',
    'key' => env('PUSHER_APP_KEY'),
    'secret' => env('PUSHER_APP_SECRET'),
    'app_id' => env('PUSHER_APP_ID'),
    'options' => [
        'cluster' => env('PUSHER_APP_CLUSTER'),
        'host' => '127.0.0.1',
        'port' => 6001,
        'useTLS' => false,
        'scheme' => 'http'
    ],
],
```

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: window.location.hostname,
    wsPort: 6001,
    forceTLS: false,
    disableStats: true
});
```

**Comment by mxmtsk** [comment]
I'm running on `1.7` as well. I've tried to connect the Dashboard and connect through Echo but no output whatsoever. My setup looks similar to @splashsky's.

**Comment by rennokki** [comment]
Is this issue related to Valet? https://github.com/beyondcode/laravel-websockets/issues/507

**Comment by mxmtsk** [comment]
@rennokki Ah, yes seems to be related to Valet. When I use `php artisan serve` instead and try to connect from there, it works fine. This is good enough for me for now! Thanks

**Comment by rennokki** [comment]
@splashsky Got the same issue with Valet?

**Comment by splashsky** [comment]
Yes, looks like serving through Artisan allows me to use WebSockets now. Not a perfect solution, but I don't have the skills to try and fix something like this haha :smiley:

**Comment by evy0311** [comment]
We use Docker to host our Laravel app on our development machines. I was also running into the issue splashky was running into above. Running the Laravel app manually with `php artisan serve` and pulling up the websocket instance that way resolved our issue.

**Comment by Gharla2Sami** [comment]
just had to start the Laravel server and the WebSocket server
