### ISSUE TITLE
PusherError 1006 on Reverse Proxy Nginx and iOS problems

### ISSUE THREAD

**Issue by butaminas** [beyondcode/laravel-websockets#538]
I am using laravel-websockets on Reverse Proxy with Nginx on - sockets.domain.com

The websocket is working fine on desktop and in general, everything seems to be working as it should.

However, it almost always doesn't work on iOS Safari (I say almost, because when I first connect to the website, it doesn't work but after I put the device to sleep and then turn it back on - it reconnects and seems to be working from that point on).

Another big problem is the PusherError 1006. I can't understand how this is happening but I have an app on Android that is using webview to display the webpage with websockets capability on Android. It is working great until after a while I would get PusherError 1006 and it stops working and only works after turning the app off and on again.

Same goes when using just the browser.

First, I thought this was the proxy\_read\_timeout, proxy\_connect\_timeout issues and indeed, it was set to 60 or so and after an hour, I would catch the websocket would stop working. After changing these Nginx settings, the issue was resolved and it would work even after few hours.  
However, from time to time, this issue still happens and I can't figure out why.

Any ideas? Would it help to remove reverse proxy and go straight forward to connecting over IP address?

My configs:

Laravel config/websockets.php:

```php
'apps' => [
    [
        'id' => env('PUSHER_APP_ID'),
        'name' => env('APP_NAME'),
        'key' => env('PUSHER_APP_KEY'),
        'secret' => env('PUSHER_APP_SECRET'),
        'path' => env('PUSHER_APP_PATH'),
        'host' => env('LARAVEL_WEBSOCKETS_HOST'),
        'capacity' => null,
        'enable_client_messages' => false,
        'enable_statistics' => true,
    ],
],
```

Laravel .env

```
PUSHER_APP_ID=lkaskldajskdjl242342
PUSHER_APP_KEY=jh34j5hj13hlj4234
PUSHER_APP_SECRET=l12h3kl1h2lk3h12l3
PUSHER_APP_CLUSTER=eu
LARAVEL_WEBSOCKETS_HOST=sockets.${APP_DOMAIN}
SOCKETS_SERVER_PORT=6001
LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=
LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=
```

JS config (Vue):

```javascript
import Echo from 'laravel-echo'
const { pskey, } = window.config

let port = 443
let host = 'sockets.' + window.location.hostname

window.Pusher = require('pusher-js')

window.Echo = new Echo({
  broadcaster: 'pusher',
  key: pskey,
  wsHost: host,
  wsPort: port,
  wssPort: port,
  disableStats: true,
  encrypted: true,
  enabledTransports: ['ws', 'wss']
})
```

Nginx config (for reverse proxy only):

```nginx
server {
   listen 443 ssl http2;
   listen [::]:443 ssl http2;
   server_name   sockets.domain.com;

   # FORGE SSL (DO NOT REMOVE!)
   ssl_certificate /etc/nginx/ssl/domain.com/879463/server.crt;
   ssl_certificate_key /etc/nginx/ssl/domain.com/879463/server.key;

   ssl_protocols TLSv1.2;
   ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
   ssl_prefer_server_ciphers on;
   ssl_dhparam /etc/nginx/dhparams.pem;

 location / {
   proxy_pass http://127.0.0.1:6001;
   proxy_read_timeout 999999;
   proxy_connect_timeout 999999;
   proxy_send_timeout 999999;
   send_timeout 999999;
   proxy_redirect         off;

   # Allow the use of websockets
   proxy_http_version 1.1;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection 'upgrade';
   proxy_set_header Host $host;
   proxy_cache_bypass $http_upgrade;
 }
}
```

**Comment by rennokki** [comment]
This needs thoroughly tested. 🤔

**Comment by butaminas** [comment]
@rennokki If you have suggestions on how to better debug this, I will try and do that.

The Android issue is hard to debug, but the iOS Safari issue is straightforward.  
I don't understand why it is not working properly and how to debug it.

**Comment by DaemonKun** [comment]
> @rennokki If you have suggestions on how to better debug this, I will try and do that.
> 
> The Android issue is hard to debug, but the iOS Safari issue is straightforward.
> I don't understand why it is not working properly and how to debug it.

I believe this was caused by this.
https://support.apple.com/en-ph/HT210176

**Comment by butaminas** [comment]
@DaemonKun I use LetsEncrypt to generate the SSL certificate. Safari (both on Mac and iPhone) doesn't show that there is a problem with SSL, also, iOS Safari Console doesn't show any errors as well.  
  
Besides, if it would be an SSL issue, then it wouldn't start working after you put your device to sleep and wake up or after a while, it would either work or not work.  
  
The issue on iOS is giving me a hard time since it doesn't work but after I debug for a while it starts working and I can't make it not work again.  
I was able to catch `/broadcasting/auth` 403 error once when it was not working. I wonder if this was it or was it unrelated since I was doing other changes at the time.
