### ISSUE TITLE
Custom Channel Manager, how can i access channel name?

### ISSUE THREAD

**Issue by technobecet** [beyondcode/laravel-websockets#539]
****
Hello, i have to perform some actions when the connection is lost from a certain presence channel. To do this, I created my Channel Manager and proceeded through the removeFromAllChannels function.
```
    public function removeFromAllChannels(ConnectionInterface $connection)
    {
        if (! isset($connection->app)) {
            return;
        }

        $user_id = collect(Arr::get($this->channels, $connection->app->id, []))
            ->filter(function (Channel $channel) {
                return $channel instanceof PresenceChannel;
            })
            ->map(function (PresenceChannel $channel) {
                Log::info($channel->channelName);
                return $channel->getUsers();
            })
            ->filter(function (array $users) use ($connection) {
                return isset($users[$connection->socketId]);
            })
            ->map(function (array $users) use ($connection) {
                return $users[$connection->socketId]->user_id;
            })
            ->first();
        parent::removeFromAllChannels($connection);
        $user = User::find($user_id);
        Log::info($user);
    }
```
However, i cannot access the channel name in this way because its protected variable and i do not find it appropriate to add a direct change or a function in the vendor folder. How should I go about it, there is a any solution for that?

**Comment by rennokki** [comment]
Package version? 1.x or 2.x?

**Comment by technobecet** [comment]
"beyondcode/laravel-websockets": "^1.4",

**Comment by rennokki** [comment]
Update to `1.8.1` and you can use `$channel->getName()` to get the channel name.

**Comment by technobecet** [comment]
With update ```$users[$connection->socketId]->user_id``` that area doesnt work, when i inspect users list, no more using socketId, directly using user_id, how can i filter with new listing system?
