### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by jsandfordhughes** [beyondcode/laravel-websockets#545]
Hi there, 

Been having an issue with some users not connecting to the websocket, I know this is not an issue with this package but probably an issue with the users network or something else blocking the connection. 

![image (1)](https://user-images.githubusercontent.com/35659248/93670924-bd86fc00-fa96-11ea-9ac8-06ff51692d80.png)

Image above of the error they are having, this is a screenshot from a user having trouble, I know this looks like an authentication error for private channels however when the authorisation XHR request return false and fails it also logs this in the console which as you can see is not the case so it looks like this is happening when opening the connection to the websocket before it authenticates the channels. 

I have also logged in as one of the users having this issue on my own computer in my own network and the websocket works fine so it must be something to do with their computer, network, extensions etc

Has anyone seen this before and can offer some guidance on what is blocking the websocket connection?

**Comment by rennokki** [comment]
Using Cloudflare?

**Comment by jsandfordhughes** [comment]
For the websocket server? No that is just a single instance on AWS with the DNS pointing directly to it

**Comment by rennokki** [comment]
Package version?

**Comment by jsandfordhughes** [comment]
V1.8 just updated to see if it fixed it but did not change the error for those specific users

**Comment by DarrellDD** [comment]
I'm having the same problem, websockets suddenly stopped working with the exact same error. Couldn't find out why, no message appears in the websocket console either. Locally it shows something in the console. but in the webconsole it still throws me a 403.

**Comment by homayoonprs** [comment]
same problem

**Comment by jsandfordhughes** [comment]
@DarrellDD are you saying you get a 403 error when accessing the websocket dashboard?

**Comment by DarrellDD** [comment]
No, when trying to connect to the websocket. Same error as in your issue.

**Comment by jsandfordhughes** [comment]
Are there any leads on somewhere to investigate this issue? We are still getting users reporting this error

**Comment by rennokki** [comment]
I'm trying to figure out too, before using `1.8.x`, do you remember the last version it worked on?

**Comment by jsandfordhughes** [comment]
To be honest the last version I was on was V6 and that's when I updated to see if it fixed the issue. 

I don't suppose this could be related to Nginx? I am reverse proxying the sockets with SSL to the server. Is anyone else here doing the same?

**Comment by DarrellDD** [comment]
I did the same with versioning, switched to v8 when the issue started on v6. I'm not reverse proxing, everything goes straight to Nginx.

**Comment by xiaohuilam** [comment]
I caught whole same problem.
Is there anyone knew and solved it?

![image](https://user-images.githubusercontent.com/6964962/98333787-764fcd00-203c-11eb-889f-7979da35ed2f.png)

**Comment by jsandfordhughes** [comment]
So we did some investigation and found out this is not an error with this package but something on clients computer and or network that is blocking websockets. 

We have been testing this with clients having the issue by sending them to the link below to test websockets. 

https://www.websocket.org/echo.html

**Comment by xiaohuilam** [comment]
> So we did some investigation and found out this is not an error with this package but something on clients computer and or network that is blocking websockets.
> 
> We have been testing this with clients having the issue by sending them to the link below to test websockets.
> 
> https://www.websocket.org/echo.html
> 
> We have not managed to find out what exactly is blocking them yet but I'm sure it could be many things

![image](https://user-images.githubusercontent.com/6964962/98339928-786b5900-2047-11eb-8029-b41b60d84b30.png)

My computer and network, quite operational~

**Comment by jsandfordhughes** [comment]
Well that's very interesting.

**Comment by xiaohuilam** [comment]
My problem resolved!

My to resolve is very simple... Only need to sure `config/websockets.php`'s
```
'allowed_origins' =>  [],
```

The origin list be empty! It doesn't support regex or wildcard! Repeat, it doesn't support regex or wildcard!

![image](https://user-images.githubusercontent.com/6964962/98351774-1d8e2d80-2058-11eb-9135-efdf45172512.png)


This matter bothered me whole two days! ...

**Comment by Tayyab1101** [comment]
I am facing same problem. I am working on an app with laravel jetstream. But It is not working on the project I started one month ago. Rather, its working fine if I create a new laravel project (also with laravel jetstream).

laravel-websockets route was even giving me 404 error. I am a beginner and I don't know that much but this command solved my problem.
`php artisan optimize`

**Comment by rehmatweb** [comment]
add this code in boot method of AuthserviceProvider
Gate::define('viewWebSocketsDashboard', function ($user = null) {
            return $user != null;
         });
         this solve my problem
