### ISSUE TITLE
Custom Web Socket Handler Events

### ISSUE THREAD

**Issue by fatduckling** [beyondcode/laravel-websockets#549]
Hi

I have the following routes in the `web.php`

```php
Route::get('/', [PagesController::class, 'home']);
Route::get('/new-event', [PagesController::class, 'n']);

WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);
```

My PagesController:
```php
class PagesController extends Controller
{
    public function home()
    {
        return view('welcome');
    }

    public function n()
    {
        $message = new Message("hello world");
        event(new PrivateMessage($message));
    }
}
```

My MyCustomWebSocketHandler:
```php
class MyCustomWebSocketHandler implements MessageComponentInterface
...
public $connections = array();
...
public function onMessage(ConnectionInterface $connection, MessageInterface $msg)
    {
        // TODO: Implement onMessage() method.
        echo "Message: '" . strval($msg->message) . "'";
        var_dump($msg);
    }

    public function onNewPrivateMessage(PrivateMessage $event)
    {
        foreach ($this->connections as &$connection) {
            $connection->send($event->message);
        }
        $id = spl_object_hash($this);
        var_dump($id);
    }

    /**
     * Register the listeners for the subscriber.
     *
     * @param Dispatcher $events
     * @return array
     */
    public function subscribe(Dispatcher $events)
    {
        $events->listen(
            'App\Events\PrivateMessage',
            [MyCustomWebSocketHandler::class, 'onNewPrivateMessage']
        );
    }
```

Finally, EventServiceProvider:

```php
protected $subscribe = [
        'App\MyCustomWebSocketHandler',
    ];
```

When I visit the `/my-websocket` endpoint, it generates a new event and I can see it getting fired.
However, it creates a new instance of `MyCustomWebSocketHandler` instead of using the existing instance that is served when `php artisan websockets:serve` is called. 

Therefore, my `public $connections = array();` is always empty so I can't emit my messages to the users.

Is it possible to make the EventServiceProvider use the same instance of MyCustomWebSocketHandler as my web socket handler?
Thanks

**Comment by rennokki** [comment]
This is because the `websocket:serve` process and the Request cycle in Laravel are two different things. The command that launches the server registers an instance of the WebSockets Handler, and it cannot be accessed outside the server.

You might want to upgrade to `2.x` (see details here: https://github.com/beyondcode/laravel-websockets/pull/447) and extend the existing handler and change it as you'd like.

**Comment by azizahmed45** [comment]
@fatduckling 
Any solution found?

**Comment by azizahmed45** [comment]
@fatduckling 
Any solution found?

**Comment by fatduckling** [comment]
> @fatduckling 
> Any solution found?
> 

Hello friend, it's been a while since I looked into it but I stopped using Ratchet and moved on to using other languages
