### ISSUE TITLE
Forced use of Facades

### ISSUE THREAD

**Issue by 4levels** [beyondcode/laravel-websockets#55]
Hi,

this library enforces the use of Facades.  Facades are optional and userland helpers that don't belong in a Laravel or Lumen framework library.

I'm currently testing the changes required to achieve this, so far it seems pretty straightforward ;-)
I'll create a PR from my fork.

Thanks again for this great package!

**Comment by 4levels** [comment]
See Pull #56

**Comment by freekmurze** [comment]
We'll continue the conversation in #56

**Comment by 4levels** [comment]
Hi @freekmurze,

pretending to continue a conversation just to simply close this (and the related PR) for some personal opinion is not done in my book.

This issue is still as real is it can get!

@mpociot
