### ISSUE TITLE
Pusher is not defined

### ISSUE THREAD

**Issue by Steelze** [beyondcode/laravel-websockets#561]
Added the package and anytime I click connect on the stats page I get  `Uncaught ReferenceError: Pusher is not defined` and pusher-js library is installed.

**app.js file**
```js
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: true
});
```

**Comment by rennokki** [comment]
The stats page do not require the `app.js`, it already comes with a Pusher JS SDK v7, so make sure you don't have an ad blocker on for the stats page.

**Comment by avidianity** [comment]
I had the same issue. Disabling ad blockers solved it for me.
