### ISSUE TITLE
Get socket connection by id?

### ISSUE THREAD

**Issue by TribalKing** [beyondcode/laravel-websockets#562]
Hello,

Is there any way to get connection by id? Or any other way to get already opened connection inside the Laravel app?

Everything working fine when I connect to the websocket, and when I send messages from that client, but when I want to create an API that needs to send some message to existing websockets I cannot instantiate them.

Kind Regards,
TribalKing

**Comment by rennokki** [comment]
1.x or 2.x?

**Comment by TribalKing** [comment]
Current version:

"beyondcode/laravel-websockets": "^1.4"

**Comment by rennokki** [comment]
Using the 1.x, you should extend the default ArrayChannelManager and specify the extended class in config and add a method that resembles like this one: https://github.com/beyondcode/laravel-websockets/blob/master/src/WebSockets/Channels/ChannelManagers/ArrayChannelManager.php#L55

Upgrading to `2.x` gives you the opportunity to get this using a method:

```php
use BeyondCode\LaravelWebSockets\Contracts\ChannelManager;

$channelManager = app(ChannelManager::class);

$channelManager->getLocalConnections()->then(function ($connections) {
     //
});
```

**Comment by TribalKing** [comment]
Upgraded to 2.x version, but keep getting Target [BeyondCode\LaravelWebSockets\Contracts\ChannelManager] is not instantiable.

**Comment by TribalKing** [comment]
Ok I'm working with 1.x version, and somehow my channels variable is empty, and I'm assigning my connection to the channel.

```
$std = new \stdClass; 
$channelManager = new LocalChannelManager;
$channel = $channelManager->findOrCreate(env('PUSHER_APP_ID'), 'general');
$channel->subscribe($connection, $std);
```

Later I'm using this for getting my channels:

```
$channelManager = new LocalChannelManager;
$channel = $channelManager->findOrCreate(env('PUSHER_APP_ID'), 'general');
```

Getting empty array every time, no matter how many connections and subscribers I have. Should I maybe use something else for `stdClass $payload` in `Channel` model?

**Comment by TribalKing** [comment]
Update:

When I try this one:

`$channel = $channelManager->find(env('PUSHER_APP_ID'), 'hitch');`

It's null. Somehow my channel is not saved, although creation is running before this one.

**Comment by TribalKing** [comment]
One more update :)

Basically connection is reachable in `onOpen` method, and there I can see it, but whatever I do there (save in db, cache, global variables). When I hit it from the outside API, it's not there. Like I'm on two totally different platforms.

Is it possible to hit already existing websocket connection from the outside app?

**Comment by rennokki** [comment]
You can only access the channel manager within the server.

**Comment by TribalKing** [comment]
Is there some way to get the connection by id maybe?

**Comment by rennokki** [comment]
You might want to add a separate route for the WebSockets router and make it return a connection by id and access it.

**Comment by TribalKing** [comment]
Is there maybe documentation about the WebSockets router? Basically I just need my established websocket connection, to be able to send messages to that connection from the internal API call.

**Comment by rennokki** [comment]
Even if you would make an endpoint available, you won't be able to access the `$connection` variable outside the server because:
1. An HTTP request is JSON-compatible only for the API
2. `$connection` cannot be serialized at all (because it wraps a WebSocket connection). So jobs or events won't do the thing.

However, you can make a WebSocket endpoint that will run your business logic on that connection if you want to. Check the docs for 2.x here: https://github.com/beyondcode/laravel-websockets/blob/2.x/docs/advanced-usage/custom-websocket-handlers.md

If doing so, you will be able to access the channel manager directly with `$channelManager = app(ChannelManager::class);`

**Comment by simonbuehler** [comment]
hi,

i also have the same issue and it doesn't work with 2.0 yet.
the thing i try to do is this: 
- emit a event in the laravel backend 
- broadcast it 
- react to it in the laravel-websocket context ( get channel manager, enumerate users in a channel, select one, send a message to the users first socket_id)

How can this be done in 2.*?
