### ISSUE TITLE
Multiple Issue with this package

### ISSUE THREAD

**Issue by bilalswiftsolutions** [beyondcode/laravel-websockets#568]
**Problem 1**
I am using laravel version 5.8 and websocket version 1.4 . Package was Giving error below

```
pusher.min.js:8 WebSocket connection to 'ws://52.64.101.38:6001/app/ABCDEF?protocol=7&client=js&version=4.3.1&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

```
```
pusher.min.js:8 POST http://52.64.101.38/auth 404 (Not Found)
jquery-3.3.1.min.js:2 GET http://52.64.101.38/api/098765/statistics 404 (Not Found)

```
it was working fine on localhost but when we deploy it on aws it starts giving these errors. 

Then I start figuring it out.  I Found that in ```dashboard.blade.php``` file of this package in ```connect()```
there is property ```authEndpoint: '/{{ request()->path() }}/auth',``` .  In console I was seeing this error  ```http://52.64.101.38/auth 404 (Not Found)```

Basically it was not picking the route correctly . then I changed it to ```/laravel-websockets/auth'``` gets connected at the moment.  

**Problem 2**

I was trigger an event from controller  ```event(new PrintLabelEvent($consignment_id));``` You can see i was passing data to event but unfortunately websocket server is not getting this data.  

Then I manually created Event through Dashboard which is created successfully . 

There was difference between manually created event and event created in controller

Dashboard log for manually created event 
```
Channel: PrintLabel, Event: PrintLabel
```
Dashboard Log for event created in controller
```
Channel: PrintLabel
````

You can see that event which is created in controller is not having Event name . I am not sure about this issue . But Please try solve it with me

**Comment by bilalswiftsolutions** [comment]
@rennokki

**Comment by rennokki** [comment]
5.8 is not supported anymore

**Comment by bilalswiftsolutions** [comment]
all the versions of websockets are not compatible?

**Comment by xlcrr** [comment]
5.8 is working for me in production with websockets v1.1

but I can't get it working locally anymore

**Comment by bilalswiftsolutions** [comment]
what problem you are getting? @xlcrr

**Comment by xlcrr** [comment]
I can connect, but the events are not showing on the frontend 

https://github.com/beyondcode/laravel-websockets/issues/420

I was previously able to get this working and posted an answer to get it working with homestead [here](https://stackoverflow.com/questions/55076399/laravel-websocket-in-homestead-not-working/56370064#56370064) but the same methods not working anymore 

Hoping for v2.0 fix. Been stuck on this for hours!

**Comment by bilalswiftsolutions** [comment]
Have  you read mine Problem 1 . where I talked about url . what do you think about it?

**Comment by xlcrr** [comment]
If you are getting connection refused, have you tried creating new pusher keys for this project? I am able to connect in a click no problem. Recently created new keys for this project. If you are using the same keys for another project that is not recommended. What version laravel? I recently upgraded from 7 to 8 and 8 is connecting instantly

**Comment by xlcrr** [comment]
I was able to get it working on Homestead by downgrading pusher-js to 4.4.0
