### ISSUE TITLE
Sudden loss of all broadcasts - have no idea what happened

### ISSUE THREAD

**Issue by garrettboone** [beyondcode/laravel-websockets#569]
This project is great - I started working with it only last week and everything was fine until today. I have no idea what happened and am looking for guidance.

- When I run the /laravel-websockets dashboard ALL the broadcasts are making it to the ledger
- I have channels like "UserJoined", "RoomCreated". "UserDisconnected", etc.
- But, when I run the websockets:serve it ONLY shows "New connection" and "Connection ###.### closed" along with pongs

The client side is getting nothing, reflects the Laravel job as described above. I've gone through my code and have confirmed it's making it all the way to `event(new UserJoined('xyz')`

I have restarted everything, cleared cache, and there are no Laravel errors. What should I look for next?

Thanks for any help.

**Comment by rennokki** [comment]
Package version 1.x or 2.x?

**Comment by garrettboone** [comment]
^1.8

I ran `php artisan websockets:serve --debug` and it caused the terminal readout to show the broadcasts again...but the clients are still not receiving them.

The websocket connection at the client shows the connection established, and my client-end logic to push the socketId to the backend is working fine. But only pongs are coming through.

**Comment by rennokki** [comment]
Show me the configurations for your broadcasting driver, Laravel Echo and your event.

**Comment by garrettboone** [comment]
broadcasting.php:
```
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                // 'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],
```

bootstrap.js:
```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: true,
    wsHost: window.location.hostname,
    wsPort: 443,
    disableStats: true,
});
```

From the page script which works okay:
```
var echo = Echo;
socketId = echo.socketId();
```

The part that doesn't:
```
echo.channel(sponsorId)
    .listen('UserDisconnected', (e) => {
        [code redacted here]
    })
    .listen('UserJoinedRoom', (e) => {
       [code redacted here]
        }
```

The event would be triggered with something like this:
```
            $message = [
                    "event" => "userjoinedroom",
                    "data" => [
                        'circle_user_id' =>$request->circle_user_id,
                        'room_id' => $room_id,
                        'room_user_count' => $room_user_count,
                        'room_name' => $room_name_obj->room_name,
                        'user_full_name' => $user_full_name,
                        'total_room_count' => $total_room_count,
                        'total_user_count' => $total_user_count
                    ]
                ];

            event(new UserJoinedRoom($message));
```

UserJoinedRoom.php:
```
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class UserJoinedRoom implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $message;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
        return new Channel('2c1bbbc5-50b8-4b1b-8b44-469ecb9e782c');
    }
}
```

The channel names for all the events are all the same and hard-coded at the moment. Thank you for taking a look at this.

**Comment by garrettboone** [comment]
Also, I have it running behind an NGINX reverse proxy so it can be http locally.

**Comment by rennokki** [comment]
`wsPort: 443` should match the `6001` port you set in `broadcasting.php`

**Comment by garrettboone** [comment]
But 6001 on the server is not open to the public, so I have 443, which redirects to 6001 via NGINX.

**Comment by garrettboone** [comment]
I have also attempted to troubleshoot by removing various listeners to see if that might work. But nothing. No errors in Laravel. No failed jobs. It's all very weird. I have no errors on the server...it's as if the browsers cannot hear...but the Dashboard is hearing fine.

**Comment by rennokki** [comment]
Okay, so you're terminating the SSL at the nginx level, while upgrading the request there to point from '/some-route' to `:6001` ?

**Comment by garrettboone** [comment]
NGINX config:
```
upstream backend {
    server app:6001;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.mydomain.com;
    return 301 https://mydomain.com;

    ssl_certificate         /etc/nginx/ssl/fullchain.crt;
    ssl_certificate_key     /etc/nginx/ssl/private.key;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name mydomain.com;

    ssl_certificate         /etc/nginx/ssl/fullchain.crt;
    ssl_certificate_key     /etc/nginx/ssl/private.key;
    ssl_session_timeout     1d;
    ssl_session_cache       shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets     off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam
    ssl_dhparam             /etc/nginx/ssl/dhparam.pem;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers blah blah
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    #ssl_stapling on;
    #ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    #ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;

    root /var/www/public;

    index index.php index.html;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }


    # Laravel-Websockets
    location /app/ {
        proxy_pass              http://backend;
        proxy_set_header Host   $host;
        proxy_read_timeout      60;
        proxy_connect_timeout   60;
        proxy_redirect          off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by garrettboone** [comment]
"app" is a docker container in the same network as the NGINX container.

**Comment by garrettboone** [comment]
**The Dashboard is connecting fine...and the terminal will display the message if the Dashboard is open. It will not display if the Dashboard is closed. Like when someone disconnects, I send out a message that they have.**

![image](https://user-images.githubusercontent.com/47018474/94995191-a9e59600-056a-11eb-8ca4-c6f469ba76c7.png)

**After a user connects, it will push a UserJoinedRoom message.**

![image](https://user-images.githubusercontent.com/47018474/94995221-e3b69c80-056a-11eb-9ebe-fed56f72478a.png)

**But there's nothing to the client.**

**Comment by garrettboone** [comment]
The connection is enough to tell the server the user is connected/disconnected. Not enough to receive anything.

![image](https://user-images.githubusercontent.com/47018474/94995358-c3d3a880-056b-11eb-920c-da2290ad250c.png)

**Comment by garrettboone** [comment]
I resolved the problem - the call to a function got moved. This has been an error on my part. Thank you for your help - maybe my posting of NGINX template will help others. Everything in the package is working okay. I will try to pay it forward when I see a chance. 

Is there anything you think I can help with right now?

**Comment by vesper8** [comment]
@garrettboone can you explain in more details how you solved the problem? I'm experiencing what I believe is the same issue

**Comment by garrettboone** [comment]
@vesper8 I think it came down to calling a local vs global variable.

My code flow was:

1. a user was entered into the page with an userId. 
2. some global variables were set to null
3. axios call to get the parent id that went with that userId
4. make a connection using that parentId, wait two seconds, 
5. get the socketId

I passed parentId to #4 instead of this.parentId or something like that.
