### ISSUE TITLE
Required to include routes in web.php / `require_once channels.php`?

### ISSUE THREAD

**Issue by spekulatius** [beyondcode/laravel-websockets#570]
Hello,

Thanks for this! It made my live much easier! I've got the websockets configured and working as expected.

But the routes didn't work in `routes/channels.php`. Instead I've I had to add  them to `routes/web.php` (or include a `require_once channels.php` in the web routes). 

I'm wondering if this is expected and I just missed it or did I do something wrong? I can provide further details or answer question, if that helps.

Cheers!

**Comment by rennokki** [comment]
You should use `channels.php` and uncomment the `BroadcastingServiceProvider` from `config/app.php`

**Comment by spekulatius** [comment]
Awesome, thank you!
