### ISSUE TITLE
Can't access the served url

### ISSUE THREAD

**Issue by Mrbeyond** [beyondcode/laravel-websockets#575]
I served my new created app with php artisan websockets:serve but can't access the url on 127.0.0.1:6001. It shows 404.  But when served with normal artisan serve, it works well.

**Comment by hgferreira** [comment]
Did you tried to do a local telnet to the port? It should open, write any text and press enter 3 times, it should close.

If that works, it means the service is working as expetected. The port 6001 is suposed to be used only by ws or wss protocol.
