### ISSUE TITLE
How to configure a host dashboard connects to?

### ISSUE THREAD

**Issue by chimit** [beyondcode/laravel-websockets#576]
I'm running WebSockets server on a separate sub-domain using nginx proxy (to avoid opening 6001 port and messing with SSL certificates). But the dashboard is still available under the main domain and it tries to connect to the main domain. I can only specify a port (which I have to change from 6001 to 443), but not a host. Is there any way to easily do that?

**Comment by rennokki** [comment]
Setting `LARAVEL_WEBSOCKETS_PORT` to the desired port: https://github.com/beyondcode/laravel-websockets/blob/master/config/websockets.php#L11

**Comment by chimit** [comment]
@rennokki  I'm talking about the host, not port.

**Comment by rennokki** [comment]
According to this: https://github.com/beyondcode/laravel-websockets/blob/master/resources/views/dashboard.blade.php#L116 you should add a `host` key containing the host to connect to in the config: https://github.com/beyondcode/laravel-websockets/blob/master/config/websockets.php#L25-L34

**Comment by chimit** [comment]
Thanks! It works! But I feel there is some inconsistency here. If I want to specify the host and port for the dashboard I should use `LARAVEL_WEBSOCKETS_PORT` (`websockets.dashboard.port`) and add a new `host` param into my `apps` in `websockets.php`. So the dashboard port is a "global" param, but the dashboard host is an app-wide param. Isn't it more logical to add a new global host parameter? Something like this:

```php
    /*
     * Set a custom dashboard configuration
     */
    'dashboard' => [
        'host' => env('LARAVEL_WEBSOCKETS_HOST', 'window.location.hostname'),
        'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
    ],
```

**Comment by rennokki** [comment]
I marked this as enhancement and will change it asap.
