### ISSUE TITLE
Websockets server with WSS only accepts connections as root user

### ISSUE THREAD

**Issue by hgferreira** [beyondcode/laravel-websockets#577]
Hello,

I have a laravel-websocket server running almost flawless, the only problem is that I have a user websockets and if I run the php artisan websockets:serve with that user (that is the account owner) it will not accept connections, if I run as root, everything works as normal. Due security concerns that is not a recomendable practice, so I would like to solve this, follow a screen capture:

[root@apollo code]# su websockets
[**websockets**@apollo code]$ php artisan websockets:serve
Starting the WebSocket server on port 6001...
^C
---> nothing happened

[websockets@apollo code]$ exit 
exit
[**root**@apollo code]# php artisan websockets:serve
Starting the WebSocket server on port 6001...
New connection opened for app key MyAwesomeApp.
Connection id 857260704.789554657 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"857260704.789554657\",\"activity_timeout\":30}"}
New connection opened for app key MyAwesomeApp.
Connection id 561022712.426258577 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"561022712.426258577\",\"activity_timeout\":30}"}

Anyone has ideas how to solve this?

Cheers

**Comment by rennokki** [comment]
Do you run with SSL? It can be related to https://github.com/beyondcode/laravel-websockets/issues/480

**Comment by mrABR** [comment]
@hgferreira you can symlink to the private key and fullchain, this way you don't have to keep copying files every time a new certificate is deployed
