### ISSUE TITLE
Can not bind websockets to ipv6

### ISSUE THREAD

**Issue by axel-verse** [beyondcode/laravel-websockets#588]
When running `php artisan websockets:serve` in default configuration, it won't bind to IPv6.
Netstat (`netstat -putan | grep 6001`) gives me
```
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      1886/php
```

Did I missed something I should configure, or there's no IPv6 implementation, or websockets simply don't work via IPv6?

Thanks in advance and sorry for bad English

**Comment by rennokki** [comment]
Seems like an enhancement. Might be related to https://github.com/reactphp/socket/pull/64
