### ISSUE TITLE
Auth failure doesn't close websocket?

### ISSUE THREAD

**Issue by farseekers** [beyondcode/laravel-websockets#590]
If the authEndpoint (/broadcasting/auth) fails with a 403, the websocket doesn't receive any messages, but it also doesn't close - it stays open.

Could you explain to me why this is not the case? It would seem to me that it would be good to use less server resources.
Is there a benefit that I'm not aware of?
Is this a feature that just hasn't been implemented?
I don't think this is specific to my installation, but let me know if I'm missing something.

Thanks for this library.

**Comment by rennokki** [comment]
The auth happens on the channel level, not at the connection level.

So you can still have the connection established and do your thing on joining/subscribing to other channels without having to re-establish the connection.
