### ISSUE TITLE
Get logged in user inside custom websockets handler ?

### ISSUE THREAD

**Issue by Abdullah-Hejazi** [beyondcode/laravel-websockets#593]
Hello, 
I am trying to implement Online/Offline status in my code through custom websockets handler...

I created it like so:

`
<?php

namespace App\WebSockets;

use Ratchet\ConnectionInterface;
use Ratchet\RFC6455\Messaging\MessageInterface;
use Ratchet\WebSocket\MessageComponentInterface;
use BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler;

class PrivateWebSocketHandler extends WebSocketHandler {
    public function onOpen(ConnectionInterface $connection) {
        \Log::debug('Connected');
        parent::onOpen($connection);
    }
    
    public function onClose(ConnectionInterface $connection) {
        \Log::debug('Disconnected');
        parent::onClose($connection);
    }

    public function onError(ConnectionInterface $connection, \Exception $e) {
        parent::onError($connection, $e);
    }

    public function onMessage(ConnectionInterface $connection, MessageInterface $msg) {
        parent::onMessage($connection, $msg);
    }
}

`

My problem is that I can't figure out how to get the current User model inside the onOpen & onClose.
The request() method always return NULL

Is there anyway to get the current logged-in user in the websockets handler ?

**Comment by rodrigoross** [comment]
Hello, why it was closed? I'm trying to implement a similar control before onOpen and onClose methods in a custom websocket handler.

**Comment by Abdullah-Hejazi** [comment]
I am not sure why it was closed
