### ISSUE TITLE
cannot subscribe to channels in IOS hybrid app (via Cordova)

### ISSUE THREAD

**Issue by vesper8** [beyondcode/laravel-websockets#594]
I'm really struggling to debug this issue and though maybe you would have some insight that could help me.

I'm building a hybrid app using a single codebase for web, IOS and Android.

I'm using the latest 2.x-dev version of laravel-websockets.

My app is able to emit and subscribe to channels on the web, including on web Safari, as well as on Android.. without any problem. It even works fine on IOS Safari (using the web browser on my IOS device)

In my IOS app however (real app built with Cordova), then there is no channel subscription at all.

I'm wondering if this is maybe related to CORS and I see you've added a new `allowed_origins` which by default is an empty array.

It's rather difficult to debug this. @rennokki do you have any idea why it's working in all contexts except when it's within an IOS App?

Is there a way to tell CORS to "allow everything without question" ? Is there any documentation on how this `allowed_origins` is supposed to work?

It's also possible this has nothing to do with CORS

When looking at the laravel-websockets dashboard, on web/android/ios safari I can see all the channel subscriptions and unsubscriptions.. but when I load the IOS app, I don't see any of those but I do see this:

```
connected | {   "origin": "http://socket.mydomain.com",   "socketId": "56370598.462720583" } | 16:57:55

replicator-subscribed | {   "serverId": "33f8bbcf-23f0-4b9c-9df1-2d4302bdbd55",   "pubsubTopic": "laravel_database_6641070849" }
```

So I know at least something is happening, but no channel subscriptions

Many thanks for any help you can give me

**Comment by vesper8** [comment]
Update:

So actually on the IOS app, I can emit client events (whisper).. which is crazy that I am able to emit without actually subscribing to the private channel first.

I am unable to listen to whisper events or to receive any kind of websocket events.. and the websocket dashboard indicates that it receives my whispers, but as stated above, does not indicate that I am subscribing to any channels, unlike on web/android/ios safari

**Comment by vesper8** [comment]
Figured it out.. it was indeed a cors issue but unrelated to laravel-websockets, it was failing cors when hitting /broadcasting/auth, this only happened on IOS because IOS has some quirks that other clients don't and needed an exception case

**Comment by AugmentBLU** [comment]
@vesper8 We're having issue trying to get Swift/Pusher SDK to connect to our server. Did you use the Swift SDK or the standard JS? You mention hybrid app that's why I ask.

We have the web app working real well, just cannot get the iOS to connect. It doesn't even look like it's hitting the socket server at all when we run it in `--debug` mode. Like your issue, I'm convinced it's a CORS issue or security policy somewhere but with no debug info, it's hard to figure out.

**Comment by vesper8** [comment]
I'm using pusher and laravel-echo in a hybrid vue app

my issue turned out to be a CORS issue. I had added an axios interceptor that inserts a specific header that tells my laravel back-end to allow cors when that header is present, but for some reason I still don't understand, that header was not being added on IOS

I confirmed this was a CORS issue by simply turning off CORS on my back-end temporarily and noticing that this fixed the problem

**Comment by AugmentBLU** [comment]
Ah we're trying to use the official Pusher SDK as its a native iOS app. 

I created a very simple HTML file that can connect to the server just by running the file in a browser and works fine so I'm not so sure it's CORS if that can connect. 

It's a massive headache, really hoping someone with iOS experience manages to share a working solution. I'd pay them!

**Comment by rennokki** [comment]
Will continue the issue to https://github.com/beyondcode/laravel-websockets/issues/602
