### ISSUE TITLE
How can I use this with pure android and IOS?

### ISSUE THREAD

**Issue by vipin733** [beyondcode/laravel-websockets#60]

**Comment by Braunson** [comment]
You'd have to run Laravel with this Package? You couldn't just run this directly inside an iOS and Android device?

**Comment by vipin733** [comment]
@Braunson yes I know this package for laravel but for client how can i connect like for javascript is laravel/echo is there any alternate of   laravel/echo

**Comment by velegip** [comment]
@vipin733 
for Android: [pusher-websocket-java](https://github.com/pusher/pusher-websocket-java)

**Comment by vipin733** [comment]
@Braunson thanks for suggestion so I have to use [pusher-websocket-java](https://github.com/pusher/pusher-websocket-java) instead of [socket.io-client-java](https://github.com/socketio/socket.io-client-java)

**Comment by sam961** [comment]
So I should use Pusher SDK on ios to  be compatible with this too ?

**Comment by stayallive** [comment]
@sam961 yes. in theory it does (I did not try it myself).
