### ISSUE TITLE
Graphql Subscriptions

### ISSUE THREAD

**Issue by Mihai-github** [beyondcode/laravel-websockets#601]
Hi, 
   I am trying to implement subscriptions with lighthouse, but the problem is that for some kind of reason the communication between lighthouse and Laravel Websockets is not happening, I've found something on a issue that i've tested and it looks like it works but i am wondering if there is a official way of resolving this problem...
   
   I've tested the connection using a custom event and it works, but with graphql no

**Comment by rennokki** [comment]
Related to https://github.com/beyondcode/laravel-websockets/issues/111 ?
