### ISSUE TITLE
iOS SDK Connection Possible?

### ISSUE THREAD

**Issue by AugmentBLU** [beyondcode/laravel-websockets#602]
Hi there,

is it possible to connect to laravel-websockets from iOS, using the official iOS SDK? I have someone attempting to build out an iOS app to connect to the service but they're not having any luck. I don't have any debug info as yet but wondered if anyone has managed it?

If anyone has managed it, is it possible to share a simple code snippet to help us on the way?

Thanks!

**Comment by rennokki** [comment]
As long as this package works as a Pusher protocol-backed server, it should work: https://pusher.com/docs/channels/getting_started/ios

**Comment by AugmentBLU** [comment]
I'm using the latest 2.x version and works great on the web side of things but the iOS dev cannot connect for some reason. He setup a test account with Pusher and can connect to their service fine but not laravel-websockets. 

We will be working on debugging the issue next week, I just wanted to see if anyone has managed to actually connect an iOS app to laravel-websockets successfully before we started so I had a heads up on what to look out for. I'm not an iOS dev and don't have a Mac to even attempt a basic test myself so thought I would reach out here.

I know there's a few threads about iOS but none really give a definitive answer if it works or a working example. It's a make or break issue for the app so I'm feeling the pressure to get it working.

**Comment by AugmentBLU** [comment]
@rennokki Are we allowed to post a bounty to get help with certain tasks such as this one? Like I said, this is really important that I get working and I'm willing to pay someone to get a working example. 

I sat with the iOS dev yesterday for a couple hours and we couldn't get this working. Connection is always refused or doesn't get established. There's no sign that it's even attempting to connect to the server at all when running the websockets server in debug move.

**Comment by AugmentBLU** [comment]
For now, I'll need to move my development to use the official Pusher service since we cannot get iOS to connect - which is unfortunate! 

If anyone manages to get a working example of iOS connecting, please let me know. The offer of a bounty is still there if we can manage to get a confirmed working example.

**Comment by rennokki** [comment]
@AugmentBLU You are allowed to post bounties. I cannot provide a good answer to this since I have whatsoever no experience with iOS, but I can provide support on the package side if it needs changes or protocol updates related to any dependencies.

**Comment by AugmentBLU** [comment]
@rennokki Thanks for the offer.

Funny thing is, the iOS dev can connect to the official Pusher service using their Swift SDK without any issues but simply cannot connect to this package, even though it appears to be working perfectly fine for the web app and even a simple local HTML test connection.

There's no real debug info from Xcode as to why there is no connection and on the server side, using the `--debug` flag, it doesn't even appear as if there's any attempt to connect at all. We tried a simple test channel, with no auth required and just nothing. It's incredibly frustrating as we have things working for the web app so well but iOS just won't play ball, I suspect it's something simple but without any real debug info from the iOS side, it's hard to see what the issue is.

I did think about just going with the paid Pusher service but we have some payloads that are around 20kb, and Pusher have a limit of 10kb on payloads, unless you're an enterprise user with a dedicated cluster - which will probably cost a fortune. 

I'm convinced we're just missing something with the connection side, whether it's Apple's overly sensitive security policies or a CORS issue, maybe a setting but so far nothing. That's why I'm willing to pay someone, who has managed to get this working to help us at least get a connection established.

**Comment by tomirons** [comment]
@AugmentBLU I haven't tested this but I found this little snippet while looking into using Pusher in a Flutter app.

In your `Info.plist` add the following:
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>example.com <- REPLACE THIS WITH YOUR DOMAIN</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSIncludesSubdomains</key>
            <true/>
        </dict>
    </dict>
</dict>
```

**Comment by zerubabbel** [comment]
@AugmentBLU Do you have any updates about getting it to work? I'm considering using this to tie in to an iOS app as well.

**Comment by salmanhijazi** [comment]
Use the version 8.0.0 of the Swift SDK. There is a bug in the latest one that doesn't let you connect. As of right now, the bug is not fixed and the author recommends using version 8.0.0 instead.

**Comment by Albertscot** [comment]
@zerubabbel @AugmentBLU Did you find any solution of this issue?

**Comment by magespider** [comment]
> 
> 
> @AugmentBLU Do you have any updates about getting it to work? I'm considering using this to tie in to an iOS app as well.

**Comment by djbe** [comment]
Can confirm that using the iOS SDK version 9 or higher doesn't work (connect) with self hosted pusher using this library. Reverting to the iOS SDK 8.0 fixes connection issues. For now we're using that older SDK version, but it's far from an ideal situation.

Is there anything we can do to help debug this? Are there specific logs that would help?

The pusher team is not going to change their SDK. As long as it works with their own servers, they have no intention of fixing stuff for other servers 🤷 Relevant quote:
> We replaced the underlying package that initiates the connection request in v9 so this will be the cause of the issue - however as this works well with our own service our advice would be to continue to use v8 as we can't commit to supporting custom websocket server connections.

**Comment by djbe** [comment]
Allright, did some testing with Charles and a modified iOS SDK 8.0.0 (to be able to proxy socks to log in charles), and there is a difference in what the new SDK requests, namely it defines a `Sec-WebSocket-Protocol`.

Old SDK requests this:
```
GET /app/v0if...redacted...?client=pusher-websocket-swift&version=8.0.0&protocol=7 HTTP/1.1
Host: ...redacted...:443
Sec-WebSocket-Version: 13
Upgrade: websocket
Sec-WebSocket-Key: cWdzb29kcmludGlwa3RibQ==
Connection: Upgrade
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits; server_max_window_bits=15
Origin: wss://...redacted...:443
```

New SDK requests this:
```
GET /app/...redacted...?client=pusher-websocket-swift&version=9.2.2&protocol=7 HTTP/1.1
Host: ...redacted...
Sec-WebSocket-Version: 13
Upgrade: WebSocket
Sec-WebSocket-Key: HwX9AWGC9AZPkakGRTUPsw==
Connection: Upgrade
Sec-WebSocket-Protocol: pusher-channels-protocol-7
```

The response (error) that the new SDK gets is:
```
HTTP/1.1 426 No Sec-WebSocket-Protocols requested supported
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 21 May 2021 01:47:02 GMT
Transfer-Encoding: chunked
Upgrade: websocket
Sec-WebSocket-Version: 13
X-Powered-By: Ratchet/0.4.3
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Connection: keep-alive
```

So the new SDK **requires** a specific websocket protocol. The current `WebSocketHandler` does not define any sub protocols. The only thing we need to do is implement `WsServerInterface` (and thus `getSubProtocols` function), as explained here: https://github.com/ratchetphp/Ratchet/issues/697

**Comment by djbe** [comment]
Aha! Also had to implement `WsServerInterface` on the `WebsocketsLogger` (and have it query `$this->app->getSubProtocols()`), and now I can successfully connect to the server using the new SDK 🎉

**Comment by Khairulbashar010** [comment]
Having a hard time with this. IOS developer cannot connect and we're running out of time. Can anyone suggest any alternative for this situation? Or any suggestion regarding what should I do. He said SDK 8 isn't working either.

**Comment by djbe** [comment]
@Khairulbashar010 have you tried the changes from the PR #769? Those changes were enough to fix it for me.

(note: if needed, read [this article](https://medium.com/swlh/using-your-own-forks-with-composer-699358db05d9) on how to use forks with composer)

**Comment by MarekGH21** [comment]
Two days with the problem ;)
To make it work on iOS, the latest SDK, do at first what @djbe suggested (WsServerInterface + getSubProtocols()).
Unfortunatelly it unables js client with Echo+Pusher to connect ;) 
To make both iOS and web clients work I added my custom named protocol to pusher.js's 
l.4026: return new Constructor(url, 'mine-web-protocol-1')  
and then the same  'mine-web-protocol-1' to 'pusher-protocols-x' array in getSubProtocols() method. 
(through new WebSocket(url, protocols)) it adds new header 'Sec-WebSocket-Protocol' that we need for laravel-websockets server successful handshake.

**Comment by josephmangmang** [comment]
How to make it work @djbe ? The PR is outdated now
