### ISSUE TITLE
Don't understand about hosting websocket independently 

### ISSUE THREAD

**Issue by kaungsandev** [beyondcode/laravel-websockets#603]
According to documentation , I understand that I can host webscoket as one project(let's say "websocketproject.test") and I can connect it from another apps (projects, "mychatapp.test", "shopapp.test") for their own message and events.

How should I configure to achieve that ? 

Do I need to configure both host app and mychatapp ? If yes, how ?

Do I also need to install "laravel-websockets" package on mychatapp ?

Thanks !

**Comment by 19peaches** [comment]
I implemented a free standing server, but it would never seem to stay online.
