### ISSUE TITLE
some packages are abandoned

### ISSUE THREAD

**Issue by rifRocket** [beyondcode/laravel-websockets#604]
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.

**Comment by rennokki** [comment]
The last three packages are not handled directly by us, is a dependency of one of our dependencies. The faker package will be replaced once things establish regarding the faker fork.

**Comment by avenCN** [comment]
![image](https://user-images.githubusercontent.com/14192055/99627520-6d64ef80-2a6f-11eb-92a2-be20be826cfd.png)

Hope next version will solve it.

**Comment by calliday** [comment]
@rennokki Is there any update on the faker fork?

**Comment by rennokki** [comment]
https://github.com/FakerPHP/Faker

**Comment by rennokki** [comment]
@avenCN @rifRocket This CLI output is non-critical.
