### ISSUE TITLE
Maintaining a fork of pusher-js that is fully compatible with this package

### ISSUE THREAD

**Issue by slothstronaut** [beyondcode/laravel-websockets#605]
Hello 👋 

One significant caveat with the "drop-in replacement" aspect of this package, is that `pusher-js` by default will revert to XHR streaming after a 2nd failed connection. It is difficult to emulate in testing, and generally most developers won't even notice this issue, but your users will be impacted, and they probably won't realize it either. 

If you install client side tracking for how often your client will lose its connection to this custom Pusher backend on mobile, you will realize this package is not fully compatible with `pusher-js`, and many users on a SPA/Mobile app will lose their connection after being backgrounded a few times once reverting to XHR streaming.

So... I created this fork of the official `pusher-js` package: https://github.com/findmate/pusher-js-websocket-only

This fork simply hard-codes `pusher-js` to *always* use websockets, even if it fails several times. This is critical to ensure mobile users stay connected to pusher for SPA and mobile apps. 

It all started from this thread when I read about others having the same issue: https://github.com/beyondcode/laravel-websockets/issues/163

I'll leave it to you whether you want to mention it on the docs.

**Comment by rennokki** [comment]
Feel free to add a PR with the docs. 🎉
