### ISSUE TITLE
ZeroMQ Custom Driver

### ISSUE THREAD

**Issue by 19peaches** [beyondcode/laravel-websockets#608]
Can websockets accept ZeroMQ messages if I build a custom driver as per the docs?

**Comment by rennokki** [comment]
For emitting the messages between servers for horizontal scaling, yes. You will need to find a way to store the channel data just like the Redis driver does.

**Comment by 19peaches** [comment]
Channel data can be passed as a topic.

```js
socket.send([channel, message])
```
