### ISSUE TITLE
WebSocket is closed before the connection is established + Usability questions

### ISSUE THREAD

**Issue by just-tom** [beyondcode/laravel-websockets#610]
Hi guys. Looking to move over to using this instead of Pusher. Great work so far! I have a few questions though beforehand:

1) Can this be used standalone on its own server? I don't want the ws traffic to impact our API servers by running them on the same. 

2) If so are there any caveats?

3) When is 2.x expected to be released and production ready?

Any thoughts/answers will be much appreciated, thanks

In the mean time I have attempted to deploy to my own server and hitting a major block. Everything I try I end up receiving the `WebSocket is closed before the connection is established.` message.

What I have tried:

 - Tried the latest 1.* branch
 - Now currently on the 2.* branch
 - Stripped nginx right back
 - tried with and without SSL

Setup is API on local valet, nuxt on local node for FE, laravel-websockets on DO ubuntu droplet. Once confirmed working locally I can push to our staging env.

Heres the minimal nignx that I have tried:

```
server {
    server_name HOST;
    root /var/www/ws/current/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";


    location / {
        proxy_pass             http://127.0.0.1:2096;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
       proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/HOST/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/HOST/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = HOST) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name HOST;
    listen 80;
    return 404; # managed by Certbot
}
```

Her is a full nginx conf I have tried (so I have dashboard access too)

```
map $http_upgrade $type {
  default "web";
  websocket "ws";
}

server {
    server_name HOST;
    root /var/www/ws/current/public;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.nginx-debian.html index.php;


    location @web {
        try_files $uri /index.php?$query_string;
    }

    location @ws {
        proxy_pass             http://127.0.0.1:2096;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

    	# Allow the use of websockets
    	proxy_http_version 1.1;
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection 'upgrade';
    	proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }


    location ~ .php$ {
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/HOST/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/HOST/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = HOST) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name HOST;
    listen 80;
    return 404; # managed by Certbot
}
```

UFW is currently disabled on the server so that I can be sure its not blocking.

For setup I have only changed the port for the websockets env to 2096 for cloudflare (although cloudflare is NOT proxying, its straight through).

Results are the same if reintroducing the dashboard and connect button and via FE so I don't think echo is the issue.

API Broadcasting.php:

```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => false,
                'host' => 'HOST',
                'port' => 2096,
                'scheme' => 'https',
            ],
        ],
```

this is everything that has changed/is custom, so very minimal. Any thoughts?

**Comment by just-tom** [comment]
Any ideas with this guys? Under pressure to get this working! Any help would be appreciated. Thanks

**Comment by toni-ismail** [comment]
Have you tried to change nginx location block ?
Is your js error like this ?
`
failed: Error during WebSocket handshake: Unexpected response code: 404
`

So maybe you need to try to specify your websocket path on your server location block. 
For example I'm using custom websocket :
 
in my routes.php
```
// Web Socket Test
\BeyondCode\LaravelWebSockets\Facades\WebSocketsRouter::webSocket('/mywebsocket', \App\WebSockets\GameSocketHandler::class);
```
path `https://mydomain.tld/mywebsocket`
port `6001`
so you need to specify `/mywebsocket` on  nginx location block like this
```
location /mywebsocket {
        proxy_pass             http://127.0.0.1:6001;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

    	# Allow the use of websockets
    	proxy_http_version 1.1;
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection 'upgrade';
    	proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

and your websocket url will be:
`wss://mydomain.tld/mywebsocket`

restart nginx, restart websocket and test at [Echo Test](https://www.websocket.org/echo.html)

Hope it will help. Thx.

**Comment by laocoi** [comment]
I was able to circumvent this error by specifying `enabledTransports` in my JS config:

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
    wsPort: 6001,
    disableStats: true,
    enabledTransports: ['ws', 'wss'] // <- added this param
});
```

Otherwise the pusher-js api tries to connect to the official Pusher service.

_Originally posted by @simplethemes in https://github.com/beyondcode/laravel-websockets/issues/83#issuecomment-453634042_
