### ISSUE TITLE
Ability to publish dashboard blade view

### ISSUE THREAD

**Issue by SelimSalihovic** [beyondcode/laravel-websockets#614]
We have an app running in production on beta26 of the 2.0 refactor (https://github.com/beyondcode/laravel-websockets/pull/447)

We'd like the ability to publish the dashboard view file so we can modify it so it disregards the port 6001. Right now we cannot remove the port from the URL the dashboard is trying to connect to. Our app connects to wss://ourapp.dev while the dashboard is trying to connect to wss://ourapp.dev:6001 so we'd like to remove the ':6001'.

I would be open to submit a PR myself it you agree that this should be done.

**Comment by alexhackney** [comment]
I know this is a few months old. We also need the ability to overide the view so that we can use local assets instead of ones on a cdn. Is this possible?

**Comment by danielsefton** [comment]
Also need this as Pusher is trying to connect to `wss://127.0.0.1:6001/app/` instead of our domain, it would be easy to just directly modify it in the view file, unless anyone knows a config param in the backend that could be causing that?

**Comment by alexhackney** [comment]
> Also need this as Pusher is trying to connect to `wss://127.0.0.1:6001/app/` instead of our domain. It would be easy to just directly modify it in the view file, unless anyone knows a config param in the backend that could be causing that? (dashboard.domain in websockets.php is already fine, the Dashboard loads and displays ok with correct domain it's just the websocket connection itself).

Where is this happening? You can tell echo where to connect like this:

`
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    forceTLS: forceTLS,
    wsPort: process.env.MIX_LARAVEL_WEBSOCKETS_BROADCAST_PORT,
    wssPort: process.env.MIX_LARAVEL_WEBSOCKETS_BROADCAST_PORT,
    disableStats: true,
    enabledTransports: enabledTransports,
    **wsHost: process.env.MIX_APP_BROADCAST_URL,**
    **wssHost: process.env.MIX_APP_BROADCAST_URL,**
});
`

**Comment by danielsefton** [comment]
Hi Alex, I'm referring to the Websockets Dashboard, not the Echo connection. The Dashboard does it like this, and I need to change the wsHost. Hence needing a way to publish the view as described.

`this.pusher = new Pusher(this.app.key, {
          wsHost: this.app.host === null ? window.location.hostname : this.app.host,
          wsPort: {{ $port }},
          wssPort: {{ $port }},
          wsPath: this.app.path === null ? '' : this.app.path,
          disableStats: true,
          authEndpoint: `${window.baseURL}/auth`,
          auth: {
            headers: {
              'X-CSRF-Token': "{{ csrf_token() }}",
              'X-App-ID': this.app.id,
            },
          },
          enabledTransports: ['ws', 'wss'],
          forceTLS: false,
        });`

**Comment by alexhackney** [comment]
I just checked my instance and it connects to the domain not 127.0.0.1

I would check your .env to make sure it's right.
