### ISSUE TITLE
Get user ID by socket ID

### ISSUE THREAD

**Issue by jesperbjoernandersen** [beyondcode/laravel-websockets#617]
I'm trying to make my backend modify some data in my Database, when a user disconnects from websockets.

I noticed that PresenceChannel.php has a $sockets variable where $connection->socketId gets mapped to $userId. Unfortunately, $sockets is protected.

There's the getUsers() method, but that doesn't have any information about the connection. It would be nice with a getConnections() method that would return the $sockets array.

Is there any workaround I can use?

**Comment by rennokki** [comment]
If you jump to 2.x, you can extend the base functionalities and access the connection on each connection/disconnection: https://github.com/beyondcode/laravel-websockets/pull/447

**Comment by BurakcanKolay** [comment]
> I'm trying to make my backend modify some data in my Database, when a user disconnects from websockets.
> 
> I noticed that PresenceChannel.php has a $sockets variable where $connection->socketId gets mapped to $userId. Unfortunately, $sockets is protected.
> 
> There's the getUsers() method, but that doesn't have any information about the connection. It would be nice with a getConnections() method that would return the $sockets array.
> 
> Is there any workaround I can use?

I am currently having this problem. Please help on how to solve it. I can only access socket id on $connection variable.

**Comment by thermostat42** [comment]
It's a hack, but you can access to the protected $sockets variable like this :
```
$channel = $this->channelManager->findOrCreate('YOUR_APP_ID', 'YOUR_CHANNEL');
$channel_as_array = (array)$channel;
$prefix = chr(0).'*'.chr(0);
$sockets = $channel_as_array[$prefix.'sockets'];
```
