### ISSUE TITLE
Can I use this as a saas application?

### ISSUE THREAD

**Issue by SuryaJD** [beyondcode/laravel-websockets#618]
I am planning to use it as multitenancy.  Is there any way to do that?

**Comment by messi89** [comment]
Yes

You need just to read this [https://beyondco.de/docs/laravel-websockets/advanced-usage/app-providers](url)

The main idea is to override the AppProvider in order to manage several applications and store them in a database instead of a config file

**Comment by rennokki** [comment]
Sure, just configure your own channel manager/app manager and you are ready to go.

**Comment by scramatte** [comment]
Hello,

I'm running Laravel 8 and laravel-websockets 2.x  and I'm unable  to set app manager.
Websockets server returns me  Target class [App\Providers\WebsocketConfigAppProvider] does not exist.

Any idea?
