### ISSUE TITLE
High CPU usage on statistics update

### ISSUE THREAD

**Issue by Mkaddem97** [beyondcode/laravel-websockets#621]
11K Peak Connections
5K Websocket Messages
420 Api Messages

Everything is going well if statistics are disabled, otherwise CPU load reaches 100% usage at the time where the statistics are updated. (it stays ~20s and then CPU load come back to 2%)
Here you can see on the left the statistics are enabled and on the right side are disabled
![Websockets](https://user-images.githubusercontent.com/39562776/100386376-77659000-3025-11eb-8416-eefa8da583ca.png)
(DigitalOcean do not show exactly CPU usage on update time, but I notice it from console "top -i")

DigitalOcean Server :  8Gb RAM / 4 CPU
Version : v2.0.0-beta.30

**Comment by rennokki** [comment]
Might be duplicated to: https://github.com/beyondcode/laravel-websockets/issues/623

**Comment by rennokki** [comment]
We'll continue any relevant issues in #623
