### ISSUE TITLE
PHP pusher library can connect without valid appkey

### ISSUE THREAD

**Issue by lovetoast** [beyondcode/laravel-websockets#622]
Hi,

I've tested this in the latest version, and an older one and it appears that the application is allowed API requests from the PHP pusher library (and probably others) without a valid appkey. Only the app secret is checked.

**Comment by lovetoast** [comment]
As far as I can see, this is still a bug, I have tried a few things including the suggested commit, but I don't think that works.

**Comment by rennokki** [comment]
@lovetoast It was a bit misleading. The `/event` endpoint from the dashboard sends events to the pusher broadcaster directly, where the `/app/{appId}/events` endpoint does get authenticated, but #626 fixes key & secret check. For the dashboard, it is not necessarily needed since it's internal.

**Comment by rennokki** [comment]
@lovetoast 1.x is somehow legacy and shouldn't be used unless it takes more to upgrade to 2.x that keeping it like that. But my recommendation is a v2.x upgrade.

**Comment by lovetoast** [comment]
Hi @rennokki, happy new year, thanks for your reply. Are you referring to the commit with the fix? As my query is, that it doesn't actually solve the issue? Unless in v1 it is somewhere else?

**Comment by rennokki** [comment]
The issue is not a security issue since the checkups for key & secret do happen at the API level.

**Comment by lovetoast** [comment]
Understood @rennokki however, after testing, it does not actually check at API level, I'm quite sure it is not checking for the key.

**Comment by rennokki** [comment]
It is obsolete since the API authentication is done using the App ID, not the app key. The app key is used for the frontend connection.
