### ISSUE TITLE
Cant get statistics work

### ISSUE THREAD

**Issue by mttzzz** [beyondcode/laravel-websockets#624]
Hi, this is my config: 

"beyondcode/laravel-websockets": 1.9.0

 'apps' => [
        [
            'id' => '12345',
            'name' => '123',
            'key' => '123',
            'secret' => '123',
            'enable_client_messages' => true,
            'enable_statistics' => true,
        ],

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: '123',
    wsHost: 'ws.fake.biz',
    wsPort: 6001,
    wssPort: 6001,
    disableStats: false,
    encrypted: true
})

APP_URL=https://ws.fake.biz
Events work perfect, but i cant see any statistics. DB have table from migration, but it is empty.
Can anyone help?

**Comment by HayriCan** [comment]
I am having same issue on version 1.2.0. It is not creating record on database :(

**Comment by bbashy** [comment]
Does your APP_URL actually resolve? It uses that to perform a POST request I believe.

**Comment by mttzzz** [comment]
> Does your APP_URL actually resolve? It uses that to perform a POST request I believe.

yep. my APP_URL resolve.

**Comment by bbashy** [comment]
Can you see it in your access logs then?

Should be like;
```
123.45.6.78 - - [02/Dec/2020:19:41:31 +0000] "POST /laravel-websockets/statistics HTTP/1.1" 200 12 "-" "ReactPHP/1" "123.45.6.78"
```

**Comment by mttzzz** [comment]
> Can you see it in your access logs then?
> 
> Should be like;
> 
> ```
> 123.45.6.78 - - [02/Dec/2020:19:41:31 +0000] "POST /laravel-websockets/statistics HTTP/1.1" 200 12 "-" "ReactPHP/1" "123.45.6.78"
> ```

log -- clear %:((

**Comment by bbashy** [comment]
Use that to try find out why it's not then. Least you know it's not even trying to do it.

**Comment by mttzzz** [comment]
> Use that to try find out why it's not then. Least you know it's not even trying to do it.

lol. this is production server and access logs from nginx - disabled. thx for help.

**Comment by mttzzz** [comment]
https://yadi.sk/i/TDDyqyAM_4u6Yg
 in ws i see all events in dashoard

**Comment by bbashy** [comment]
Stats are done via ReactPHP so you wouldn't see it in the dashboard.

Since you gave little information about your setup etc, I can't help.

**Comment by mttzzz** [comment]
> Stats are done via ReactPHP so you wouldn't see it in the dashboard.
> 
> Since you gave little information about your setup etc, I can't help.

my setup. clear laravel 8 and laravel-websockets. i ran migration. DB exist, config at the first post/ PHP 7.4.10
Do u need anything else?

**Comment by mttzzz** [comment]
SOLVED!!!  in config  -- 'perform_dns_lookup' => **true**,

**Comment by bbashy** [comment]
Good. Was just about to say, need the values on all the config, like `'interval_in_seconds' => 60,` etc.
