### ISSUE TITLE
I can't start websocket server of my Laravel Project on my cpanel A2 hosting server

### ISSUE THREAD

**Issue by iampapaisarkar** [beyondcode/laravel-websockets#625]
every thing is okay on local machine, but when I command php artisan websockets:serve on live server through SSH, then its only showing websockets connecting to port:6001. nothings happen and browser console showing websockets connecting failed.
please help and resolve this issue.

thank you

**Comment by rennokki** [comment]
It's highly recommended to use it with a VPS and to have the 6001 port opened.

**Comment by iampapaisarkar** [comment]
can you please explain this in more details ?

**Comment by rennokki** [comment]
Having cPanel means you are in some kind of shared hosting, and this is not the ideal environment. You can use forge.laravel.com or ploi.io to deploy your Laravel-ready VPS on DigitalOcean or Linode and make things work as expected.
