### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by maximal** [beyondcode/laravel-websockets#627]
When updating composer packages in PHP 8 environment, we got:

```
  Problem 1
    - Root composer.json requires beyondcode/laravel-websockets dev-master -> satisfiable by beyondcode/laravel-websockets[dev-master].
    - beyondcode/laravel-websockets dev-master requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
```

**Comment by rennokki** [comment]
Package version 2.x comes with Laravel 6.x, 7.x and 8.x (which include PHP 8.0 support). Check 2.x branch: https://github.com/beyondcode/laravel-websockets/tree/2.x and the changelog in https://github.com/beyondcode/laravel-websockets/pull/447
