### ISSUE TITLE
I'm facing issue on cPanel A2 host server Websocket Connection error

### ISSUE THREAD

**Issue by iampapaisarkar** [beyondcode/laravel-websockets#628]
In my local machine its work really perfectly but when I push all my work on cpanel then websockets not working .. its getting error "failed: Error during WebSocket handshake: Unexpected response code: 404" 

please help me.. quick guide

Here is website link, here you can check error
https://slchats.com/chats

![sss](https://user-images.githubusercontent.com/50805880/101136117-d97c5180-3632-11eb-85bb-ad9e817abab5.png)

**Comment by rennokki** [comment]
It's recommended to not use shared hosting.
