### ISSUE TITLE
Dashboard not showing any Events

### ISSUE THREAD

**Issue by baderAmmoun** [beyondcode/laravel-websockets#63]
should I configure the frontEnd in case I want to Monitoring  the events on the laravel-websockets dashboard?I mean I need just to ensure that my  event  is broadcasted   I don't want to listen it right now on the front-end  because of  testing purpose

**Comment by stefandanaita** [comment]
No, just make sure you've enabled statistics on your app and installed the package properly (including the migration).

https://docs.beyondco.de/laravel-websockets/1.0/getting-started/installation.html
https://docs.beyondco.de/laravel-websockets/1.0/debugging/dashboard.html#statistics
