### ISSUE TITLE
How to run this package on production (ubuntu + apache2) ?

### ISSUE THREAD

**Issue by MarceloLuis1997** [beyondcode/laravel-websockets#635]
Hi,

I'm using this package in  my dev server and it works well, I run it with the command `php artisan websockets:serve`.
I would like to know how can I run it in my production server.

**Comment by Ghostscypher** [comment]
Well I tried to write an article https://ghostscypher.medium.com/running-laravel-websockets-in-production-def368a84d56 here hopefully it helps you out. Had the exact same problem as you before.

**Comment by MarceloLuis1997** [comment]
Hello @Ghostscypher , i'll take a look, thank you very much!
