### ISSUE TITLE
websocket serve stops working after a minute (ssl)

### ISSUE THREAD

**Issue by aleex1848** [beyondcode/laravel-websockets#64]
laravel/framework 5.7.19
beyondcode/laravel-websockets 1.0.3
php-fpm 7.2.12

I got everything working with ssl by following the very nice documentation.
Now when i start the websocket server everything seems to be working fine:

- Dashboard connects and shows all subscriptions and so on
- Client Browser subscribes to privat channel using laravel echo 
- Broadcast-Event reaches the client browser.
- All good.

But after a minute it stops working. Dashboard looses connection. Reconnect results in:
- Dashboard shows "Channels current state is unavailable".
- Browser console says "WebSocket opening handshake timed out".
- artisan output is: 
´
Connection id 17030417.641664442 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"17030417.641664442\",\"activity_timeout\":30}"}
Connection id 17030417.641664442 closed.`

Are there any debugging possibilities? I can't see nothing atm...thanks !

**Comment by srirag1987** [comment]
I am using Let's Encrypt SSL configured in a project, the same happens in mine also. WebSocket opening handshake timed out after certain period of time.


  'local_cert' => "/etc/letsencrypt/live/domain.com/fullchain.pem",
        /*
         * Path to local private key file on filesystem in case of separate fil$
         * certificate (local_cert) and private key.
         */
         'local_pk' => "/etc/letsencrypt/live/domain.com/privkey.pem",

**Comment by stayallive** [comment]
^ are you using a seperate app for just the websockets by any chance?

The statistics use the Broadcasting features of Laravel, if that's not correctly configured (which it could possibly be on a seperated instance) it will crash on not being able to broadcast the event (to itself).

**Comment by bam-tbf** [comment]
I had the same issue as @aleex1848 and the same fix worked. It would be nice to know what is causing the problem so I could reenable statistics. It was a very confusing bug! Thanks for the suggestion.

**Comment by stayallive** [comment]
It would be interesting to see a bit more context about the actual exception.

https://github.com/laravel/framework/blob/5459ac15b56cdee8e176827ddbb30357119ceabb/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php#L117-L119

Looking at how or why it's thrown it can be for two reasons, it either got an error while sending (which can also show up in the `php artisan websockets:serve` log) or could not connect at all.

However, disabling the statistics works and I assume that normal broadcasting events (again, assuming you are using https://laravel.com/docs/5.7/broadcasting in your app, correct me if wrong) are working... I'm guessing the server is somehow not happy with the event and the exception should contain the error response or the `php artisan websockets:serve` output shows an exception before it exits.

**Comment by bam-tbf** [comment]
@stayallive Thanks for helping to investigate/resolve this.

To answer your question, yes other event broadcasting is working in the app without problem.

The only exceptions/errors that showed up were the BroadcastExceptions in the laravel server logs, just like aleex1848 showed above, while the CPU maxed out at 100% for the  ```php artisan websockets:serve``` process until I killed it. No error/exception in ```php artisan websockets:serve``` log file. 

Let me know if I can provide any other information.

---

Thanks for the suggestion on WebsocketsServiceProvider. Good to know that is possible, but may be more/more involved than most users would need/want. 

Also good to know about /app(s) being required for Pusher. That's fair. You are correct that I could use the same domain and port 6001 for SSL for the websocket. I was hoping to only have to have ports 80/443 open on the server for security, but its not too bad to have 6001 also open.

**Comment by stayallive** [comment]
@bam-tbf no problem ofcourse, however I'm a bit out of idea's on why this might be happening since it looks like a "regular" broadcast message seems to get stuck except it always is the statistics-updated one (?), which is not very special/big/heavy... if anyone has some ideas on how to reproduce or what might cause this would be great!

Some more context around the Exception (from Sentry etc. for example) could possibly also help to see what the heck is going on... but really not sure right now.

**Comment by bam-tbf** [comment]
Ok, thanks. We will just leave stats disabled for now. Hopefully someone else will have information or ideas on what the cause or contributing factors are.

**Comment by kotenarok** [comment]
Any updates on this issue?
