### ISSUE TITLE
laravel-websockets

### ISSUE THREAD

**Issue by waqas837** [beyondcode/laravel-websockets#641]
1.Undefined constant "BeyondCode\LaravelWebSockets\Console\Commands\SIGTERM"

while runing this command   php artisan websocket:serve

2.also issue of connecting.
![websocket does'nt connect](https://user-images.githubusercontent.com/73779175/102453801-c6b84280-405e-11eb-9e01-993603914363.jpg)
I am just a begginner,please help

**Comment by Ghostscypher** [comment]
I believe it's the same issue as #639

**Comment by Ghostscypher** [comment]
> 
> 
> 1.Undefined constant "BeyondCode\LaravelWebSockets\Console\Commands\SIGTERM"
> 
> while runing this command php artisan websocket:serve
> 
> 2.also issue of connecting.
> ![websocket does'nt connect](https://user-images.githubusercontent.com/73779175/102453801-c6b84280-405e-11eb-9e01-993603914363.jpg)
> I am just a begginner,please help

I believe it's the same thing as issue #639

**Comment by waqas837** [comment]
i have php 8.00 but i am stuck here

**Comment by waqas837** [comment]
thanks  sir
