### ISSUE TITLE
Disable TLS 1.0/1.1

### ISSUE THREAD

**Issue by sdousley** [beyondcode/laravel-websockets#646]
Is it at all possible to disable TLS 1.0 and 1.1.

PCI scans have started to fail due to TLS 1.0 being supported by this package, as such, it would be great to only support TLS 1.2+ (with maybe an option to configure the minimum supported version should 1.2 become deprecated also).

**Comment by CodeJunkieio** [comment]
If all else fails, you can fork the repo :D
