### ISSUE TITLE
Multiple apps not working

### ISSUE THREAD

**Issue by issamahwach** [beyondcode/laravel-websockets#647]
I have two Laravel applications hosted on the same server (master, client) , and I'm trying to make them both listen to the same Websockets server.

The master app is configured correctly and it's receiving the events, but I can't make this happen with the client.

Master configuration:

  ```
 'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
```

        [
            'id' => 'client',
            'name' => 'client1',
            'key' => 'clientkey',
            'secret' => 'clientsecret',
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],

Client configuration on the separated app (bootstrap.js):

```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    forceTLS: false,
    wsHost: 'master.websockets11.com',
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    enabledTransports: ['ws', 'wss'],
});
```

It's completely working on the master app. sending and receiving the events, and I can see when the client connects to the channel and (subscribes), but no events is showing on the client app.

**Comment by CodeJunkieio** [comment]
@issamahwach  If you try to run both at the same time they will both be trying to run on port 6001. I'm not sure if this is recommended or even possible but perhaps you can change the port on one of the instances? If you're using nginx you may be able to proxy the port on a specific (sub)/domain. As far as a single domain from a single server, I don't believe you can have 2 open at the same time

I would try something like
wss1.domain.com -> direct to backend on port 6001
wss2.domain.com -> proxy 6001 to 6002 -> to backend

Hope that gives you some better insight
