### ISSUE TITLE
Does this package enforce to use Facade when integrating with Lumen?

### ISSUE THREAD

**Issue by ssi-anik** [beyondcode/laravel-websockets#649]
I checked the service provider and there it uses `Route` and `Gate` facade. And within the code, it uses `Cache` Facade as well. Can't those be replaced with the underlying accessors? Doing so it'll let Lumen users use the package without enabling the facade.

Just a thought. Cause developers may want to integrate the package with Lumen.

**Comment by eleimt** [comment]
Hello
I want have using this package with Lumen.

**Comment by ssi-anik** [comment]
The maintainers haven't answered it. And, it's not possible. As there are so many facades used within the codebase.

**Comment by ssi-anik** [comment]
@rennokki I can help. Hopefully within a few days. hmu.

**Comment by eleimt** [comment]
Sorry, I don't understand English well. Tell me this package will support Lumen?

**Comment by ssi-anik** [comment]
in your bootstrap/app.php, if you enable facade then it will support.

**Comment by eleimt** [comment]
Append manual in Readme for Lumen, please. Thanks.
