### ISSUE TITLE
Connection count is not accurate after reset

### ISSUE THREAD

**Issue by nerg4l** [beyondcode/laravel-websockets#65]
The current implementation of `ChannelManager::getConnectionCount` in `ArrayChannelManager` counts the active connections per channel. In my opinion this does not show the real connection count. 

For example:

- a client *may not* connect to any channel which is calculated as `0` connection
- a client *may* connect to `n` channel which is calculated as `n` connections

Maybe it is not relevant, but Pusher connections counted per WebSocket connections not per channel connections. This information can be found in their FAQ: https://support.pusher.com/hc/en-us/articles/202092346-How-are-connections-counted-

> A connection is counted as a WebSocket connection to Pusher.

**Comment by stayallive** [comment]
So it's always inaccurate, not only after reset.

I noticed this too, if you start the server and connect to the dashboard to the connection count spikes to 8, which is not very useful information.

**Comment by vesper8** [comment]
It would be nice if the number of current connections was more obvious in the dashboard too, similar to how it is in Pusher.. I mean it could have its own box instead of having to hover over the graph

**Comment by nerg4l** [comment]
This was resolved in #74
