### ISSUE TITLE
WebSocket connection to 'wss://domain/app/ Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by tingan** [beyondcode/laravel-websockets#651]
Hi,

`
the broadcasting is:
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'log' => true,
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => false,
                //'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],
`
the boostrap.js is
`
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: window.location.hostname,
    encrypted: false,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    forceTLS: false,
    enabledTransports: ['ws', 'wss'],
    //disabledTransports: ['sockjs', 'xhr_polling', 'xhr_streaming'],
    //scheme: process.env.MIX_PUSHER_SCHEME
});
`

even i set forTLS to false and encryption to false, the connection is still wss instead ws (but the site is https instead of http).  but i enable TLS and set up the letsencrypt fulchain and privkey( copied to storage folder), it also fails.  please help me, i stuck for whole day already. sometimes, the error is failed: Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH . thx.

It seems many users have similar problem, if possible, please provide some example implementation code or gist. thx.

**Comment by Ghostscypher** [comment]
Can you try removing wss port and also ws from enabled transport and check if that works

**Comment by tingan** [comment]
Hi
I think the best way is to use nginx reverse proxy. but also didn't get it working. please provide complete documents for this. .g. how nginx configuration is and how bootstrap.js echo part and the broadcasting.php pusher part settings. I google a lots, seems many users stuck with it. it also works fine locally but not in prouction.

**Comment by tingan** [comment]
Hi,
I tried your suggestion, there is no error in chrome console, but laravel error:
2021-01-08 09:55:36] production.ERROR: Failed to connect to Pusher. {"userId":3,"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Failed to connect to Pusher. at vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:122)

**Comment by Ghostscypher** [comment]
I thought you were actually testing it locally if this is the case then you can check out this issue #635

**Comment by tingan** [comment]
hi,
i finally get it working after 2 days struggling. I didn't use nginx reverse proxy. i use the laravel websockets serve 6001 with ssl . copied from letsencrypt to laravel storage folder and chown to make it accessible.
`
broadcasting.php
'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],

`
the bootstrap.js
`
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: process.env.MIX_PUSHER_HOST, //window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    forceTLS: true,
    enabledTransports: ['ws','wss'],
});

`
it's important to add wssPort as it serve with wss instead of ws. thanks.

**Comment by Ghostscypher** [comment]
@tingan I am glad it worked

**Comment by jameshappykang** [comment]
@tingan I am glad it worked for you. But I still have some problem.
Could you show about how to set config/websockets.php. 
below is my  websocket.php 
please let me know is there anywhere need to be revising.
`<?php

use BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize;

return [

    /*
     * Set a custom dashboard configuration
     */
    'dashboard' => [
        'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
    ],

    /*
     * This package comes with multi tenancy out of the box. Here you can
     * configure the different apps that can use the webSockets server.
     *
     * Optionally you specify capacity so you can limit the maximum
     * concurrent connections for a specific app.
     *
     * Optionally you can disable client events so clients cannot send
     * messages to each other via the webSockets.
     */
    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],

    /*
     * This class is responsible for finding the apps. The default provider
     * will use the apps defined in this config file.
     *
     * You can create a custom provider by implementing the
     * `AppProvider` interface.
     */
    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,

    /*
     * This array contains the hosts of which you want to allow incoming requests.
     * Leave this empty if you want to accept requests from all hosts.
     */
    'allowed_origins' => [
        //
    ],

    /*
     * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
     */
    'max_request_size_in_kb' => 250,

    /*
     * This path will be used to register the necessary routes for the package.
     */
    'path' => 'laravel-websockets',

    /*
     * Dashboard Routes Middleware
     *
     * These middleware will be assigned to every dashboard route, giving you
     * the chance to add your own middleware to this list or change any of
     * the existing middleware. Or, you can simply stick with this list.
     */
    'middleware' => [
        'web',
        Authorize::class,
    ],

    'statistics' => [
        /*
         * This model will be used to store the statistics of the WebSocketsServer.
         * The only requirement is that the model should extend
         * `WebSocketsStatisticsEntry` provided by this package.
         */
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,

        /**
         * The Statistics Logger will, by default, handle the incoming statistics, store them
         * and then release them into the database on each interval defined below.
         */
        'logger' => BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger::class,

        /*
         * Here you can specify the interval in seconds at which statistics should be logged.
         */
        'interval_in_seconds' => 60,

        /*
         * When the clean-command is executed, all recorded statistics older than
         * the number of days specified here will be deleted.
         */
        'delete_statistics_older_than_days' => 60,

        /*
         * Use an DNS resolver to make the requests to the statistics logger
         * default is to resolve everything to 127.0.0.1.
         */
        'perform_dns_lookup' => false,
    ],

    /*
     * Define the optional SSL context for your WebSocket connections.
     * You can see all available options at: http://php.net/manual/en/context.ssl.php
     */
    'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => "D:/xampp/ssl/ifa/certificate.pem",

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => "D:/xampp/ssl/ifa/private.key",

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => null,
    ],

    /*
     * Channel Manager
     * This class handles how channel persistence is handled.
     * By default, persistence is stored in an array by the running webserver.
     * The only requirement is that the class should implement
     * `ChannelManager` interface provided by this package.
     */
    'channel_manager' => \BeyondCode\LaravelWebSockets\WebSockets\Channels\ChannelManagers\ArrayChannelManager::class,
];
`

**Comment by tingan** [comment]
my websockets.php is always the same except one trivial difference: 
  'enable_client_messages' => true,

one key is that i copied the letsenccrypt privkey and public key files from /etc/  original default folder to laravel storage folder.

**Comment by mahdi4187** [comment]
check open this port

**Comment by sirdoro1** [comment]
@mahdi4187 were you able to make it work? I am having exact same issue.

**Comment by sirdoro1** [comment]
I have not been able to get this stuff to work. here is my 

`broadcasting.php`

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Broadcaster
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    | Supported: "pusher", "ably", "redis", "log", "null"
    |
    */

    'default' => env('BROADCAST_DRIVER', 'null'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],

        'ably' => [
            'driver' => 'ably',
            'key' => env('ABLY_KEY'),
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

        'log' => [
            'driver' => 'log',
        ],

        'null' => [
            'driver' => 'null',
        ],

    ],

];
```

`bootstrap.js`

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    forceTLS: true,
    enabledTransports: ['ws','wss'],
});
```
`.env`

```
PUSHER_APP_ID=local
PUSHER_APP_KEY=local
PUSHER_APP_SECRET=local
PUSHER_APP_CLUSTER=mt1
MIX_PUSHER_HOST=mydomain.com

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT="/var/www/html/mydomain.com/storage/fullchain.pem"
LARAVEL_WEBSOCKETS_SSL_LOCAL_PK="/var/www/html/mydomain.com/storage/privkey.pem"

```

I copied local_cert and local_pk from /etc to my laravel package storage. 

Thanks

**Comment by Ghostscypher** [comment]
@sirdoro1 the best option so far was to use a reverse proxy, I'd highly recommend you try that, this way stripping of SSL certificates can be done by the server. In short run Laravel websockets on localhost, then set up a reverse proxy, either using nginx or apache mod_proxy.

**Comment by sirdoro1** [comment]
Thanks @Ghostscypher for replying.

Please do you have any guide on using reverse proxy I am using VPS server

**Comment by Ghostscypher** [comment]
@sirdoro1 here is an article I wrote a while back, it should hopefully point you in the right directionRunning Laravel Websockets in production https://ghostscypher.medium.com/running-laravel-websockets-in-production-def368a84d56
In case of anything kindly reach out. I'll be happy to help

**Comment by sirdoro1** [comment]
@Ghostscypher  thanks, I checked out the article but I am still having issues here is my configurations

`websockets-default.conf`
```
<VirtualHost _default_:6001>
    ServerName ws.mysub.domain.co.uk  // also used it as "mysub.domain.co.uk"
        ProxyPass "/app/" "ws://127.0.0.1:6000/app/"
        ProxyPass "/apps/" "http://127.0.0.1:6000/apps/"
</VirtualHost>
```

 //Listen 6001  <- when I added this "Listen 6001" it kept giving error that i was not able to restart apache2 until i removed it because I am using centOS.

`broadcsting.php`

```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'host' => 'mysub.domain.co.uk', //also tried '120.0.0.1'
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'port' => 6001,
                'scheme' => 'https',
            ],
        ],
```

`boostrap.js`

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: 'mysub.domain.co.uk', //also tried '120.0.0.1'
    encrypted: false,
    wssPort: 6001,
    disableStats: true,
    forceTLS: false,
    enabledTransports: ['ws','wss'],
    disabledTransports: ['sockjs', 'xhr_polling', 'xhr_streaming']
});
```

`websockets.conf`

```
[program:websockets]
command=sudo php /var/www/html/mysub.domain.co.uk/artisan websockets:serve --host 127.0.0.1 --port 6000
numprocs=1
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/html/mysub.domain.co.uk/storage/logs/websockets.log
```

supervisor command is working fine

but still having the following errors from browsers
Firefox : The connection to wss://mysub.domain.co.uk:6001/app/local?protocol=7&client=js&version=7.0.3&flash=false was interrupted while the page was loading.

Chrome: app.js:2 WebSocket connection to 'wss://mysub.domain.co.uk:6001/app/local?protocol=7&client=js&version=7.0.3&flash=false' failed: 

Thanks for your time.

**Comment by Ghostscypher** [comment]
I believe the error is because mod proxy has been disabled. I'd your proxy module enabled? What error do you get when you try to run apache2? Kindly paste it here `journalctl -xe`

**Comment by sirdoro1** [comment]
[root@localhost ~]# service apache2 restart
Redirecting to /bin/systemctl restart apache2.service
Failed to restart apache2.service: Unit not found.
[root@localhost ~]# journalctl -xe
Apr 14 23:56:04 localhost.localdomain sshd[19919]: input_userauth_request: inval
Apr 14 23:56:04 localhost.localdomain sshd[19919]: pam_unix(sshd:auth): check pa
Apr 14 23:56:04 localhost.localdomain sshd[19919]: pam_unix(sshd:auth): authenti
Apr 14 23:56:05 localhost.localdomain sshd[19932]: Failed password for root from
Apr 14 23:56:06 localhost.localdomain unix_chkpwd[19937]: password check failed
Apr 14 23:56:06 localhost.localdomain sshd[19932]: pam_succeed_if(sshd:auth): re
Apr 14 23:56:06 localhost.localdomain sshd[19919]: Failed password for invalid u
Apr 14 23:56:06 localhost.localdomain sshd[19919]: Received disconnect from 183.
Apr 14 23:56:06 localhost.localdomain sshd[19919]: Disconnected from 183.66.119.
Apr 14 23:56:06 localhost.localdomain sshd[19935]: Invalid user yyy from 103.127
Apr 14 23:56:06 localhost.localdomain sshd[19935]: input_userauth_request: inval
Apr 14 23:56:06 localhost.localdomain sshd[19935]: pam_unix(sshd:auth): check pa
Apr 14 23:56:06 localhost.localdomain sshd[19935]: pam_unix(sshd:auth): authenti
Apr 14 23:56:07 localhost.localdomain sshd[19932]: Failed password for root from
Apr 14 23:56:07 localhost.localdomain unix_chkpwd[19938]: password check failed
Apr 14 23:56:07 localhost.localdomain sshd[19932]: pam_succeed_if(sshd:auth): re
Apr 14 23:56:08 localhost.localdomain sshd[19935]: Failed password for invalid u
Apr 14 23:56:08 localhost.localdomain sshd[19935]: Received disconnect from 103.
Apr 14 23:56:08 localhost.localdomain sshd[19935]: Disconnected from 103.127.108
Apr 14 23:56:10 localhost.localdomain sshd[19932]: Failed password for root from
Apr 14 23:56:10 localhost.localdomain sshd[19932]: Received disconnect from 218.
Apr 14 23:56:10 localhost.localdomain sshd[19932]: Disconnected from 218.92.0.20
Apr 14 23:56:10 localhost.localdomain sshd[19932]: PAM 2 more authentication fai
lines 1256-1278/1278 (END)
Apr 14 23:54:34 localhost.localdomain sshd[19860]: Received disconnect from 106.53.239.28 port 55524:11: Bye Bye [preauth]
Apr 14 23:54:34 localhost.localdomain sshd[19860]: Disconnected from 106.53.239.28 port 55524 [preauth]
Apr 14 23:54:49 localhost.localdomain unix_chkpwd[19866]: password check failed for user (root)
Apr 14 23:54:49 localhost.localdomain sshd[19862]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=218.92.0.205  user=root
Apr 14 23:54:49 localhost.localdomain sshd[19862]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
Apr 14 23:54:50 localhost.localdomain sshd[19864]: reverse mapping checking getaddrinfo for 11-55-5-191.viartelecom.com.br [191.5.55.11] failed - POSSIBLE BREAK-IN ATTEMPT!
Apr 14 23:54:50 localhost.localdomain sshd[19864]: Invalid user toth from 191.5.55.11 port 44057
Apr 14 23:54:50 localhost.localdomain sshd[19864]: input_userauth_request: invalid user toth [preauth]
Apr 14 23:54:50 localhost.localdomain sshd[19864]: pam_unix(sshd:auth): check pass; user unknown
Apr 14 23:54:50 localhost.localdomain sshd[19864]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=191.5.55.11
Apr 14 23:54:51 localhost.localdomain sshd[19862]: Failed password for root from 218.92.0.205 port 61187 ssh2
Apr 14 23:54:52 localhost.localdomain unix_chkpwd[19869]: password check failed for user (root)
Apr 14 23:54:52 localhost.localdomain sshd[19862]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
Apr 14 23:54:53 localhost.localdomain sshd[19864]: Failed password for invalid user toth from 191.5.55.11 port 44057 ssh2
Apr 14 23:54:53 localhost.localdomain sshd[19864]: Received disconnect from 191.5.55.11 port 44057:11: Bye Bye [preauth]
Apr 14 23:54:53 localhost.localdomain sshd[19864]: Disconnected from 191.5.55.11 port 44057 [preauth]
Apr 14 23:54:54 localhost.localdomain sshd[19862]: Failed password for root from 218.92.0.205 port 61187 ssh2
Apr 14 23:54:54 localhost.localdomain unix_chkpwd[19870]: password check failed for user (root)
Apr 14 23:54:54 localhost.localdomain sshd[19862]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
Apr 14 23:54:56 localhost.localdomain sshd[19862]: Failed password for root from 218.92.0.205 port 61187 ssh2
Apr 14 23:54:56 localhost.localdomain sshd[19862]: Received disconnect from 218.92.0.205 port 61187:11:  [preauth]
Apr 14 23:54:56 localhost.localdomain sshd[19862]: Disconnected from 218.92.0.205 port 61187 [preauth]
Apr 14 23:54:56 localhost.localdomain sshd[19862]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=218.92.0.205  user=root
Apr 14 23:55:01 localhost.localdomain crond[27660]: (cd) ERROR (getpwnam() failed)
Apr 14 23:55:01 localhost.localdomain systemd[1]: Started Session 72996 of user root.
-- Subject: Unit session-72996.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-72996.scope has finished starting up.
--
-- The start-up result is done.
Apr 14 23:55:23 localhost.localdomain sshd[19867]: Accepted password for root from 197.210.84.157 port 60479 ssh2
Apr 14 23:55:23 localhost.localdomain systemd[1]: Started Session 72997 of user root.
-- Subject: Unit session-72997.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-72997.scope has finished starting up.
--
-- The start-up result is done.
Apr 14 23:55:23 localhost.localdomain systemd-logind[954]: New session 72997 of user root.
-- Subject: A new session 72997 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-- A new session with the ID 72997 has been created for the user root.
--
-- The leading process of the session is 19867.
Apr 14 23:55:23 localhost.localdomain sshd[19867]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 14 23:55:48 localhost.localdomain polkitd[1581]: Registered Authentication Agent for unix-process:19899:823668264 (system bus name :1.146367 [/usr/bin/pkttyagent --notify-fd 5 --fallbac
Apr 14 23:55:48 localhost.localdomain polkitd[1581]: Unregistered Authentication Agent for unix-process:19899:823668264 (system bus name :1.146367, object path /org/freedesktop/PolicyKit1/A
Apr 14 23:55:50 localhost.localdomain sshd[19915]: Invalid user jenkins from 198.211.101.119 port 53470
Apr 14 23:55:50 localhost.localdomain sshd[19915]: input_userauth_request: invalid user jenkins [preauth]
Apr 14 23:55:50 localhost.localdomain sshd[19915]: pam_unix(sshd:auth): check pass; user unknown
Apr 14 23:55:50 localhost.localdomain sshd[19915]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=198.211.101.119
Apr 14 23:55:52 localhost.localdomain sshd[19915]: Failed password for invalid user jenkins from 198.211.101.119 port 53470 ssh2
Apr 14 23:55:52 localhost.localdomain sshd[19915]: Received disconnect from 198.211.101.119 port 53470:11: Bye Bye [preauth]
Apr 14 23:55:52 localhost.localdomain sshd[19915]: Disconnected from 198.211.101.119 port 53470 [preauth]
Apr 14 23:55:55 localhost.localdomain sshd[19917]: Invalid user user from 45.15.143.141 port 43252
Apr 14 23:55:55 localhost.localdomain sshd[19917]: input_userauth_request: invalid user user [preauth]
Apr 14 23:55:55 localhost.localdomain sshd[19917]: pam_unix(sshd:auth): check pass; user unknown
Apr 14 23:55:55 localhost.localdomain sshd[19917]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=45.15.143.141
Apr 14 23:55:58 localhost.localdomain sshd[19917]: Failed password for invalid user user from 45.15.143.141 port 43252 ssh2
Apr 14 23:55:58 localhost.localdomain sshd[19917]: Received disconnect from 45.15.143.141 port 43252:11: Normal Shutdown, Thank you for playing [preauth]
Apr 14 23:55:58 localhost.localdomain sshd[19917]: Disconnected from 45.15.143.141 port 43252 [preauth]
Apr 14 23:56:01 localhost.localdomain crond[27660]: (cd) ERROR (getpwnam() failed)
Apr 14 23:56:01 localhost.localdomain systemd[1]: Started Session 72998 of user root.
-- Subject: Unit session-72998.scope has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit session-72998.scope has finished starting up.
--
-- The start-up result is done.
Apr 14 23:56:01 localhost.localdomain CROND[19923]: (root) CMD (cd  /var/www/html/asifor.nshub.co.uk && php artisan schedule:run >> /dev/null 2>&1)
Apr 14 23:56:04 localhost.localdomain unix_chkpwd[19934]: password check failed for user (root)
Apr 14 23:56:04 localhost.localdomain sshd[19932]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=218.92.0.205  user=root
Apr 14 23:56:04 localhost.localdomain sshd[19932]: pam_succeed_if(sshd:auth): requirement "uid >= 1000" not met by user "root"
Apr 14 23:56:04 localhost.localdomain sshd[19919]: Invalid user nagios from 183.66.119.66 port 18575
Apr 14 23:56:04 localhost.localdomain sshd[19919]: input_userauth_request: invalid user nagios [preauth]
Apr 14 23:56:04 localhost.localdomain sshd[19919]: pam_unix(sshd:auth): check pass; user unknown
Apr 14 23:56:04 localhost.localdomain sshd[19919]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=183.66.119.66
Apr 14 23:56:05 localhost.localdomain sshd[19932]: Failed password for root from 218.92.0.205 port 52082 ssh2
Apr 14 23:56:06 localhost.localdomain unix_chkpwd[19937]: password check failed for user (root)

if the websockets.conf is with Listen 6001 and restarting apache 'service apache2 restart' comes with error  
**Redirecting to /bin/systemctl restart apache2.service
Failed to restart apache2.service: Unit not found.**
```
Listen 6001

<VirtualHost _default_:6001>
    ServerName ws.asifor.nshub.co.uk
    ProxyPass "/app/" "ws://127.0.0.1:6000/app/"
    ProxyPass "/apps/" "http://127.0.0.1:6000/apps/"
</VirtualHost>
```

but if it is configured as 
```
<VirtualHost _default_:6001>
    ServerName ws.asifor.nshub.co.uk
    ProxyPass "/app/" "ws://127.0.0.1:6000/app/"
    ProxyPass "/apps/" "http://127.0.0.1:6000/apps/"
</VirtualHost>
```
the apache restarts properly but the websockets still wont work.

**Comment by Ghostscypher** [comment]
Nice some progress, let's do one more test
1. Make sure that apache2 is running the websockets `netstat -tulpn | grep 6001`
2. Make sure that you allow TCP traffic through firewall on port 6001 (very important)
Depending on the OS you are using, google your OS firewall command, might probably use iptables or firewallcmd

**Comment by Ghostscypher** [comment]
As I can see also you are using httpd not apache2 so your command to restart the service will probably be `systemctl restart https` or `service httpd restart`

**Comment by sirdoro1** [comment]
I have been able to make Listen on port 8443

Listen 8443
<VirtualHost _default_:8443>
    ServerName ws.asifor.nshub.co.uk
        ProxyPass "/app/" "ws://127.0.0.1:6000/app/"
        ProxyPass "/apps/" "http://127.0.0.1:6000/apps/"
</VirtualHost>

**Comment by Ghostscypher** [comment]
@sirdoro1 
Nice, now we check
1. Is the server running on that port
2. Have you exposed that port since by default it is usually blocked from traffic

**Comment by sirdoro1** [comment]
I have check the port 
`tcp   LISTEN     0      128                                                           [::]:8443                                                                      [::]:*`

Tied this in my browser https://asifor.nshub.co.uk:8443/ and I got 
**This site can’t be reached
asifor.nshub.co.uk took too long to respond.**

**Comment by Ghostscypher** [comment]
One last change, and it should work 
The reason I changed this is because in order to use ws.asifor.nshub.co.uk you'll need to add that dns record. But let's not get into that
```
Listen 8443
<VirtualHost _default_:8443>
    ServerName asifor.nshub.co.uk # changed this
        ProxyPass "/app/" "ws://127.0.0.1:6000/app/"
        ProxyPass "/apps/" "http://127.0.0.1:6000/apps/"
</VirtualHost>
```

**Comment by Ghostscypher** [comment]
@sirdoro1 after you are done as a security precaution, kindly strip your log above to the except for the apache2 error, update all reference of your domain to some generic name such as mydomain.com this is to protect yourself and your domain identity. I'll do so on my end, after you've solved your issues on your end. Trust me it works, I use it myself.

**Comment by sirdoro1** [comment]
Thanks @Ghostscypher. I still couldnt get it to work.

**Comment by Ghostscypher** [comment]
> Thanks @Ghostscypher. I still couldnt get it to work.

@sirdoro1 hey can you contact me on bngetich69@gmail.com I believe I'll be able yo be of help from there.

**Comment by egbavou** [comment]
Hello everyone I hope you are well.
I have the same error to make the websocket work with ssl.
Nothing I've read here helps.

**Comment by Reof07** [comment]
hola.. tengo el siguiente problema 

app.js:22846 WebSocket connection to 'wss://127.0.0.1:6001/app/5ad9d002d6375a1bd08b?protocol=7&client=js&version=7.4.0&flash=false' failed: WebSocket is closed before the connection is established.
