### ISSUE TITLE
I'm getting this issue when I try to install this plugin on laravel 8.

### ISSUE THREAD

**Issue by pneves001** [beyondcode/laravel-websockets#663]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[2.0.0-beta.1, ..., 2.0.0-beta.29] require php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.
    - beyondcode/laravel-websockets[2.0.0-beta.28, ..., 2.0.0-beta.32] require doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.12.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets ^2.0@beta -> satisfiable by beyondcode/laravel-websockets[2.0.0-beta.1, ..., 2.0.0-beta.32].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Here is my php version. 

PHP 8.0.1 (cli) (built: Jan  8 2021 12:35:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies

"laravel/framework": "^8.12",

**Comment by myckhel** [comment]
Delete `composer.lock.json` and composer install

**Comment by pneves001** [comment]
this is a brand new Laravel install.

**Comment by myckhel** [comment]
did you try the suggestion?

**Comment by rennokki** [comment]
Make sure in your `composer.json` file you have `doctrine/dbal` set to at least `^2.9`, not `^3.x`
