### ISSUE TITLE
How can I catch messages from websockets without custom handler?

### ISSUE THREAD

**Issue by Alexxosipov** [beyondcode/laravel-websockets#664]
I read all the documentation that I found on https://beyondco.de/docs/laravel-websockets/ and I didn't find any information about handling incoming messages from websocket on backend. Is there a way to handle it without custom handler? Or the only way is to create my own handler? If yes, is it possible to create 2 different websockets: one for default Laravel notifications that sending via private channels and another for receiving messages?

**Comment by simonbuehler** [comment]
in  2.x you can use the `BeyondCode\LaravelWebSockets\Events\WebSocketMessageReceive` Event, see https://github.com/beyondcode/laravel-websockets/blob/2.x/docs/advanced-usage/dispatched-events.md

**Comment by yaofong** [comment]
Hi, I could trigger the WebSocketMessageReceive event, however I could not get the payload data. Anyone tried this before?

**Comment by simonbuehler** [comment]
pls show some code and a dump of the `$event`in the handle method

**Comment by yaofong** [comment]
> pls show some code and a dump of the `$event`in the handle method

added to EventServiceProvider.php

`WebSocketMessageReceived::class => [
      HandleWebSocketMessage::class,
  ]`


in HandleWebSocketMessage.php
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Log;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use BeyondCode\LaravelWebSockets\Events\WebSocketMessageReceived;

class HandleWebSocketMessage
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  WebSocketMessageReceived  $event
     * @return void
     */
    public function handle(WebSocketMessageReceived $event)
    {
        Log::info(json_encode($event, true));
    }
}
```

Log:

> local.INFO: {"appId":"CROWDCONNECT","socketId":"915320443.338638457","message":{},"decodedMessage":{"event":"pusher:subscribe","data":{"auth":"","channel":"kitchen-channel"}}}  


From websocket console:
![Screen Shot 2021-02-02 at 4 53 44 PM](https://user-images.githubusercontent.com/107328/106575978-9cbbd080-6577-11eb-8059-33f6a99d72a3.png)

**Comment by simonbuehler** [comment]
ok the key point is the difference between *received* and *sent* messages.

i guess you want to monitor the Messages from the server to the Client?

**Comment by yaofong** [comment]
> ok the key point is the difference between _received_ and _sent_ messages.
> 
> i guess you want to monitor the Messages from the server to the Client?

Yup, I want to get the message sent, and save it to db as a log.

**Comment by Fenslau** [comment]
> > pls show some code and a dump of the `$event`in the handle method
> 
> added to EventServiceProvider.php
> 
> `WebSocketMessageReceived::class => [ HandleWebSocketMessage::class, ]`
> 
> in HandleWebSocketMessage.php
> 
> ```
> <?php
> 
> namespace App\Providers;
> 
> use Illuminate\Support\Facades\Log;
> use Illuminate\Queue\InteractsWithQueue;
> use Illuminate\Contracts\Queue\ShouldQueue;
> use BeyondCode\LaravelWebSockets\Events\WebSocketMessageReceived;
> 
> class HandleWebSocketMessage
> {
>     /**
>      * Create the event listener.
>      *
>      * @return void
>      */
>     public function __construct()
>     {
>         //
>     }
> 
>     /**
>      * Handle the event.
>      *
>      * @param  WebSocketMessageReceived  $event
>      * @return void
>      */
>     public function handle(WebSocketMessageReceived $event)
>     {
>         Log::info(json_encode($event, true));
>     }
> }
> ```
I have the same code but i don't get Log at all :(
I don't know what to do. 
On my own events - all is work, but this dispatched didn't working :(
No log, No info in queue:work 
- Not At All.
2.x
How should I turn it on?
What kind of debug could be?

**Comment by mounir-1999** [comment]
@yaofong, Did you find a solution for your case, I am facing same issue
