### ISSUE TITLE
[2.x] SSL Options verify_peer

### ISSUE THREAD

**Issue by AndyTWF** [beyondcode/laravel-websockets#665]
Hiya,

First of all, thank you for this project - it's been a huge asset to our not-for-profit community to provide a central service for coordinating operations in realtime!

We went through the upgrade from 1.x to 2.x this evening as we were having a few issues around CPU usage and had read on various issues that 2.x resolved these issues. Everything went smoothly except we kept hitting SSL-related issues where the server would give an empty response (curl error 52) when any traffic was directed at it.

We eventually tracked this down to the `verify_peer` option in `websockets.php` (https://github.com/beyondcode/laravel-websockets/blob/2.x/config/websockets.php). If this option was disabled, then everything worked fine - but otherwise any attempt to hit :6001 would result in an empty response.

We don't think it's related to our SSL setup as everything else was talking quite happily over SSL. The SSL config we have is identical to the example provided.

Is there anything we're missing here? :)

**Comment by rennokki** [comment]
Have you also provided a CA certificate? It should work if you enabled verify peer and have a CA certificate set.

**Comment by AndyTWF** [comment]
By this, are you referring to the CA-bundle, or a specific certificate? In our test we pointed it at the bundle on the server :)

**Comment by rennokki** [comment]
In the config, the `ssl` keys' parameters are actually passed to the stream context. You can try and experiment a bit with this wide range of parameters: https://www.php.net/manual/en/context.ssl.php

**Comment by AndyTWF** [comment]
Thank you for your help - think we've managed to resolve this :)
