### ISSUE TITLE
Dispatch message from queue rabbitMQ

### ISSUE THREAD

**Issue by housewi** [beyondcode/laravel-websockets#668]
Hi all, this is a great package but i have a problem:

**.env**
`BROADCAST_DRIVER=pusher
CACHE_DRIVER=file
QUEUE_CONNECTION=rabbitmq
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=memcached

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=12345
PUSHER_APP_KEY=12345
PUSHER_APP_SECRET=12345
PUSHER_APP_CLUSTER=mt1`

**broadcasting.php**
`
return [

    /*
    |--------------------------------------------------------------------------
    | Default Broadcaster
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    | Supported: "pusher", "redis", "log", "null"
    |
    */

    'default' => env('BROADCAST_DRIVER', 'null'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => false,
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],`

**app\Events\RealTimeMessage.php**
`
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * @var string
     */
    public $message;

    /**
     * Create a new event instance.
     *
     * @param string $message
     */
    public function __construct(string $message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return Channel|array
     */
    public function broadcastOn()
    {
     return new Channel('events');
    }
`

**MessageQueue.php**
`

class MessageQueue implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Execute the job.
     *
     * @param $job
     * @param $payload
     * @return void
     */
    public function handle($job, $payload)
    {
        try {
            dump($payload["data"]["message"]);

            $message = $payload["data"]["message"];
            event(new RealTimeMessage($payload["data"]["message"]));
            $job->delete();
        }catch (\Exception $e){
            echo json_encode([
               "code" => $e->getCode(),
               "error" => $e->getMessage()
            ]);
        }

    }
}
`

When i start php artisan queue:work and send a message from broker RabbitMQ i have this error
`
[2021-01-19 11:14:39][] Processing: App\Jobs\MessageQueue@handle
"ciao"
[2021-01-19 11:14:39][] Processed:  App\Jobs\MessageQueue@handle
[2021-01-19 11:14:39][] Processing: App\Jobs\MessageQueue@handle
{"code":0,"error":"Undefined index: message"}[2021-01-19 11:14:39][] Processed:  App\Jobs\MessageQueue@handle`

I don't understand....

**Comment by simonbuehler** [comment]
a dump of the `$payload`would help
