### ISSUE TITLE
Cannot access laravel-websockets dashboard on xampp

### ISSUE THREAD

**Issue by JesseCoinmerce** [beyondcode/laravel-websockets#670]
I'm trying to run laravel-websockets on XAMPP however, I cannot access localhost:8000/laravel-websockets debugging dashboard after running php artisan websockets:serve.

Inside the console I am getting Starting the WebSocket server on port 6001 but when I go to localhost:8000/laravel-websockets it throws 404 not found

laravel/framework: 8.12
PHP 7.3.25 
XAMPP v3.2.4
Pusher v3.4.1

**Comment by MahmoudElsherbeny** [comment]
do you reach the solution ?
