### ISSUE TITLE
How to emit a Laravel event through the WebSocket?

### ISSUE THREAD

**Issue by deepnees** [beyondcode/laravel-websockets#672]
For example, if I'm making a simple mobile chat app I can only receive messages from a WebSocket, but I can't send them to the WebSocket and handle in Laravel? I can use whispering, but in that case, Laravel won't receive it anyway. So the only way to store chat messages on the server is to use HTTP requests for outgoing messages? Am I a right?

In that case, it looks like the power of full duplex WebSocket protocol isn't used. I am using Laravel as a backend API and trying to communicate only with websockets. Is it possible?

**Comment by simonbuehler** [comment]
see the discussion in https://github.com/beyondcode/laravel-websockets/issues/190#issuecomment-516211152

**Comment by deepnees** [comment]
I see there ongoing progress for this topic. Thanks! 
But let me point my question to this. 

Currently it's possible to create own WebsockerHandler. So I manage to hook my trigger message in MyWebsockerHandler.php. In the onMessage() method I can catch incoming messages. My message looks like this:
`{"event":"App\\Events\\SendChatMessage","channel":"presence-App.Chat.Room.1","data":{"message":"test","room_id":1}}`

I fire SendChatMessage event with data then I listen with NewMessageListener again broadcast new message with ChatMessageWasReceived event to others.

Problem is I can't solve/understand authorization part. How to authorize user in this progress? I mean i'm using 
Laravel Sanctum. I can pass token and authorize with that token but Is this proper way to do this.

**Comment by michaelandersen1995** [comment]
Can you try to submit some code?
