### ISSUE TITLE
Allowed memory size error, php artisan websockets:serve stopped working.

### ISSUE THREAD

**Issue by andrewlim7** [beyondcode/laravel-websockets#676]
First of all, when I first received the allowed memory size error was using `128M` in `php.ini`. Then I have updated to `256M`, the problem still exists and the error log messages are listed below. After few days of attempts, I have decided to set `enable_statistics => false`, I no longer receive the memory size error. I think this could be related to dashboard/statistic data. 

I am using Laravel 6.x version and beyondcode 1.9 version.

`Exception "InvalidArgumentException" thrown: "Unable to parse URI: http://:6001/
apps/{app_id}/events?auth_key={CUSTOM_APP_ID}&auth_signature=b6783c7e38a1fb7c30eadcf1
173f06150b9a4fbbbbd8b19f9f21a0933f7aecc3&auth_timestamp=1612288364&auth_version=
1.0&body_md5=ef941a1e172d852c69756c5f6815c43a"`

`PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in Server\Directory\vendor\react\promise-stream\src\functions.php on line 61`

`Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes)`

`at Server\Directory\vendor\react\promise-stream\src\functions.php:61`
    57|     $buffer = '';
    58|
    59|     $promise = new Promise\Promise(function ($resolve, $reject) use ($stream, $maxLength, &$buffer, &$bufferer) {
    60|         $bufferer = function ($data) use (&$buffer, $reject, $maxLength) {
  > 61|             $buffer .= $data;
    62|
    63|             if ($maxLength !== null && isset($buffer[$maxLength])) {
    64|                 $reject(new \OverflowException('Buffer exceeded maximum length'));
    65|             }

`Whoops\Exception\ErrorException: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes)`
 `at Server\Directory\vendor\react\promise-stream\src\functions.php:61`
    57|     $buffer = '';
    58|
    59|     $promise = new Promise\Promise(function ($resolve, $reject) use ($stream, $maxLength, &$buffer, &$bufferer) {
    60|         $bufferer = function ($data) use (&$buffer, $reject, $maxLength) {
  > 61|             $buffer .= $data;
    62|
    63|             if ($maxLength !== null && isset($buffer[$maxLength])) {
    64|                 $reject(new \OverflowException('Buffer exceeded maximum length'));
    65|             }

`Exception trace:`
`1   Whoops\Run::handleError("Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes)", "Server\Directory\vendor\react\promise-stream\src\functions.php") Server\Directory\vendor\filp\whoops\src\Whoops\Run.php:454`

`2   Whoops\Run::handleShutdown()
      [internal]:0
`

**Comment by simonbuehler** [comment]
In your first exception the invalid uri is missing the hostname, check your config file

**Comment by andrewlim7** [comment]
@simonbuehler Do you mean ````broadcast.php```` ? By default, it is working fine, after few hours of idle status. It will crash and show the error above. So not sure why the hostname is missing.

this is part of my code from ````broadcast.php````
````
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
            ],
        ],
````

````bootstrap.js````
````
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true,
    forceTLS: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
	disableStats: true,
	enabledTransports: ['ws', 'wss']
});
````

**Comment by simonbuehler** [comment]
ok, the missing hostname seems to be a follow up error of the memory running out - the only way to find out is to trace memory usage using [xdebug profiling](https://www.netways.de/blog/2018/12/06/tracing-php-memory-usage-with-xdebug/) with statistics on
