### ISSUE TITLE
How do I connect with Laravel Echo broadcaster

### ISSUE THREAD

**Issue by sts-ryan-holton** [beyondcode/laravel-websockets#679]
How do I connect this with Laravel echo? My driver is set to `null` and my config is...

```
/*
|--------------------------------------------------------------------------
| Default Broadcaster
|--------------------------------------------------------------------------
|
| This option controls the default broadcaster that will be used by the
| framework when an event needs to be broadcast. You may set this to
| any of the connections defined in the "connections" array below.
|
| Supported: "pusher", "redis", "log", "null"
|
*/

'default' => env('BROADCAST_DRIVER', 'null'),
```

**Comment by mssayari** [comment]
You can either set this in your `.env` file `BROADCAST_DRIVER=pusher` or remove `BROADCAST_DRIVER` variable from your `.env` and replace `null ` with `pusher` here.

btw, this is not Laravel Echo. Echo is JavaScript library after you install it you can set your config in `resources/js/bootstrap.js`

**Comment by sts-ryan-holton** [comment]
@mssayari I get that, I followed the demo repo example associated with this project and have been replicating the configuration. I'm not planning on using Pusher, but understand this library is essentially a web sockets integration. Here's my set up...

I have a Laravel 8.x API, and it's purely an API, it has all of my routes in there for communicating with my database. I've installed this library, I also have a Nuxt JS front-end with the [Laravel Echo](https://github.com/nuxt-community/laravel-echo) package for Nuxt JS, and am struggling a bit to link that, not sure how it links together, I don't see any errors, but equally, I'm not seeing any events loading on my front end

**Comment by mssayari** [comment]
well, I personally use this with Laravel 8 and vue, I haven't had any problems.

btw, if there is no error, make sure Laravel worker is running and your queue is working or in dev environment you can put `QUEUE_CONNECTION=sync` in your `.env`

**Comment by sts-ryan-holton** [comment]
@mssayari Turns out I was missing one thing...

```
composer require pusher/pusher-php-server "~3.0"
```
