### ISSUE TITLE
Dashboard additional features

### ISSUE THREAD

**Issue by tkrause** [beyondcode/laravel-websockets#68]
As a feature request, it would be amazing to be able to have the debug dashboard in Telescope under a Websocket section instead of yet another hidden login page.

In addition, it would be nice to be able to drill down into the events to see data that was passed, who sent it, and which clients are currently connected etc.

**Comment by kerrsmith** [comment]
> In addition, it would be nice to be able to drill down into the events to see data that was passed, who sent it, and which clients are currently connected etc.

I think this would be a very handy additional feature as it would make looking for bugs much easier if you could see if your broadcast event or notification was sending the data you programmed it to.
