### ISSUE TITLE
[2.x] Large CPU Jumps

### ISSUE THREAD

**Issue by AndyTWF** [beyondcode/laravel-websockets#685]
Hi there,

We’ve been having an issue recently by which, after several hours of operation, the websocket process suddenly jumps to high CPU usage and stays there. In today’s instance, we had about 35 connections on a dual core box that was also running other PHP applications.

We have statistics turned off and when we checked the output (we had debug mode on to try and diagnose the issue) nothing really happened in the period bar a few disconnections and new connections.

We are a bit at a loss as everything is fine for several hours and then it suddenly shoots up and stays there in a short space of time.

Any ideas what might be causing this?

**Comment by simonbuehler** [comment]
Maybe attach some xdebug profiling to it to find the issue?

**Comment by AndyTWF** [comment]
We're not able to attach xdebug unfortunately due to it being in production, though I will attempt to replicate the workload in my docker env and see what I can find!

**Comment by rennokki** [comment]
Found anything?
