### ISSUE TITLE
Is it possible to make the socket server use all cpu cores?

### ISSUE THREAD

**Issue by merijndk** [beyondcode/laravel-websockets#686]
I've done some high volume tests the other day. I managed to get 1 cpu to 100% usage but the other one stays at 0.7%. Is it possible to make the websocket server use both cores?

**Comment by rennokki** [comment]
This is led by the OS, not by the application.

**Comment by merijndk** [comment]
Thanks for the reply. I run miltiple Laravel instances using Apache. They are all multi thread. But when using "php artisan websockets:serve" the websocket server is single thread (Because php artisan is single thread?). So how could I fire up the websocket server multi threaded?

**Comment by rennokki** [comment]
If you give one process a limit of 1 thread, it will stick with it. Or, in some other instances, you can spawn new children by executing new processes along the way PHP. So there is no way of multi-threading it other than spawning multiple processes (in this case you need to use 2.x).

Apache has nothing to do with the websockets process either, unless you proxy it through nginx/apache.
