### ISSUE TITLE
HELP: The correct Ngnix configuration is?

### ISSUE THREAD

**Issue by blakeyman** [beyondcode/laravel-websockets#689]
I can get this package working (locally) but I have never had any success in running on a production server.
Can anybody help out here?

As per official documentation (and I guess for most solutions) I want to run on the same server and same Ngnix instance.
I want it to be secure (SSL should just be standard now, especially since LetsEncrypt is easliy available)

This therefore seems the obvious starting point
https://beyondco.de/docs/laravel-websockets/basic-usage/ssl#same-location-for-websockets-and-web-contents

So following the example
```
server {
  # Your default configuration comes here...
```

And given that the default configuration is
https://laravel.com/docs/5.8/deployment#nginx

I use this on my server but get the obligatory error the users of this package are familiar with...

`Firefox can't establish a connection to the server at wss://staging.gigsforstreamers.com:6001/app/c852e217e8230dc977b3?protocol=7&client=js&version=7.0.3&flash=false. app.js:27069:15
The connection to wss://staging.gigsforstreamers.com:6001/app/c852e217e8230dc977b3?protocol=7&client=js&version=7.0.3&flash=false was interrupted while the page was loading.`

I would so *love* for this package to work!

This is the ngnix config I'm trying (and to no avail)

```
`# Ploi Webserver Configuration, do not remove!
include /etc/nginx/ploi/staging.gigsforstreamers.com/before/*;

server {
    listen 80;
    listen [::]:80;

    root /home/ploi/staging.gigsforstreamers.com/public;
    server_name staging.gigsforstreamers.com;

    include /etc/nginx/ssl/staging.gigsforstreamers.com;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    index index.php index.html;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    # Ploi Configuration, do not remove!
    include /etc/nginx/ploi/staging.gigsforstreamers.com/server/*;

    location / {
            try_files $uri $uri/ /index.php?$query_string;
    }

    access_log off;
    error_log  /var/log/nginx/staging.gigsforstreamers.com-error.log error;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }


      location /app/  {
        proxy_pass             http://127.0.0.1:6001;
        proxy_set_header Host  $host;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
}

# Ploi Webserver Configuration, do not remove!
include /etc/nginx/ploi/staging.gigsforstreamers.com/after/*;`
```

**Comment by lovetoast** [comment]
Hey!

Can you post your websockets.php, broadcasting.php, I'll correct those first, and then give a simplified nginx server config.

**Comment by blakeyman** [comment]
`<?php

use BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize;

return [

    /*
     * Set a custom dashboard configuration
     */
    'dashboard' => [
        'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
    ],

    /*
     * This package comes with multi tenancy out of the box. Here you can
     * configure the different apps that can use the webSockets server.
     *
     * Optionally you specify capacity so you can limit the maximum
     * concurrent connections for a specific app.
     *
     * Optionally you can disable client events so clients cannot send
     * messages to each other via the webSockets.
     */
    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],


    /*
     * This class is responsible for finding the apps. The default provider
     * will use the apps defined in this config file.
     *
     * You can create a custom provider by implementing the
     * `AppProvider` interface.
     */
    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,

    /*
     * This array contains the hosts of which you want to allow incoming requests.
     * Leave this empty if you want to accept requests from all hosts.
     */
    'allowed_origins' => [
        //
    ],

    /*
     * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
     */
    'max_request_size_in_kb' => 250,

    /*
     * This path will be used to register the necessary routes for the package.
     */
    'path' => 'laravel-websockets',

    /*
     * Dashboard Routes Middleware
     *
     * These middleware will be assigned to every dashboard route, giving you
     * the chance to add your own middleware to this list or change any of
     * the existing middleware. Or, you can simply stick with this list.
     */
    'middleware' => [
        'web',
        Authorize::class,
    ],

    'statistics' => [
        /*
         * This model will be used to store the statistics of the WebSocketsServer.
         * The only requirement is that the model should extend
         * `WebSocketsStatisticsEntry` provided by this package.
         */
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,

        /**
         * The Statistics Logger will, by default, handle the incoming statistics, store them
         * and then release them into the database on each interval defined below.
         */
        'logger' => BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger::class,

        /*
         * Here you can specify the interval in seconds at which statistics should be logged.
         */
        'interval_in_seconds' => 60,

        /*
         * When the clean-command is executed, all recorded statistics older than
         * the number of days specified here will be deleted.
         */
        'delete_statistics_older_than_days' => 60,

        /*
         * Use an DNS resolver to make the requests to the statistics logger
         * default is to resolve everything to 127.0.0.1.
         */
        'perform_dns_lookup' => env('LARAVEL_WEBSOCKETS_PERFORM_DNS_LOOKUP', true),
    ],

    /*
     * Define the optional SSL context for your WebSocket connections.
     * You can see all available options at: http://php.net/manual/en/context.ssl.php
     */
    'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
        'verify_peer' => false,
    ],

    /*
     * Channel Manager
     * This class handles how channel persistence is handled.
     * By default, persistence is stored in an array by the running webserver.
     * The only requirement is that the class should implement
     * `ChannelManager` interface provided by this package.
     */
    'channel_manager' => \BeyondCode\LaravelWebSockets\WebSockets\Channels\ChannelManagers\ArrayChannelManager::class,
];
`

**Comment by blakeyman** [comment]
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Broadcaster
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    | Supported: "pusher", "redis", "log", "null"
    |
    */

    'default' => env('BROADCAST_DRIVER', 'null'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],

        'ably' => [
            'driver' => 'ably',
            'key' => env('ABLY_KEY'),
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

        'log' => [
            'driver' => 'log',
        ],

        'null' => [
            'driver' => 'null',
        ],

    ],

];
`

**Comment by lovetoast** [comment]
> ```
> 
> return [
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Default Broadcaster
>     |--------------------------------------------------------------------------
>     |
>     | This option controls the default broadcaster that will be used by the
>     | framework when an event needs to be broadcast. You may set this to
>     | any of the connections defined in the "connections" array below.
>     |
>     | Supported: "pusher", "redis", "log", "null"
>     |
>     */
> 
>     'default' => env('BROADCAST_DRIVER', 'null'),
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Broadcast Connections
>     |--------------------------------------------------------------------------
>     |
>     | Here you may define all of the broadcast connections that will be used
>     | to broadcast events to other systems or over websockets. Samples of
>     | each available type of connection are provided inside this array.
>     |
>     */
> 
>     'connections' => [
> 
>         'pusher' => [
>             'driver' => 'pusher',
>             'key' => env('PUSHER_APP_KEY'),
>             'secret' => env('PUSHER_APP_SECRET'),
>             'app_id' => env('PUSHER_APP_ID'),
>             'options' => [
>                 'cluster' => env('PUSHER_APP_CLUSTER'),
>                 'encrypted' => true,
>                 'host' => '127.0.0.1',
>                 'port' => 6001,
>                 'scheme' => 'https',
>                 'curl_options' => [
>                     CURLOPT_SSL_VERIFYHOST => 0,
>                     CURLOPT_SSL_VERIFYPEER => 0,
>                 ],
>             ],
>         ],
> 
>         'ably' => [
>             'driver' => 'ably',
>             'key' => env('ABLY_KEY'),
>         ],
> 
>         'redis' => [
>             'driver' => 'redis',
>             'connection' => 'default',
>         ],
> 
>         'log' => [
>             'driver' => 'log',
>         ],
> 
>         'null' => [
>             'driver' => 'null',
>         ],
> 
>     ],
> 
> ];
> ```

Use scheme http in websockerts.php

Also, can you try the server block code here?

**Comment by blakeyman** [comment]
@lovetoast and remove?
```
'curl_options' => [
      CURLOPT_SSL_VERIFYHOST => 0,
      CURLOPT_SSL_VERIFYPEER => 0,
],```

**Comment by lovetoast** [comment]
> @lovetoast and remove?
> 
> ```
> 'curl_options' => [
>       CURLOPT_SSL_VERIFYHOST => 0,
>       CURLOPT_SSL_VERIFYPEER => 0,
> ],```
> ```

I don't think that is required, no, so it shouldn't make a difference.

**Comment by blakeyman** [comment]
So, yes, my websockets are connecting but now my "Events" are failing...
![Screenshot 2021-02-23 at 19 02 50](https://user-images.githubusercontent.com/3405810/108894103-c9f51f00-7609-11eb-8ca2-c7423c150d3e.png)

**Comment by lovetoast** [comment]
Is perform dns lookup enabled?

**Comment by lovetoast** [comment]
> So, yes, my websockets are connecting but now my "Events" are failing...
> 
> ![Screenshot 2021-02-23 at 19 02 50](https://user-images.githubusercontent.com/3405810/108894103-c9f51f00-7609-11eb-8ca2-c7423c150d3e.png)
> 
> With a `Failed to connect to Pusher.` exception...

Is perform DNS lookup enabled?

**Comment by lovetoast** [comment]
@rennokki I'm open to drafting a new page for a fresh install with nginx, I think that would be a welcome addition to the docs.

**Comment by lovetoast** [comment]
> So, yes, my websockets are connecting but now my "Events" are failing...
> 
> ![Screenshot 2021-02-23 at 19 02 50](https://user-images.githubusercontent.com/3405810/108894103-c9f51f00-7609-11eb-8ca2-c7423c150d3e.png)
> 
> With a `Failed to connect to Pusher.` exception...

       'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
        'host' => '{host}',
        'port' => {public port, is it 443 ?],
		        'encrypted' => true,

        'scheme' => 'https'
            ],
			
			
			Can you set these please and then restart the websocket server?

**Comment by blakeyman** [comment]
@lovetoast so changing

`{host}` to `'mystagingdomain.com'` and port=443 didn't work...

`{host}` to `'mystagingdomain.com'` and port=6001 *DOES* work!

Buy you expected it to work on port 443?

And I agree with your comment to @rennokki.

Some better examples on getting this setup (and what is actaully happening)
I'm quite new to web sockets and given the fact this is utilising Pusher (which IS easy to use) it would be great if this community could be empowered more?

I'm quite happy to contribute, describe my process so perhaps as seasoned, competent users, you (and us all) can  understand why some many newcomers struggle.

Thanks for your help!
:)

**Comment by blakeyman** [comment]
Port on client side is 6001...

So, shall I change that to 443 and then the Pusher port to 443 and if I suspect correctly, this will verify if indeed Ngnix is doing a reverse proxy?

**Comment by lovetoast** [comment]
Yes, I think it is actually connected directly.

1) Block port 6001 on the server
2) make sure when you start the reverse proxy it is using the host option to 127.0.0.1

**Comment by blakeyman** [comment]
So, no - that definitaley isn't working for me...
```wss://mystagingdomain.com/app/c852e217e8230dc977b3?protocol=7&client=js&version=7.0.3&flash=false
[HTTP/1.1 502 Bad Gateway 199ms]```

**Comment by lovetoast** [comment]
OK that's a start, now, can you paste the last 10 lines from /var/log/nginx/error.log please?

I'm happy to look at this if you send me the login details btw.

**Comment by blakeyman** [comment]
[log.txt](https://github.com/beyondcode/laravel-websockets/files/6035695/log.txt)

**Comment by lovetoast** [comment]
```
map $http_upgrade $type {
  default "web";
  websocket "ws";
}

server {
  listen        443 ssl;
  listen        [::]:443 ssl;
  server_name   {host}

root {path to public}
  # Start the SSL configurations
  ssl_certificate     {cert path}
  ssl_certificate_key {key path}
 location / {
    try_files /nonexistent @$type;
  }
    location /app  {
    proxy_pass             http://127.0.0.1:6001;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
  location @ws  {
    proxy_pass             http://127.0.0.1:6001;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}
  ```

Try this please, and reload nginx, hopefully it is evident where things need to be changed.

**Comment by blakeyman** [comment]
I am no expert in Ngnix configuration.
I have a *vague* idea of everything that config is suggesting... 

When I change `try_files $uri $uri/ /index.php?$query_string;` to `try_files /nonexistent @$type;` I now get a 500 server error...

It would appear one has to be a "Ngnix Ninja" to get this working... ;)

**Comment by lovetoast** [comment]
@blakeyman  I am more than happy to take a look if you can send me the access details, but if you cannot, you only need to change the things in curly braces, which is the host, cert, and key.

**Comment by blakeyman** [comment]
@lovetoast I've no idea how to contact you directly via GitHub...

My ngnix config already loads the correct host, cert & keys though...

**Comment by lovetoast** [comment]
@blakeyman Do you have discord? If so, you can send me a link to your profile, or, a private repo here and invite me.

I recognise that error, I think it is trying to pick up a cert in laravel-websockets, are you certain there are no cert and key paths set in the laravel package?

**Comment by blakeyman** [comment]
This is what worked in the end!

```map $http_upgrade $type {
   default "web";
   websocket "ws";
}

server {

    root /home/mydomain.com/public;
    server_name mydomain.com;

    include /etc/nginx/ssl/mydomain.com;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    index index.php index.html;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    location / {
        try_files /nonexistent @$type;
    }
    location @web  {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location @ws  {
    proxy_pass             https://127.0.0.1:6001;
    proxy_set_header Host  $host;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;

    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

    access_log off;
    error_log  /var/log/nginx/mydomain.com-error.log error;

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
    
    
}```
