### ISSUE TITLE
laravel echo not reconnect after fail

### ISSUE THREAD

**Issue by svn292** [beyondcode/laravel-websockets#69]
laravel echo not reconnect after fail
here is my code
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: window.location.hostname,
     wsPort: 6001,
     disableStats: true,
});

**Comment by stephenlake** [comment]
It may be worth while if you actually provided some output and/or input since "my code" is the default copy/paste. Regardless, pretty sure Echo does reconnect automatically by default - it attempts every couple of seconds, but falls back to Pusher if no connection can be made.

Add `enabledTransports: ['ws', 'wss']` to your Echo options to prevent using Pusher as a fallback.

**Comment by stayallive** [comment]
According to [the docs](https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/pusher.html#usage-with-laravel-echo) the `enabledTransports` is not needed. If that is needed you might want to PR that to the docs @stephenlake.

But yes, @svn292 please add some more info. This is how the docs says you should do it and works for a lot of people so we need a bit more context or error output.

**Comment by stephenlake** [comment]
@stayallive You're correct, `enabledTransports` is not **needed**. It's **available** to restrict [transports](https://github.com/pusher/pusher-js#enabledtransports-array) and in turn _**fallback**_ transports which is usually the underlying cause of the client no reconnecting to the correct defined `wsHost`.

See Issue #9 (Laravel Echo will still connect to Pusher as fallback). Echo will reconnect on a potential different transport if a connection fails.

**Comment by svn292** [comment]
its working

**Comment by SVV-team** [comment]
Hi all found great solution ;)

1. Bind to pusher event state_changed
2. When state = disconnected call connect method ;)
3. Enjoy !
```JS
window.Echo.connector.pusher.connection.bind('state_change', function(states) {
  if(states.current === 'disconnected') {
      window.Echo.connector.pusher.connect();
  }
});
```
