### ISSUE TITLE
[1.x] Error on save in HttpStatisticsLogger

### ISSUE THREAD

**Issue by mihob** [beyondcode/laravel-websockets#700]
Maybe I am wrong, but I think there is a bug in the HttpStatisticsLogger class. In the Save function the value "key" is not passed to the post request, only secret is present. 

This leads to an exception in BeyondCode\LaravelWebSockets\Statistics\Http\Middleware\Authorize where the value "key" must be passed since commit e0d8f6a.

**Comment by dannydinges** [comment]
Having the same issue on a recent merge. 

Argument 1 passed to BeyondCode\LaravelWebSockets\Apps\App::findByKey() must be of the type string, null given, called in /home/forge/modexconnect.com/releases/187/vendor/beyondcode/laravel-websockets/src/Statistics/Http/Middleware/Authorize.php on line 11

**Comment by lovetoast** [comment]
Apologies @simonbuehler , you are indeed correct. It does not appear to stop the stats from working though I have a feeling it would stop events being broadcast?

**Comment by bbashy** [comment]
Getting same issue after `Upgrading beyondcode/laravel-websockets (1.9.0 => 1.11.0)`
```
TypeError POST /laravel-websockets/statistics
Argument 1 passed to BeyondCode\LaravelWebSockets\Apps\App::findByKey() must be of the type string, null given,
called in /filepath/releases/16744/vendor/beyondcode/laravel-websockets/src/Statistics/Http/Middleware/Authorize.php on line 11
```

**Comment by lovetoast** [comment]
@rennokki Fastest way is to change this to look at findBySecret, rather than findByKey, correct? If that works shall I make a PR or can you change?

**Comment by rennokki** [comment]
Just opened the PR to revert the change made in https://github.com/beyondcode/laravel-websockets/pull/626
