### ISSUE TITLE
High CPU usage (2.0.0-beta.33)

### ISSUE THREAD

**Issue by Mkaddem97** [beyondcode/laravel-websockets#702]
Very high cpu usage when I updateted to 2.0.0-beta.33 
but when I come back to **2.0.0-beta.32** it is normal.
hier screenshot below show u the difference (btw 25% = 100%)
![Websocket](https://user-images.githubusercontent.com/39562776/109345184-0de95d80-7870-11eb-9d43-e74701e06fc2.png)

**Comment by simonbuehler** [comment]
which channelmanager do you use and could you attach a [xdebug profiler](https://xdebug.org/docs/profiler#starting) to it to find the cpu hog?

**Comment by rennokki** [comment]
@Mkaddem97 Is anything related [to the new features](https://github.com/beyondcode/laravel-websockets/releases/tag/2.0.0-beta.33) ?

**Comment by mpociot** [comment]
I'll close this as we are on beta.36 in the meanwhile. Please reopen this issue if it still exists on the latest beta version.

**Comment by Mkaddem97** [comment]
It was fixed on beta.36.
Thank you so much !
All supports !!
