### ISSUE TITLE
Slight correction on the documentation

### ISSUE THREAD

**Issue by prof-anis** [beyondcode/laravel-websockets#703]
I was trying to install laravel-websockets as a pusher replacement and following the documentation, i was supposed to run `composer require pusher/pusher-php-server "~3.0"` to install the pusher sdk . However, pusher/pusher-php-server "~3.0" does not work with laravel 8 as i was getting a 500 error when laravel echo calls the /broadcasting/auth endpoint with the message `Call to undefined method Pusher\Pusher::presence_auth()`
 This can be fixed by removing the version constraint and allowing composer to use the latest version (in my case i used "~5.0" or using a more specific version that has been tested to work fine with it and updating it as need be.

**Comment by rennokki** [comment]
Use 4.0 or 5.0, 3.0 is deprecated and no longer in use. We try to keep up with the latest updates only.
