### ISSUE TITLE
Pusher API ? How to query channels / users in channels ?

### ISSUE THREAD

**Issue by vesper8** [beyondcode/laravel-websockets#71]
In my current video chat app, as part of the admin dashboard, it's possible to query the rest api which in turn queries Pusher to ask how many users are in which channels without having to actually join the channels on the client side.. like this:

```
    public function channelStats(Request $request)
    {
        $users = User::get(['id', 'name', 'gender'])->keyBy('id');

        $usersInOnline = Pusher::get('/channels/presence-online/users');
        $usersInLobby = Pusher::get('/channels/presence-lobby/users');
        $usersInVideo = Pusher::get('/channels/presence-video/users');

        $onlineUserIds = collect($usersInOnline['result']['users'])->map(function ($user) { return $user['id']; });
        $lobbyUserIds = collect($usersInLobby['result']['users'])->map(function ($user) { return $user['id']; });
        $videoUserIds = collect($usersInVideo['result']['users'])->map(function ($user) { return $user['id']; });

        return [
            'online' => count($usersInOnline['result']['users']),
            'lobby' => count($usersInLobby['result']['users']),
            'video' => count($usersInVideo['result']['users']),
            'users' => [
                'online' => $users->whereIn('id', $onlineUserIds),
                'lobby' => $users->whereIn('id', $lobbyUserIds),
                'video' => $users->whereIn('id', $videoUserIds),
            ],
        ];
    }
```

My question is.. how could I achieve this with laravel-websockets ?

**Comment by mpociot** [comment]
We offer the same API as Pusher does. I think you can even tell the pusher PHP SDK to use a different host, but I’m not sure how. 

See 
https://github.com/beyondcode/laravel-websockets/blob/master/src/Server/Router.php#L37

**Comment by vesper8** [comment]
Hrmm.. so is this API only used internally at the moment?

I tried this

```
        $connection = config('broadcasting.connections.pusher');

        $appId = $connection['app_id'];

        $channels = Pusher::get("/apps/{$appId}/channels");

        dd($channels);
```

That still just returns 'false' as it did before

Then I tried to change the host in the connection

```
        $connection = config('broadcasting.connections.pusher');

        $pusher = new Pusher\Pusher(
            $connection['key'],
            $connection['secret'],
            $connection['app_id'],
            [
                'cluster' => $connection['options']['cluster'],
                'useTLS' => true,
                'curl_options' => $connection['options']['curl_options'],
                'host' => 'socketmaster.dev',
                'port' => '6001',
            ]
        );

        $appId = $connection['app_id'];

        $channels = $pusher->get("/apps/{$appId}/channels");

        dd($channels);
```

again 'false'

And if I try to visit https://socketmaster.dev:6001/apps/1234567890/channels

I get   "error": "Invalid auth signature provided."

So this is meant to be used with laravel echo ? But not really meant to be called from the server side ?

I suppose I can modify the client to make the calls directly then.. @mpociot could you show an example of how it would be called from the client side please? I would also have loved to get it working from the server side.

Thanks!

**Comment by vesper8** [comment]
Got it to work by adding the scheme to https

```
            $pusher = new Pusher\Pusher(
                $connection['key'],
                $connection['secret'],
                $connection['app_id'],
                [
                    'cluster' => $connection['options']['cluster'],
                    'useTLS' => true,
                    'curl_options' => $connection['options']['curl_options'],
                    'host' => 'socketmaster.dev',
                    'port' => '6001',
                    'scheme' => 'https',
                ]
            );

$channels = $pusher->get('/channels')['result']['channels'];
```

It would be useful to know however if it's now possible to query this directly from Laravel Echo and if so.. how ?

**Comment by BTeodor** [comment]
This doesn't work for me. How i can check from php the presence channels?

**Comment by vesper8** [comment]
maybe if you post your code? what error are you getting?

**Comment by BTeodor** [comment]
```
$connection = config( 'broadcasting.connections.pusher' );

    $pusher = new Pusher\Pusher(
        $connection['key'],
        $connection['secret'],
        $connection['key'],
        [
            'cluster' => $connection['options']['cluster'],
            'useTLS'  => TRUE,
            'host'    => 'chat.dev',
            'port'    => '6001',
            'scheme'  => 'https',
            'debug'   => TRUE,
        ]
    );
   
    $channels = $pusher->get_channels();

   dd($channels); // i get false
```

Dashboard and echo is working

**Comment by vesper8** [comment]
what about your curl_options?

```
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
```

and why is your call to get_channels() different from mine?

```
$channels = $pusher->get('/channels');
dd($channels); // gives what?
```

**Comment by BTeodor** [comment]
Thanks. That was the issue.

**Comment by PollieDev** [comment]
Is this still viable?
I'm struggling fetching any data regarding current channels and users.

I have tried all sorts of code such as code blocks provided above and fetching that information through AppProvider & ChannelManagers without success.

**Comment by jefrisingh** [comment]
Hi, for me pusher subscription and broadcast is working fine , but
 $channels = $pusher->get('/channels');
always returns empty!!

I'm using Laravel 8, 
Any help:(

**Comment by shailesh-matariya** [comment]
$connection = config( 'broadcasting.connections.pusher' );
    $pusher = new Pusher\Pusher(
        $connection['key'],
        $connection['secret'],
        $connection['app_id'],
        [
            'cluster' => $connection['options']['cluster'],
            'debug'   => TRUE,
        ]
    );
   
    $channels = $pusher->get_channels();
    dd($channels);

   
   
   This works for me!

**Comment by maynor96** [comment]
> Hi, for me pusher subscription and broadcast is working fine , but $channels = $pusher->get('/channels'); always returns empty!!
> 
> I'm using Laravel 8, Any help:(

It seems that restarting the WebSocket service is necessary after adding the code.
