### ISSUE TITLE
404 Not Found broadcast

### ISSUE THREAD

**Issue by chistel** [beyondcode/laravel-websockets#711]
Stucked on this issue for a few hours, I keep getting the error Illuminate\Broadcasting\BroadcastException: Pusher error: Not Found, and I can't identify what's not found 

I currently run php8 with apache.

below are the configs I use.

For the broadcasting config
`
pusher' => [
			'driver' => 'pusher',
			'key' => env('PUSHER_APP_KEY'),
			'secret' => env('PUSHER_APP_SECRET'),
			'app_id' => env('PUSHER_APP_ID'),
			'options' => [
				'cluster' => env('PUSHER_APP_CLUSTER'),
				'useTLS' => false,
				'encrypted' => true,
				'host' => env('PUSHER_HOST', '127.0.0.1'),
				'port' => env('PUSHER_PORT', 6001),
				'scheme' => env('PUSHER_SCHEME', 'http'),
			],

`

and for the websocket config,
`
'apps' => [
		[
			'id' => env('PUSHER_APP_ID'),
			'name' => env('APP_NAME'),
			'key' => env('PUSHER_APP_KEY'),
			'secret' => env('PUSHER_APP_SECRET'),
			'capacity' => null,
			'enable_client_messages' => false,
			'enable_statistics' => true,
		],
	],

`

the Vue config is 
`

window.Echo = new Echo({
	broadcaster: 'pusher',
	key: process.env.MIX_PUSHER_APP_KEY,
	wsHost: window.location.hostname,
	wsPort: 6001,
	forceTLS: false,
	disableStats: true,
});
`

**Comment by neoacevedo** [comment]
????

**Comment by codetestmg** [comment]
@chistel how you fixed this issue

**Comment by chistel** [comment]
Yea, had to do some configuration on the server

**Comment by codetestmg** [comment]
@chistel  could you please post it here so it helps me to solve it? Thanks @chistel
