### ISSUE TITLE
Channels current state is unavailable! (IIS)

### ISSUE THREAD

**Issue by rezasys2** [beyondcode/laravel-websockets#714]
Hello guys,
I'm using Laravel 7.3 on IIS server - Windows server 2019. I'm getting this error "Channels current state is unavailable" and the cmd stuck on Starting the websocket server on 6001".
My package versions are listed below:
"pusher/pusher-php-server": "~3.0",
"beyondcode/laravel-websockets": "^1.9",

I'm also using Laravel echo and the cert and key file are all set fine.
Websocket config:

     'apps' => [
              [
                  'id' => env('PUSHER_APP_ID'),
                  'name' => env('APP_NAME'),
                  'key' => env('PUSHER_APP_KEY'),
                  'secret' => env('PUSHER_APP_SECRET'),
                  'capacity' => null,
                  'enable_client_messages' => true,
                  'enable_statistics' => true,
                  'encrypted' => true,
              ],
          ],

   
      'ssl' => [

              'local_cert' => 'C:/cer/certify.crt',
      
              'local_pk' => 'C:/cer/private.key',
      
              'passphrase' => '',
      
              'verify_peer' => false,
      
              'allow_self_signed' => true,
    ],
    
    broadcasting config:
    
            'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'useTLS' => true,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
               ]
           ],
       ],

**Comment by criting** [comment]
I have the same issue here. 3 days and still can not make it to work again

**Comment by tupywebteam** [comment]
I have the same issue

**Comment by rezasys2** [comment]
Any experienced users could help us? Or does it have any logs to check?

**Comment by McAlvaro** [comment]
I also have the same problem ... Did anyone find a solution ...?

**Comment by shahpankaj981** [comment]
Facing same issue. Can anyone help?

**Comment by jackbaron** [comment]
I have a same issue. Anyone find a solution?

**Comment by rezasys2** [comment]
Finally, [this solution ](https://github.com/beyondcode/laravel-websockets/issues/109#issuecomment-754781478) worked for me, I had to change the port and config.
