### ISSUE TITLE
[Question] Force-closing a websocket connection

### ISSUE THREAD

**Issue by dganzella** [beyondcode/laravel-websockets#715]
Hello! We use pusher`s presence channel in our app with laravel websockets.

We always run into an issue: When a user switches wifi or run out of battery in a mobile phone and does not properly close the connection, the backend takes too long (75 seconds) to notice that the user is no longer in the channel.

Because we do not allow multiple connections with the same user in our app (for consistency reasons), we would like to know if, upon the same user authenticating again either on the same device or in another one, but on the same channel, if we can force-close the previous connection so we guarantee that the user is connected in just one device at a time without needing to wait for the entire 75 seconds.

Thanks,

danilo

**Comment by simonbuehler** [comment]
use a custom websocket handler and add the logic to the onMessage function like find the relevant user connections and close() it.
set the class in the websocket.conf as the websocket handler and enjoy
