### ISSUE TITLE
Deploying to digitalocean

### ISSUE THREAD

**Issue by oxytoxin** [beyondcode/laravel-websockets#723]
Hi! I already had a deployed site with ssl. It was using previously on pusher but now I would like to migrate to laravel-websockets. I tried what the documentation says up until the ssl part because I could not understand if I should create a subdomain for the websocket server or if I should just use the domain of my site. I have also tried changing the port used to 443 but to no avail. What should I do?

**Comment by simonbuehler** [comment]
no subdomain needed so routing to e.g. socket.mydomain.com is optional. its better to not use the included ssl part but rather use a reverse proxy to handle the ssl certificates to the outside (e.g. with letsencrypt) and the local proxy can use plain http to the localhost websocket server.
