### ISSUE TITLE
[bug] Incorrect logged Origin in DashboardLogger

### ISSUE THREAD

**Issue by andreiromila** [beyondcode/laravel-websockets#726]
Hi, I have an issue with the dashboard, it shows the server address and not the origin one. I could be wrong but in the DashboardLogger.php on line 26 it always gets the uri (server's) sheme and host. 

https://github.com/beyondcode/laravel-websockets/blob/583022a11d217caf5fbf5b8f1ae8837f473c41f9/src/Dashboard/DashboardLogger.php#L20-L29

Shouldn't get the "Origin" header if there is one?
I tried with something like this: 
```php
public static function connection(ConnectionInterface $connection)
{
    /** @var \GuzzleHttp\Psr7\Request $request */
    $request = $connection->httpRequest;

    if ($request->hasHeader('origin')) {
        $details = "Origin: {$request->getHeaderLine('origin')}";
    } else {
        $details = "Origin: {$request->getUri()->getScheme()}://{$request->getUri()->getHost()}";
    }

    static::log($connection->app->id, static::TYPE_CONNECTION, [
        'details' => $details,
        'socketId' => $connection->socketId
    ]);
}
```
And works great.
Can you make an official fix?
Thanks.

**Comment by kzvonov** [comment]
@rennokki Hey 👋 

Can I take this one?
