### ISSUE TITLE
[Pusher] Pusher 6.x support

### ISSUE THREAD

**Issue by lbreza** [beyondcode/laravel-websockets#728]
A new version of [pusher/pusher-http-php ](https://github.com/pusher/pusher-http-php) (6.x) has been released recently.
Currently there are supported only versions up to 5.x.

**Comment by DarkGhostHunter** [comment]
The changelog between 6.0 and 5.0 [it's minimal](https://github.com/pusher/pusher-http-php/releases/tag/6.0.0).

> [CHANGED] internal HTTP client to Guzzle
> [ADDED] optional client parameter to constructor
> [CHANGED] useTLS is true by default
> [REMOVED] from options
> [REMOVED] customer logger
> [REMOVED] host, port and timeout constructor parameters
> [REMOVED] support for PHP 7.1
> [CHANGED] lower severity level of logging to DEBUG level

Some fixes should be [happening here](https://github.com/beyondcode/laravel-websockets/blob/2.x/src/Concerns/PushesToPusher.php#L23), for example.

**Comment by DarkGhostHunter** [comment]
#752

**Comment by rennokki** [comment]
I'll keep the PR #752 on hold until Laravel is going to support Pusher 6.x. As far as I can see, [Laravel's last Pusher update allows up to 5.x](https://github.com/laravel/framework/commit/3404185fbe36139dfbe6d0d9595811b41ee53068#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34).

**Comment by DarkGhostHunter** [comment]
Here to remind that Laravel now supports 6.x.

**Comment by shehi** [comment]
Any news on this?

**Comment by DarkGhostHunter** [comment]
It's not 7.0. I would wait some months until they stop jumping between major versions.
