### ISSUE TITLE
How to use with laravel vapor?

### ISSUE THREAD

**Issue by ajcastro** [beyondcode/laravel-websockets#730]
I found this twitter thread https://twitter.com/thierylaverdure/status/1154891852786688002
and I understand we need to spin up a server for this. 

Is there a blog post or article or clear instructions on how to link the laravel-websockets to our laravel apps hosted in laravel-vapor?

**Comment by rennokki** [comment]
You will need a separate Laravel server that will be kept alive and will serve the WebSocket connections. AWS Lambda is for fast workload, you can try do websocket on it and end up with huge bills.

Just install it as a normal Laravel app and when users access your pages, the browser JS will connect to the websocket server.
