### ISSUE TITLE
[2.x] Error when starting websocket with custom handler.

### ISSUE THREAD

**Issue by rodrigoross** [beyondcode/laravel-websockets#731]
Hello. 

I'm trying to create a custom handler, my laravel-websocket current version is **2.0.0-beta.33**.

`app\MyCustomWebSocketHandler.php`
```
namespace App;

use BeyondCode\LaravelWebSockets\Server\WebSocketHandler;
use Exception;
use Illuminate\Support\Facades\Log;
use Ratchet\ConnectionInterface;
use Ratchet\RFC6455\Messaging\MessageInterface;
use Ratchet\WebSocket\MessageComponentInterface;

class MyCustomWebSocketHandler extends WebSocketHandler
{
    public function onOpen(ConnectionInterface $connection)
    {
        Log::info($connection->httpRequest);
    }
}
```

In my `routes/web.php` I added the following

```
use App\MyCustomWebSocketHandler;
use BeyondCode\LaravelWebSockets\Facades\WebSocketRouter;

WebSocketRouter::get('/test', MyCustomWebSocketHandler::class);
```

But when I try to restart the websocket server, I get the following error:

![image](https://user-images.githubusercontent.com/25902368/113449287-7f667f80-93cb-11eb-863c-8a0e011deef0.png)

Searching in the error in the issues page I found the #531, however it says that was fixed at beta.21, So I'd like to know if there is another workaround, or there is a step that I missed.

I even changed the `WebSocketRouter::get('/test', MyCustomWebSocketHandler::class);` to boot() in `AppServiceProvider.php`, but to no avail.

**Comment by 91Abdullah** [comment]
Hi, try this: 

`WebSocketsRouter::webSocket('/app/{appKey}', \App\Websocket\MyCustomWebsocketHandler::class);`

**Comment by rennokki** [comment]
After the mentioned PR is merged, there will be one way to register the routes that's strict for 2.x:

```php
WebSocketsRouter::addCustomRoute('GET', '/my-websocket', \App\MyCustomWebSocketHandler::class);
```
