### ISSUE TITLE
connection failure in wss port

### ISSUE THREAD

**Issue by Chegua** [beyondcode/laravel-websockets#732]
Greetings dear, I currently have problems for the transmission of events via websocket with the use of the laravel-websocket package. This problem occurs in production, I have in mind the necessary configurations for the https connection, but in the same way it shows me a link like this wss: //mysite.com: 6001 / app / mykey? Protocol = 7 & client = js & version = 7.0.3 & flash = false
been with 101.

config/broadcast.php
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' =>  [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => env('BC_USE_TLS'),
                'encrypted' => env("BC_ENCRYPTED"),
                'host' => env("BC_HOST"),
                'port' => env("BC_PORT"),
                'scheme' => env("BC_SCHEME"),
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],

resources/js/bootstrap.js

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: process.env.MIX_BC_ENCRYPTED === "true",
    wsHost: window.location.hostname,
    wsPort: Number(process.env.MIX_BC_PORT),
    wssPort: Number(process.env.MIX_BC_PORT),
    disableStats: true,
    forceTLS: true,
    enabledTransports: ['ws', 'wss']
});

**Comment by simonbuehler** [comment]
please provide the network response from the developer toolbar to make the issue understandable

**Comment by the-provost** [comment]
I have the issue as well. I think this happens when the number of connections reach a certain number but I dont know where that threshold is mentioned. If you figure something out, please share

**Comment by kailasb10** [comment]
resources/js/bootstrap.js
```
import Echo from 'laravel-echo';

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    encrypted: false,
    wsHost: window.location.hostname,
    wsPort: process.env.MIX_LARAVEL_WEBSOCKETS_PORT,
	wssPort: process.env.MIX_LARAVEL_WEBSOCKETS_PORT,
    enabledTransports: ['ws', 'wss'],
	forseTLS:true,
});
```
config/broadcast.php
```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => env('LARAVEL_WEBSOCKETS_PORT'),
                'scheme' => 'https',
                'encrypted' => true,
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
```
config/websocket.php
set SSL certificate in ENV file with the constant name given in the file. also added extra **'verify_peer'=>false**.

Console
![wss-log](https://user-images.githubusercontent.com/82386026/124568656-c5b3fa80-de62-11eb-9b8b-7058e3d85300.png)

Network
for first call it's showing msg "WebSocket is closed before the connection is established." but next onwards calls it's not showing any msg
