### ISSUE TITLE
add possibility to set base url for websocket-server

### ISSUE THREAD

**Issue by N3XT0R** [beyondcode/laravel-websockets#737]
Hey Guys,
could you add a possibility to set the base url on the websocket-server? 
Actually its not possible to configure a websocket server behind a sub-url like (https://beyondco.de/docs/laravel-websockets/basic-usage/ssl#same-location-for-websockets-and-web-contents):
`location /ws { ... }`

By configuring a websocket server at http://example.com/ws the route configuration does not match anymore in: 

BeyondCode\LaravelWebSockets\Server\Router::echo(), so the websocket-server will permanently return 404 http status codes.

**Comment by drmax24** [comment]
I agree. Btw any ideas how to solve this now apart from server-proxy?

**Comment by drmax24** [comment]
Using v2.0 beta 36

We can add
`WebSocketsRouter::addCustomRoute('GET', '/my-websocket', \App\MyCustomWebSocketHandler::class);`


and set 
```
    PUSHER_APP_PATH: 'my-websocket'
    LARAVEL_WEBSOCKETS_PORT: '80'
```

though it still does not work

**Comment by mrfarhadir** [comment]
@drmax24 You saved my day.
