### ISSUE TITLE
Custom WebSocket Handlers - routes/web.php - route not found when cache is enabled

### ISSUE THREAD

**Issue by ivanomatteo** [beyondcode/laravel-websockets#738]
Inserting into 
**routes/web.php**
the following line (as suggested by the documentation)
`WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);`

**do not work when the routes are cached (php artisan route:cache)**, ending with a 404 response from websocket server.

A quick workaround:
instead of adding it to **routes/web.php**
add this to the RouteServiceProvider at the end of boot() method:
 ```
Route::middleware('web')  ->group(function () {
         WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);
 });
```

**Comment by rennokki** [comment]
Package version?

**Comment by ivanomatteo** [comment]
1.12.0

**Comment by rennokki** [comment]
Move the `WebSocketsRouter::webSocket` call in `AppServiceProvider`.

**Comment by ivanomatteo** [comment]
@rennokki 
Ok, but you should update the documentation.

**Comment by manojmilani** [comment]
How to send events/messages on this custom route?

**Comment by ivanomatteo** [comment]
@manojmilani just open raw websocket connection to that url

**Comment by manojmilani** [comment]
@ivanomatteo Can you help me if there is any method in this package which does the same?

**Comment by ivanomatteo** [comment]
Explain better what you need to do.

**Comment by manojmilani** [comment]
I need to receive messages/events on this custom handler, when they are broadcasted by laravel events.

**Comment by ivanomatteo** [comment]
@manojmilani as far I know is not possible receive broadcast events when using a custom handler.

but you could create a custom channel that connect directly to the custom websocket handler
And send the data there.
