### ISSUE TITLE
specify schema for laravel-websocket monitor interface

### ISSUE THREAD

**Issue by drmax24** [beyondcode/laravel-websockets#744]
2.0 beta 36

laravel-websocket works fine but it's front-end mini-app connects back-end auth via http not https and i can't see where i can set this

**Comment by sirosfakhri** [comment]
do you mean something like this?
`config/broadcast.php

'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'scheme' => 'https',
            ]
        ],`
