### ISSUE TITLE
Server goes down when it reaches ~500 connections

### ISSUE THREAD

**Issue by jakub-skapski-dev** [beyondcode/laravel-websockets#745]
Hello, I run websockets server through supervisor, but when it reaches higher volume of connection it just shutdown, I cannot find any logs regarding that.

![image](https://user-images.githubusercontent.com/66777263/115895124-5bdaa600-a45a-11eb-90c3-f67eb1518d8f.png)

**Comment by rennokki** [comment]
Consider reading about more issues on `ulimit`: https://github.com/beyondcode/laravel-websockets/search?q=ulimit&type=issues
