### ISSUE TITLE
Question Regarding 2.x

### ISSUE THREAD

**Issue by AdamKyle** [beyondcode/laravel-websockets#747]
Hello, I have a couple questions regarding the 2.x branch.

I am currently still developing on PHP 7.4 and I haven't been able to upgrade to 8.0 let alone think of 8.1 because I still use the 1.x branch of this project. I have seen other threads stating to use the 2.x branch, but its still in beta. So my questions are:

1. Even though its in beta, is it stable enough for production deployment - I have seen issues around the CPU jumps.
2. Is it compatible with (I assume yes) php 8.1?

I am sorry for opening an issue to discuss this, but since there's no discord or dedicated forms to this project and it would be just as inappropriate to ask on stack, I ask here.

I would very much like to upgrade to 8.0 but I question the stability of the 2.x beta y path. Could you shed some light? thank you.

**Comment by DarkGhostHunter** [comment]
> Even though its in beta, is it stable enough for production deployment

Works question of the year.

Also, considering PHP 8.1 it's not yet available, and some upstream packages are just getting PHP 8.0 support, I doubt for current PHP 8.1 compatibility. This package doesn't enforces a PHP version.

**Comment by rennokki** [comment]
@AdamKyle 
1. Since there are still ongoing issues, it's still beta.
2. It should be. However, as @DarkGhostHunter pointed, 8.1 is not yet published so there is no way to test it so far.
