### ISSUE TITLE
laravel -websocket using all of cpu memory

### ISSUE THREAD

**Issue by ramay2088** [beyondcode/laravel-websockets#749]
laravel-weboscket using all cpu memory i am using version 2.x . server start crashing when i enable supervisor worker 

websocket.conf file

```
[program:websockets]
command=php /var/www/html/siloc/artisan websockets:serve
numprocs=1
autostart=true
stdout_logfile=/var/www/html/siloc/websocket.log
autorestart=true

```

**Comment by mehmetbeyHZ** [comment]
try without stdout_logfile and differen port (6002)

**Comment by ramay2088** [comment]
without stdout_logfile  i have tried but with port didn't just let me check

**Comment by xitox97** [comment]
@ramay2088 does it solves your issue?

**Comment by guspan** [comment]
@ramay2088 did you try the different port? did it help?
