### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by ericyam94** [beyondcode/laravel-websockets#753]
I tried to run port 6001 on my local and it worked but not work in production.
I am using Cloudflare CDN with Flexi SSL configuration. 

I had also double check that I allowed port 6001 in my firewall and it is running.
![image_2021-05-02_01-02-56](https://user-images.githubusercontent.com/40621654/116789601-31d05600-aae2-11eb-9a27-04e2f99c9bf8.png)

===========================================================================================
Here is my settings:
**websockets.php**
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
],
'ssl' => [
        'local_cert' => null,
        'local_pk' => null,
        'passphrase' => null,
],

**broadcasting.php**
'pusher' => [
        'driver' => 'pusher',
        'key' => env('PUSHER_APP_KEY'),
        'secret' => env('PUSHER_APP_SECRET'),
        'app_id' => env('PUSHER_APP_ID'),
        'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => false,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
                'useTLS' => false,
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
         ],
],

**client side**
window.Echo = new Echo({
        broadcaster: 'pusher',
        key: "mykey",
        cluster: "mt1",
        wsHost: window.location.hostname,
        wsPort: 6001,
        wssPort: 6001,
        disableStats: true,
        enabledTransports: ['ws', 'wss'] // <- added this param
})

**Comment by hsyir** [comment]
I have same problem,
any problem when i try to connect from "http" client website .. but  this problem occurred when i try to connect with "https" client website..

**Comment by simonbuehler** [comment]
is this a echo / pusher.js error?

**Comment by lovetoast** [comment]
> I tried to run port 6001 on my local and it worked but not work in production.
> I am using Cloudflare CDN with Flexi SSL configuration.
> 
> I had also double check that I allowed port 6001 in my firewall and it is running.
> ![image_2021-05-02_01-02-56](https://user-images.githubusercontent.com/40621654/116789601-31d05600-aae2-11eb-9a27-04e2f99c9bf8.png)
> 
> ===========================================================================================
> Here is my settings:
> **websockets.php**
> 'apps' => [
> [
> 'id' => env('PUSHER_APP_ID'),
> 'name' => env('APP_NAME'),
> 'key' => env('PUSHER_APP_KEY'),
> 'secret' => env('PUSHER_APP_SECRET'),
> 'path' => env('PUSHER_APP_PATH'),
> 'capacity' => null,
> 'enable_client_messages' => false,
> 'enable_statistics' => true,
> ],
> ],
> 'ssl' => [
> 'local_cert' => null,
> 'local_pk' => null,
> 'passphrase' => null,
> ],
> 
> **broadcasting.php**
> 'pusher' => [
> 'driver' => 'pusher',
> 'key' => env('PUSHER_APP_KEY'),
> 'secret' => env('PUSHER_APP_SECRET'),
> 'app_id' => env('PUSHER_APP_ID'),
> 'options' => [
> 'cluster' => env('PUSHER_APP_CLUSTER'),
> 'encrypted' => false,
> 'host' => '127.0.0.1',
> 'port' => 6001,
> 'scheme' => 'http',
> 'useTLS' => false,
> 'curl_options' => [
> CURLOPT_SSL_VERIFYHOST => 0,
> CURLOPT_SSL_VERIFYPEER => 0,
> ]
> ],
> ],
> 
> **client side**
> window.Echo = new Echo({
> broadcaster: 'pusher',
> key: "mykey",
> cluster: "mt1",
> wsHost: window.location.hostname,
> wsPort: 6001,
> wssPort: 6001,
> disableStats: true,
> enabledTransports: ['ws', 'wss'] // <- added this param
> })

Sorry, know I'm a bit late, but if you try  NGINX and reverse proxy, this will work better.
