### ISSUE TITLE
How to use Let's encrypt for implement ssl

### ISSUE THREAD

**Issue by hsyir** [beyondcode/laravel-websockets#757]
Hello.. 
i have a vps with directadmin implementation.
deployed this package on a special host and subdomain and use "Free & automatic certificate from Let's Encrypt" option for ssl certificate.
there is a private key and certificate generated on ssl tab.
can i use this data for the laravel websocket server ssl config?
if not .. how should i config the server? 
i have install certbot but im not sure how can i use that.. 
please help me ..

**Comment by andreas83** [comment]
I try to archive the same thing via nginx, sadly no luck so far.

**WebSocket is closed before the connection is established.**

here is my nginx config, any hints are highly appreciated. 

```
 server {
    listen 443 ssl;
    server_name socket.server.com;
    ssl_certificate /etc/letsencrypt/live/socket.server.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/socket.server.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $host;

      proxy_pass https://ws-backend;

      proxy_ssl_certificate      /etc/letsencrypt/live/socket.server.com/fullchain.pem;
      proxy_ssl_certificate_key /etc/letsencrypt/live/socket.server.com/privkey.pem; 

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
  upstream ws-backend {
    # enable sticky session based on IP
    #ip_hash;

    server localhost:6002;
  }
```
