### ISSUE TITLE
[URGENT] Using dev dependencies

### ISSUE THREAD

**Issue by DarkGhostHunter** [beyondcode/laravel-websockets#759]
I just figured out that deep in the code of the `composer.json`, the stability is issued as `dev`.

In other words, each fetch of this package (2.0) is getting packages on development, so the 2.0 will break _evrytaim_.

[Whole branch 2.0](https://github.com/beyondcode/laravel-websockets/blob/9dbc38aff9d01fdf5de21cfb941dd684d7548a21/composer.json#L75) is affected.

**Comment by kamui545** [comment]
2.0 is beta and not stable, so I guess this is intentional?

**Comment by DarkGhostHunter** [comment]
You always develop on versions constraints to avoid breaking. If I did this on my job, I wouldn’t last a week. 

Italo Baeza C.
