### ISSUE TITLE
Exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey`

### ISSUE THREAD

**Issue by NIkita-Kim** [beyondcode/laravel-websockets#76]
Hi!

I'm facing this issue when starting server:
```Exception `BeyondCode\LaravelWebSockets\WebSockets\Exceptions\UnknownAppKey` thrown: `Could not find app key `xxxxxxxxxxxxxxxxxxxxxxx`.`
Unknown app id```

All keys are copied and works locally, but on staging - no.

**Comment by stayallive** [comment]
Hi, there are a few things to check here.

- Check to make sure your `config/websockets.php` contains the app key you are trying to use (on your staging site).

- Also try to clear your config cache (`php artisan config:clear`) to make sure the values are not cached.

- If your config is loaded from your `.env` (default is `'key' => env('PUSHER_APP_KEY'),`) make sure the `PUSHER_APP_KEY` is in there with the app key you are trying to use.

**Comment by NIkita-Kim** [comment]
Yeah, i think cache... Thanks!

**Comment by bintariq** [comment]
I just hard coded   env('PUSHER_APP_KEY'),  to my custom key  "myKey" Solved the problem for me.
          

  'key' => env('PUSHER_APP_KEY'),

  to
            
'key' => 'mykey',

**Comment by mMartinCore** [comment]
yeah bintariq, that work

**Comment by MojSkin** [comment]
my websockets.php (config file):
`'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],`

my .env config:
`PUSHER_APP_ID=mojskin-developer
PUSHER_APP_KEY=mojskin-developer
PUSHER_APP_SECRET=mojskin-developer-as-salt-security-key`

but still having connection error

**Comment by RyanSacks** [comment]
I tried the recommended 3 options, but I still get the error. Using pusher app id and pusher app key from .env file. Help?
