### ISSUE TITLE
[Pusher] Pusher 7.x support

### ISSUE THREAD

**Issue by lbreza** [beyondcode/laravel-websockets#763]
A new version of [pusher/pusher-http-php ](https://github.com/pusher/pusher-http-php) (7.x) has been released recently.
Currently there are supported only versions up to 5.x.

Support for version 6.x is in progress (https://github.com/beyondcode/laravel-websockets/issues/728).

**Comment by rassemdev** [comment]
following

**Comment by shehi** [comment]
Yea, would be great to have this.

**Comment by aeremichev** [comment]
+1

**Comment by calebanthony** [comment]
For this to get implemented, we need to wait on Laravel to update to Pusher 7.x. Currently, it only supports up to Pusher 6.x.

Pusher 7.x deprecates several methods by changing their name: https://github.com/pusher/pusher-http-php/blob/master/CHANGELOG.md#700

So I wouldn't expect Laravel to update to Pusher 7 until at least the Laravel 9.x release, and maybe not even then, so they can maintain more backward functionality.

**Comment by rassemdev** [comment]
> For this to get implemented, we need to wait on Laravel to update to Pusher 7.x. Currently, it only supports up to Pusher 6.x.
> 
> Pusher 7.x deprecates several methods by changing their name: https://github.com/pusher/pusher-http-php/blob/master/CHANGELOG.md#700
> 
> So I wouldn't expect Laravel to update to Pusher 7 until at least the Laravel 9.x release, and maybe not even then, so they can maintain more backward functionality.

@calebanthony I have a project on laravel-6. Where i am using pusher-7. I don't think that's the issue. Laravel already support pusher-7.

**Comment by calebanthony** [comment]
While it may work for your use case, it's not officially supported by Laravel (which you can see in their [composer.json](https://github.com/laravel/framework/blob/8.x/composer.json)). Their recommendation in the 8.x branch is to install up to Pusher 6.x. There are a couple of issues where Pusher 7.x  breaks certain functionalities, and it's not recommended to upgrade yet.
