### ISSUE TITLE
Problem when installing websockets

### ISSUE THREAD

**Issue by salah-rhl** [beyondcode/laravel-websockets#768]
Hello guys, I'm getting this problem when running "composer require beyondcode/laravel-websockets".

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require pusher/pusher-php-server ^3.0|^4.0|^5.0 -> found pusher/pusher-php-server[dev-master, 3.0.0, ..., v3.4.1, v4.0.0, ..., v4
.1.5, v5.0.0, ..., 5.0.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

I already have pusher package installed.

Here's my composer json:
"require": {
        "php": "^7.4|^8.0",
        "ext-json": "*",
        "ext-pdo": "*",
        "barryvdh/laravel-dompdf": "^0.9.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "hardevine/shoppingcart": "^2.9",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "pusher/pusher-php-server": "^7.0",
        "spatie/laravel-cookie-consent": "^2.12",
        "stripe/stripe-php": "^7.77"
    },

do you have any idea how to solve this?

thank you in advance.

**Comment by mpociot** [comment]
You already require the pusher php server version 7, which is not supported by this package. 
You can use laravel websockets in combination with Pusher Server up to 5.x/soon 6.x

If you don't specifically need any 7.x features, just remove the pusher dependency from your local composer file, as this package requires it anyway.
