### ISSUE TITLE
Trying to implement HandleWebSocketMessage

### ISSUE THREAD

**Issue by thyagomuris** [beyondcode/laravel-websockets#770]
I have a question and I don't know if I'm doing it wrong.

I'm trying to hear all the new connections and I'm using the example from the documentation

https://github.com/beyondcode/laravel-websockets/blob/master/docs/advanced-usage/dispatched-events.md

But when I add the reference BeyondCode\LaravelWebSockets\Events\NewConnection does not exist.

I checked and it doesn't exist, so I don't know what I'm doing wrong

**Comment by mdprotacio** [comment]
Maybe you are using the version 1.x of the package when you require the package. I'm currently using dev-master.
