### ISSUE TITLE
Pusher Failed

### ISSUE THREAD

**Issue by the-provost** [beyondcode/laravel-websockets#773]
I used laravel-websockets and pusher to build a real-time auction platform for a small group of farmers. But no matter what I do, the app stops getting new events and "Pusher failed" error is thrown. I tried to increase server size, u limit is 1000. But anytime more than 20 people use the app. Everything goes to hell.

Please help. Is there anything I can do to increase limits and scale other than the ulimit mentioned in the documentation. Does pusher have any limit hardcoded or something?

**Comment by AdrienBayles** [comment]
I am facing the same issue : once I reach +/- 360 simultaneous connections, events are not broadcasted anymore and Laravel starts sending "BroadcastingError / connection to Pusher failed" errors.

The app and sockets server are on 2 different domains/servers and communicate over ssl.

I have tried to follow instructions listed in the [Deployment](https://beyondco.de/docs/laravel-websockets/faq/deploying) section

and increased the ulimit successfully, but the installation of the 'event' package fails (needs to install php devel, which relies on another dependency etc etc - installation is blocked)

**Comment by calebanthony** [comment]
This is unlikely to be a library problem and more likely to be a server configuration problem. I use this library to serve events to players in a browser game, and typically have anywhere from 300-500 players connected simultaneously without dropping events.

**Comment by the-provost** [comment]
Any suggestions on how to configure a VM for this?
