### ISSUE TITLE
Having an isssue running the supervisord deamon.

### ISSUE THREAD

**Issue by aFluxx** [beyondcode/laravel-websockets#78]
When trying to run the deamon I was constantly getting the following error;
`websockets: ERROR (spawn error)`

After some debugging and enabling loggin in the websockers.conf file I found that the problem was:
```
2019-01-08 21:15:43,932 INFO spawned: 'websockets' with pid 13139
2019-01-08 21:15:43,972 INFO exited: websockets (exit status 1; not expected)
Could not open input file: /home/laravel-echo/laravel-websockets/artisan
```

Now I'm not really sure how to fix this. I went checking and there is not laravel-echo folder in my home directory.

But I deploy with forge, am I missing something here?

Also informative:
```
$ sudo supervisorctl status
websockets                       FATAL     Exited too quickly (process log may have details)
```

**Comment by aFluxx** [comment]
I managed to fix it:

I wasn't aware that in the command line you have to change two things, the user and the folder where you site is located.

This is the docu;
```
[program:websockets]
command=/usr/bin/php /home/laravel-echo/laravel-websockets/artisan websockets:serve
numprocs=1
autostart=true
autorestart=true
user=laravel-echo
```

I've changed:
`command=/usr/bin/php /home/laravel-echo/laravel-websockets/artisan websockets:serve`
To
`command=/usr/bin/php /home/{my user}/{my site}/artisan websockets:serve`

**_Beware, this is deployed via forge, custom deployments may differ!_**

**Comment by kazi-shahin** [comment]
For me it worked without giving the user in command. 
command=/usr/bin/php /home/{my user}/{my site}/artisan websockets:serve

I did not needed to provide the value of the {my user}. I removed the /home/{my user

**Comment by Michael-0208** [comment]
It worked well! You are an angel man! @aFluxx
