### ISSUE TITLE
Could not set route with Custom WebSocket Handlers

### ISSUE THREAD

**Issue by kablin** [beyondcode/laravel-websockets#781]
Try to use Custom WebSocket Handlers example in Laravel 8.
`
class MyCustomWebSocketHandler implements MessageComponentInterface`

`WebSocketsRouter::webSocket('/my-websocket', \App\MyCustomWebSocketHandler::class);`

Got the error

```
BeyondCode\LaravelWebSockets\Exceptions\InvalidWebSocketController

Invalid WebSocket Controller provided. Expected instance of  Ratchet\WebSocket\MessageComponentInterface, 
but received App\MyCustomWebSocketHandler
```

**Comment by yajo10** [comment]
You may wan't to check your Namespaces. I had the same error and after fixing the namespaces of MyCustomWebSocketHandler it's not throwing this error anymore.

**Comment by SamuelBuendia** [comment]
> 

Pudiste solucionarlo?

**Comment by SIMONNABUKO** [comment]
Interestingly, I moved the websockets files from the laravel root folder to app folder and updated the namespaces and it worked.

**Comment by bvalerin** [comment]
> You may wan't to check your Namespaces. I had the same error and after fixing the namespaces of MyCustomWebSocketHandler it's not throwing this error anymore.

Actually the error was the namespace, thank you!
