### ISSUE TITLE
How to emit data on client side and listen on server side?

### ISSUE THREAD

**Issue by dalisalvatore** [beyondcode/laravel-websockets#782]
I'd like to emit data on client side, and listen this data on server side. How may i do this?

I'd like to listen on server side this data and start uploading big files. Then i'd like to broadcast this to regarding user.
I'd be so glad if you help me through this.

**Comment by wjstraver** [comment]
You can interact with this library in the same way as you would with Pusher, so you can use the documentation over there.
However, if you look in the documentation of Laravel itself, broadcasting is not really made to send data from client to the server, like you would with other websocket libraries like Socket.io. Better practice is to use Http requests for that.
