### ISSUE TITLE
Has anyone gotten this to work with Homestead recently?

### ISSUE THREAD

**Issue by jesperbjerke** [beyondcode/laravel-websockets#787]
Has anyone gotten this to work with Homestead recently? If so, a guide would be much appreciated!
I've tried multiple different suggestions found in previous issues but can still not get the client to connect to the server. Port forwarding in Homestead.yaml, configuring nginx etc. Nothing works.
I've also tried multiple versions of `pusher/pusher-php-server`. The documentation says to use "~3.0".

Getting either failed directly or connection closed before "WebSocket is closed before the connection is established".

**Comment by TheArKaID** [comment]
How did you configure this to work in Homestead? Could you please share that?
