### ISSUE TITLE
server responds with message only when connection is closing

### ISSUE THREAD

**Issue by my-random-username** [beyondcode/laravel-websockets#791]
Hello . For a long time, I have been using the beyondcode/laravel-websockets package as socket server. I recently noticed that web socket connections are established but no message is sent by the server after communication.
I tested the web socket server with "fire camp" app and noticed something strange. After communication, no message is sent from the server, but the desired message is sent at the moment of disconnection. Even when I stop the web socket server, the message is sent the moment the connection is closed.

the message when I use ctrl+c to close the socket server :
**((Note that this message is only sent when the application is closed and not when the connection is established))**

{
    "event": "pusher:connection_established",
    "data": "{\"socket_id\":\"835589398.433296428\",\"activity_timeout\":30}"
}

***In general, a message is sent only when the connection is being closed***

~~Os : centos 7~~

~~Php version :~~

~~PHP 8.0.7 (cli) (built: Jun  9 2021 16:40:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.7, Copyright (c), by Zend Technologies~~

**Comment by my-random-username** [comment]
update 1 :
I created a raw project and just installed the web socket package on it then set APP_DEBUG = true
  Now when the connection is established, this message is displayed in the console:


Connection id 383735544.78498234 sending message {"event":"pusher:connection_established","data":"{\"socket_id\":\"383735544.78498234\",\"activity_timeout\":30}"}


 but this message is also sent only when I stop the server ( like using ctrl + c ). Could this be a problem with opCache?

**Comment by my-random-username** [comment]
update 2 :
I tested without using the domain and by entering the ip and port directly and there was no problem at all everything worked as expected . I use the cloudflare CDN service on my domain. wired 🤔

**Comment by iamafasha** [comment]
SO what would be the solution if you still don't want to use the port directly?

**Comment by my-random-username** [comment]
> SO what would be the solution if you still don't want to use the port directly?

I think the problem is from apache app. its not sending the body of the Websocket data. I think Apache is collecting body data to compress it before sending.
the solution is to nginx as reverse proxy for websocket.
