### ISSUE TITLE
Standalone Docker Image

### ISSUE THREAD

**Issue by jaydrogers** [beyondcode/laravel-websockets#793]
Hey guys,

Thanks for putting this project together!

My friend @danpastori and I are just getting started with websockets and noticed your package. Looks amazing!

We were going through the documentation and noticed that we have two options:

1. Install laravel-websockets into our existing Laravel project
2. Run laravel-websockets as our own server (separate from our other Laravel app)

We really like option 2 so we can reuse it many times.

### My question
* Do you have a docker image that can run your project as a standalone server?

If not, we'd love to contribute one. 😁

### Our vision
I've been working on open sourcing our base PHP images: https://github.com/serversideup/docker-php/tree/dev

I was going to take your package, install it in a default Laravel install (on top of our PHP image), then package the entire app up into its own image so we can easily use and maintain multiple projects with it.

This would make it very easy for people to get started with the project as well.

We don't even need to put the image under the "beyondcode" Github organization. We can keep the image separate at first then make it an "official image" later on if you really like it. 

We started working on doing this internally already but ran into some issues. Before we get too far ahead, we just wanted to hear your perspective and make sure we are not reinventing the wheel. 😆

Interested in hearing your thoughts!

**Comment by robjuz** [comment]
I'm also interested in a standalone docker image.

I'm using this package with my laravel project and it works great. Now I have an other project (Symfony) and need a websocket server.

I had exact the same idea. Create a basic laravel project with this package and get it into a container.

**Comment by jaydrogers** [comment]
**Just adding an update since our last post:** We currently have web sockets working with a Docker image from Soketi (https://docs.soketi.app/).

We discovered Soketi after Taylor Otwell tweeted about his contributions to the documentation for that project.

I haven't had the chance to play around with Laravel Websockets yet (mainly because I was waiting to hear back on reusable deployments with Docker), but I am sure both projects have their use cases.

Just wanted to share this resource in case anyone else is in the same boat.

**Comment by chudaozhe** [comment]
I made an independent mirror, welcome to experience
[laravel-websockets standalone image](https://github.com/chudaozhe/docker-laravel-websockets)
