### ISSUE TITLE
Unable to install this package in Latest Laravel

### ISSUE THREAD

**Issue by back2Lobby** [beyondcode/laravel-websockets#794]
I have PHP 8.0.8 installed with Chocolatey on Windows 10. Composer Fully Updated. When I add this package with `composer require beyondcode/laravel-websockets` into a fresh laravel project. It shows me the following error.
> Problem 1
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

![Composer Error](https://user-images.githubusercontent.com/29447722/124386891-ea3e9400-dcf5-11eb-9639-4d4a1e049017.png)

And if I do it with `--with-all-dependencies`, then
![2error](https://user-images.githubusercontent.com/29447722/124387365-bbc1b880-dcf7-11eb-85dd-ecf31b21a63c.png)

**Comment by grenni78** [comment]
I had the same problem. It was successfully running on an other server with same laravel version.
The only difference was the version of guzzlehttp/psr7. The running system had 1.8.2 installed, the other 2.0.0.
After a downgrade I was able zu install the websockets package.

**Comment by back2Lobby** [comment]
@grenni78 Exactly! I checked that `guzzlehttp/guzzle` started using `guzzlehttp/psr7 ^2.0` from `v7.3`. So, I downgraded a bit by changing it in composer.json as `"guzzlehttp/guzzle": "7.2"` (which is still using `guzzlehttp/psr7: ^1.7`)
After that `composer update` and now laravel-websockets is installed successfully. Thanks mate!

**Comment by nguyenhaidangyq** [comment]
You can use the way: 
1. run composer require guzzlehttp/psr7 
2. in file composer.json, you change version "guzzlehttp/psr7": "^2.0", to "guzzlehttp/psr7": "^1.5",
3. after that, you run composer update
4. run composer require beyondcode/laravel-websockets
->> Good luck

**Comment by JahanzaibHussain** [comment]
to install **beyondcode/laravel-websockets**
the more simple way is:

1.  add two properties under require in **composer.json**
     _example_
        "require": {
          "guzzlehttp/guzzle": "^7.0.1",
          "beyondcode/laravel-websockets": "^1.12",
          "pusher/pusher-php-server": "^5.0",
        }
2.  run **composer update**

![image](https://user-images.githubusercontent.com/16865035/131364442-4c440752-f5d3-48a4-8ed3-4722325debb4.png)

**Comment by alexvergara** [comment]
Easiest way:

```
composer require guzzlehttp/psr7:^1.5
composer require beyondcode/laravel-websockets
```

**Comment by laravelteacher** [comment]
change "guzzlehttp/guzzle": "^6.3", like this then changed that write in terminal 
composer require beyondcode/laravel-websockets
this work goood

**Comment by gfdsa201666** [comment]
composer require guzzlehttp/psr7 "^1.5"
Then
composer require beyondcode/laravel-websockets

**Comment by hncvj** [comment]
This worked for me on Laravel 8 having lighthouse-php installed

composer require guzzlehttp/psr7:^1.5
composer require pusher/pusher-php-server:^5.0
composer require beyondcode/laravel-websockets
