### ISSUE TITLE
Can't install laravel 8

### ISSUE THREAD

**Issue by aeremichev** [beyondcode/laravel-websockets#796]
I did a clean install of laravel 8

When trying to install a package
```
composer require beyondcode/laravel-websockets
```

I get the error

``` 
Creating websocket-laravel-test_app-php-cli_run ... done
Using version ^1.12 for beyondcode/laravel-websockets
./composer.json has been updated
Running composer update beyondcode/laravel-websockets
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not
 match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by mowses** [comment]
composer have installed for me when I:
- add "beyondcode/laravel-websockets": "^1.12", in composer.json under "require" property;
- run `composer update`.

**Comment by aeremichev** [comment]
> composer have installed for me when I:
> 
> * add "beyondcode/laravel-websockets": "^1.12", in composer.json under "require" property;
> * run `composer update`.

Thank you! It worked.

**Comment by m-mohammadi-developer** [comment]
works thansks a lot

**Comment by siddharth** [comment]
It is compatible with laravel 8 but only upto version 8.17.2. I am on 8.45 and get the following error -

`
  Problem 1
    - The requested package laravel/framework (locked at v8.17.2, required as ^8.45) is satisfiable by laravel/framework[v8.17.2] but these conflict with your requirements or minimum-stability.
`

**Comment by ARSHADKHAN615** [comment]
i face same issue but it worked
thank you so much bro.

**Comment by myckhel** [comment]
> > composer have installed for me when I:
> > 
> > * add "beyondcode/laravel-websockets": "^1.12", in composer.json under "require" property;
> > * run `composer update`.
> 
> Thank you! It worked.

@aeremichev 
If the issue has been solved
i guess you should close the issue.

**Comment by Asadbekinha** [comment]
> composer have installed for me when I:
> 
> * add "beyondcode/laravel-websockets": "^1.12", in composer.json under "require" property;
> * run `composer update`.

thank you, worked properly!
