### ISSUE TITLE
Exist a way to implement webhooks?

### ISSUE THREAD

**Issue by joaokamun** [beyondcode/laravel-websockets#80]
The only missing feature for me fully migrate from pusher is the event webhooks, I could not find anything about it. Is something planned to have? I can contribute to that, just want to know if you guys have something in mind or some direction to follow.

Regards,

**Comment by enzonotario** [comment]
I also want this!
For now (maybe it is a wrong way, but it works) I just have created a class that extends `BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler`, and a custom Router, and put my own logic in certain hooks...

**Comment by stayallive** [comment]
This would be really cool but possibly also tricky looking at the docs it has a few "specialties" that requires some work to make this work correctly.

For example: https://pusher.com/docs/webhooks#delay

Just spit-ballin' here, but it might be a good one to write events to an Redis buffer/list and let another process/cron handle the actual sending to prevent adding to much work to the websocket server process causing it to block more than needed (which also would be an easy-ish way to get batched hook working easily).

**Comment by joaokamun** [comment]
@stayallive So basically the main feature to be develop here could be just an option to save events somewhere (like redis), and each individual project cares about what to do with the events?

**Comment by stayallive** [comment]
@joaokamun well, I would implement a `php artisan websockets:webhooks` command or something like that in this package so you could just add to a cron or daemon running that command which handles all the webhook sending.

**Comment by nicolasvahidzein** [comment]
@stefandanaita You sir are BRILLIANT!!!!!!!!!! This was a lifesaver!!! Thank you so much. Quick question though, do you know i can know which client disconnect from the app when the connection is closed? That's the whole point of extending this package. I need to tell the chat app he is offline after a non graceful log out. Thanks.

**Comment by wmfairuz** [comment]
> @stefandanaita You sir are BRILLIANT!!!!!!!!!! This was a lifesaver!!! Thank you so much. Quick question though, do you know i can know which client disconnect from the app when the connection is closed? That's the whole point of extending this package. I need to tell the chat app he is offline after a non graceful log out. Thanks.

@nicolasvahidzein Did you figured out how to identify user once we extend the WebSocketHandler?

**Comment by noobshooter27** [comment]
Hi,
In my custom onClose function how can I get user's id or username if I use presence channels?

**Comment by rennokki** [comment]
@noobshooter27 The connection can make use of the channel manager and you can get the connection from there.

**Comment by rennokki** [comment]
2.x will contain extendable hooks: https://github.com/beyondcode/laravel-websockets/pull/465

**Comment by hengjingyoong** [comment]
Hi @rennokki , may I know how can I get the private channel name from the `$connection` in my custom `onClose` function?
Tried this `$this->channelManager->getChannels($connection->app->id)`, but it seem like don't have the channel name inside.

**Comment by noobshooter27** [comment]
> Hi @rennokki , may I know how can I get the private channel name from the `$connection` in my custom `onClose` function?
> Tried this `$this->channelManager->getChannels($connection->app->id)`, but it seem like don't have the channel name inside.

try dd($this->channelManager); you'll find everything there

**Comment by rennokki** [comment]
@hengjingyoong Have you called `parent::onClose($connection, $exception)` before anything else in your custom method?

**Comment by hengjingyoong** [comment]
@rennokki, I just used the original WebSocketHandler to test it out.

Thanks @noobshooter27 , finally I managed to find out what is the channel name from the closing connection.

What I did was defined a custom function in `BeyondCode\LaravelWebSockets\WebSockets\Channels\Channel`
```php
    public function checkConnection($socketId)
    {
        if ($this->subscribedConnections[$socketId] ?? null) {
            return $this->channelName;
        }

        return false;
    }
```

and then in `BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler`, get the channel name before it closed.
```php
    public function onClose(ConnectionInterface $connection)
    {
        $allChannels = $this->channelManager->getChannels($connection->app->id);

        foreach($allChannels as $channel){
            if ($channelName = $channel->checkConnection($connection->socketId)) {
                break;
            }
        }
        dd($channelName);

        $this->channelManager->removeFromAllChannels($connection);

        DashboardLogger::disconnection($connection);

        StatisticsLogger::disconnection($connection);
    }
```
But I'm not sure if that is secure to work in this way.

ps: my working scenario is attach the user_id to the private channel name, that's why I need to get back the user_id from channel name, and notify my backend which user is offline.

**Comment by rennokki** [comment]
@hengjingyoong It's highly recommended to not change any `vendor/*` files.

**Comment by hengjingyoong** [comment]
> @hengjingyoong It's highly recommended to not change any `vendor/*` files.

okays, I knew it. 
I do this for testing out my logic only, in real case will stick with the custom WebSocket Handler.
Thanks for remind though.

**Comment by hengjingyoong** [comment]
Finally I figure out how to get the closing channel name. 

Here is it.
```php
<?php

namespace App\WebSocket;

use Ratchet\ConnectionInterface;
use BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler as BaseWebSocketHandler;

class CustomWebSocketHandler extends BaseWebSocketHandler
{
    public function onClose(ConnectionInterface $connection)
    {
        $allChannels = $this->channelManager->getChannels($connection->app->id);

        foreach($allChannels as $channelName => $channel){

            if($channel->getSubscribedConnections()[$connection->socketId] ?? null) {
                $closingChannel = $channel->getChannelName();
                break;
            }
        }

        dd($closingChannel);

        parent::onClose($connection);
    }
}
```

ps: I was missed out the `getSubscribedConnections` function in  `BeyondCode\LaravelWebSockets\WebSockets\Channels\Channel` lol

**Comment by damianed** [comment]
Thank you @hengjingyoong!
I made just had to do some minor changes because it was throwing an error, I will leave it here in case someone else needs it

```php
<?php

namespace App\WebSocket;

use Ratchet\ConnectionInterface;
use BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler as BaseWebSocketHandler;

class CustomWebSocketHandler extends BaseWebSocketHandler
{
    public function onClose(ConnectionInterface $connection)
    {
        $allChannels = $this->channelManager->getChannels($connection->app->id);
        $closingChannel = null;

        foreach($allChannels as $channelName => $channel){

            if($channel->getSubscribedConnections()[$connection->socketId] ?? null) {
                $closingChannel = $channelName;
                break;
            }
        }

        dd($closingChannel);

        parent::onClose($connection);
    }
}
```

**Comment by S1ipKn0T** [comment]
> Thank you @hengjingyoong! I made just had to do some minor changes because it was throwing an error, I will leave it here in case someone else needs it
> 
> ```
> <?php
> 
> namespace App\WebSocket;
> 
> use Ratchet\ConnectionInterface;
> use BeyondCode\LaravelWebSockets\WebSockets\WebSocketHandler as BaseWebSocketHandler;
> 
> class CustomWebSocketHandler extends BaseWebSocketHandler
> {
>     public function onClose(ConnectionInterface $connection)
>     {
>         $allChannels = $this->channelManager->getChannels($connection->app->id);
>         $closingChannel = null;
> 
>         foreach($allChannels as $channelName => $channel){
> 
>             if($channel->getSubscribedConnections()[$connection->socketId] ?? null) {
>                 $closingChannel = $channelName;
>                 break;
>             }
>         }
> 
>         dd($closingChannel);
> 
>         parent::onClose($connection);
>     }
> }
> ```

Hi thank you for your code but I need users data inside of $allChannels how can get it?
(In my case I use presence channel)

**Comment by garrettboone** [comment]
Another approach that is simple is using the custom ArrayChannelManager as indicated in the websockets config, and then make a call like:

```
    public function removeFromAllChannels(ConnectionInterface $connection)
    {
        // THIS ONE LINE
        $response = Http::get(config('app.url') . '/socket-disconnected/' . $connection->socketId . '/{key-for-security}');
        
        if (!isset($connection->app)) {
            return;
        }

       ....

    }

```

In web.php:
```
use App\Http\Controllers\WebsocketController;
Route::get('/socket-disconnected/{socket_id}/{security_key}', [WebsocketController::class, 'socketDisconnected']);
```

Dispatch the desired job in WebsocketController:
```
class WebsocketController extends Controller
{
    public function socketDisconnected(Request $request, string $socket_id, string $security_key)
    {
        logger("Socket id received: " . $socket_id);
        if($security_key == config('websockets.security_key')) {
            ProcessWebsocketDisconnects::dispatch($socket_id);
       }
        return response('OK', 200)->header('Content-Type', 'text/plain');
    }
}
```

**Comment by nicolasvahidzein** [comment]
Thank you @garrettboone I will have to try this soon. Sounds awesome.
