### ISSUE TITLE
 beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.     - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].

### ISSUE THREAD

**Issue by bisnukundu** [beyondcode/laravel-websockets#803]
![image](https://user-images.githubusercontent.com/48401689/125955704-f7dd5a6d-bf44-4baa-bce7-a0edd352a2e3.png)
I can't install laravel-WebSockets. how to solve this problem?. If I use -W then I get another error.
![image](https://user-images.githubusercontent.com/48401689/125955961-a9e26f4f-4b0b-42cb-b242-e9912cfc3376.png)

**Comment by jannejava** [comment]
See https://github.com/beyondcode/laravel-websockets/issues/796#issuecomment-876501668
