### ISSUE TITLE
Delete WebSocket statistics

### ISSUE THREAD

**Issue by afrizal423** [beyondcode/laravel-websockets#819]
hello i want to ask,
First of all, I thank you for your dedication in making this websocket package.
Here I want to delete the statistics in the database, but I can't.
I've used the command ```php artisan websockets:clean ``` the database keeps the previous statistics.
i want to delete how to do with one command?
please see my screenshot https://ibb.co/tx5DrjC

**Comment by calebanthony** [comment]
You can do this pretty easily with Laravel's DB facade:

`DB::table('websockets_statistics_entries')->truncate();`

If you want to access this via Artisan, you should [create a custom command](https://laravel.com/docs/master/artisan#writing-commands).
