### ISSUE TITLE
Failed to connect to Pusher

### ISSUE THREAD

**Issue by matze1708** [beyondcode/laravel-websockets#820]
Hello I have a problem with the extension.
I followed the instructions.
https://beyondco.de/docs/laravel-websockets/basic-usage/pusher

There is pusher-php-server 3.0 installed.

I can access the WebSockets dashboard and connect. 
When I want to send an event, I get the error

`{message: "Failed to connect to Pusher.", exception: "Illuminate\Broadcasting\BroadcastException",…}
exception: "Illuminate\\Broadcasting\\BroadcastException"
file: "/var/www/PhytecCampusServer/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php"
line: 142
message: "Failed to connect to Pusher."`

broadcasting.php

`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http'
            ],
        ],`

websockets.php

` 'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],`

App\Events\GAUpdate.php

`namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class GAUpdate implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public $message;

    public function __construct($message)
    {
        $this->message = $message;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
//        return new PrivateChannel('channel-name');
        return new Channel('GAUpdate');
    }
}`

**Comment by calebanthony** [comment]
Make sure the websockets server is running with `php artisan websockets:serve`.

**Comment by matze1708** [comment]
Hello, thank you for your reply.

I have the service running in the Docker container, on the CLI I see that it is running.

**Comment by matze1708** [comment]
hi, i have been able to get a connection to the pusher.
I looked on the Docker container to see what IP it has.
when I enter this IP 172.18.0.3 in the broadcast.php I don't get an error message anymore.

From external I still have problems. I have to see how I get the workspace container public.
