### ISSUE TITLE
404-Not found when laravel app is sending request to laravel websockets hosted on different server

### ISSUE THREAD

**Issue by ajcastro** [beyondcode/laravel-websockets#832]
Hi. 

We have a laravel api-backend hosted on a separate server and a laravel-websockets app hosted on another separate server. 

The websockets-app is configured on port 443. 
Everytime the api-backend is trigerring a request to websockets-app, I checked `Pusher` is sending a POST request to websocket host which looks like this: `https://websockets.myapp.com:443/apps/my_app/events?auth_key=my_app&auth_signature=XXXXXXXXXXXXXXXXXXX&auth_timestamp=1628835658&auth_version=1.0&body_md5=XXXXXXXXXXX`. This request is resulting to 404-Not found from a html/blade response. 

Here is my guess. It is because the request is being catched by laravel routing because the port used is 443 which is the port for https. 

Should I just use a different port so that the request will be catched by `websockets:serve`?
Or is there a way to still use 443 for websockets?

**Comment by codetestmg** [comment]
@ajcastro  have you got solution.i have same issue
