### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by wrabit** [beyondcode/laravel-websockets#839]
I don't understand the install guide. "Pusher replacement" then goes onto say "Requirements: To make use of the Laravel WebSockets package in combination with Pusher...."

But if it's a replacement as the main title suggests, why would we want to use in combination with Pusher?

https://beyondco.de/docs/laravel-websockets/basic-usage/pusher

**Comment by realtebo** [comment]
It's confusing. But doc it's simply telling you to use this package Pusher  _package_. So you need the usher package but not pusher itself, because your using this very package instead of a real pusher server
