### ISSUE TITLE
Error 404 with wss

### ISSUE THREAD

**Issue by neoacevedo** [beyondcode/laravel-websockets#847]
I can see Laravel Websockets works in HTTP environment, but if I get it in HTTPS, I get the status 404.

`wss://my-domain/app/thekey?protocol=7&client=js&version=7.0.3&flash=false` returns 404
`ws://my-domain/app/scvbmzkmvc?protocol=7&client=js&version=7.0.3&flash=false` works

Moreover, checking in HTTPS, this packages fires all to pusher.com: 
`https://sockjs-mt1.pusher.com/pusher/app/thekey/379/snu3m846/xhr_streaming?protocol=7&client=js&version=7.0.3&t=1630591746626&n=1`

This doesn't happen if I run in local environment (HTTP).

**Comment by stea4lth** [comment]
I'm having the same issue.

**Comment by neoacevedo** [comment]
And no answer.

**Comment by codetestmg** [comment]
I'm having the same issue.
