### ISSUE TITLE
[Feature Request] UI for managing apps and store them in a database table

### ISSUE THREAD

**Issue by vesper8** [beyondcode/laravel-websockets#85]
In an effort to further imitate the services offered by Pusher, and in line with a model where one uses a central websocket server to serve multiple applications across potentially multiple servers, it would be very nice to be able to add/manage apps via an interface, and have the apps stored in a database table, as an alternative to having to modify the websockets.php when needing to add/manage your apps

This could be an optional usage for advanced users and would be backwards compatible with the 'websockets.apps' configuration array

**Comment by masterix21** [comment]
I'm working over this feature, and i will do a pull request asap

**Comment by masterix21** [comment]
https://github.com/beyondcode/laravel-websockets/pull/90
