### ISSUE TITLE
When will the v2 release?

### ISSUE THREAD

**Issue by rakishii13** [beyondcode/laravel-websockets#856]
Is there any potential date for v2 release?

**Comment by imkonsowa** [comment]
+1

**Comment by JonathanGuo** [comment]
+1. I am keen on new [events](https://github.com/beyondcode/laravel-websockets/blob/master/docs/advanced-usage/dispatched-events.md), which could be very handy.

**Comment by mrmsharp** [comment]
+1

**Comment by ariaieboy** [comment]
+1

**Comment by MohinSandhi** [comment]
+1

**Comment by hamransp** [comment]
+1
