### ISSUE TITLE
Lumen Installation, HELP!!

### ISSUE THREAD

**Issue by Enriquez-Johnmark** [beyondcode/laravel-websockets#859]
Can you help me guys, how to install laravel-websocket with lumen. 
I got this error:
In Facade.php line 261:                                                     
  Call to undefined method Laravel\Lumen\Routing\Router::prefix() 

Any inputs will be appreciated, thanks.

**Comment by KNobHack** [comment]
Can you specify where the Facade.php is?

**Comment by louia** [comment]
No
