### ISSUE TITLE
It's been 12hrs exactly. Any help would be appreciated

### ISSUE THREAD

**Issue by SylarRuby** [beyondcode/laravel-websockets#861]
Our app is hosted on ec2. Laravel was deployed though bitbucket pipelines. Our ec2 has a private ip and a public ip: 10.0.0.1 and 52.0.0.1 respectively. I keep getting "404 not found". When stopping the websocket (ws) server, I get "502 bad gateway". I've followed [this guide](https://alex.bouma.blog/posts/installing-laravel-websockets-on-forge-with-ssl/) as this was the last guide to follow.

nginx:

```

# Main block that listens for 443
server {..}

server {
  listen 6002 ssl http2;
  listen [::]:6002 ssl http2;

  # 52.0.0.1 is not that actual IP but I use it for troubleshooting with Postman (the ws section)
  server_name 52.0.0.1;

  # SSL
  ssl_certificate /etc/nginx/ssl/cert.crt;
  ssl_certificate_key /etc/nginx/ssl/key.key;
  ssl_session_timeout         3m;
  ssl_session_cache           shared:SSL:30m;
  ssl_protocols               TLSv1.1 TLSv1.2;
  
  # Diffie Hellmann performance improvements
  ssl_ecdh_curve              secp384r1;

  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options "nosniff";

  location /v2/api/ws {
    proxy_pass             http://127.0.0.1:6001;
    proxy_read_timeout     60;
    proxy_connect_timeout  60;
    proxy_redirect         off;
    
    # Allow the use of websockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location ~ /\.ht {
    deny all;
  }
}
```

config/broadcasting.php:

```
'pusher' => [
    'driver'  => 'pusher',
    'key'     => env('PUSHER_APP_KEY'),
    'secret'  => env('PUSHER_APP_SECRET'),
    'app_id'  => env('PUSHER_APP_ID'),
    'options' => [
        'host'   => '52.0.0.1', # I've tried '127.0.0.1'
        'port'   => 6001,
        'scheme' => 'http',
        'useTLS' => true
    ],
],

```

Then I manually start ws: 

```
php artisan websockets:serve --host=127.0.0.1

```

Using postman with `ws://52.0.0.1/v2/api/ws` I get "404 Not Found". Stopping ws I get "502 bad request". What am I doing wrong? an EC2 issue? Up next I'll spin up DigitalOcean droplet and try.

**Comment by SylarRuby** [comment]
Going to close this as it works at the root and at `/v2/api/ws/`. Why? I'll investigate and blog about it.

**Comment by pesakitan22** [comment]
> SylarRuby

hello, how do you solve this?

**Comment by pesakitan22** [comment]
> Going to close this as it works at the root and at `/v2/api/ws/`. Why? I'll investigate and blog about it.
hello, how do you solve this? @SylarRuby

**Comment by SylarRuby** [comment]
Hi. Honestly I cannot remember. I'm not on the project anymore to have a look. Sorry.
