### ISSUE TITLE
Laravel Websockets in Azure Web Services

### ISSUE THREAD

**Issue by Antsmash** [beyondcode/laravel-websockets#867]
Hello,
I'm hoping someone can help point me to some relevant articles to help us. We're trying to configure Laravel Websockets on our Azure App Service (Currently Windows Based). I have a feeling our difficulties are related to it running on port 6001 and the browser can't get to the Azure service on that port (My understanding App Services only allow 80 and 443). We may have to setup some kind of reverse proxy or similar?

If anyone has any experience doing this in Azure that would be a great help :)

Thanks

**Comment by bajki** [comment]
Also looking for same solution.
