### ISSUE TITLE
removeObsoleteConnections delete all connections that are alive after 2 minutes when messages are being sent to clients

### ISSUE THREAD

**Issue by genesiscz** [beyondcode/laravel-websockets#869]
So this has bugged me for a while, but I finally got it!

After some time (exactly two minutes) the library stopped sending me messages because Laravel Echo/Pusher-js doesn't ping-pong in case there's traffic going on. So the lastPongedAt doesn't get updated, which in turn, deletes the client from the channel connections list and stops sending the messages to that client. I can ping-pong manually, but I feel this is a wider problem and I am shocked nobody actually pointed it out. This should be at least a big red in the documentation.

**Comment by JulianLiu** [comment]
You may want to take a look at this PR
https://github.com/beyondcode/laravel-websockets/pull/778

**Comment by genesiscz** [comment]
> Having the same issue. Did you find any fix?

- I changed it in the vendor folder to not remove them for a day (I am resetting the websocket once a day)
- I started ping ponging manually
