### ISSUE TITLE
Cloudflare, Forge's Load balancer and SSL

### ISSUE THREAD

**Issue by stefandanaita** [beyondcode/laravel-websockets#87]
Has anyone managed to run the websockets server behind Cloudflare (with the orange arrow, not just redirect) which is pointed to a Forge Load balancer (SSL enabled) forwarding the requests to the 6001 port of the server where Websockets is running?

I'm not sure if I need the certificates inside the websockets config as well given that the traffic between the LB and the websockets server is not on SSL 🤔

**Comment by Livijn** [comment]
Cloudflare only allows port 8443 for sockets. Try that port instead, and make sure it is open in Forge.

**Comment by stayallive** [comment]
Check out some notes here: https://alex.bouma.me/installing-laravel-websockets-on-forge/#what-about-cloudflare

But basically choose an (SSL) port they allow: https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

**Comment by AugmentBLU** [comment]
I don't suppose you managed to get this working? I can get everything working locally but receiving 404 when using Cloudflare >  Forge load balancer > app server. I have Cloudflare set to redirecting only, usual options enabled such as allow Websockets. 

I used to have Laravel Echo Server running which worked fine through Cloudflare and the load balancer but I cannot get Larevel-websockets working.
