### ISSUE TITLE
send back response from client to Private Channel

### ISSUE THREAD

**Issue by sirosfakhri** [beyondcode/laravel-websockets#870]
I have a private Channel that dispatch an event and sends data from server to client.
I handle it with `laravel echo` like a charm.
now I want to send back response from my client to server (to channel).
is this possible?
how can I trigger event in js?
how can I handle that in laravel?

**Comment by varunvarde** [comment]
any feedback on this i am facing a similar issue. I am able to send events but i am unable to use the data in laravel to perform operations

**Comment by Dmmoim** [comment]
any update here?
