### ISSUE TITLE
Remote debug dashboard can not connect to websockets-server

### ISSUE THREAD

**Issue by a207052002** [beyondcode/laravel-websockets#871]
I set up the whole stuffs in the official docs.
But in dashboard I still got :
![image](https://user-images.githubusercontent.com/25178377/137401237-fa57d692-41b0-4f49-a2a8-fa16ed1010d9.png)
And nothing appeared in console:
![image](https://user-images.githubusercontent.com/25178377/137401296-2b69de8d-ef9d-40aa-87a3-e0c32f0fd7dd.png)
The required envs is set like:
![image](https://user-images.githubusercontent.com/25178377/137401475-3adb377a-a1f8-49b2-8c70-01ae2eb80087.png)
config/broadcasting.php 
![image](https://user-images.githubusercontent.com/25178377/137401538-aa0dd2b2-34e5-4348-b280-5169192a0059.png)

config/websockets.php
![image](https://user-images.githubusercontent.com/25178377/137401627-e2e0307d-1495-4012-9e82-27d8befdf4fa.png)

the 6001 port is used:
![image](https://user-images.githubusercontent.com/25178377/137401779-906c2e8d-4090-406e-a801-5de936eb678f.png)

And also I added rules for websockets in iptables for 6001 port.
![image](https://user-images.githubusercontent.com/25178377/137402115-91e02060-dcff-4dfd-a9d9-512b2ce015f1.png)
![image](https://user-images.githubusercontent.com/25178377/137402121-3bbbc25f-f142-47c9-9006-4922b48791b2.png)

I'm confused. I saw many people got similar problems but the most are not solved... or the situation is different.

I also tried to debug by comparing my works with [https://www.youtube.com/watch?v=rNOGLLPXzwc](this example), I still can not figure out what I did is wrong.

Sorry if my words are not clear, my native language is not English.

**Comment by StefanNeuser** [comment]
Why they closed this, it's still a issue also for me
