### ISSUE TITLE
Broadcast exception on production but not on local. 

### ISSUE THREAD

**Issue by Pondake** [beyondcode/laravel-websockets#880]
Tried multiple variations of configuration to make it work with nginx so that SSL is allowed ([like this](https://beyondco.de/docs/laravel-websockets/basic-usage/ssl#usage-with-a-reverse-proxy-like-nginx)).

broadcast.php in config folder

 ```
 'pusher' => [
      'driver' => 'pusher',
      'key' => env('PUSHER_APP_KEY'),
      'secret' => env('PUSHER_APP_SECRET'),
      'app_id' => env('PUSHER_APP_ID'),
      'options' => [
          'cluster' => env('PUSHER_APP_CLUSTER'),
          'host' => env('PUSHER_APP_HOST', '127.0.0.1'),
          'port' => env('PUSHER_APP_PORT', 6001),
          'encrypted' => true,
          'scheme' => 'https',
          'debug' => true, // I noticed that pusher 4.1.5 is using debug instead of 'log'
          'curl_options' => [
              CURLOPT_SSL_VERIFYHOST => 0,
              CURLOPT_SSL_VERIFYPEER => 0,
          ],
          'useTLS' => true,
      ],
  ],
```
websockets.php in config folder

```
'apps' => [
    [
        'id' => env('PUSHER_APP_ID'),
        'name' => env('APP_NAME'),
        'key' => env('PUSHER_APP_KEY'),
        'secret' => env('PUSHER_APP_SECRET'),
        'path' => env('PUSHER_APP_PATH'),
        'capacity' => null,
        'enable_client_messages' => true,
        'enable_statistics' => true,
        'encrypted' => true,
    ],
],

'ssl' => [
    'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),
    'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),
    'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
    'verify_peer' => false,
    'allow_self_signed' => true
],
```

.env file in root

```
BROADCAST_DRIVER=pusher
PUSHER_APP_ID=**
PUSHER_APP_KEY=**
PUSHER_APP_SECRET=**
PUSHER_APP_CLUSTER=mt1
PUSHER_APP_HOST="**" // the url websockets is hosted on, verified working on "wss" by checking the dashboard
PUSHER_APP_PORT="443"

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```
Notice that local_cert is not applied here. That's because that's not available through the chosen hosting. 

app.js (which usually is bootstrap.js)

```
window.Echo = new Echo({
      broadcaster: 'pusher',
      key: key, // entry in env
      cluster: cluster, // entry in env
      wsHost: host, // entry in env
      wssHost: host, // entry in env
      wsPort: port, // entry in env
      wssPort: port, // entry in env
      encrypted: true,
      forceTLS: true,
      enabledTransports: ['ws','wss'],
  });
```

Connecting with the public channel through laravel Echo works fine, but upon sending a message it gives a fat 404 through laravel Horizon. 

![image](https://user-images.githubusercontent.com/4643209/140347670-b783dca0-c7cd-45c4-88f2-ad9ffd9845e2.png)

Locally it works perfect with or without HTTPS using valet. I have spent more than a week at this but I'm starting to get clueless.

**Comment by Pondake** [comment]
Turn out I had to configure broadcasting.php through http (and everything als secure) as kubernetes was set-up for http locally/internally. I unfortunately ran into another problem that the server doesn't work in multiple pods. Anyhow, that's the solution for this issue.

**Comment by bayf** [comment]
I am experiencing almost the same issue.
Please could you share broadcasting.php setup that worked for you?
Thanks.
