### ISSUE TITLE
Laravel Websockets Failed to connect to Pusher (on production only)

### ISSUE THREAD

**Issue by allamo123** [beyondcode/laravel-websockets#887]
Am using [Laravel Websockets Package][1] for real time application on localhost everything work perfect but on production i have some issues.

I run websockets through supervisor on centos, i can can access to Laravel websockets Debug Dashboard and connect successfully which mean that laravel websocket run in the background.

[![enter image description here][2]][2]

when I Triger an event i get error **Failed to connect to Pusher.**

[![enter image description here][3]][3]

**Route to test event**

    Route::get('test-event', function(){
        event(new NewMessage('hello'));
    });
--------------------------------------------------------------------------------------------------

**app/Events/NewMessage**

    <?php
    
    namespace App\Events;
    
    use Illuminate\Broadcasting\Channel;
    use Illuminate\Broadcasting\InteractsWithSockets;
    use Illuminate\Broadcasting\PresenceChannel;
    use Illuminate\Broadcasting\PrivateChannel;
    use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
    use Illuminate\Foundation\Events\Dispatchable;
    use Illuminate\Queue\SerializesModels;
    
    class NewMessage implements ShouldBroadcast
    {
        use Dispatchable, InteractsWithSockets, SerializesModels;
    
        /**
         * Create a new event instance.
         *
         * @return void
         */
    
    
        public $message;
    
        public function __construct($message)
        {
            $this->message  =   $message;
        }
    
        /**
         * Get the channels the event should broadcast on.
         *
         * @return \Illuminate\Broadcasting\Channel|array
         */
        public function broadcastOn()
        {
            return new Channel('chat-test');
        }
    }

Am also check the network for listening it seems that laravel websocket run correctly
[![enter image description here][4]][4]

so my last step to solve pusher connection when event fire !!

**package.json**

    "laravel-echo": "^1.11.3",
    "pusher-js": "^7.0.3"

**composer.json**

    "pusher/pusher-php-server": "^4.1.3" //i try to work with this version but when i run composer it install version v4.1.5

**.env**

    BROADCAST_DRIVER=pusher
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    PUSHER_APP_ID=my-app-id
    PUSHER_APP_KEY=my-app-key
    PUSHER_APP_SECRET=my-app-secret
    PUSHER_APP_CLUSTER=mt1
    
    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    
    LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT="/home/my-user/<cetification_path>/my-cert.crt"
    LARAVEL_WEBSOCKETS_SSL_LOCAL_PK="/home/my-user/<cetification_key_path>/my-key.key"

**config/websockets.php**

    <?php
    
    use BeyondCode\LaravelWebSockets\Dashboard\Http\Middleware\Authorize;
    
    return [
    
        /*
         * Set a custom dashboard configuration
         */
        'dashboard' => [
            'port' => env('LARAVEL_WEBSOCKETS_PORT', 6001),
        ],
    
        /*
         * This package comes with multi tenancy out of the box. Here you can
         * configure the different apps that can use the webSockets server.
         *
         * Optionally you specify capacity so you can limit the maximum
         * concurrent connections for a specific app.
         *
         * Optionally you can disable client events so clients cannot send
         * messages to each other via the webSockets.
         */
        'apps' => [
            [
                'id' => env('PUSHER_APP_ID'),
                'name' => env('APP_NAME'),
                'key' => env('PUSHER_APP_KEY'),
                'secret' => env('PUSHER_APP_SECRET'),
                // 'path' => env('LARAVEL_WEBSOCKETS_PATH', 'laravel-websockets'),
                'capacity' => null,
                'enable_client_messages' => false,
                'enable_statistics' => true,
            ],
        ],
    
        /*
         * This class is responsible for finding the apps. The default provider
         * will use the apps defined in this config file.
         *
         * You can create a custom provider by implementing the
         * `AppProvider` interface.
         */
        'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,
    
        /*
         * This array contains the hosts of which you want to allow incoming requests.
         * Leave this empty if you want to accept requests from all hosts.
         */
        'allowed_origins' => [
            //
        ],
    
        /*
         * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
         */
        'max_request_size_in_kb' => 250,
    
        /*
         * This path will be used to register the necessary routes for the package.
         */
        'path' => 'laravel-websockets',
    
        /*
         * Dashboard Routes Middleware
         *
         * These middleware will be assigned to every dashboard route, giving you
         * the chance to add your own middleware to this list or change any of
         * the existing middleware. Or, you can simply stick with this list.
         */
        'middleware' => [
            'web',
            Authorize::class,
        ],
    
        'statistics' => [
            /*
             * This model will be used to store the statistics of the WebSocketsServer.
             * The only requirement is that the model should extend
             * `WebSocketsStatisticsEntry` provided by this package.
             */
            'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,
    
            /**
             * The Statistics Logger will, by default, handle the incoming statistics, store them
             * and then release them into the database on each interval defined below.
             */
            'logger' => BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger::class,
    
            /*
             * Here you can specify the interval in seconds at which statistics should be logged.
             */
            'interval_in_seconds' => 60,
    
            /*
             * When the clean-command is executed, all recorded statistics older than
             * the number of days specified here will be deleted.
             */
            'delete_statistics_older_than_days' => 60,
    
            /*
             * Use an DNS resolver to make the requests to the statistics logger
             * default is to resolve everything to 127.0.0.1.
             */
            'perform_dns_lookup' => false,
        ],
    
        /*
         * Define the optional SSL context for your WebSocket connections.
         * You can see all available options at: http://php.net/manual/en/context.ssl.php
         */
        'ssl' => [
            /*
             * Path to local certificate file on filesystem. It must be a PEM encoded file which
             * contains your certificate and private key. It can optionally contain the
             * certificate chain of issuers. The private key also may be contained
             * in a separate file specified by local_pk.
             */
            'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),
    
            /*
             * Path to local private key file on filesystem in case of separate files for
             * certificate (local_cert) and private key.
             */
            'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),
    
            /*
             * Passphrase for your local_cert file.
             */
            'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
            
            'verify_peer' => false,
            
        ],
    
        /*
         * Channel Manager
         * This class handles how channel persistence is handled.
         * By default, persistence is stored in an array by the running webserver.
         * The only requirement is that the class should implement
         * `ChannelManager` interface provided by this package.
         */
        'channel_manager' => \BeyondCode\LaravelWebSockets\WebSockets\Channels\ChannelManagers\ArrayChannelManager::class,
    ];
**config/broadcasting.php**

    'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => true,
                'host' => 'my-domain-name',
                'port' => 6001,
                'scheme' => 'https',
            ],
            'curl_options' => [
                CURLOPT_SSL_VERIFYHOST => 0,
                CURLOPT_SSL_VERIFYPEER => 0,
            ],
            // 'verify_peer' => false,
        ],

**resources/js/bootstrap.js**

        window._ = require('lodash');
    
    /**
     * We'll load jQuery and the Bootstrap jQuery plugin which provides support
     * for JavaScript based Bootstrap features such as modals and tabs. This
     * code may be modified to fit the specific needs of your application.
     */
    
    try {
        window.Popper = require('popper.js').default;
        window.$ = window.jQuery = require('jquery');
    
        require('bootstrap');
    } catch (e) {}
    
    /**
     * We'll load the axios HTTP library which allows us to easily issue requests
     * to our Laravel back-end. This library automatically handles sending the
     * CSRF token as a header based on the value of the "XSRF" token cookie.
     */
    
    window.axios = require('axios');
    
    window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
    
    /**
     * Echo exposes an expressive API for subscribing to channels and listening
     * for events that are broadcast by Laravel. Echo and event broadcasting
     * allows your team to easily build robust real-time web applications.
     */
    
     import Echo from 'laravel-echo';
    
     window.Pusher = require('pusher-js');
     
     window.Echo = new Echo({
         broadcaster: 'pusher',
         key: process.env.MIX_PUSHER_APP_KEY,
         wsHost: window.location.hostname,
         wsPort: 6001,
         wssPort: 6001,
         forceTLS: true,
         disableStats: true,
         enabledTransports: ['ws','wss'],
     });

It's work perfect on localhost without ssl and without supervisor but i face this error 
**Failed to connect to Pusher.** on production only when i use ssl

***Thank you for your help in advance.***

  [1]: https://beyondco.de/docs/laravel-websockets/basic-usage/pusher
  [2]: https://i.stack.imgur.com/TJs4T.jpg
  [3]: https://i.stack.imgur.com/609nR.png
  [4]: https://i.stack.imgur.com/WhXz1.png

**Comment by allamo123** [comment]
@rennokki

**Comment by allamo123** [comment]
issue has been solved by adding the curl options inside options not outside

**Comment by anwardote** [comment]
@allamo123 

I am getting same issue. I tried same the same as you mentioned. but I think, it is nginx virutal host problem.. can you please share virtual hosting settings?
