### ISSUE TITLE
No App in dashboard

### ISSUE THREAD

**Issue by mklanderman** [beyondcode/laravel-websockets#89]
I've tried to get websockets up and running, but I'm not able to get the "App" selector in the websockets-dashboard populated with any App name.

In .env I have:
APP_NAME=Laravel
PUSHER_APP_ID=1
PUSHER_APP_KEY=b9f65c07-3aaf-4c2d-8301-683c0a340365
PUSHER_APP_SECRET=secret
PUSHER_APP_CLUSTER=

(I will update key and secret once it works, this is just as an example of what I have now)

In config/websockets.php I have:
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => false,
            'enable_statistics' => true,
        ],
    ],

But for some reason the dashboard is not showing any App to select or connect to.
The websockets server is up and running showing "Starting the WebSocket server on port 6001..."

I hope someone can help me get this up and running.

**Comment by mklanderman** [comment]
Yes, I have. It appears after a few seconds.

Didn't see it before:

content_script_bundle.js:13 Uncaught (in promise) ReferenceError: currentURL is not defined
    at then.catch.e (content_script_bundle.js:13)

**Comment by masterix21** [comment]
What is your PHP version?

**Comment by mklanderman** [comment]
PHP 7.1.19

**Comment by kudjieRaymond** [comment]
In your .env file make sure you change your broadcast driver from log to pusher.
BROADCAST_DRIVER=pusher

**Comment by xlcrr** [comment]
Try clearing your config cache

php artisan config:clear

**Comment by mklanderman** [comment]
Thanks for the help. In the end I made new config file and all works.
