### ISSUE TITLE
Do you plan to support Laravel 5.5 

### ISSUE THREAD

**Issue by GERJohnson** [beyondcode/laravel-websockets#9]
I am running Laravel 5.5 and get following error when installing the package:

`beyondcode/laravel-websockets 1.0.0 requires illuminate/routing 5.7.* -> satisfiable by illuminate/routing[v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
`

Do you plan to support Laravel 5.5. in future?

Thx, Johnson

**Comment by mpociot** [comment]
No we do not plan to add Laravel 5.6 or lower support. 
The package makes use of the new Guest user gate that was added in 5.7: https://laravel.com/docs/5.7/authorization#guest-users
