### ISSUE TITLE
laravel-websockets with spatie / laravel-multitenancy

### ISSUE THREAD

**Issue by sys-auditing** [beyondcode/laravel-websockets#905]
Hi,

how can i integrate your package with `laravel-multitenancy`, noting that i'm using `multi databases` approach?

Any help will be appreciated.

Thanks

**Comment by yashiroiori** [comment]
I use other package, into websocket server make a provider and into tenant server make a pusher custom Broadcaster to work

https://tenancyforlaravel.com/

**Comment by penh** [comment]
@yashiroiori How did you config? can you detail how to config i face problem config does not work ?
