### ISSUE TITLE
Incorrect error reporting by laravel-websokets

### ISSUE THREAD

**Issue by Scarle-t** [beyondcode/laravel-websockets#909]
We have encountered an issue when starting the websocket server using ```php artisan websockets:serve```
while we were investigating the issue for hours with the given clue (which is truncated in laravel.log): "Class Pusher error", we focused on any code error on our side that could possibly cause this error.
At the end we found out it is due to laravel-websockets do not have permission to access the SSL certificate, and we only found that out by checking nginx and php error log seeing "SSL handshake error".

Please fix the error reporting by providing some useful error and stacktrace, as well as display errors when it hit these kind of fatal error, what I can only see from running the command is: "Starting the WebSocket server on port 6001" and no error.

**Comment by PaolaRuby** [comment]
Feel free to make a PR
