### ISSUE TITLE
iOS Integration

### ISSUE THREAD

**Issue by sam961** [beyondcode/laravel-websockets#91]
I initialized my local server and it seems working.
Now I tried to work in the ios application using PUSH SDK

```
    override func viewDidLoad() {
        super.viewDidLoad()
        let options = PusherClientOptions(
            host: .host("ws://127.0.0.1"),
            port : 6001
        )
         pusher = Pusher(key: "myKey", options: options)
                pusher.delegate=self
        pusher.connect()
    }
```

But the status of the connection is always connecting...disconnected

**Comment by stayallive** [comment]
If you are using the simulator this [should work](https://stackoverflow.com/a/6077929/1580028) but you might need `localhost` instead of `127.0.0.1`.

But if you are using a real device you need the IP of the machine the websockets server is running inside your network (and make sure your Mac has no firewall active to block the connection).

**Comment by sam961** [comment]
@stayallive 
Iam using the simulator  and the change the code to : 
`let options = PusherClientOptions(
            host: .host("ws://localhost:6001")
        )`
        ` pusher = Pusher(key: "myKey", options: options)
                pusher.delegate=self`
       ` pusher.connect()`

and the  configration on the server is : 
`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => 'localhost',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],`

bootstrap.js : 
`import Echo from 'laravel-echo'`
`window.Pusher = require('pusher-js');`
`window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'myKey',
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    disableStats: true,
    encrypted: true
});`

But still same issue

**Comment by stayallive** [comment]
@sam961 try it with:

```swift
let options = PusherClientOptions(
    host: .host("localhost"),
    port: 6001,
    encrypted: false
)
```

That seems to work for me 👍

**Comment by sam961** [comment]
Guess what ? 
It is working  :D Thank you

**Comment by stayallive** [comment]
Awesome! Than you can close this issue 💯

**Comment by anilios** [comment]
Can someone please help with the connection, I am trying got connect using Pusher Swift but the connection never gets connected.

`let options = PusherClientOptions(
            autoReconnect: true,
            host: .host("https://xyz.com"), //This is the server where web socket is working just fine.
            port: 6001
        )
        //Key is not actual key from Pusher, this is just some string that is set up on the server. Do we need to actually buy a key to make this work?
        let pusher = Pusher(key: "ChatAppKey", options: options)
        pusher.delegate=self
        pusher.connect()`

**Comment by AugmentBLU** [comment]
Has anyone managed to get this working with Pusher iOS Swift SDK? 

If so, I'd be interested in how you managed to get it working. I am willing to pay to get a working example with the server I have setup.
