### ISSUE TITLE
Action BeyondCode\LaravelWebSockets\Statistics\Http\Controllers\WebSocketStatisticsEntriesController@store not defined.

### ISSUE THREAD

**Issue by kenith8** [beyondcode/laravel-websockets#910]
Can't access (127.0.0.1:8000/laravel-websockets) dashboard

**Comment by kenith8** [comment]
when I run "php artisan websockets:serve" command, it displays this error . . . 
 
InvalidArgumentException 

  Action BeyondCode\LaravelWebSockets\Statistics\Http\Controllers\WebSocketStatisticsEntriesController@store not defined.

  at vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:483
    479▕      */
    480▕     public function action($action, $parameters = [], $absolute = true)
    481▕     {
    482▕         if (is_null($route = $this->routes->getByAction($action = $this->formatAction($action)))) {
➜ 483▕             throw new InvalidArgumentException("Action {$action} not defined.");
    484▕         }
    485▕ 
    486▕         return $this->toRoute($route, $parameters, $absolute);
    487▕     }

      +22 vendor frames 
  23  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by erikn69** [comment]
Maybe try this example `https://github.com/beyondcode/laravel-websockets-demo/pull/22`

**Comment by rstriquer** [comment]
Hi there. Newbie websocket guy here! Is there any prevision for when the PR #22 will be ready to production? Thanks.

**Comment by kenith8** [comment]
> Maybe try this example `https://github.com/beyondcode/laravel-websockets-demo/pull/22`
