### ISSUE TITLE
Support custom logger to write logs

### ISSUE THREAD

**Issue by KingWu** [beyondcode/laravel-websockets#917]
Just investigate how to define custom logger to log the correction information into a single file. Found that `laravel-websockets` do not support to define a custom connection logger / websocket logger. 

We wanna to define the laravel logger to handle logging in a centralized way.

Will support custom logger in the future?

**Comment by LAGGOUNE-Walid** [comment]
Hello , is suggest creating custom hanlder https://beyondco.de/docs/laravel-websockets/advanced-usage/custom-websocket-handlers
and on each event (onOpen, onMessage ...) keep the base functionalities , and you could inject your custom Logger there.
