### ISSUE TITLE
pusher/pusher-php-server 7.0 support !

### ISSUE THREAD

**Issue by farshidpg** [beyondcode/laravel-websockets#919]
plz support for pusher/pusher-php-server 7.0

**Comment by erikn69** [comment]
There is support
https://github.com/beyondcode/laravel-websockets/blob/fd2070fc3d28696247acceacc4f40667828f3016/composer.json#L43

**Comment by diazsasak** [comment]
hi @erikn69 , i got this error. i think the documentation is outdated, it ask to install pusher php 3.0 , and 


![image](https://user-images.githubusercontent.com/7880137/151735974-ce1d2bd4-0bee-4217-b7ae-84d5f53496ac.png)

**Comment by diazsasak** [comment]
![image](https://user-images.githubusercontent.com/7880137/151736161-e3ae3bcd-0898-4128-bbc7-4067f2511bf5.png)

**Comment by erikn69** [comment]
Use the dev branch
