### ISSUE TITLE
Can't get SSL to work

### ISSUE THREAD

**Issue by eminos** [beyondcode/laravel-websockets#92]
I've tried following the docs, both the first SSL related sections and the Valet specific settings.
I'm running on a cPanel server with Let's Encrypt cert.

Without HTTPS on the site and "encrypted: true" for Echo, laravel-websockets works fine!

The websockets.php config file comment says "Path to local certificate file on filesystem. It must be a PEM encoded file which contains your certificate and private key." 

I'm not sure that the file contains both the certificate and private key. Is there a way to check?

I also tried creating a separate key file on the cPanel server and using that in websockets.php. Not sure if that is supposed to work. Are the cert and key file supposed to be created at the same time?

php artisan websockets:serve always works ("Starting the WebSocket server on port 6003..."), no matter the config and even misspelled cert file paths. Is there a way to get some feedback in the console if the SSL settings / cert works as expected or not? I've tried --debug, but no difference.

I'm using the Pusher settings with Echo and with port 6003.
Getting this error in the browser: 
`WebSocket connection to 'wss://removed-domain.com:6003/app/6c8c855975c5f6c4ad88?protocol=7&client=js&version=4.3.1&flash=false' failed: WebSocket is closed before the connection is established.`

If I stop the websockets server, I get `connection refused` error. So it seems it's trying to connect to the websockets server correctly.

I think I've tried all the suggested server and client settings, from the SSL related issues here.

I'm suspecting something is wrong with my cert (although it works fine for HTTPS with Apache), but I don't know how to investigate further. I'm stuck.

Does anyone have some clues?

**Comment by eminos** [comment]
I have now also tried with a self-signed certificate, from within cPanel. That way I get both a cert file and a key file. Set the file paths in websockets.php and restarted `websockets:serve`.

Now I'm getting two different errors in the browser (random every time I reload the browser):

`Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`
or
`WebSocket is closed before the connection is established.` (same as before)

I've tried with Echo setting `encrypted` both true and false. Seems no difference.

**Comment by kerrsmith** [comment]
I posted the following this morning to another similar question, the link below may help:

https://github.com/beyondcode/laravel-websockets/issues/86#issuecomment-455128488

The Let's Encrypt certificates are usually named as follows:

cert.pem ----------> this is the certificate file
chain.pem ----------> this is the chain file
fullchain.pem ----------> this is the certificate and chain in one file
privkey.pem ----------> this is the private key

In config/websockets.php use the following:

'local_cert' use full path to fullchain.pem
'local_pk' use use full path to privkey.pem

Also, make sure these two files can be read by the user (maybe www-data for example) that is running the Laravel website. If you are not sure about this and have everything else set up as described above (and it still does not work) then copy these two needed key files to your home directory and (as a test) set the permissions to allow full access (777). If the SSL then starts to work you will know it is a permission issue.

I got SSL working by doing the 'Usage with Laravel Valet' setup exactly as shown in the documentation, the only other thing I needed was to add 'perform_dns_lookup' => true in config/websockets.php and also give access to the certificates to my Laravel domain user.

**Comment by eminos** [comment]
Well, I'm using a cPanel plugin (Let's Encrypt for cPanel) to generate and install the Let's Encrypt certificate. It seems it's not generating, or at least not creating, a private key file.
Out of those four files you're mentioning I'm only seeing one (the cert I presume).

I have contacted the developer of the cPanel plugin to see if he can help me find the cert **and** private key file.

I have tried the Laravel Valet settings from the docs as well. At this point I'm fairly certain there's something wrong with the server/certificate setup. **I wish the server could validate the SSL config on startup and give some info if something is not correct, right away.** Right now it's hard to troubleshoot when you don't really know if it's the server or the client that's "faulty".

Isn't the `perform_dns_lookup` setting related to statistics? I don't see that having an impact on SSL? Maybe someone could confirm.

**Comment by kerrsmith** [comment]
Yes, I you are correct about the DNS lookup - I just wanted to give all the things I did to get it working completely.

If you are missing a certificate then that would explain it not working correctly. If you are creating a certificate for the domain then you could just visit the secure version of the website (https) and that would show whether the certificate was actually created and working.

If the secure version of website works then the certificates are there and working, it would then just be a matter of actually locating them in the file system and adding the correct paths to websockets.php.

**Comment by cjguajardo** [comment]
Could you share your config please, I'm having the same problem i think.

**Comment by eminos** [comment]
@cjguajardo It's just the Laravel Valet setup from the docs:
https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#usage-with-laravel-valet

My issue was actually using the correct crt and key files, which is very specific in my case since I'm using cPanel with FleetSSL (Let's Encrypt) plugin.

**Comment by lukadriel7** [comment]
Hello to you all. I have read in all the places I could find and tried everything. Since I couldn't get it to work I post here. I am using laravel websockets which works great with http. To test for https, I made a self signed certificate using openssl following command:
`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /var/www/cert/key.pem -out /var/www/cert/certificate.pem`.
I then proceeded to follow the tutorial for laravel valet with no result. The websocket server simply doesn't start. I tried moving the certificate and key file, giving full access and all. Nothing seems to work.
my configuration files are the same as in [https://docs.beyondco.de/laravel-websockets/1.0/basic-usage/ssl.html#server-configuration](url) except for the paths.
The error output on the server start is as follow :
Exception `RuntimeException` thrown: `Unable to read from stream: stream_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate`
Can anyone help me ? 
Thank you very much in advance.

**Comment by kerrsmith** [comment]
Looking at the error ('alert bad certificate') it appears to be a problem with the certificate.

I would suggest trying to use Let's Encrypt to create a certificate, this will generate a valid certificate that will work without any errors / warnings being thrown about self signed certificates. Let's Encrypt is completely free and the certificates it generates are accepted by all browsers so you get the green padlock symbol (or equivalent) showing when accessing the site.

I would give this a try first and see if you get a better outcome with a Let's Encrypt certificate.

**Comment by lukadriel7** [comment]
Thank you for your answer. The thing is I use let's encrypt on my production server. I don't have a certificate for my development machine beside my self signed one. I tried using let's encrypt for my local machine with no success due to the domain name not being supported. Also The let's encrypt website recommended using openssl for local development [https://letsencrypt.org/docs/certificates-for-localhost/](url). 
My certificate has no problem in the browser beside being indicated has self signed. 
I will however try to acquire a certificate from let's encrypt again for my localhost and come back to you.

**Comment by kerrsmith** [comment]
If it is not possible for you to test your code on your production server then you can get a 'real' certificate for your local server but it will need to be accessible from the internet using a domain name so Let's Encrypt can validate it as part of the certificate generation process.

I used to have a testing machine at home with Linux (Apache, PHP and MySQL etc) on it - all you need to do is make sure a domain name points to your local (home) IP address and then use port forwarding to allow your local server to be accessed from the internet.

Obviously this will take some setting up but it is one option that may be worth a try if you really can not get your code to work with a self signed certificate.

This, of course, may not be the issue. It could be your code just needs some other setting added or removed to make it work - unfortunately I am not sure about this as I have not tried to do what you are attempting.

**Comment by lukadriel7** [comment]
Hey, I succeeded in using websockets. I Changed my certificate to the one on my production server (surely not recommended but I needed to test). Using the same configuration as with laravel valet.
I also changed my local server name to my development servername and redirected traffic to my website domain name to localhost(127.0.0.1) by editing /etc/hosts. Thank you for your help. 
P.S. : It would be great if laravel-websocket could use self-signed certificate

**Comment by kerrsmith** [comment]
That's great - it is also very helpful for others to know a different way of getting it to work on a local testing machine - using the /etc/hosts file to direct the domain name to the local machine and a certificate generated on a different machine for that domain.

**Comment by simonhamp** [comment]
I'm using Laravel Valet and cannot get SSL to work at all. Then when downgrading to HTTP-only, I can't seem to hear any events.

Holding onto hope 😅

**Comment by bArraxas** [comment]
Hi, this is a bit dated but I think it helped a few.
If you encounter the same problem as "emios", it is that you forgot an additional parameter to add in "websockets.php / sll". Here is the setting: "'verify_peer' => false"
I'm on window with XAMPP and certification auto signed generated by XAMPP. All work perfectly and the documentation of "beyondco/laravel-websockets" is correct.

**Comment by mantiz8x** [comment]
Hi, I finally got it to work with SSL, but got a new problem now.
Everything is working fine when I run php artisan websocket:serve from the project directory.
But when I run it using supervisor, I am getting an ERR_SSL_VERSION_OR_CIPHER_MISMATCH error.
Can someone help me find out what's wrong? 
Here's my supervisord conf:

```
[program:websockets]
command=/usr/bin/php /var/www/project-name/artisan websocket:serve
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/www/project-name/storage/logs/socketerr.log
stdout_logfile=/var/www/project-name/storage/logs/socketout.log
user=ubuntu
```

It is working fine when I run the command `/usr/bin/php /var/www/project-name/artisan websocket:serve` from the directory as well. The issue is only when it's run through supervisor.

**Comment by theabhisheksingh** [comment]
I have facing same issue, whenever i installed SSL, WebSocket not working, Channels current state is unavailable
Can you please guide me ?
How can i Fix?

**Comment by bArraxas** [comment]
Here my .env if it could help : 

  LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=C:\xampp\apache\conf\ssl.crt\server.crt
  LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=C:\xampp\apache\conf\ssl.key\server.key
  LARAVEL_WEBSOCKETS_SSL_PASSPHRASE=bibibaba
  LARAVEL_WEBSOCKETS_VERIFY_PEER=false

**Comment by theabhisheksingh** [comment]
its problem on aws and I am using lets encrypt

**Comment by mantiz8x** [comment]
Try using the path to the actual key files rather than the symlinks. I think this worked in my case.

**Comment by DengSihan** [comment]
Thanks to [@kerrsmith ](https://github.com/beyondcode/laravel-websockets/issues/92#issuecomment-455192084) and [elhaouari-mohammed](https://github.com/beyondcode/laravel-websockets/issues/109#issuecomment-467412706), I fix this problem, and here are points needed to be pay special attention:

（I am using **Lets Encrypt**）

1. `configs/broadcasting.php`:
```php
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],
```

2. `configs/websockets.php`
```php
    'ssl' => [

        'local_cert' => env('SSL_CERT', null),

        'local_pk' => env('SSL_PK', null),

        'passphrase' => env('JWT_SECRET', null),

        'verify_peer' => false,
    ],
```

3. `.env`
```.env
SSL_CERT=/etc/letsencrypt/live/example.com/fullchain.pem
SSL_PK=/etc/letsencrypt/live/example.com/privkey.pem
```

4. on client side
```js
        window.ECHOR = new Echo({
            broadcaster: 'pusher',
            key: process.env.MIX_PUSHER_APP_KEY,
            wsHost: window.location.hostname,
            wsPort: 6001,
            wssPort: 6001,
            disableStats: true,
            enabledTransports: ['ws', 'wss'],

            // I am using jwt, if you are not, ignore this
            auth: {
                headers: {
                    Authorization: `${store.state.auth.token.token_type} ${store.state.auth.token.access_token}`
                }
            }
        });
```

**Comment by alansary** [comment]
### This worked for me

**broadcasting.php**
`
return [

    /*
    |--------------------------------------------------------------------------
    | Default Broadcaster
    |--------------------------------------------------------------------------
    |
    | This option controls the default broadcaster that will be used by the
    | framework when an event needs to be broadcast. You may set this to
    | any of the connections defined in the "connections" array below.
    |
    | Supported: "pusher", "redis", "log", "null"
    |
    */

    'default' => env('BROADCAST_DRIVER', 'null'),

    /*
    |--------------------------------------------------------------------------
    | Broadcast Connections
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the broadcast connections that will be used
    | to broadcast events to other systems or over websockets. Samples of
    | each available type of connection are provided inside this array.
    |
    */

    'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 8443,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

        'log' => [
            'driver' => 'log',
        ],

        'null' => [
            'driver' => 'null',
        ],

    ],

];
`

**websockets.php**
`
return [

    /*
     * Set a custom dashboard configuration
     */
    'dashboard' => [
        'port' => env('LARAVEL_WEBSOCKETS_PORT', 8443),
    ],

    /*
     * This package comes with multi tenancy out of the box. Here you can
     * configure the different apps that can use the webSockets server.
     *
     * Optionally you specify capacity so you can limit the maximum
     * concurrent connections for a specific app.
     *
     * Optionally you can disable client events so clients cannot send
     * messages to each other via the webSockets.
     */
    'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'path' => env('PUSHER_APP_PATH'),
            'capacity' => null,
            'enable_client_messages' => true,
            'enable_statistics' => true,
            'encrypted' => true,
        ],
    ],

    /*
     * This class is responsible for finding the apps. The default provider
     * will use the apps defined in this config file.
     *
     * You can create a custom provider by implementing the
     * `AppProvider` interface.
     */
    'app_provider' => BeyondCode\LaravelWebSockets\Apps\ConfigAppProvider::class,

    /*
     * This array contains the hosts of which you want to allow incoming requests.
     * Leave this empty if you want to accept requests from all hosts.
     */
    'allowed_origins' => [
        //
    ],

    /*
     * The maximum request size in kilobytes that is allowed for an incoming WebSocket request.
     */
    'max_request_size_in_kb' => 250,

    /*
     * This path will be used to register the necessary routes for the package.
     */
    'path' => 'laravel-websockets',

    /*
     * Dashboard Routes Middleware
     *
     * These middleware will be assigned to every dashboard route, giving you
     * the chance to add your own middleware to this list or change any of
     * the existing middleware. Or, you can simply stick with this list.
     */
    'middleware' => [
        'web',
        Authorize::class,
    ],

    'statistics' => [
        /*
         * This model will be used to store the statistics of the WebSocketsServer.
         * The only requirement is that the model should extend
         * `WebSocketsStatisticsEntry` provided by this package.
         */
        'model' => \BeyondCode\LaravelWebSockets\Statistics\Models\WebSocketsStatisticsEntry::class,

        /**
         * The Statistics Logger will, by default, handle the incoming statistics, store them
         * and then release them into the database on each interval defined below.
         */
        'logger' => BeyondCode\LaravelWebSockets\Statistics\Logger\HttpStatisticsLogger::class,

        /*
         * Here you can specify the interval in seconds at which statistics should be logged.
         */
        'interval_in_seconds' => 60,

        /*
         * When the clean-command is executed, all recorded statistics older than
         * the number of days specified here will be deleted.
         */
        'delete_statistics_older_than_days' => 60,

        /*
         * Use an DNS resolver to make the requests to the statistics logger
         * default is to resolve everything to 127.0.0.1.
         */
        'perform_dns_lookup' => false,
    ],

    /*
     * Define the optional SSL context for your WebSocket connections.
     * You can see all available options at: http://php.net/manual/en/context.ssl.php
     */
    'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),

        'verify_peer' => false,

        'allow_self_signed' => true,
    ],

    /*
     * Channel Manager
     * This class handles how channel persistence is handled.
     * By default, persistence is stored in an array by the running webserver.
     * The only requirement is that the class should implement
     * `ChannelManager` interface provided by this package.
     */
    'channel_manager' => \BeyondCode\LaravelWebSockets\WebSockets\Channels\ChannelManagers\ArrayChannelManager::class,
];

`

**bootstrap.js**
```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true,
    wsHost: window.location.hostname,
    wsPort: 8443,
    wssPort: 8443,
    forceTLS: true,
    disableStats: false,
    enabledTransports: ['ws', 'wss']
});
```

**.env**
```
BROADCAST_DRIVER=pusher
APP_URL_BASE=DOMAIN_NAME_HERE
APP_URL=https://${APP_URL_BASE}
LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=/etc/letsencrypt/live/DIR_NAME_HERE/fullchain.pem
LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=/etc/letsencrypt/live/DIR_NAME_HERE/privkey.pem
```

**/etc/supervisorctl/conf.d/websockets.conf**
```
[program:websockets]
process_name=%(program_name)s
command=sudo php artisan websockets:serve --port=8443
directory=/var/www/html/PROJECT_NAME_HERE
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/html/PROJECT_NAME_HERE/storage/logs/websockets.log
```

**Comment by mrABR** [comment]
Let me get this straight, ya'll using https and then forcing the verification of the certificate to false? might just accept an http connection, its pretty much the same security wise.

Anyone with actual resolution without `verify => false`?
I've had this issue with Let'sEncrypt certificates and Sectigo's, no different output.

**Comment by Abdulkader2021** [comment]
This worked for me in the cpanel.

**broadcasting.php**

'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => env('APP_URL'),
                'port' => 6001,
                'scheme' => env('PUSHER_SCHEME'),
                'useTLS' => true,
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ]
            ],
        ],


**The websockes page**
  'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null),
//        'local_cert' => '~/etc/ssl/certs/apache-selfsigned.crt',

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null),
//        'local_pk' => '~/etc/ssl/private/apache-selfsigned.key',

        /*
         * Passphrase for your local_cert file.
         */
//        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),
        'passphrase' => null,
//
//        'verify_peer' => false,
    ],

**And the client side code**

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'pusherAppKey',
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true,
    wsHost: window.location.hostname,
    wsPort: 6001,
    wssPort: 6001,
    // forceTLS: true,
    disableStats: true,
    enabledTransports: ['ws', 'wss']
});

**Comment by Temepest74** [comment]
> Let me get this straight, ya'll using https and then forcing the verification of the certificate to false? might just accept an http connection, its pretty much the same security wise.
> 
> Anyone with actual resolution without `verify => false`?
> I've had this issue with Let'sEncrypt certificates and Sectigo's, no different output.

Did you find anything?

**Comment by mrABR** [comment]
Nothing yet @Temepest74, currently still running with verify false. Haven't been able to make it work
