### ISSUE TITLE
How can i config SSL ?

### ISSUE THREAD

**Issue by farshidpg** [beyondcode/laravel-websockets#920]
I have domain with SSL  and my project work with PUSHER_SCHEME = http  or PUSHER_SCHEME  = https in local 
but when i deploy on server ( centOs  , directadmin , php 7.4 )  http or https not working 
how can i found the

local_cert 
local_pk 
passphrase 

for SSL run , i thing http ( ws ) not workinf in production on the https domains  and i should use ssl configs for run project on the server .

plz help me to found  ssl config file on the server 

tnx

**Comment by erikn69** [comment]
that depends on your server, search the path of certs on nginx config, apache config, etc

**Comment by farshidpg** [comment]
this is list of inside certs
![Screenshot 2022-01-11 203647](https://user-images.githubusercontent.com/9290073/148988658-9c4f8797-4165-4538-b9be-be70720242d9.png)

what should i do ?

**Comment by erikn69** [comment]
Set it on `.env` for config
https://github.com/beyondcode/laravel-websockets/blob/fd2070fc3d28696247acceacc4f40667828f3016/config/websockets.php#L240-L254
Also read [oficial documentation](https://beyondco.de/docs/laravel-websockets/basic-usage/ssl)

**Comment by farshidpg** [comment]
@erikn69 

is it  true ? 

LARAVEL_WEBSOCKETS_SSL_CA="/etc/ssl/certs/ca-bundle.crt"
LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=null
LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=null
LARAVEL_WEBSOCKETS_SSL_PASSPHRASE=null

**Comment by erikn69** [comment]
>is it true ?

I'm not sure, try

**Comment by farshidpg** [comment]
@erikn69  no , not working . i dont have .pem and  .key files ...

**Comment by farshidpg** [comment]
anyone cant help me ?? i try for 3 days and i think back to limit pusher ... plz help me

**Comment by afilippov1985** [comment]
> anyone cant help me ?? i try for 3 days and i think back to limit pusher ... plz help me

`config/broadcasting.php`
```php
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'host' => '127.0.0.1',
                'port' => 6001,
            ],
        ],
```

Nginx config
```
server {
..............
    location /pusher/ {
        rewrite ^/pusher/(.*)$ /$1 break;
        proxy_pass             http://127.0.0.1:6001;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
...................
}
```

JavaScript
```js
		this.echo = new Echo({
			broadcaster: 'pusher',
			key: '...',
			wsHost: window.location.hostname,
			wsPath: '/pusher',
			disableStats: true,
			enabledTransports: ['ws', 'wss'],
			authEndpoint: '/api/broadcasting/auth',
		});

```

**Comment by farshidpg** [comment]
@afilippov1985 the domain use SSL and i have poblem with wss youre code in ws ( none SSL ) also i use apache . You write Nginx config

**Comment by erikn69** [comment]
>the domain use SSL and i have poblem with wss youre code in ws

read again, it uses ssl, it's a really good and easy solution for wss

>also i use apache . You write Nginx config

use the same idea for apache, do not expect that they give you configuring your server too

**Comment by farshidpg** [comment]
@erikn69 
thank you , can  you help me for apache config like youre nginx ? i have .htaccess and know that . but   dont have knowledge about apcahe and convert nginx config to apache :)

**Comment by erikn69** [comment]
> do not expect that they give you configuring your server too

I left apache behind a long time ago and use nginx now

**Comment by farshidpg** [comment]
@afilippov1985 tnx i try youre configs but i cant config apache  can you help me for config apache with htaccess ?

**Comment by afilippov1985** [comment]
> @afilippov1985 the domain use SSL and i have poblem with wss youre code in ws ( none SSL ) also i use apache . You write Nginx config

For Apache
```
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
.........
<VirtualHost *:443>
..........
  ProxyPass "/pusher/" "ws://127.0.0.1:6001/"
...........
</VirtualHost>
```

**Comment by EM-LilianaIturribarria** [comment]
Hi guys, i've looked everywhere and tested almost anything i found on the issues in here and i still can make it work.
localhost with http works perfectly
but when i deploy to my diff environments with centos + apache on EC2 and https with Cloudflare. (https)
it took me some time to make the port work and i connect successfully to the dashboard, i no longer have errors on my console
but when i push events there's an error:

[2022-02-02 08:10:19] stg.ERROR: Pusher error: . {"exception":"[object] (Illuminate\\Broadcasting\\BroadcastException(code: 0): Pusher error: . at /app/shared/docroots/stg/play.evolvemediallc.com/releases/20220201T160656/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:128)
[stacktrace]

as well that my websocket connects but then it disconnects after a minute, even thought i already set these up:

`
KeepAlive On
Timeout 5400
ProxyTimeout 5400
`

here's also my configuration on the files:

broadcasting.php
`
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => true,
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => '8443,
                'scheme' => 'https'
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
`

websockets.php
`
'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT', null), <<< this is set up on .env

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LARAVEL_WEBSOCKETS_SSL_LOCAL_PK', null), <<< this is set up on .env

        /*
         * Passphrase for your local_cert file.
         */
        'passphrase' => env('LARAVEL_WEBSOCKETS_SSL_PASSPHRASE', null),

        'verify_peer' => env('APP_ENV') === 'prd',

        'allow_self_signed' => env('APP_ENV') !== 'prd',
    ],
`

can someone please help me? i've been struggling with this for weeks now.

**Comment by devsaurabh1003** [comment]
@farshidpg have you managed to get it working on apache server with ssl, if yes please share with me the final configurations of apache , .htaccess and the config files please. I'm stuck in this for last 2 days and not getting even closer just same error.

**Comment by Marsad1998** [comment]
@devsaurabh1003 did you find any solution with apache+ssl?
