### ISSUE TITLE
 Provisional headers are shown - on every browsers!

### ISSUE THREAD

**Issue by p4rh4m** [beyondcode/laravel-websockets#931]
Laravel-WebSocket was built on top of pusher right? so it should be really easy to change some codes and make it works with Laravel-WebSocket but no! I did everything still got the "Provisional headers are shown" error on the live host! on the other hand, pusher.js works fine! even Laravel-WebSocket works fine in localhost
I thought the error is related to CORS so I created a sub-domain on port:6001 but still not working

**Comment by kelvinthiongo** [comment]
Did you get a solution to this. I feel wasted, nkt!
