### ISSUE TITLE
Channels current state is unavailable in production environment

### ISSUE THREAD

**Issue by shaheermalayil** [beyondcode/laravel-websockets#935]
in local enviroment it is working fine, but deployed to our qa server it shows following error ,
in laravel 5.8

![shot1](https://user-images.githubusercontent.com/37526954/151521906-9a05357e-a931-4073-ac56-59f8cb33aa15.jpg)

my websocket.php configuration is as follows

![shot2](https://user-images.githubusercontent.com/37526954/151521934-41624f05-ea91-403c-b209-dca778645468.jpg)

and ssl path also added as follows and updated in .env file

![shot3](https://user-images.githubusercontent.com/37526954/151521947-01da27e4-d344-4053-84e0-fe9a44f3b0e1.jpg)

broadcasting .php is updated with curl_options as shown below

![shot4](https://user-images.githubusercontent.com/37526954/151521979-e7738035-2796-451a-a40f-bc3215f9abf3.jpg)

after weeks of research on different portals and GitHub issues I couldn't solve the problem yet. is any one here got the same problem and solution.. ?   thanks in advance

**Comment by erikn69** [comment]
>after weeks of research on different portals and GitHub issues

#929 #920 #921

**Comment by subooom** [comment]
Dude, I have done everything there is to do, yet unable to get the websocket server to work in production. Been at it for 45 days.
I am using a VPS and when i do:
`php artisan tinker`
`>>> event(new \App\Events\EmailVerified('test@test.com'))`
Illuminate\Broadcasting\BroadcastException with message 'Pusher error: .'
This vague error comes up.

**Comment by TaoufikElkahlaoui** [comment]
any solution ?

**Comment by parallels999** [comment]
Well the solution was to switch to soketi.

**Comment by lpovkhan** [comment]
I had such error. The problem was in APP_URL. It needs to be the same as PUSHER_HOST in .env file.

**Comment by redaoutamra** [comment]
@shaheermalayil any luck you fixed if you did please can you tell me what did you change thanks in adv
