### ISSUE TITLE
High load on the CPU thread that runs laravel-websockets

### ISSUE THREAD

**Issue by Hillcow** [beyondcode/laravel-websockets#936]
<img width="468" alt="Bildschirmfoto 2022-01-29 um 18 42 58" src="https://user-images.githubusercontent.com/20979750/151671518-71963afc-ab84-4ebf-97c5-368f5d187d5a.png">

Is there any possibility to distribute the load? I mean, I'm already running quite a nice dedicated server with up to 5GHz (i9 9900k) and there isn't too much going on with the websocket. It's always at 100% nomatter how much is going on.

**Comment by erfanhemmati** [comment]
@Hillcow i have this issue too and i don't understand!

**Comment by pvodicka** [comment]
I have same issue. It's all the time on full CPU load.

**Comment by Hillcow** [comment]
@sananAhmad but this isn't a new issue, I had this problem since day 1 (over 3 years). I'm not sure if a solution is in the works.

**Comment by sananAhmad** [comment]
first make sure if not satisfied this solution then you can check if port 6001 is running or not.
if running then this is your problem solution

**Comment by mpociot** [comment]
Which version are you using? Please try one of the available v2 betas, as this should increase the performance

**Comment by Hillcow** [comment]
@mpociot I tried both the latest stable and the latest beta, same problem.

**Comment by azizahmed45** [comment]
@Hillcow Any update on this issue?
Did you found any solution?
