### ISSUE TITLE
artisan websockets:restart ?

### ISSUE THREAD

**Issue by eminos** [beyondcode/laravel-websockets#94]
Is there a way to restart the websockets server?

I am running supervisor, but the laravel app user doesn't have permission to access it.

Maybe the same kind of solution that `queue:restart` does? (that works fine regarding permissions in my case)

**Comment by crnkovic** [comment]
Any updates to this?

**Comment by mikemand** [comment]
What about mimicing how Horizon does it? [`php artisan horizon:terminate`](https://github.com/laravel/horizon/blob/cc98b8274d2f629ccb639508faf7dcd92e724e4d/src/Console/TerminateCommand.php)

**Comment by siddharth** [comment]
Just a question, what happens to the existing connections if the server is restarted or goes down for a certain amount of time? Do they resume id the server comes back online within a time limit (if yes, what's this time limit) ?
