### ISSUE TITLE
Miss versions pusher/pusher-php-server in required composer.json

### ISSUE THREAD

**Issue by GuilhermeFerro** [beyondcode/laravel-websockets#951]
The new version: 1.13 the composer json not include  "pusher/pusher-php-server": "^3.0|^4.0|^5.0|**^6.0|^7.0**", in required composer.json

``` Problem 1
    - beyondcode/laravel-websockets[1.13.0, ..., 1.x-dev] require pusher/pusher-php-server ^3.0|^4.0|^5.0 -> found pusher/pusher-php-server[dev-master, 3.0.0, ..., v3.4.1, v4.0.0, ..., v4.1.5, v5.0.0, ...
, 5.0.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^7.0).
    - Root composer.json requires beyondcode/laravel-websockets ^1.13 -> satisfiable by beyondcode/laravel-websockets[1.13.0, 1.x-dev].
```

in branch master with then.

- master
https://github.com/beyondcode/laravel-websockets/blob/master/composer.json

- v.1.13.0
https://github.com/beyondcode/laravel-websockets/blob/1.13.0/composer.json

**Comment by erikn69** [comment]
maybe try `composer require "beyondcode/laravel-websockets:dev-master"`
