### ISSUE TITLE
[dev-master]: Error with migration Update 0000_00_00_000000_rename_statistics_counters.ph

### ISSUE THREAD

**Issue by 60poro** [beyondcode/laravel-websockets#953]
Throws an error related to this migration when starting migration:
`Update 0000_00_00_000000_rename_statistics_counters.php`

I have no error content as I had to skip the package from my project.

Replication:
Add laravel websockets to your project and run `php artisan migrate`

**Comment by erikn69** [comment]
change 
https://github.com/beyondcode/laravel-websockets/blob/605a7fa71ddabfffe381b079acc21403c7547ea2/database/migrations/0000_00_00_000000_create_websockets_statistics_entries_table.php#L7

To 
```php
return new class extends Migration 
```
Example:
https://github.com/laravel/laravel/blob/9.x/database/migrations/2014_10_12_000000_create_users_table.php
