### ISSUE TITLE
No Realtime Statistics - No DB Stats Entries

### ISSUE THREAD

**Issue by devedup** [beyondcode/laravel-websockets#959]
I've got it setup on localhost. I'm in debug mode. I'm seeing events on the console. I've connected an iOS client with pusher-swift - all that was painful, but it's now working. 

However, the realtime stats graph is refusing to display any statistics, and the websockets_statistics_entries is always empty - nothing is being logged to the DB. 

Are there any gotchas that I might have overlooked? I saw the one about the APP_URL=http://localhost in the .env file.

**Comment by devedup** [comment]
Ok, somehow it's working now... I've no idea what exactly i changed to make it work, I tried rolling some settings back to break it again and determine the cause but now it continues to work..😀

The only settings I was adjusting was the APP_URL switching between localhost and APP_URL=http://192.168.100.8 and APP_URL=http://localhost/. And PUSHER_APP_KEY from a simple word to a long UUID.  🤷‍♂️

However... my graph isn't refreshing automatically every minute. I have to reload the page, which seems a bit odd. Is this normal?

**Comment by lovemintblue** [comment]
> 
this is not normal
