### ISSUE TITLE
Unable to broadcast to different apps

### ISSUE THREAD

**Issue by stefandanaita** [beyondcode/laravel-websockets#97]
The package supports multi-tenancy through multiple apps. My question is..how do I broadcast from Laravel to different apps on the fly, knowing that the apps have different keys/secrets? Do I need multiple connections in `config/broadcasting.php` and switch between them on the fly? 😢 

Has anyone managed to do this in a `!spaghetti` way?

**Comment by stayallive** [comment]
Yes. You would need multiple apps in `config/broadcasting.php` exactly the same as if you would have multiple database connections.

You need to switch between them too. With database drivers you can do that through the model but I don't think you can switch between broadcasting drivers very easily in Laravel unless I missed something. Also the routing and authentication would need to be registered for each app.

I am wondering what your use case is for needing to broadcast to multiple apps from the same app? I believe the multi-tenancy is meant as a feature so you can have a single broadcasting Laravel app setup that your other apps can connect to not for a single Laravel app to broadcast to multiple apps directly if that makes sense.
