### ISSUE TITLE
Client message event problem

### ISSUE THREAD

**Issue by MohammadZarifiyan** [beyondcode/laravel-websockets#970]
Hi there

How can i get **user_id** and **channelName** when client triggers event ?

In `\BeyondCode\LaravelWebSockets\Events\WebSocketMessageReceived` there is nothing helpful.

**Comment by erikn69** [comment]
Make your own events

**Comment by MohammadZarifiyan** [comment]
But how should i get `user_id` and `channelName` before triggering `\BeyondCode\LaravelWebSockets\Events\WebSocketMessageReceived` ?

**Comment by MohammadZarifiyan** [comment]
> Make your own events

But how should i get user_id and channelName before triggering \BeyondCode\LaravelWebSockets\Events\WebSocketMessageReceived ?

**Comment by giunashvili** [comment]
I have the same problem
