### ISSUE TITLE
Undefined property: stdClass::$event

### ISSUE THREAD

**Issue by maclonghorn** [beyondcode/laravel-websockets#972]
I'm using laravel-websockets 1.13.1 as my Pusher replacement and it's receiving a message fine, but it's not actually pushing anything.  I'm seeing this in the domain_supervisord_websockets.log:

1338465: exception `ErrorException` thrown: `Undefined property: stdClass::$event`.

Any ideas?

laravel-websockets:  1.13.1
pusher-php-server: 3.4.1

**Comment by SIMONNABUKO** [comment]
Did you solve this error? I am encountering the same error!

**Comment by maclonghorn** [comment]
I don't recall if I solved this particular issue.  We ended up using Pusher for the time being.  Our intent is still to use Laravel Websockets but it's on the backlog for now.  Sorry.

**Comment by RizwanBlogger** [comment]
Exception `ErrorException` thrown: `Undefined property: stdClass::$event`
1665526: exception `ErrorException` thrown: `Undefined property: stdClass::$event`
