### ISSUE TITLE
Pusher error: cURL error 35: SSL Issue

### ISSUE THREAD

**Issue by manshu** [beyondcode/laravel-websockets#978]
Hello Everyone, I've been having issues regarding Laravel Websockets.

Let me give you some context on my code. I am using Laravel Valet for local setup, but when I am trying to post anything, it gives me an error Pusher error: cURL error 35:

This is how my `app.js` file looks like

```
window.Echo = new Echo({
  broadcaster: 'pusher',
  key: process.env.MIX_PUSHER_APP_KEY,
  wsHost: process.env.MIX_PUSHER_APP_HOST,
  encrypted: true,
  wsPort: 6001,
  wssPort: 6001,
  disableStats: true,
  enabledTransports: ['ws', 'wss']
})
```

This is how my `broadcasting.php` file looks like.

```
'connections' => [

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'https',
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
```
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/2611283/165881663-697bfffc-b28a-42c9-a3dd-854feef36413.png">

```
Pusher error: cURL error 35: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding (see 
https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://127.0.0.1:6001/apps/local/events?
auth_key=local&auth_timestamp=1651193153&auth_version=1.0&body_md5=a91cf944aa7faa20dde52c231dd35c2e&auth_signat
ure=f69864e5444c1d1e94a22d5b9e07b060b675c23a0234f968f9e90912811d6310.
```

`production.ERROR: cURL error 60: SSL: no alternative certificate subject name matches target host name '127.0.0.1'`

**Comment by Arslan1122** [comment]
@manshu did you find solution for this problem? I'm also facing the same issue. Please help me to solve this If you find any issue ? Thanks in advance

**Comment by aqjw** [comment]
any solution?

**Comment by manshu** [comment]
Yes, used soketi instead of this and it worked. i’ll try to make a video in my channel. https://youtube.com/@gurulabsdev

**Comment by manshu** [comment]
> I'm having the exact same issue with socketi though.

Have u tried switching socketi?

**Comment by remcovg89** [comment]
> > I'm having the exact same issue with socketi though.
> 
> Have u tried switching to socketi?

I'm using soketi, but i've just realised my PUSHER_SCHEME=http .env variable was still set to https.

**Comment by manshu** [comment]
> > > I'm having the exact same issue with socketi though.
> > 
> > 
> > Have u tried switching to socketi?
> 
> I'm using soketi, but i've just realised my PUSHER_SCHEME=http .env variable was still set to https.

Great. I’ve it working now. It was issue with the package. Socketi works like a boss!
