### ISSUE TITLE
Exception `ErrorException` thrown: `Undefined property: stdClass::$auth`

### ISSUE THREAD

**Issue by zhxscript** [beyondcode/laravel-websockets#98]
Nevermind....

Anybody who might come across this... make sure to set broadcast in .env to pusher LOL

**Comment by wallysonn** [comment]
> Nevermind....
> 
> Anybody who might come across this... make sure to set broadcast in .env to pusher LOL

could you show an example?

**Comment by Kamleshpaul** [comment]
i m getting same issue with laravel sanctum

**Comment by germanow** [comment]
BROADCAST_DRIVER=pusher
