### ISSUE TITLE
Problem with config wss, certs, etc

### ISSUE THREAD

**Issue by ssheduardo** [beyondcode/laravel-websockets#986]
First of all, many thanks to the team for making this package possible.
I will detail the exact steps I take to try to configure the wss.

My configuration
```
- Laravel 5.7
- beyondcode/laravel-websockets 1.3.0
- pusher/pusher-php-server 4.1.5

```
Nginx with proxy reverse
```
location /app {
        proxy_pass             http://127.0.0.1:6001;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

STEP

1. I have created a domain without https.
2. Config websockets.php and broadcasting.php (simple config)
3.  I have uploaded the project and it works without problem, I can enter the panel and see the statistics.
4. Seeing that everything works perfectly.

**NOW, ACTIVATE WSS**
======

STEP
I should mention that I have read and tested many tutorials and issues here.

1. I have created some certificates on my server with this command.
`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/websockets-selfsigned.key -out /etc/ssl/certs/websockets-selfsigned.crt`
2. Open file config/websockets.php and the configuration
```
....
....
'apps' => [
        [
            'id' => env('PUSHER_APP_ID'),
            'name' => env('APP_NAME'),
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'enable_client_messages' => true,
            'enable_statistics' => true,
        ],
    ],
....
....

'ssl' => [
        /*
         * Path to local certificate file on filesystem. It must be a PEM encoded file which
         * contains your certificate and private key. It can optionally contain the
         * certificate chain of issuers. The private key also may be contained
         * in a separate file specified by local_pk.
         */
        'local_cert' => env('LOCAL_CERT', null),

        /*
         * Path to local private key file on filesystem in case of separate files for
         * certificate (local_cert) and private key.
         */
        'local_pk' => env('LOCAL_KEY', null),

        /*
         * Passphrase with which your local_cert file was encoded.
         */
        'passphrase' => null,
        'verify_peer' => false,
        'allow_self_signed' => true,
    ],

```

My .ENV

```
PUSHER_APP_ID=666666
PUSHER_APP_KEY='AAbLk31NuAA'
PUSHER_APP_SECRET='VV6dfnj6K32aCNuFa'
PUSHER_APP_CLUSTER=mt1
PUSHER_SCHEME='https'

LOCAL_CERT='/etc/ssl/certs/websockets-selfsigned.crt'
LOCAL_KEY='/etc/ssl/private/websockets-selfsigned.key'
LOCAL_PEM='/etc/ssl/certs/websockets-selfsigned.pem'

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

3. Open file config/brodcasting.php and the configuration
```
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => true,
                'useTLS' => true,
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => env('PUSHER_SCHEME'),
                'curl_options' => [
                    CURLOPT_SSL_VERIFYHOST => 0,
                    CURLOPT_SSL_VERIFYPEER => 0,
                ],
            ],
        ],
```
4. Add config for nginx.ssl.conf (Port 443)
```
location /app {
        proxy_pass             https://127.0.0.1:6001;        
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```
5. Restart nginx
6. Now Testing laravel-websockets panel and fail.

`WebSocket connection to 'wss://websockets.ubublog.com:80/app/ygbLk87NuyN?protocol=7&client=js&version=4.3.1&flash=false' failed: `

![image](https://user-images.githubusercontent.com/1160138/169032078-e235c377-9afd-4dce-9e08-2595be209a6b.png)

-----
I have followed all the steps as per various tutorials and reviews here and I get this error.
If anyone has managed to get wss working, can you tell me where I am going wrong.
The steps are simple but there is something wrong with setting it up.

**Comment by zmoukit** [comment]
I'm facing the same issue:
`beyondcode/laravel-websockets": "^1.13",`
`"laravel/framework": "^7.24",`
`"pusher/pusher-php-server": "~4.0"`

**Comment by ssheduardo** [comment]
I don't understand why something so "EASY" to configure is so difficult.

**Comment by lukehebb** [comment]
Try port 443, port 80 won't be using the SSL config so is likely what is causing the WSS connection to fail

**Comment by ssheduardo** [comment]
> Try port 443, port 80 won't be using the SSL config so is likely what is causing the WSS connection to fail

I try with port 443 some error.

It is really so "COMPLICATED" to install it or give support, I do not believe that anyone does not work the WSS, it is impossible, I ask the community who has it configured can help us with this.

**Comment by lukehebb** [comment]
We use WSS successfully for thousands of clients though we do it in a slightly different way as we use V2 of laravel-websockets behind a load balancer. One thing I can see is you are using a self-signed certificate so it may be best to replace that with one issued by letsencrypt instead as it could also be your browser not liking the self-signed cert

As you are using nginx to proxy the connections, you can remove the SSL config from the socket application instead and purely handle SSL within nginx, then let nginx proxy to the websocket service without SSL as its handled locally on the machine so will be safe

**Comment by ssheduardo** [comment]
> We use WSS successfully for thousands of clients though we do it in a slightly different way as we use V2 of laravel-websockets behind a load balancer. One thing I can see is you are using a self-signed certificate so it may be best to replace that with one issued by letsencrypt instead as it could also be your browser not liking the self-signed cert
> 
> As you are using nginx to proxy the connections, you can remove the SSL config from the socket application instead and purely handle SSL within nginx, then let nginx proxy to the websocket service without SSL as its handled locally on the machine so will be safe

I currently have my site:
www.demo.com with let'sEncrypt.
Now from what I understood you say that inside the proxy stop using wss and instead ws.

What I don't understand is how if from a client X I make the call to ws from outside, that is insecure.
That's the part I don't understand how to do that, can't you provide a practical example of how to do it by having a domain with HTTPS but calling ws?


Translated with www.DeepL.com/Translator (free version)

**Comment by lukehebb** [comment]
We have it so our clients use wss://domain.com which runs nginx to accept SSL on port 443. This then uses nginx to proxy to the laravel-websockets application under the hood

Within the websockets application we don't configure SSL at all

For our laravel echo clients we use this config

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    wsHost: 'domain.tld',
    wsPort: 443,
    authEndpoint: "https://domain.tld/broadcasting/auth",
    disableStats: true,
    forceTLS: true
});

**Comment by ssheduardo** [comment]
> We have it so our clients use wss://domain.com which runs nginx to accept SSL on port 443. This then uses nginx to proxy to the laravel-websockets application under the hood
> 
> Within the websockets application we don't configure SSL at all
> 
> For our laravel echo clients we use this config
> 
> window.Echo = new Echo({ broadcaster: 'pusher', key: process.env.MIX_PUSHER_APP_KEY, wsHost: 'domain.tld', wsPort: 443, authEndpoint: "https://domain.tld/broadcasting/auth", disableStats: true, forceTLS: true });

What you say makes more sense, I will try to do what you say, this information is very valuable.

**Comment by ssheduardo** [comment]
Hi, @lukehebb 
I have tried to make the changes but it has been impossible to make it work, I have tried to follow the steps more or less as you say but I have not succeeded.
Can you please add an example of the configuration of nginx, websockets.php and brodcasting.php.
I can't think what else to do and although you say you have installed in many clients the wss option, I would appreciate if you could share how you do it.
Thanks

Translated with www.DeepL.com/Translator (free version)

**Comment by gkia999** [comment]
I didn't open any issue on this topic, I just commented there with hope to
find solutions for my problem or get some answer from someone regarding the
issue.

I would appreciate if you could guide me, to understand the problem and
debug the issue.

**Comment by ikopmans** [comment]
I am using self-signed cert (with CA cert added into browser) and in my case I had to add following lines:
'ssl' => [
      ...
        'verify_peer' => false,
        'verify_peer_name'=>false,
        'allow_self_signed'=>true,
    ],
into websockets.php to make it work.
