### ISSUE TITLE
ross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://sockjs-mt1.pusher.com/pusher/app//186/om7hvlep/xhr_streaming?protocol=7&client=js&version=7.0.2&t=1653565326360&n=

### ISSUE THREAD

**Issue by mahmoud-elhawy** [beyondcode/laravel-websockets#987]
i got this error 
`cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [http://sockjs-mt1.pusher.com/pusher/app//186/om7hvlep/xhr_streaming?protocol=7&client=js&version=7.0.2&t=1653565326360&n=](http://sockjs-mt1.pusher.com/pusher/app//186/om7hvlep/xhr_streaming?protocol=7&client=js&version=7.0.2&t=1653565326360&n=1)`

here is configuration 
**`bootstrap.js`**
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    wsHost: window.location.hostname,
    wsPort: 6001,
    forceTLS: false,
    disableStats: true,
	logToConsole: true

});

`broadcasting.php`

`'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'useTLS' => false,
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'host' => '127.0.0.1',
                'port' => 6001,
                'scheme' => 'http',
                'encrypted' => false,
            ],
        ],`
![Screenshot from 2022-05-26 13-39-24](https://user-images.githubusercontent.com/93072752/170483081-ca47e6fa-9b3c-4c62-8c6d-a3bb17f67b9d.png)

**Comment by peterson-umoke** [comment]
which pusher version are you using ?

**Comment by mahmoud-elhawy** [comment]
no pusher i use 
only `"pusher/pusher-php-server": "~4.0",`
i did not know why it is calling pusher even if i use Pusher Replacement

**Comment by peterson-umoke** [comment]
and your PHP version?

**Comment by peterson-umoke** [comment]
> no pusher i use only `"pusher/pusher-php-server": "~4.0",` i did not know why it is calling pusher even if i use Pusher Replacement

its sort of a requirements, even other implementations like [soketi](https://docs.soketi.app/getting-started/client-configuration/laravel-echo) still use pusherjs under the hood for laravel echo

**Comment by GarryLai** [comment]
Just add `enabledTransports: ['ws', 'wss'],` in `window.Echo`.

**Comment by mahmoud-elhawy** [comment]
> Just add `enabledTransports: ['ws', 'wss'],` in `window.Echo`.

this not work

**Comment by mahmoud-elhawy** [comment]
> and your PHP version?

7.4

**Comment by jomisacu** [comment]
> > Just add `enabledTransports: ['ws', 'wss'],` in `window.Echo`.
> 
> this not work

Looks likes works for me. After this modification you must re-run npm run dev.
